src/objects/AccountingInvestment__c.object
<CustomObject>
    <fields>
        <fullName>investmentID__c</fullName>
        <label>Investment ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>totalCostProceedsAccounting__c</fullName>
        <label>Total Cost/Proceeds (Accounting)</label>
        <summarizedField>AccountingTransaction__c.costProceeds__c</summarizedField>
        <summaryForeignKey>AccountingTransaction__c.investment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Accounting Investment</label>
    <nameField>
        <displayFormat>ACCINV-{0000000000}</displayFormat>
        <label>Accounting Investment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountingTransaction__c.object
<CustomObject>
    <fields>
        <fullName>accountingIntegrationJob__c</fullName>
        <label>Accounting Integration Job</label>
        <referenceTo>AccountingIntegrationJob__c</referenceTo>
        <relationshipLabel>Accounting Transactions</relationshipLabel>
        <relationshipName>AccountingTransactions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>costProceeds__c</fullName>
        <label>Cost/Proceeds</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>investmentId__c</fullName>
        <formula>investment__r.investmentID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Investment Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>investmentTypeDescription__c</fullName>
        <label>Investment Type Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>investment__c</fullName>
        <label>Investment</label>
        <referenceTo>AccountingInvestment__c</referenceTo>
        <relationshipLabel>Accounting Transactions</relationshipLabel>
        <relationshipName>AccountingTransactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>reconciliationType__c</fullName>
        <label>Reconciliation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost</fullName>
                    <default>true</default>
                    <label>Cost</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>settleDate__c</fullName>
        <label>Settle Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tradeDate__c</fullName>
        <label>Trade Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>transactionDescription__c</fullName>
        <label>TXN Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transactionNumber__c</fullName>
        <externalId>true</externalId>
        <label>TXN No</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Accounting Transaction</label>
    <nameField>
        <displayFormat>AT-{0000000000}</displayFormat>
        <label>Accounting Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/InventoryAsset__c.object
<CustomObject>
    <fields>
        <fullName>accountingInvestment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting Investment</label>
        <referenceTo>AccountingInvestment__c</referenceTo>
        <relationshipLabel>Inventory Assets</relationshipLabel>
        <relationshipName>InventoryAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acquisitionCloseDate__c</fullName>
        <formula>IF( assetAcquisitionOverride__c != null, assetAcquisitionOverride__r.Opportunity__r.CloseDate, assetAcquisition__r.Opportunity__r.CloseDate)</formula>
        <label>Acquisition Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acquisitionEffectiveDate__c</fullName>
        <formula>IF( assetAcquisitionOverride__c != null, assetAcquisitionOverride__r.Opportunity__r.Effective_Date__c, assetAcquisition__r.Opportunity__r.Effective_Date__c )</formula>
        <label>Acquisition Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acquisitionOpportunityId__c</fullName>
        <formula>IF( assetAcquisitionOverride__c != null,  CASESAFEID( assetAcquisitionOverride__r.Opportunity__c ), CASESAFEID( assetAcquisition__r.Opportunity__c) )</formula>
        <label>Acquisition Opportunity Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acquisitionOpportunityName__c</fullName>
        <formula>IF( assetAcquisitionOverride__c != null,  assetAcquisitionOverride__r.Opportunity__r.Name ,  assetAcquisition__r.Opportunity__r.Name  )</formula>
        <label>Acquisition Opportunity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acquisitionTotalPrice__c</fullName>
        <formula>IF( assetAcquisitionOverride__c != null, assetAcquisitionOverride__r.totalPrice__c, assetAcquisition__r.totalPrice__c ) * -1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Acquisition Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acquisitionUnitPrice__c</fullName>
        <formula>IF( assetAcquisitionOverride__c != null, assetAcquisitionOverride__r.unitPrice__c, assetAcquisition__r.unitPrice__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Acquisition Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>buyerNextOwnerId__c</fullName>
        <formula>IF( assetSaleOverride__c != null,  CASESAFEID( assetSaleOverride__r.Opportunity__r.Acquiring_Entity__c) ,  CASESAFEID( assetSale__r.Opportunity__r.Acquiring_Entity__c ))</formula>
        <label>Buyer (Next Owner) Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>buyerNextOwnerName__c</fullName>
        <formula>IF( assetSaleOverride__c != null, assetSaleOverride__r.Opportunity__r.Acquiring_Entity__r.Name , assetSale__r.Opportunity__r.Acquiring_Entity__r.Name )</formula>
        <label>Buyer (Next Owner) Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inventoryOwnerId__c</fullName>
        <formula>CASESAFEID(assetAcquisition__r.Opportunity__r.Acquiring_Entity__c)</formula>
        <label>Inventory Owner Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inventoryOwnerName__c</fullName>
        <formula>assetAcquisition__r.Opportunity__r.Acquiring_Entity__r.Name</formula>
        <label>Inventory Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>saleCloseDate__c</fullName>
        <formula>IF( assetSaleOverride__c != null, assetSaleOverride__r.Opportunity__r.CloseDate, assetSale__r.Opportunity__r.CloseDate)</formula>
        <label>Sale Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>saleEffectiveDate__c</fullName>
        <formula>IF( assetSaleOverride__c != null, assetSaleOverride__r.Opportunity__r.Effective_Date__c, assetSale__r.Opportunity__r.Effective_Date__c)</formula>
        <label>Sale Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>saleOpportunityId__c</fullName>
        <formula>IF( assetSaleOverride__c != null,  CASESAFEID(assetSaleOverride__r.Opportunity__c) ,  CASESAFEID(assetSale__r.Opportunity__c ))</formula>
        <label>Sale Opportunity Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>saleOpportunityName__c</fullName>
        <formula>IF( assetSaleOverride__c != null, assetSaleOverride__r.Opportunity__r.Name , assetSale__r.Opportunity__r.Name )</formula>
        <label>Sale Opportunity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>saleTotalPrice__c</fullName>
        <formula>IF( assetSaleOverride__c != null, assetSaleOverride__r.totalPrice__c, assetSale__r.totalPrice__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sale Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>saleUnitPrice__c</fullName>
        <formula>IF( assetSaleOverride__c != null, assetSaleOverride__r.unitPrice__c, assetSale__r.unitPrice__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sale Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>sellerPreviousOwnerId__c</fullName>
        <formula>IF( assetAcquisitionOverride__c != null,  CASESAFEID( assetAcquisitionOverride__r.Opportunity__r.AccountId) ,  CASESAFEID( assetAcquisition__r.Opportunity__r.AccountId ))</formula>
        <label>Seller (Previous Owner) Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sellerPreviousOwnerName__c</fullName>
        <formula>IF( assetAcquisitionOverride__c != null, assetAcquisitionOverride__r.Opportunity__r.Account.Name , assetAcquisition__r.Opportunity__r.Account.Name )</formula>
        <label>Seller (Previous Owner) Name</label>
        <type>Text</type>
    </fields>
    <label>Inventory Asset</label>
    <nameField>
        <displayFormat>IA-{0000000000}</displayFormat>
        <label>Inventory Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <formula>if(Total_Cost__c = 0, 0, Total_Cost__c /  Total_Acreage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Sum of all &quot;Total Cost&quot; fields</description>
        <label>Total Cost</label>
        <summarizedField>Opportunity_Tract__c.Total_Cost__c</summarizedField>
        <summaryForeignKey>Opportunity_Tract__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <description>OTG = &quot;Off the Ground&quot; - how much was paid to the previous owner (does not include commissions, title costs etc.)</description>
        <inlineHelpText>OTG = &quot;Off the Ground&quot; - how much waspaid to the previous owner (does not include commissions, title costs etc.)</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <inlineHelpText>OTG Cost per Acre</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <formula>if (netAcres__c == 0,0,Total_Cost__c /  netAcres__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Costs divided by Net Acres</inlineHelpText>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountingInvestmentController.cls
public class AccountingInvestmentController {
 // test July 13, 2021
	
	// changeto in branch from git interface 
    @AuraEnabled
    public static  List<AccountingTransaction__c> getAccountingTransaction(Id recordId){
        List<AccountingTransaction__c> accountingTransactionList = new List<AccountingTransaction__c>();
        if(Schema.AccountingIntegrationJob__c.SObjectType == recordId.getSobjectType()){
            accountingTransactionList = [Select Id,Name,tradeDate__c,settleDate__c,costProceeds__c,
                                    transactionNumber__c, investment__c, investment__r.Name, transactionDescription__c,description__c,
                                    investmentTypeDescription__c, reconciliationType__c, quantity__c from AccountingTransaction__c
                                    Where accountingIntegrationJob__c =: recordId];
        }else if(Schema.AccountingInvestment__c.SObjectType == recordId.getSobjectType()){
            accountingTransactionList = [Select Id,Name,tradeDate__c,settleDate__c,costProceeds__c,
                                    transactionNumber__c, investment__c, investment__r.Name, transactionDescription__c,description__c,
                                    investmentTypeDescription__c, reconciliationType__c, quantity__c from AccountingTransaction__c
									 where investment__c =: recordId];
        }
        return accountingTransactionList;
    }

    
	@AuraEnabled
	public static List<AccountingInvestment__c> getAccountingInvestment(Id recordId){
				Set<Id> aiIds = new Set<Id>();
			   for(AccountingTransaction__c txn : [Select id, investment__c from AccountingTransaction__c
												Where accountingIntegrationJob__c =: recordId]){
               aiIds.add(txn.investment__c);
            
		}

		List<AccountingInvestment__c> accountingInvestmentList = [Select Id, Name, CreatedDate, LastModifiedDate, investmentID__c, totalCostProceedsAccounting__c
																	from AccountingInvestment__c where id in :aiIds];

		return accountingInvestmentList;
	}

	@AuraEnabled
    public static InventoryAssetSearchResult getSearchResults(String searchString, Integer searchCounter){
        InventoryAssetSearchResult response = new InventoryAssetSearchResult();
		response.searchCounter = searchCounter;
		List<InventoryAsset__c> inventoryAssets = new List<InventoryAsset__c>();
        //Escape special characters for SOSL search - order of replacement matters - if you replace all backslashes late, you will end up with double backslashes.
        //searchString = searchString.replaceAll('[|,|.|\\,||"||:|~|!|@|#|$|%|^|&|*|_|+|=|<|>|?|\\(|\\)|\\{|\\}|\\;|\\\'"]', '-');
        searchString = searchString.replace('\\', '\\');
        searchString = String.escapeSingleQuotes(searchString);
        searchString = searchString.replace('-', '\\-');
        searchString = searchString.replace('+', '\\+');
        searchString = searchString.replace('&', '\\&');
        searchString = searchString.replace('|', '\\|');
        searchString = searchString.replace('!', '\\!');
        searchString = searchString.replace('{', '\\{');
        searchString = searchString.replace('}', '\\}');
        searchString = searchString.replace('[', '\\[');
        searchString = searchString.replace(']', '\\]');
        searchString = searchString.replace('(', '\\(');
        searchString = searchString.replace(')', '\\)');
        searchString = searchString.replace('^', '\\^');
        searchString = searchString.replace('~', '\\~');
        searchString = searchString.replace('*', '\\*');
        searchString = searchString.replace(':', '\\:');
        searchString = searchString.replace('\"', '\\"');
        
        String searchQuery = 'FIND {' + searchString + '} IN ALL FIELDS RETURNING InventoryAsset__c (Name,accountingInvestment__c,acquisitionOpportunityId__c,'+
													'acquisitionOpportunityName__c,acquisitionUnitPrice__c, acquisitionTotalPrice__c,acquisitionCloseDate__c,'+
													'acquisitionEffectiveDate__c,buyerNextOwnerId__c,buyerNextOwnerName__c,inventoryOwnerId__c,inventoryOwnerName__c,'+
													'saleCloseDate__c,saleEffectiveDate__c,saleOpportunityId__c,saleOpportunityName__c,saleTotalPrice__c,'+
													'sellerPreviousOwnerId__c,sellerPreviousOwnerName__c, saleUnitPrice__c  ORDER BY Name) LIMIT 50';
        
        List<List<SObject>>searchList = Search.query(searchQuery);
        for(SObject currentSObject:searchList[0]){
            InventoryAsset__c currentInventoryAsset = (InventoryAsset__c)currentSObject;
            inventoryAssets.add(currentInventoryAsset);
        }
		response.inventoryAssets = inventoryAssets;
        return response;
    }

	@AuraEnabled
	public static OpportunitySearchResult getOpportunitySearchResults(List<String> opportunityIds){
		OpportunitySearchResult response = new OpportunitySearchResult();
		List<Id> oppTractIds = new List<Id>();
		response.oppTracts = [Select Id, Name, Opportunity__c,Opportunity__r.Name,
                                            Tract__c,Tract__r.Name,OTG_Cost_Per_Acre__c,Total_Cost_Per_Acre__c,
                                            Total_Cost__c, Instrument_Type__c,Opportunity__r.CloseDate
                                            from Opportunity_Tract__C where Opportunity__c In: opportunityIds];
		for(Opportunity_Tract__c oppTract: response.oppTracts){
			oppTractIds.add(oppTract.Id);
		}
		response.inventoryAssets = [SELECT acquisitionOpportunityId__c,acquisitionOpportunityName__c,acquisitionUnitPrice__c, acquisitionTotalPrice__c,acquisitionCloseDate__c,
										acquisitionEffectiveDate__c,buyerNextOwnerId__c,buyerNextOwnerName__c,inventoryOwnerId__c,inventoryOwnerName__c,
										saleCloseDate__c,saleEffectiveDate__c,saleOpportunityId__c,saleOpportunityName__c,saleTotalPrice__c,
										sellerPreviousOwnerId__c,sellerPreviousOwnerName__c, Name, saleUnitPrice__c, accountingInvestment__c
									FROM InventoryAsset__c 
									WHERE assetAcquisition__c IN :oppTractIds
									OR assetAcquisitionOverride__c IN :oppTractIds
									OR assetSale__c IN :oppTractIds
									OR assetSaleOverride__c IN :oppTractIds];
		response.opps = [Select Id,Name from Opportunity Where Id In: opportunityIds];
		return response;
	}

	@AuraEnabled
    public static List<InventoryAsset__c> getInventoryAssets(Id recordId){
        List<InventoryAsset__c> response = [SELECT acquisitionOpportunityId__c,acquisitionOpportunityName__c,acquisitionUnitPrice__c, acquisitionTotalPrice__c,acquisitionCloseDate__c,
													acquisitionEffectiveDate__c,buyerNextOwnerId__c,buyerNextOwnerName__c,inventoryOwnerId__c,inventoryOwnerName__c,
													saleCloseDate__c,saleEffectiveDate__c,saleOpportunityId__c,saleOpportunityName__c,saleTotalPrice__c,
													sellerPreviousOwnerId__c,sellerPreviousOwnerName__c, Name, saleUnitPrice__c
												FROM InventoryAsset__c 
												WHERE accountingInvestment__c =:recordId];
        return response;                      
    }

	@AuraEnabled
    public static InventoryAsset__c getInventoryAsset(Id recordId){
        InventoryAsset__c response = [SELECT acquisitionOpportunityId__c,acquisitionOpportunityName__c,acquisitionUnitPrice__c, acquisitionTotalPrice__c,acquisitionCloseDate__c,
													acquisitionEffectiveDate__c,buyerNextOwnerId__c,buyerNextOwnerName__c,inventoryOwnerId__c,inventoryOwnerName__c,
													saleCloseDate__c,saleEffectiveDate__c,saleOpportunityId__c,saleOpportunityName__c,saleTotalPrice__c,
													sellerPreviousOwnerId__c,sellerPreviousOwnerName__c, Name, saleUnitPrice__c, assetAcquisition__c, assetSale__c
												FROM InventoryAsset__c 
												WHERE Id =:recordId
												LIMIT 1];
        return response;                      
    }
    
   /* @AuraEnabled
    public static opportunityTractWrapper getOpportunityTract(String recordId,List<String> opportunityIds){
        Set<Id> oppTractId = new Set<Id>();
        opportunityTractWrapper opportunityTractWrap = new opportunityTractWrapper();

        for(Opportunity_Tract__c oppTract : [Select Id, Name, Opportunity__c,Opportunity__r.Name,
                                            Tract__c,Tract__r.Name,OTG_Cost_Per_Acre__c,Total_Cost_Per_Acre__c,
                                            Total_Cost__c, Instrument_Type__c,Opportunity__r.CloseDate
                                            from Opportunity_Tract__c where accountingInvestment__c=:recordId]){
            oppTractId.add(oppTract.Id);
        }
        opportunityTractWrap.oppTracts = [Select Id, Name, Opportunity__c,Opportunity__r.Name,
                                            Tract__c,Tract__r.Name,OTG_Cost_Per_Acre__c,Total_Cost_Per_Acre__c,
                                            Total_Cost__c, Instrument_Type__c,Opportunity__r.CloseDate
                                            from Opportunity_Tract__C where Opportunity__c In: opportunityIds];
        opportunityTractWrap.selectedOppTracts = new List<Opportunity_Tract__c>();                                    
        
		for(Opportunity_Tract__c oppTract : opportunityTractWrap.oppTracts){
            if(!oppTractId.isEmpty() && oppTractId.contains(oppTract.Id)){
                opportunityTractWrap.selectedOppTracts.add(oppTract);
            }                               
        }
        opportunityTractWrap.opps = [Select Id,Name from Opportunity Where Id In: opportunityIds];
        return opportunityTractWrap;
    }
    @AuraEnabled
    public static void associateOpportunityTracts(Id recordId,List<String> oppTractIds){

        set<String> selectedOppTracts = new Set<String>(oppTractIds);
        List<Opportunity_Tract__c> otList = new List<Opportunity_Tract__c>();
        for(String otId :selectedOppTracts ){
            system.debug(otId);
            system.debug(recordId);
            otList.add(new Opportunity_Tract__c(Id=otId,accountingInvestment__c = recordId));
        }
        if(!otList.isEmpty()){
            update otList;
        }
    }*/

	@AuraEnabled
    public static void updateRecordAssociation(Id recordId,Id inventoryAssetId, String change){
		System.debug('udpateAssociation called with parameters recordId: ' + recordId + ' inventoryAssetId: ' + inventoryAssetId + ' change: ' + change);
		InventoryAsset__c currentInventoryAsset = new InventoryAsset__c();
		currentInventoryAsset.Id = inventoryAssetId;
        switch on change{
			when 'Remove-'{
				currentInventoryAsset.accountingInvestment__c = null;
			}
			when 'Add+'{
				currentInventoryAsset.accountingInvestment__c = recordId;
			}
		}
		update currentInventoryAsset;
    }

	public class InventoryAssetSearchResult{
		@AuraEnabled
		public List<InventoryAsset__c> inventoryAssets {get;set;}
		@AuraEnabled
		public Integer searchCounter {get;set;}

		public InventoryAssetSearchResult(){
			inventoryAssets = new List<InventoryAsset__c>();
			searchCounter = 0;
		}
	}
    
    public class opportunityTractWrapper{
        
        @AuraEnabled
        public List<Opportunity_Tract__c> oppTracts{get;set;}
        @AuraEnabled
        public List<Opportunity_Tract__c> selectedOppTracts{get;set;}
        @AuraEnabled
        public List<Opportunity> opps{get;set;}
        
    }

	public class OpportunitySearchResult{
		@AuraEnabled
		public List<InventoryAsset__c> inventoryAssets{get;set;}
		@AuraEnabled
		public List<Opportunity> opps{get;set;}
		@AuraEnabled
        public List<Opportunity_Tract__c> oppTracts{get;set;}

		public OpportunitySearchResult(){
			inventoryAssets = new List<InventoryAsset__c>();
			opps = new List<Opportunity>();
			oppTracts = new List<Opportunity_Tract__c>();
		}

	}
}