src/objects/AccountingTransaction__c.object
<CustomObject>
    <fields>
        <fullName>reconciliationTypeLock__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should be set to true when user manually updates Reconciliation Type and used to prevent import records from overwriting user&apos;s manual selection.</description>
        <label>Reconciliation Type Lock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>reconciliationType__c</fullName>
        <label>Reconciliation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost</fullName>
                    <default>true</default>
                    <label>Cost</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>updateFromImport__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System variable set during import routine temporarily to determine when an update is being triggered by the import process vs. a manual update by a user in the interface.</description>
        <label>Update from Import</label>
        <type>Checkbox</type>
    </fields>
    <label>Accounting Transaction</label>
    <nameField>
        <displayFormat>AT-{0000000000}</displayFormat>
        <label>Accounting Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountingTransactionTriggerHelper.cls
public class AccountingTransactionTriggerHelper  {

	public static void handleReconciliationTypeUpdate(List<AccountingTransaction__c> oldList, Map<Id,AccountingTransaction__c> oldMap, List<AccountingTransaction__c> newList, Map<Id, AccountingTransaction__c> newMap){
		for (AccountingTransaction__c at: newList) {
			//Check to see if reconciliation type has changed
			if(oldMap.get(at.Id).reconciliationType__c != newMap.get(at.Id).reconciliationType__c){
				//Check to see if update is from import or not
				if(newMap.get(at.Id).updateFromImport__c){
					//If import check to see if record is locked
					if(newMap.get(at.Id).reconciliationTypeLock__c){
						//If record is locked reset value back to previous
						newMap.get(at.Id).reconciliationType__c = oldMap.get(at.Id).reconciliationType__c;
					}
				}
				//If update is not from import lock the record for future updates.
				else{
					newMap.get(at.Id).reconciliationTypeLock__c = true;
				}	
			}
			//Set updateFromImport = false on the actual record.  This field should never get committed as true.
			newMap.get(at.Id).updateFromImport__c = false;
		}
	
	}
}