src/objects/boSRPFieldHistory__b.object
<CustomObject>
    <fields>
        <fullName>action__c</fullName>
        <description>What type of action was taken on the primary record - usually either update or delete.</description>
        <label>Action</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fieldNameIndex__c</fullName>
        <description>Stores the first 40 characters of the field name for index purposes. If a delete operation, populate with &quot;NA&quot; as the entire record will be deleted, but this field will be necessary for the index portion of a custom big object.</description>
        <label>Field Name Index</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>historyCreatedDate__c</fullName>
        <description>Populate with same value as normal Created Date - necessary for index on Big Object.</description>
        <label>History Created Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>recordId__c</fullName>
        <description>Stores the record Id of the primary object being modified.</description>
        <label>Record Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectNameIndex__c</fullName>
        <description>Stores the type of the primary object.</description>
        <label>SObject Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SRP Field History</label>
    <pluralLabel>SRP Field Histories</pluralLabel>
</CustomObject>

src/objects/SRPFieldHistoryConversionSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store values to control SRP Field History Conversion to Big Object SRP Field History records</description>
    <fields>
        <fullName>deleteCronTriggerId__c</fullName>
        <label>deleteCronTriggerId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>deleteSObjectNameIndex__c</fullName>
        <label>DeleteSObjectNameIndex</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>deleteSize__c</fullName>
        <label>DeleteSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>minutesBetweenRuns__c</fullName>
        <description>Number of minutes to delay before running the next scheduled group if items remain.</description>
        <label>Minutes Between Runs</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SRP Field History Conversion Settings</label>
</CustomObject>

src/classes/DeleteSRPFieldHistory.cls
public class DeleteSRPFieldHistory  {

	private List<boSRPFieldHistory__b> deleteList {get; set;}
	private List<CronTrigger>currentSchedule {get; set;}
	private Boolean runAgain {get; set;}
	private SRPFieldHistoryConversionSettings__c conversionSettings{get; set;}
	private String nextRunTime {get; set;}

	public DeleteSRPFieldHistory(){
		this.deleteList = new List<boSRPFieldHistory__b>();
		this.runAgain = true;
		//Kill existing schedule and calculate next run time
		conversionSettings = SRPFieldHistoryConversionSettings__c.getOrgDefaults();
		Integer addMinutes = Integer.valueOf(conversionSettings.minutesBetweenRuns__c);
		Integer deleteSize = Integer.valueOf(conversionSettings.deleteSize__c);
		String sObjectNameIndex = conversionSettings.deleteSObjectNameIndex__c;
		this.deleteList.addAll([SELECT action__c,fieldNameIndex__c,historyCreatedDate__c,recordId__c,sObjectNameIndex__c FROM boSRPFieldHistory__b WHERE sObjectNameIndex__c = :sObjectNameIndex LIMIT :deleteSize]);
		if(this.deleteList.size() < deleteSize && !Test.isRunningTest()){
			this.runAgain = false;
		}
		Database.deleteImmediate(this.deleteList);

		if(conversionSettings.deleteCronTriggerId__c != null){
			currentSchedule = [SELECT ID FROM CronTrigger WHERE ID = :conversionSettings.deleteCronTriggerId__c];
			if(currentSchedule.size()>0){
				System.abortJob(conversionSettings.deleteCronTriggerId__c);
			}
		}
		
		
		

		if(runAgain){
			nextRunTime = '0 ' + String.valueOf(System.now().addMinutes(addMinutes).minute()) + ' ' + String.valueOf(System.now().addMinutes(addMinutes).hour() + ' ' + String.valueOf(System.now().addMinutes(addMinutes).day()) + ' ' + String.valueOf(System.now().addMinutes(addMinutes).month()) + ' ? ' + String.valueOf(System.now().addMinutes(addMinutes).year())  );
			srpFieldHistoryDeleteSchedule deleteHandler = new srpFieldHistoryDeleteSchedule(); //Schedule apex class name
			conversionSettings.deleteCronTriggerId__c = system.schedule('SRP Field History Delete', nextRunTime, deleteHandler);
			
		}
		else{
			conversionSettings.deleteCronTriggerId__c = '';
		}
		update conversionSettings;

	}
}