src/objects/boSRPFieldHistory__b.object
<CustomObject>
    <fields>
        <fullName>action__c</fullName>
        <description>What type of action was taken on the primary record - usually either update or delete.</description>
        <label>Action</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>changedBy__c</fullName>
        <description>Lookup value to the user that initiated the record change.</description>
        <label>Changed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>boSRPFieldHistories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fieldLabel__c</fullName>
        <description>The label of the updated field.  Please note this value will be stored as a text representation and will not reflect updates to the field label after the history record is created.</description>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fieldNameIndex__c</fullName>
        <description>Stores the first 40 characters of the field name for index purposes. If a delete operation, populate with &quot;NA&quot; as the entire record will be deleted, but this field will be necessary for the index portion of a custom big object.</description>
        <label>Field Name Index</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fieldName__c</fullName>
        <description>Used to store the API Name of the field referenced.</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>historyCreatedDate__c</fullName>
        <description>Populate with same value as normal Created Date - necessary for index on Big Object.</description>
        <label>History Created Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>isReference__c</fullName>
        <description>Field would normally be a checkbox field type which relates to a boolean field.  Neither option is available on Big Objects, so utilizing text field that should be populated with &quot;true&quot; or &quot;false&quot;</description>
        <label>Is Reference</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>newId__c</fullName>
        <description>Used when the update involves a reference or lookup field being changed.  Should only be populated when isReference is also &quot;true&quot;. Stores the Id of the newly referenced object.</description>
        <label>New Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>newValue__c</fullName>
        <description>Holds the updated value from the record or if the field is a reference or lookup field, the value from the name field of the new referenced object.</description>
        <label>New Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>oldId__c</fullName>
        <description>Used when the update involves a reference or lookup field being changed. Should only be populated when isReference is also &quot;true&quot;.  Stores the Id of the previous referenced object.</description>
        <label>Old Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>oldValue__c</fullName>
        <description>Holds the previous value from the record or if the field is a reference or lookup field, the value from the name field of the previously referenced object.</description>
        <label>Old Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>recordId__c</fullName>
        <description>Stores the record Id of the primary object being modified.</description>
        <label>Record Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>recordName__c</fullName>
        <description>Stores the Name of the primary record being modified at time of modification.  Will not capture future updates to the record&apos;s name.</description>
        <label>Record Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>referenceSObjectType__c</fullName>
        <description>Stores the type of referenced object.  Should only be populated if Is Reference value is true.</description>
        <label>Reference SObject Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectNameIndex__c</fullName>
        <description>Stores the type of the primary object.</description>
        <label>SObject Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <description>Stores the type of the primary object.</description>
        <label>SObject Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SRP Field History</label>
    <pluralLabel>SRP Field Histories</pluralLabel>
</CustomObject>

src/objects/srpFieldHistory__c.object
<CustomObject>
    <description>Used for storing history of changes by object and field.</description>
    <fields>
        <fullName>action__c</fullName>
        <description>Should be either Updated or Deleted.</description>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>changedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the User that made the change</description>
        <label>Changed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SRP_Field_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fieldLabel__c</fullName>
        <description>Stores the field Label at time of history item creation.</description>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fieldName__c</fullName>
        <description>Name of the field on the related Record that was changed.</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isReference__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine if the field history is actually a reference value to another field.  If this is true, oldId and newId fields should be populated.</description>
        <label>Is Reference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>newId__c</fullName>
        <description>Used to store the new Id value of the referenced object.</description>
        <label>New Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>newValue__c</fullName>
        <description>The value of the field after change</description>
        <label>New Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>oldId__c</fullName>
        <description>Used to store the previous Id of the related object.</description>
        <label>Old Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>oldValue__c</fullName>
        <description>The value of the field before the change</description>
        <label>Old Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>recordId__c</fullName>
        <externalId>true</externalId>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>recordName__c</fullName>
        <label>Record Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>referenceSObjectType__c</fullName>
        <description>If history is for a reference field, store the type of the object that has changed.</description>
        <label>Reference SObject Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <label>SObject Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>SRP Field History</label>
    <nameField>
        <label>SRP Field History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SRP Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/boSRPFieldHistoryUtility.cls
public class boSRPFieldHistoryUtility {
	
	public static void boSRPHistoryCreate(List<srpFieldHistory__c> newEntries){
		List<boSRPFieldHistory__b> newHistories = new List<boSRPFieldHistory__b>();
		for(srpFieldHistory__c newEntry: newEntries){
			boSRPFieldHistory__b newHistory = new boSRPFieldHistory__b();
			newHistory.action__c = newEntry.action__c;
			if(newEntry.fieldName__c == null){
				newHistory.fieldNameIndex__c = 'NA';
			}
			else{
				newHistory.fieldNameIndex__c = newEntry.fieldName__c.left(30);
			}
			newHistory.fieldName__c = newEntry.fieldName__c;
			newHistory.recordName__c = newEntry.recordName__c;
			newHistory.sObjectName__c = newEntry.sObjectName__c;
			newHistory.referenceSObjectType__c = newEntry.referenceSObjectType__c;
			newHistory.historyCreatedDate__c = newEntry.CreatedDate;
			if(newEntry.sObjectName__c == null){
				newHistory.sObjectNameIndex__c = 'UNKNOWN';
			}
			else{
				newHistory.sObjectNameIndex__c = newEntry.sObjectName__c.left(30);
			}
			newHistory.recordId__c = newEntry.recordId__c;
			newHistory.changedBy__c = newEntry.changedBy__c;
			newHistory.fieldLabel__c = newEntry.fieldLabel__c;
			newHistory.isReference__c = String.valueOf(newEntry.isReference__c);
			newHistory.oldId__c = newEntry.oldId__c;
			newHistory.oldValue__c = newEntry.oldValue__c;
			newHistory.newId__c = newEntry.newId__c;
			newHistory.newValue__c = newEntry.newValue__c;
			newHistories.add(newHistory);
		}

		boSRPFieldHistoryHandler handler = new boSRPFieldHistoryHandler(newHistories, newEntries, false);
		//if(!Test.isRunningTest()){
			System.enqueueJob(handler);
		//}

	}
	
}