src/objects/boSRPFieldHistory__b.object
<CustomObject>
    <fields>
        <fullName>action__c</fullName>
        <description>What type of action was taken on the primary record - usually either update or delete.</description>
        <label>Action</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fieldNameIndex__c</fullName>
        <description>Stores the first 40 characters of the field name for index purposes. If a delete operation, populate with &quot;NA&quot; as the entire record will be deleted, but this field will be necessary for the index portion of a custom big object.</description>
        <label>Field Name Index</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>historyCreatedDate__c</fullName>
        <description>Populate with same value as normal Created Date - necessary for index on Big Object.</description>
        <label>History Created Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>recordId__c</fullName>
        <description>Stores the record Id of the primary object being modified.</description>
        <label>Record Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectNameIndex__c</fullName>
        <description>Stores the type of the primary object.</description>
        <label>SObject Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SRP Field History</label>
    <pluralLabel>SRP Field Histories</pluralLabel>
</CustomObject>

src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Find Royalty Check</fullName>
                </value>
                <value>
                    <fullName>Delete Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Read Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Insert Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Upsert</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                    <default>true</default>
                    <label>Error</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SRPFieldHistoryConversionSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store values to control SRP Field History Conversion to Big Object SRP Field History records</description>
    <fields>
        <fullName>beginDeleteId__c</fullName>
        <label>BeginDeleteId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>deleteCronTriggerId__c</fullName>
        <label>deleteCronTriggerId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>deleteSObjectNameIndex__c</fullName>
        <label>DeleteSObjectNameIndex</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>deleteSize__c</fullName>
        <label>DeleteSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>minutesBetweenRuns__c</fullName>
        <description>Number of minutes to delay before running the next scheduled group if items remain.</description>
        <label>Minutes Between Runs</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>referenceIdGroupSize__c</fullName>
        <label>Reference Id Group Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SRP Field History Conversion Settings</label>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DeleteTractFormulaHistory.cls
public class DeleteTractFormulaHistory  {
	
	private List<boSRPFieldHistory__b> deleteList {get; set;}
	private List<CronTrigger>currentSchedule {get; set;}
	private Boolean runAgain {get; set;}
	private SRPFieldHistoryConversionSettings__c conversionSettings{get; set;}
	private String nextRunTime {get; set;}
	private List<Tract__c> targetedTracts {get; set;}
	private Id beginTractId {get; set;}
	private List<Id> tractIdList {get; set;}
	private List<String> formulaFieldNames {get; set;}

	public DeleteTractFormulaHistory(){
		
		
		this.deleteList = new List<boSRPFieldHistory__b>();
		this.formulaFieldNames = new List<String>();
		this.targetedTracts = new List<Tract__c>();
		this.currentSchedule = new List<CronTrigger>();
		this.tractIdList = new List<Id>();

		this.runAgain = true;
		try{
			//Kill existing schedule and calculate next run time
			conversionSettings = SRPFieldHistoryConversionSettings__c.getOrgDefaults();
			Integer addMinutes = Integer.valueOf(conversionSettings.minutesBetweenRuns__c);
			Integer deleteSize = Integer.valueOf(conversionSettings.deleteSize__c);
			String sObjectNameIndex = conversionSettings.deleteSObjectNameIndex__c;
			describerUtil describerUtility = new describerUtil();
			Integer relatedRecordCount = Integer.valueOf(conversionSettings.referenceIdGroupSize__c);
			describerUtility.selectedObject = conversionSettings.deleteSObjectNameIndex__c;
			Map<String, Schema.SObjectField> fieldMap = describerUtility.getFields();
			this.beginTractId = conversionSettings.beginDeleteId__c;
		
			for(String fieldName: fieldMap.keySet()){
				//System.debug('Field Name is: '+  fieldName + ' isCalculated value is: ' + fieldMap.get(fieldName).getDescribe().isCalculated());
				if(fieldMap.get(fieldName).getDescribe().isCalculated()){
					//System.debug('Field ' + fieldName + ' is a formula field');
					this.formulaFieldNames.add(fieldName);
				}
				else{
					//System.debug('Field ' + fieldName + ' is NOT a formula field');
				}
			}
			this.targetedTracts.addAll([SELECT Id FROM Tract__c WHERE Id >= :beginTractId ORDER BY Id LIMIT 51]);

			for(Integer i = 0; i < relatedRecordCount; i++){
				if(targetedTracts.size() > i){
					this.tractIdList.add(targetedTracts[i].Id);
				}
			}
			this.deleteList.addAll([SELECT action__c,fieldNameIndex__c,historyCreatedDate__c,recordId__c,sObjectNameIndex__c FROM boSRPFieldHistory__b WHERE sObjectNameIndex__c = :sObjectNameIndex AND recordId__c IN :tractIdList LIMIT :deleteSize]);
			System.debug('Initial deleteList size is: ' + deleteList.size());
			//System.debug('Targeted Tract size is: ' + this.targetedTracts.size());
			//If all records were checked and at end of list of tracts, don't run again.
			if(this.deleteList.size() < deleteSize && !Test.isRunningTest() && this.tractIdList.size() < relatedRecordCount){
				this.runAgain = false;
			}
			//If all history records for the current list were checked, increment the group size up to 50 and start the next run with the next tract record.
			else if(this.deleteList.size() < deleteSize && !Test.isRunningTest() && this.tractIdList.size() == relatedRecordCount){
				conversionSettings.beginDeleteId__c = targetedTracts[relatedRecordCount].Id;	
				conversionSettings.referenceIdGroupSize__c = conversionSettings.referenceIdGroupSize__c + 1;
				if(conversionSettings.referenceIdGroupSize__c >= 50){
					conversionSettings.referenceIdGroupSize__c = 50;
				}
			}
			//If delete list and maximum size are equal - special handling
			else if(this.deleteList.size() == deleteSize && !Test.isRunningTest()){
				
				//If the current size is already 1, not able to check all records.  Leave the setting at 1 and check the next record.
				if (conversionSettings.referenceIdGroupSize__c <= 1){
					conversionSettings.referenceIdGroupSize__c = 1;
					System.debug('next target is: ' + targetedTracts[tractIdList.size()].Id + ' tractIdList size is: ' + tractIdList.size());
					conversionSettings.beginDeleteid__c = targetedTracts[tractIdList.size()].Id;
				}
				//If the current size is larger than one, decrement the group size and start with the same record. 
				else{
					conversionSettings.referenceIdGroupSize__c = conversionSettings.referenceIdGroupSize__c - 1;
					//conversionSettings.beginDeleteid__c = targetedTracts[tractIdList.size()-1].Id;
				}
			}
			for(Integer i = 0; i < this.deleteList.size(); ){
			//for(boSRPFieldHistory__b currentHistory: deleteList){
				//System.debug('current value of i is: ' + i + ' fieldNameIndex__c value is: ' + this.deleteList[i].fieldNameIndex__c + ' formulaFieldNames not contains field value is: ' + !this.formulaFieldNames.contains(this.deleteList[i].fieldNameIndex__c));
				if(!this.formulaFieldNames.contains(this.deleteList[i].fieldNameIndex__c)){
					this.deleteList.remove(i);
				}
				else{
					i++;
				}
			}
			System.debug('Final deletelist size is: ' + this.deleteList.size());
			Database.deleteImmediate(this.deleteList);
			update conversionSettings;
			if(conversionSettings.deleteCronTriggerId__c != null){
				currentSchedule = [SELECT ID FROM CronTrigger WHERE ID = :conversionSettings.deleteCronTriggerId__c];
				if(currentSchedule.size()>0){
					System.abortJob(conversionSettings.deleteCronTriggerId__c);
				}
			}
		
		
		

			if(runAgain){
				nextRunTime = '0 ' + String.valueOf(System.now().addMinutes(addMinutes).minute()) + ' ' + String.valueOf(System.now().addMinutes(addMinutes).hour() + ' ' + String.valueOf(System.now().addMinutes(addMinutes).day()) + ' ' + String.valueOf(System.now().addMinutes(addMinutes).month()) + ' ? ' + String.valueOf(System.now().addMinutes(addMinutes).year())  );
				DeleteTractFormulaHistorySchedule deleteHandler = new DeleteTractFormulaHistorySchedule(); //Schedule apex class name
				conversionSettings.deleteCronTriggerId__c = system.schedule('SRP Tract Formula Field History Delete', nextRunTime, deleteHandler);
				System.debug('SRP Tract Formula Field History Delete Scheduled Job Id is: ' + conversionSettings.deleteCronTriggerId__c);
			
			}
			else{
				conversionSettings.deleteCronTriggerId__c = '';
			}
			update conversionSettings;
		}

		catch (Exception e) {
            Log__c log = new Log__c();                                                    
            log.Process__c = 'Delete Tract Formula History';
            log.Status__c = 'Error';
            log.Error_Message__c = e.getMessage();
            log.Stack_Trace__c = e.getStackTraceString();
            upsert log;
            System.debug('Exception: ' + e.getTypeName() + ', ' + e.getMessage());
            
        }

	}
}