src/objects/boSRPFieldHistory__b.object
<CustomObject>
    <fields>
        <fullName>action__c</fullName>
        <description>What type of action was taken on the primary record - usually either update or delete.</description>
        <label>Action</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fieldNameIndex__c</fullName>
        <description>Stores the first 40 characters of the field name for index purposes. If a delete operation, populate with &quot;NA&quot; as the entire record will be deleted, but this field will be necessary for the index portion of a custom big object.</description>
        <label>Field Name Index</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>historyCreatedDate__c</fullName>
        <description>Populate with same value as normal Created Date - necessary for index on Big Object.</description>
        <label>History Created Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>recordId__c</fullName>
        <description>Stores the record Id of the primary object being modified.</description>
        <label>Record Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectNameIndex__c</fullName>
        <description>Stores the type of the primary object.</description>
        <label>SObject Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <description>Stores the type of the primary object.</description>
        <label>SObject Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SRP Field History</label>
    <pluralLabel>SRP Field Histories</pluralLabel>
</CustomObject>

src/objects/srpFieldHistory__c.object
<CustomObject>
    <description>Used for storing history of changes by object and field.</description>
    <fields>
        <fullName>action__c</fullName>
        <description>Should be either Updated or Deleted.</description>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>conversionErrorCount__c</fullName>
        <description>Stores the number of times this record has been attempted to convert to Big Object.</description>
        <label>Conversion Error Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>recordId__c</fullName>
        <externalId>true</externalId>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <label>SObject Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>SRP Field History</label>
    <nameField>
        <label>SRP Field History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SRP Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SRPFieldHistoryConversionSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store values to control SRP Field History Conversion to Big Object SRP Field History records</description>
    <fields>
        <fullName>beginDeleteId__c</fullName>
        <label>BeginDeleteId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>conversionSize__c</fullName>
        <description>Number of records to process in a single run.</description>
        <label>Conversion Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>deleteSize__c</fullName>
        <label>DeleteSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>referenceIdGroupSize__c</fullName>
        <label>Reference Id Group Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SRP Field History Conversion Settings</label>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>netAcres__c</fullName>
        <label>Net Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/srpFieldHistoryTest.cls
//Provides test coverage for multiple classes including:
	//srpFieldHistoryConversion
	//srpFieldHistoryConversionSchedule
	//srpFieldHistoryDeleteSchedule
	//srpFieldHistoryUtility
	//SRPFieldHistoryTrigger
	//DeleteSRPFieldHistory
	//srpFieldHistoryRelatedListAura
@isTest 
private class srpFieldHistoryTest {

	@TestSetup
	static void tractReconciliationTestData(){
		TestDataFactory.dataSetup();
	}

	@isTest
	private static void mainMethod() {
		SRPFieldHistoryConversionSettings__c conversionSettings = SRPFieldHistoryConversionSettings__c.getOrgDefaults();
		List<Tract__c> allTracts = [SELECT ID FROM Tract__c];
		conversionSettings.deleteSize__c = 40000;
		conversionSettings.beginDeleteId__c = allTracts[0].Id;
		conversionSettings.referenceIdGroupSize__c = 5;
		Account a = new Account(Name = 'New Test Account');
		insert a;
		List<CronTrigger> currentTrigger = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'SRP Field History Conversion'];
		if(currentTrigger.size() > 0){
			System.abortJob(currentTrigger[0].Id);
		}
		currentTrigger = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'SRP Field History Delete'];
		if(currentTrigger.size() > 0){
			System.abortJob(currentTrigger[0].Id);
		}
		currentTrigger = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'SRP Tract Formula Field History Delete'];
		if(currentTrigger.size() > 0){
			System.abortJob(currentTrigger[0].Id);
		}
		System.debug('Count of Tracts is: ' + allTracts.size());
		for(Tract__c tract: allTracts){
			tract.netAcres__c = 5;
			tract.Account__c = a.Id; 
		}
		update allTracts;
		List<Tract__c> newTract = TestDataFactory.createTracts(1, a);
		insert newTract;
		delete newTract;
		List<srpFieldHistory__c> originalRegularHistory = [SELECT ID FROM srpFieldHistory__c];
		originalRegularHistory[0].conversionErrorCount__c = 5;
		update originalRegularHistory;
		Test.startTest();
		srpFieldHistoryConversion conversion = new srpFieldHistoryConversion();
		conversionSettings.conversionSize__c = 1000;
		update conversionSettings;
		currentTrigger = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'SRP Field History Conversion'];
		if(currentTrigger.size() > 0){
			System.abortJob(currentTrigger[0].Id);
		}
		srpFieldHistoryConversion newConversion = new srpFieldHistoryConversion();
		//DeleteTractFormulaHistorySchedule deleteHandler = new DeleteTractFormulaHistorySchedule();
		DeleteTractFormulaHistory newTractDeletion = new DeleteTractFormulaHistory();
		DeleteSRPFieldHistory newDeletion = new DeleteSRPFieldHistory();
		
		Test.stopTest();
		List<srpFieldHistory__c> regularHistory = [SELECT ID FROM srpFieldHistory__c];
		List<boSRPFieldHistory__b> bigObjectHistory = [SELECT action__c,CreatedById,CreatedDate,fieldNameIndex__c,historyCreatedDate__c,Id,recordId__c,sObjectNameIndex__c,sObjectName__c FROM boSRPFieldHistory__b];
		List<boSRPFieldHistory__b> componentHistory = srpFieldHistoryRelatedListAura.getRelatedHistory(allTracts[0].Id, 'Tract__c');
		System.debug('regularHistory size is: ' + regularHistory.size() + ' bigObjectHistory size is: ' + bigObjectHistory.size());
		
	}
	



}