src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FMV_Per_Acre__c</fullName>
        <description>Sum of all FMV divided by Total Acres for related tracts</description>
        <formula>if (Total_Acreage__c = 0,0, Total_FMV__c /  Total_Acreage__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Sum of all FMV divided by Total Acres for related tracts</inlineHelpText>
        <label>FMV Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gain_on_Asset__c</fullName>
        <description>Gain on sale (Total FMV - Total Cost)</description>
        <formula>Total_FMV__c - Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gain on sale (Total FMV - Total Cost)</inlineHelpText>
        <label>Gain on Asset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <formula>if(Total_Cost__c = 0, 0, Total_Cost__c /  Total_Acreage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Sum of all &quot;Total Cost&quot; fields</description>
        <label>Total Cost</label>
        <summarizedField>Opportunity_Tract__c.Total_Cost__c</summarizedField>
        <summaryForeignKey>Opportunity_Tract__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>FMV_Per_Acre__c</fullName>
        <label>FMV Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gain_on_Asset__c</fullName>
        <label>Gain on Asset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes from tract record</description>
        <label>Notes</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <description>OTG = &quot;Off the Ground&quot; - how much was paid to the previous owner (does not include commissions, title costs etc.)</description>
        <inlineHelpText>OTG = &quot;Off the Ground&quot; - how much waspaid to the previous owner (does not include commissions, title costs etc.)</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTG_Cost__c</fullName>
        <description>Cost per acre copied from tract for roll up calculations</description>
        <label>OTG Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Copied from Tract used for roll up calculations</description>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tract_Acres__c</fullName>
        <label>Tract Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Grid_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this option if the legal description cannot correctly be mapped based on quarter calls and/or lots</inlineHelpText>
        <label>Grid Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lot__c</fullName>
        <label>Lot</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subtract_Acres__c</fullName>
        <label>Subtract Acres</label>
        <precision>18</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subtract_Full_Legal_Description__c</fullName>
        <label>Subtract Full Legal Description</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subtract_Gross_Acres__c</fullName>
        <label>Subtract Gross Acres</label>
        <precision>18</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subtract_Quarter_Call__c</fullName>
        <label>Subtract Quarter Call</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Commission Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_Legal_Name__c</fullName>
        <formula>LandGridTract__r.Name  &amp; &apos; &apos; &amp; Quarter_Call__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gain_on_Asset__c</fullName>
        <formula>Fair_Market_Value__c -  Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>FMV - Total Cost</inlineHelpText>
        <label>Gain on Asset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grid_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has a quarter call that can not be automapped</description>
        <inlineHelpText>Has a quarter call that can not be automapped</inlineHelpText>
        <label>Grid Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gross_Acres__c</fullName>
        <label>Gross Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lots__c</fullName>
        <description>Lot detail</description>
        <inlineHelpText>Lot detail</inlineHelpText>
        <label>Lots</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <inlineHelpText>OTG Cost per Acre</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTG_Cost__c</fullName>
        <formula>netAcres__c * OTG_Cost_Per_Acre__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OTG Price per acre x Net Acres</inlineHelpText>
        <label>OTG Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Capitalized_Costs__c</fullName>
        <label>Other Capitalized Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quarter_Call__c</fullName>
        <inlineHelpText>Quarter Call</inlineHelpText>
        <label>Quarter Call</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subtract_Count__c</fullName>
        <label>Subtract Count</label>
        <summaryForeignKey>Subtract__c.Tract__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Title_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Title Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <formula>if (netAcres__c == 0,0,Total_Cost__c /  netAcres__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Costs divided by Net Acres</inlineHelpText>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>OTG Costs plus Commissions and title</description>
        <formula>(netAcres__c *  OTG_Cost_Per_Acre__c) +  Commission_Amount__c +  Title_Cost__c +  Other_Capitalized_Costs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OTG Costs plus Commissions and title</inlineHelpText>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_Per_Acre__c</fullName>
        <inlineHelpText>FMV for the tract</inlineHelpText>
        <label>FMV Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>aoiNetAcres__c</fullName>
        <description>Sum of net acres in AOI</description>
        <inlineHelpText>Sum of net acres in AOI</inlineHelpText>
        <label>AOI Net Acres</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>maxPrice__c</fullName>
        <description>Max Price for Tract</description>
        <inlineHelpText>Max Price for Tract</inlineHelpText>
        <label>Max Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>netAcres__c</fullName>
        <label>Net Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>percentCovered__c</fullName>
        <description>Sum of percentage in AOI for project AOI tract</description>
        <inlineHelpText>Sum of percentage in AOI for project AOI tract</inlineHelpText>
        <label>percentCovered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>targetPrice__c</fullName>
        <description>Sum of target price for Project AOI Tract</description>
        <inlineHelpText>Sum of target price for Project AOI Tract</inlineHelpText>
        <label>Target Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/tractHistory__c.object
<CustomObject>
    <description>Stores changes made to Tract Records.</description>
    <fields>
        <fullName>changedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the User that made the change</description>
        <label>Changed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tract_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fieldName__c</fullName>
        <description>Name of the field on the related Tract Record that was changed.</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>oldValue__c</fullName>
        <description>The value of the field before the change</description>
        <label>Old Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Tract record that was updated.</description>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Tract History Items</relationshipLabel>
        <relationshipName>tractHistoryItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tract History</label>
    <nameField>
        <label>Tract History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tract Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TractTriggerHelper.cls
public with sharing class TractTriggerHelper {

	//static variable value is also set to true by RHX_Project_AOI_Tract.trigger to prevent additional
	//trigger processing after updating Rollup Helper field values.
    //public static Boolean tractUpdating = false;
	//public static Set<String> rollupHelperFields = new Set<String> {'percentCovered__c', 'maxPrice__c', 'aoiNetAcres__c', 'targetPrice__c'};

	//Opportunity lock logic not implemented, commenting out this method (jdg 2-10-2020)
    /*public static void preventDelete(List<Opportunity_Tract__c> oldOppTracts, List<Opportunity_Tract__c> newOppTracts) {

        List<Opportunity_Tract__c> oppTracts = new List<Opportunity_Tract__c> ();
        if (oldOppTracts != null) {
            oppTracts.addAll(oldOppTracts);
        }
        if (newOppTracts != null) {
            oppTracts.addAll(newOppTracts);
        }

        if (oppTracts != null && oppTracts.size() > 0) {

            System.debug('newOTs' + oppTracts);

            Set<Id> oppIds = new Set<Id>();
            for (Opportunity_Tract__c ot : oppTracts) {
                if (ot.Opportunity__c != null)
                    oppIds.add(ot.Opportunity__c);
            }

            //System.debug('otIds: ' + otIds);
            List<Opportunity> opps = [SELECT Id, Locked__c FROM Opportunity WHERE Id IN: oppIds];

            Map<Id,Boolean> oppLockedMap = new Map<Id,Boolean>();
            for (Opportunity o : opps) {
                Boolean isLocked = o.Locked__c == true;
                oppLockedMap.put(o.Id,isLocked);
            }

            if (newOppTracts != null && newOppTracts.size() > 0) {
                // this is an update - can't put error on old version
                for (Opportunity_Tract__c ot : newOppTracts) {

                    if (oppLockedMap.containsKey(ot.Opportunity__c) && oppLockedMap.get(ot.Opportunity__c) == true) {
                        ot.addError('The related opportunity has been locked and opportunity tracts may not be modified.');
                    }
                }
            } else if (oldOppTracts != null && oldOppTracts.size() > 0) {
                for (Opportunity_Tract__c ot : oldOppTracts) {
                    if (oppLockedMap.containsKey(ot.Opportunity__c) && oppLockedMap.get(ot.Opportunity__c) == true) {
                        ot.addError('The related opportunity has been locked and opportunity tracts may not be modified.');
                    }
                }
            }
        }
    }*/

	//Changing duplicate to a unique text field that concatenates the two IDs and is populated via field updates.
    /*public static void preventDupes(List<Opportunity_Tract__c> newOpportunityTracts, Map<Id,Opportunity_Tract__c> oldMap) {

        // Build a list of changed tract ID or new tracts only
        List<Opportunity_Tract__c> modOTs = new List<Opportunity_Tract__c>();
        for (Opportunity_Tract__c ot : newOpportunityTracts) {
            if (oldMap == null || oldMap.containsKey(ot.Id) && (oldMap.get(ot.Id).Tract__c != ot.Tract__c)) {
                modOTs.add(ot);
            }
        }


        Set<Id> oppIds = new Set<Id>();
        Set<Id> tractIds = new Set<Id>();
        Map<String,Opportunity_Tract__c> otMap = new Map<String,Opportunity_Tract__c>();
        for (Opportunity_Tract__c ot : modOTs) {
            // This is either an INSERT (oldmap is null)
            // or an Update where the tract has changed

                oppIds.add(ot.Opportunity__c);
                tractIds.add(ot.Tract__c);
                if (otMap.containsKey(ot.Opportunity__c + ':' + ot.Tract__c)) {
                    ot.Tract__c.addError('Tract ' + ot.Tract__r.Name + ' is already in ' + ot.Opportunity__r.Name);
                } else {
                    otMap.put(ot.Opportunity__c + ':' + ot.Tract__c,ot);
                }

        }
        List<Opportunity_Tract__c> existingOTs = [SELECT Id,Opportunity__c,Tract__c,Tract__r.Name, Opportunity__r.Name
                        FROM Opportunity_Tract__c
                        WHERE
                            //Opportunity__r.Locked__c <>: TRUE AND
                            (Opportunity__c IN: oppIds OR Tract__c IN: tractIds)];

        for (Opportunity_Tract__c ot : existingOTs) {
            if (otMap.containsKey(ot.Opportunity__c + ':' + ot.Tract__c)) {
                Opportunity_Tract__c origOT = otMap.get(ot.Opportunity__c + ':' + ot.Tract__c);
                origOT.Tract__c.addError('Tract ' + ot.Tract__r.Name + ' is already in ' + ot.Opportunity__r.Name);
            }
        }


    }*/

    public static void deleteTractRelatedItems(Map<Id,Tract__c> oldMap) {

        System.debug('deleting opp/case tracts' + oldMap);

        if (oldMap != null && oldMap.size() > 0)
        {
            Set<Id> tractIds = oldMap.keySet();
            List<SObject> oppTracts = [SELECT Id FROM Opportunity_Tract__c WHERE Tract__c IN: tractIds];
            // TODO: Add this to support ignore of locked opps AND Opportunity__r.Locked__c = FALSE];
            //List<SObject> caseTracts = [SELECT Id FROM Case_Tract__c WHERE Tract__c IN: tractIds];
            System.debug('tract ids' + tractIds);
            System.debug('oppTracts' + oppTracts);
            //System.debug('caseTracts' + caseTracts);

            List<SObject> itemsToDelete = new List<SObject>();
            itemsToDelete.addAll(oppTracts);
            //itemsToDelete.addAll(caseTracts);
            //tractUpdating = true;
            delete itemsToDelete;
        }
    }
    // Static variable to prevent infinite recursion - when a tract is updating the Opp Tract / Case Tract,
    // the Opp Tract and Case Tract triggers should not fire.
    public static void recalcTractRelatedItems(Map<Id,Tract__c> newMap, Map<Id,Tract__c> oldMap)
    {
        system.debug('------TRACTTRIGGERHELPER');
		if(oldMap != null){
			Map<Id, Tract__c> acreageUpdate = new Map<Id, Tract__c>();
			for(Id tractId : newMap.keySet()){
				if(newMap.get(tractId).netAcres__c != oldMap.get(tractId).netAcres__c){
					acreageUpdate.put(tractId, newMap.get(tractId));
				}
			}
			if (acreageUpdate.size() > 0){
			System.debug('Calling batch for ' + acreageUpdate.size() + ' records.');
				Id batchInstanceId = Database.executeBatch(new batchUpdateProjectAOITracts(null, Trigger.newMap.keySet()));
			}
		}
        // After the tract(s) have been updated, find ALL parent caseTracts, ALL parent oppTracts
        // Replaces Sync Tract Info process builder
        Set<Id> tractIds = newMap.keySet();
        System.debug('tract ids' + tractIds);
        //List<Case_Tract__c> caseTracts = [SELECT Id,Tract__c FROM Case_Tract__c WHERE Tract__c IN: tractIds];
        List<Opportunity_Tract__c> oppTracts = [SELECT Id, Tract__c, FMV_Per_Acre__c, OTG_Cost_Per_Acre__c, 
												Total_Cost__c, Total_Cost_Per_Acre__c, Tract_Acres__c, OTG_Cost__c, Notes__c, Gain_on_Asset__c
												FROM Opportunity_Tract__c WHERE Tract__c IN: tractIds];

			
        //TODO: Use this to support locking: List<Opportunity_Tract__c> oppTracts = [SELECT Id, Tract__c FROM Opportunity_Tract__c WHERE Tract__c IN: tractIds AND Opportunity__r.Locked__c =: FALSE];
        List<Subtract__c> subTracts = [SELECT Id,Subtract_Gross_Acres__c, Subtract_Acres__c,Tract__c, Subtract_Quarter_Call__c, Subtract_Full_Legal_Description__c, Lot__c, Grid_Exception__c  
										FROM Subtract__c 
										WHERE Tract__c IN: tractIds];

        System.debug('oppTracts' + oppTracts);

        Map<Id,Tract__c> tractMap = getTractsbyIds(tractIds);

        System.debug('theTracts'+tractMap);
        List<SObject> itemsToUpdate = new List<SObject>();

        for (Opportunity_Tract__c ot : oppTracts)
        {
            Tract__c tract = tractMap.get(ot.Tract__c);
				
			Boolean oppTractUpdated  = setOppTractFields(ot,tract);
			System.debug('oppTractUpdated value is: ' + oppTractUpdated);
            if(oppTractUpdated){
				itemsToUpdate.add(ot);
			}
        }

		//Removing updates to Case Tracts per Quin (jdg 02-10-2020)
        /*for (Case_Tract__c ct : caseTracts)
        {
            Tract__c tract = tractMap.get(ct.Tract__c);
            setCaseTractFields(ct,tract);
            itemsToUpdate.add(ct);
        }*/

        for (Subtract__c st : subTracts)
        {

            Tract__c tract = tractMap.get(st.Tract__c);
            if (tract.Subtract_Count__c == 1) {
                // Copy one to one only!
				//Only modify if an update is needed
				if((st.Subtract_Acres__c != tract.netAcres__c)||(st.Subtract_Gross_Acres__c != tract.Gross_Acres__c)||(st.Subtract_Quarter_Call__c != tract.Quarter_Call__c)||
					(st.Subtract_Full_Legal_Description__c != tract.Full_Legal_Name__c)||(st.Lot__c != tract.Lots__c)||(st.Grid_Exception__c != tract.Grid_Exception__c)){
						st.Subtract_Acres__c = tract.netAcres__c;
						st.Subtract_Gross_Acres__c = tract.Gross_Acres__c;
						st.Subtract_Quarter_Call__c = tract.Quarter_Call__c;
						st.Subtract_Full_Legal_Description__c = tract.Full_Legal_Name__c;
						st.Lot__c = tract.Lots__c;
						st.Grid_Exception__c = tract.Grid_Exception__c;
						itemsToUpdate.add(st);
				}
            }
        }

        // Create a 1:1 subtract if it was deleted, or not created for any reason
        List<Subtract__c> newSubtracts = new List<Subtract__c>();
        for (Id tractId : tractMap.keySet()) {
            Tract__c t = tractMap.get(tractId);
            if (t.Subtract_Count__c == 0) {
                Subtract__c st = new Subtract__c(
                        Subtract_Acres__c = t.netAcres__c,
                        Subtract_Gross_Acres__c = t.Gross_Acres__c,
                        Subtract_Quarter_Call__c = t.Quarter_Call__c,
                        Subtract_Full_Legal_Description__c = t.Full_Legal_Name__c,
                        Lot__c = t.Lots__c,
                        Grid_Exception__c = t.Grid_Exception__c,
                        Tract__c = tractId
                );
                newSubtracts.add(st);
            }
        }



        System.debug('itemstoUdpate: ' + itemsToUpdate);
        System.debug('newSubtracts: ' + newSubtracts.size());
        System.debug('recalcing');
        //tractUpdating = true;
        update itemsToUpdate;
        if(newSubtracts.size()>0){
            insert newSubtracts;
        }
    }

    private static boolean setOppTractFields(Opportunity_Tract__c ot, Tract__c tract)
    {
		Boolean updated = false;
		if((ot.FMV_Per_Acre__c != tract.Value_Per_Acre__c)||(ot.OTG_Cost_Per_Acre__c != tract.OTG_Cost_Per_Acre__c)||
		   (ot.Total_Cost__c != tract.Total_Cost__c)||
		   (ot.Total_Cost_Per_Acre__c != tract.Total_Cost_Per_Acre__c)||(ot.Tract_Acres__c != tract.netAcres__c)||(ot.OTG_Cost__c != tract.OTG_Cost__c)||
		   (ot.Notes__c != tract.Notes__c)||(ot.Gain_on_Asset__c != tract.Gain_on_Asset__c)){
				updated = true;
				//ot.Commission_Amount__c = tract.Commission_Amount__c;
				ot.FMV_Per_Acre__c = tract.Value_Per_Acre__c;
				ot.OTG_Cost_Per_Acre__c = tract.OTG_Cost_Per_Acre__c;
				//ot.Other_Capitalized_Costs__c = tract.Other_Capitalized_Costs__c;
				//ot.Title_Cost__c = tract.Title_Cost__c;
				ot.Total_Cost__c = tract.Total_Cost__c;
				ot.Total_Cost_Per_Acre__c = tract.Total_Cost_Per_Acre__c;
				ot.Tract_Acres__c = tract.netAcres__c;
				ot.OTG_Cost__c = tract.OTG_Cost__c;
				ot.Notes__c = tract.Notes__c;
				ot.Gain_on_Asset__c = tract.Gain_on_Asset__c;
			}
		return updated;
    }

    /*public static void recalcByCaseTract(List<Case_Tract__c> newCaseTracts)
    {
        if (newCaseTracts != null && newCaseTracts.size() > 0)
        {
            Set<Id> tractIds = new Set<Id>();
            for (Case_Tract__c ct : newCaseTracts)
            {
                tractIds.add(ct.Tract__c);
            }

            Map<Id,Tract__c> tractMap = getTractsbyIds(tractIds);

            for (Case_Tract__c ct : newCaseTracts)
            {
                setCaseTractFields(ct,tractMap.get(ct.Tract__c));
            }

        }
    }*/

	/*public static void tractHistoryCreate(List<Tract__c> triggerNew, List<Tract__c> triggerOld, Map<Id, Tract__c> newMap, Map<Id, Tract__c> oldMap){
		List<tractHistory__c> newHistory = new List<tractHistory__c>();
		describerUtil describerUtility = new describerUtil();
		describerUtility.selectedObject = 'Tract__c';
		Map<String, Schema.SObjectField> fieldMap = describerUtility.getFields();
		Boolean rollupHelperOnly = true;
		for(Id updateId: newMap.keySet()){
			for(String fieldName: fieldMap.keySet()){
				if(newMap.get(updateId).get(fieldName) != oldMap.get(updateId).get(fieldName)){
					tractHistory__c newHistoryItem = new tractHistory__c();
					newHistoryItem.fieldName__c = fieldName;
					newHistoryItem.changedBy__c = UserInfo.getUserId();
					newHistoryItem.oldValue__c = String.valueOf(oldMap.get(updateId).get(fieldName));
					newHistoryItem.newValue__c = String.valueOf(newMap.get(updateId).get(fieldName));
					newHistoryItem.fieldLabel__c = String.valueOf(fieldMap.get(fieldName).getDescribe().getLabel());
					newHistoryItem.action__c = 'Update';
					newHistoryItem.tract__c = updateId;
					newHistory.add(newHistoryItem);
					if(!rollupHelperFields.contains(fieldName)){
						rollupHelperOnly = false;
					}
					System.debug('Found difference in field: ' + fieldName + ' old value is: ' + oldMap.get(updateId).get(fieldName) + ' new value is: ' + newMap.get(updateId).get(fieldName));
				}
			}
		}
		TractTriggerHelper.tractUpdating = rollupHelperOnly;
		insert newHistory;
	}*/

	/*public static void tractHistoryDelete(List<Tract__c> triggerOld, Map<Id, Tract__c> oldMap){
		List<tractHistory__c> newHistory = new List<tractHistory__c>();
		//System.debug('Tract was deleted');
		for(Id updateId: oldMap.keySet()){
			tractHistory__c newHistoryItem = new tractHistory__c();
			newHistoryItem.action__c = 'Delete';
			newHistoryItem.changedBy__c = UserInfo.getUserId();
			newHistoryItem.tract__c = updateId;
			newHistory.add(newHistoryItem);
		}
		insert newHistory;
	}*/

    public static Map<Id,Tract__c> getTractsbyIds(Set<Id> tractIds)
    {
        return new Map<Id,Tract__c>([SELECT Id,
            OTG_Cost__c, Value_Per_Acre__c, Gain_on_Asset__c,
            Total_Cost__c, Notes__c, netAcres__c, Total_Cost_Per_Acre__c, OTG_Cost_Per_Acre__c, Gross_Acres__c, Subtract_Count__c,
                Quarter_Call__c, Full_Legal_Name__c, Lots__c, Grid_Exception__c
            FROM Tract__c WHERE Id IN: tractIds]);
    }


	
    /*private static void setCaseTractFields(Case_Tract__c ct, Tract__c tract)
    {
        ct.Commission_Amount__c = tract.Commission_Amount__c;
        ct.OTG_Cost__c = tract.OTG_Cost__c;
        ct.Other_Capitalized_Costs__c = tract.Other_Capitalized_Costs__c;
        ct.Title_Cost__c = tract.Title_Cost__c;
        ct.Total_Cost__c = tract.Total_Cost__c;
        ct.Tract_Acres__c = tract.netAcres__c;
    }*/

}