src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field used in the Manage Cases modal on the Cases related list. It is initially left off the page layout in order to serve only the purpose of searching for cases in the modal.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Case__c.object
<CustomObject>
    <description>Junction obj for a many-to-many relationship between Opportunity and Case</description>
    <fields>
        <fullName>case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>Opportunity_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>Opportunity_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Case</label>
    <nameField>
        <displayFormat>OC-{0000000000}</displayFormat>
        <label>Opportunity Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/ManageOpportunitiesAuraTest.cls
@isTest
    public class ManageOpportunitiesAuraTest{
        
        @TestSetup static void makeData(){
            TestDataFactory.dataSetup();
            Case caseRec = [SELECT Id, Subject FROM Case LIMIT 1];
            caseRec.Subject = 'test case 1';
            Opportunity oppRec = [SELECT Id FROM Opportunity LIMIT 1];
            oppRec.Name = 'testRelatedCaseOpportunity';
            
            update caseRec;
            update oppRec;
    
            Opportunity_Case__c oc = new Opportunity_Case__c();
            oc.opportunity__c = oppRec.Id;
            oc.case__c = caseRec.Id;
            insert oc;
        }
        
        @isTest static void testGetOpportunities() {
            Case[] cse = [SELECT Id, Subject FROM Case];
            List<Opportunity_Case__c> oppCases = ManageOpportunitiesAura.getOpportunities(cse[0].Id);
            System.assert(oppCases.size() > 0, 'No Opp Cases returned or returned NULL in ManageOpportunitiesAuraTest.testGetOpportunities');
        }
        
        @isTest static void testGetOpportunitySearchResults() {
            List<String> oppIdLst0 = new List<String>();
            List<String> oppIdLst1 = new List<String>();
            
            //scenario 1 - opp already in the related list
            Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'testRelatedCaseOpportunity' LIMIT 1];
            Case[] cse = [SELECT Id, Subject FROM Case];
            oppIdLst0.add(String.valueOf(opp.Id));
            List<Opportunity_Case__c> oppCases0 = ManageOpportunitiesAura.getOpportunitySearchResults(oppIdLst0, cse[1].Id);
            System.assert(oppCases0.size() > 0, 'No Opp Cases returned or returned NULL in ManageOpportunitiesAuraTest.testGetCaseSearchResults');
            
            
            //scenario 2 - opp not already in the related list
            Account[] newAcct = TestDataFactory.createAccounts(1);
            newAcct[0].Name = 'Test Account 42';
            insert newAcct;
            newAcct = [SELECT Id FROM Account WHERE Name = 'Test Account 42' LIMIT 1];
            Opportunity[] newOpp = TestDataFactory.createOpportunities(3, newAcct[0]);
            newOpp[2].Name = 'testRelatedCaseOpportunity';
            insert newOpp;
            newOpp = [SELECT Id FROM Opportunity WHERE Name = 'testRelatedCaseOpportunity' LIMIT 1];
            oppIdLst1.add(String.valueOf(newOpp[0].Id));
            List<Opportunity_Case__c> oppCases1 = ManageOpportunitiesAura.getOpportunitySearchResults(oppIdLst1, cse[2].Id);
            System.assert(oppCases1.size() > 0, 'No Opp Cases returned or returned NULL in ManageOpportunitiesAuraTest.testGetCaseSearchResults');
        }
    
        @isTest static void testUpdateRecordAssociation() {
            Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'testRelatedCaseOpportunity' LIMIT 1];
            Case[] cse = [SELECT Id, Subject FROM Case WHERE Subject = 'test case 1'];
            Opportunity_Case__c oc = [SELECT Id FROM Opportunity_Case__c LIMIT 1];
            List<Opportunity_Case__c> oppCases = ManageOpportunitiesAura.updateRecordAssociation(cse[0].Id, oc.Id);
            System.assert(oppCases.size() > 0, 'No Opp Cases returned or returned NULL in ManageOpportunitiesAuraTest.testUpdateRecordAssociation');
        }
    }