src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Acquiring_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Acquiring Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Acquiring Entity)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Date__c</fullName>
        <label>PSA Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>askTotalPricePerAcre__c</fullName>
        <formula>if(askTotalPrice__c = 0, 0, askTotalPrice__c / Total_Acreage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ask Total Price Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>askTotalPrice__c</fullName>
        <label>Ask Total Price</label>
        <summarizedField>Opportunity_Tract__c.askTotalPrice__c</summarizedField>
        <summaryForeignKey>Opportunity_Tract__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>totalPricePerAcre__c</fullName>
        <formula>if(totalPrice__c = 0, 0, totalPrice__c /  Total_Acreage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>totalPrice__c</fullName>
        <label>Total Price</label>
        <summarizedField>Opportunity_Tract__c.totalPrice__c</summarizedField>
        <summaryForeignKey>Opportunity_Tract__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Acquisition</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <label>Acquisition</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Case__c.object
<CustomObject>
    <description>Junction obj for a many-to-many relationship between Opportunity and Case</description>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>Opportunity_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Case</label>
    <nameField>
        <displayFormat>OC-{0000000000}</displayFormat>
        <label>Opportunity Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityRelatedListAuraTest.cls
@isTest
public class OpportunityRelatedListAuraTest {
    static testMethod void testOpportunityRelatedList() {
        TestDataFactory.dataSetup();

        Case c = [SELECT Id FROM Case LIMIT 1];
        Opportunity o = [SELECT Id FROM Opportunity LIMIT 1];
        o.Type = 'Acquisition';
        o.PSA_Date__c = Date.today() + 15;
        o.Effective_Date__c = Date.today() + 15;
        o.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Acquisition').getRecordTypeId();
        update o;
        Opportunity_Case__c oc = [
            SELECT
                Id,
                Name,
                opportunity__c,
                opportunity__r.Name,
                opportunity__r.StageName,
                opportunity__r.Acquiring_Entity__r.Name,
                opportunity__r.Acquiring_Entity__c,
                opportunity__r.Type,
                opportunity__r.Account.Name,
                opportunity__r.AccountId,
                opportunity__r.PSA_Date__c,
                opportunity__r.CloseDate,
                opportunity__r.Effective_Date__c,
                opportunity__r.Owner.Name,
                opportunity__r.OwnerId,
                opportunity__r.totalPricePerAcre__c,
                opportunity__r.totalPrice__c,
                opportunity__r.askTotalPricePerAcre__c,
                opportunity__r.askTotalPrice__c
            FROM Opportunity_Case__c
            LIMIT 1
        ];

        System.assert(c != null);
        System.assert(o != null);
        System.assert(oc != null);

        Test.startTest();
        OpportunityRelatedListAura.getCaseOpps(c.Id);
        Test.stopTest();
    }
}