src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity_Case__c.object
<CustomObject>
    <description>Junction obj for a many-to-many relationship between Opportunity and Case</description>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>Opportunity_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Case</label>
    <nameField>
        <displayFormat>OC-{0000000000}</displayFormat>
        <label>Opportunity Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/CaseRelatedListAuraTest.cls
@isTest 
private class CaseRelatedListAuraTest {

	@TestSetup
	private static void makeData(){
		TestDataFactory.dataSetup();
		Case testCase = [SELECT Id FROM Case LIMIT 1];
		Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
		testCase.opportunity__c = opp.Id;
		opp.Name = 'testRelatedCaseOpportunity';
		update testCase;
		update opp;
	}
	
	@isTest
	private static void testMain() {
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'testRelatedCaseOpportunity' LIMIT 1];
		List<Opportunity_Case__c> oppCases = CaseRelatedListAura.getCases(opp.Id);
		System.assert(oppCases.size() > 0);

	}
}