src/objects/contactInformation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Information</relationshipLabel>
        <relationshipName>Contact_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>Contact Info -{000000}</displayFormat>
        <label>Contact Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactInformationControllerTest.cls
@isTest
public class ContactInformationControllerTest {
	
    static testMethod void testTrigger() {
        // test the trigger and helper method

        Account a1 = new Account();
        a1.Name = 'Seller';
        a1.Type = 'Portfolio Investment';
        insert a1;
        List<contactInformation__c> cilist = new List<contactInformation__c>();
		contactInformation__c ciRec = new contactInformation__c(Account__c=a1.Id,Phone__c='1234567890',Primary__c=true);
        cilist.add(ciRec);
        
        ciRec = new contactInformation__c(Account__c=a1.Id,Street__c='1234567890',Primary__c=true);
        cilist.add(ciRec);
        insert cilist;
        ContactInformationController.fetchContactInfo(a1.Id);
        ContactInformationController.saveContactInfo( ContactInformationController.createWrapperList(cilist) , a1.Id);
        ContactInformationController.deleteContactInfo(ciRec.Id);
    }
}