src/objects/contactInformation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Information</relationshipLabel>
        <relationshipName>Contact_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactInformationType__c</fullName>
        <formula>IF(ISBLANK(Phone__c),&apos;Address&apos;,&apos;Phone&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactInformationType (Formula)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>stateProvince__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zipPostalCode__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>Contact Info -{000000}</displayFormat>
        <label>Contact Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactInformationTriggerHandler.cls
public class ContactInformationTriggerHandler {
    
    public static void updateInfoOnAccount(List<contactInformation__c> newList){
        
        Map<Id,Account> accountMap = new Map<Id,Account>();
        Account accRec;
            for(contactInformation__c infoRec : newList){
                if(infoRec.Primary__c){
                    if(accountMap.containsKey(infoRec.Account__c)){
                        accRec = accountMap.get(infoRec.Account__c);
                    }else{
                        accRec = new Account(Id=infoRec.Account__c);
                    }
                    system.debug(infoRec.ContactInformationType__c );
                    if(infoRec.Phone__c != null && infoRec.Phone__c != ''){
                        accRec.Phone = infoRec.Phone__c;
                    }else{
                        accRec.BillingStreet = infoRec.Street__c;
                        accRec.BillingCity = infoRec.City__c;
                        accRec.BillingState = infoRec.stateProvince__c;
                        accRec.BillingCountry = infoRec.Country__c;
                        accRec.BillingPostalCode = infoRec.zipPostalCode__c;
                    }
                    accountMap.put(infoRec.Account__c,accRec);
                }
            }
    	system.debug(accountMap);
        if(accountMap.size()>0){
            update accountMap.values();
        }
    }
}