src/objects/deduction__c.object
<CustomObject>
    <fields>
        <fullName>EnergyLinkTypeDesc__c</fullName>
        <label>Energy Link Type Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GrossAmount__c</fullName>
        <label>Gross Amount</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpTypeCode__c</fullName>
        <label>Op Type Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpTypeDesc__c</fullName>
        <label>Op Type Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerAmount__c</fullName>
        <label>Owner Amount</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrtTypeCode__c</fullName>
        <label>Prt Type Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoyaltyLineItem__c</fullName>
        <label>Royalty Line Item</label>
        <referenceTo>Royalty_Line_Item__c</referenceTo>
        <relationshipLabel>Deductions</relationshipLabel>
        <relationshipName>Deductions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>detailId__c</fullName>
        <externalId>true</externalId>
        <label>DetailId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deduction</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Deduction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deductions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/energyLinkBucket__c.object
<CustomObject>
    <fields>
        <fullName>Invalid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>checkURL__c</fullName>
        <externalId>true</externalId>
        <label>Check URL</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>isDuplicate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Duplicate</label>
        <type>Checkbox</type>
    </fields>
    <label>Energy Link Bucket</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Energy Link Check</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energy Link Bucket</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Details__c</fullName>
        <label>Additional Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Find Royalty Check</fullName>
                </value>
                <value>
                    <fullName>Delete Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Read Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Insert Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Upsert</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                    <default>true</default>
                    <label>Error</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Total Check Amount</description>
        <inlineHelpText>Total Check Amount</inlineHelpText>
        <label>Check Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Issue_Date__c</fullName>
        <description>Date Check was Issued</description>
        <inlineHelpText>Date Check was Issued</inlineHelpText>
        <label>Check Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <externalId>true</externalId>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EnergyLink_URL__c</fullName>
        <label>EnergyLink URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator_Name__c</fullName>
        <description>Name of Operator related to check</description>
        <inlineHelpText>Name of Operator related to check</inlineHelpText>
        <label>Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Number__c</fullName>
        <label>Owner Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payee_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Royalty Checks</relationshipLabel>
        <relationshipName>Royalty_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payee_from_Source_File__c</fullName>
        <description>Payee from imported source file</description>
        <inlineHelpText>Payee from imported source file</inlineHelpText>
        <label>Payee from Source File</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payor_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Royalty Checks (Payor)</relationshipLabel>
        <relationshipName>Royalty_Checks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payor_from_Source_File__c</fullName>
        <description>Payor from source import file.</description>
        <inlineHelpText>Payor from source import file.</inlineHelpText>
        <label>Payor from Source File</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSV</fullName>
                </value>
                <value>
                    <fullName>CDEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>detailId__c</fullName>
        <externalId>true</externalId>
        <label>DetailId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>grossAdjustmentsActual__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Gross Adjustments Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>grossNetActual__c</fullName>
        <label>Gross Net Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>grossTaxesActual__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Gross Taxes Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>grossValueActual__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Gross Value Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>grossVolumeActual__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Gross volume from royalty check from operator (5 decimal places)</description>
        <inlineHelpText>Gross volume from royalty check from operator (5 decimal places)</inlineHelpText>
        <label>Gross Volume Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>interestType__c</fullName>
        <label>Interest Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lineItemDecimal__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Royalty check line item well interest / distribution decimal from operator.</description>
        <inlineHelpText>Royalty check line item well interest / distribution decimal from operator.</inlineHelpText>
        <label>Line Item Decimal</label>
        <precision>11</precision>
        <required>true</required>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ownerAdjustmentsActual__c</fullName>
        <label>Owner Adjustments Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ownerNetValueActual__c</fullName>
        <label>Owner Net Value Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ownerValueActual__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Value before tax and deductions.  Field on royalty check can be owner value or net value</description>
        <inlineHelpText>Value before tax and deductions.  Field on royalty check can be owner value or net value</inlineHelpText>
        <label>Owner Value Actual</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ownerVolumeActual__c</fullName>
        <label>Owner Volume Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>Price from operator royalty check line item (4 decimal places)</description>
        <inlineHelpText>Price from operator royalty check line item (4 decimal places)</inlineHelpText>
        <label>Price</label>
        <precision>11</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>product__c</fullName>
        <description>Product type or product code from royalty check line item (ie. oil, gas, plant product, etc)</description>
        <inlineHelpText>Product type or product code from royalty check line item (ie. oil, gas, plant product, etc)</inlineHelpText>
        <label>Product</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>production_Month__c</fullName>
        <label>Production Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <externalId>true</externalId>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>property_Id__c</fullName>
        <label>Property Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>royalty_Check__c</fullName>
        <description>Royalty Check</description>
        <label>Royalty Check</label>
        <referenceTo>Royalty_Check__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>source__c</fullName>
        <formula>TEXT(royalty_Check__r.Source__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ImportCdexChecks.cls
/**
* @Class Name          : ImportCdexChecks
* @Description        : This class is used to parse CDEX checks of JSON format and insert all details into different CDEX related objects in salesforce  
* @Author             : Jade Tran
**/
public class ImportCdexChecks {
    
    /**
* @description : This method is fired from ImportCdexChecks aura component. 
* This method queries all checks stored in JSON format in running user's library folder 'username_CdexChecks'.
* It then fires the createCdexChecks method to parse and insert all check info into CDEX related object in salesforce
* @author : Jade Tran 
* @param : none
* @return : Map<String,String>
**/
    @AuraEnabled
    public static Map<String,String> createCdexChecksFromLibrary(){
        Map<String,String> retMap = new Map<String,String>();
        return retMap;
    }
    
    public static Map<String,String> createCdexChecksFromCallout(Id checkId){
        Map<String,String> retMap = new Map<String,String>();
        String urlStr = CDEXCalloutHelper.cdex.url;
        String checkNumber = CDEXCalloutHelper.cdex.checkNumber;
        try{
            //Get Source folder name based on running user; Get Id of source and target folders 
            CdexWrapper cdexFinalWrap = new cdexWrapper();
            cdexFinalWrap = createCdexChecks();
			if(Limits.getDmlRows() + cdexFinalWrap.checkList.size() >= limits.getLimitDmlRows()){
				throw new cdexException('Error loading CDEX Check before check Insert. DML Row Limit is: ' + Limits.getLimitDmlRows() +
										' current count is: ' + Limits.getDmlRows() + ' current insert contains: ' + cdexFinalWrap.checkList.size() +
										' records.');
			}
            if(cdexFinalWrap.checkList.size()>0){
                retMap.put('Checks',String.valueOf(cdexFinalWrap.checkList.size()));
                //Database.upsert( cdexFinalWrap.checkList, Royalty_Check__c.Check_Number__c.getDescribe().getSObjectField() ,true ) ;
                if(checkId != null){
                    cdexFinalWrap.checkList[0].Id = checkId;
                    Database.update(cdexFinalWrap.checkList);
                    
                    List<Royalty_Line_Item__c> oldRliList = [Select Id from Royalty_Line_Item__c where Royalty_Check__c =: checkId];
                    If(oldRliList.size()>0){
                        database.delete(oldRliList);
                    }
                }else{
                    Database.insert( cdexFinalWrap.checkList);
                }
                
            }
			if(Limits.getDmlRows() + cdexFinalWrap.cdexLineItemList.size() >= limits.getLimitDmlRows()){
				throw new cdexException('Error loading CDEX Check before line item Insert. DML Row Limit is: ' + Limits.getLimitDmlRows() +
										' current count is: ' + Limits.getDmlRows() + ' current insert contains: ' + cdexFinalWrap.cdexLineItemList.size() +
										' records.');
			}

            //Upsert Cdex details
            if(cdexFinalWrap.cdexLineItemList.size()>0){
                retMap.put('Details',String.valueOf(cdexFinalWrap.cdexLineItemList.size()));
                //Database.upsert( cdexFinalWrap.cdexLineItemList, Royalty_Line_Item__c.detailId__c.getDescribe().getSObjectField() ,true ) ;
                Database.insert( cdexFinalWrap.cdexLineItemList);
            }

			if(Limits.getDmlRows() + cdexFinalWrap.cdexDedLineItemList.size() >= limits.getLimitDmlRows()){
				throw new cdexException('Error loading CDEX Check before Deduction Insert. DML Row Limit is: ' + Limits.getLimitDmlRows() +
										' current count is: ' + Limits.getDmlRows() + ' current insert contains: ' + cdexFinalWrap.cdexDedLineItemList.size() +
										' records.');
			}

            //Upsert Cdex deduction
            if(cdexFinalWrap.cdexDedLineItemList.size()>0){
                retMap.put('Deductions',String.valueOf(cdexFinalWrap.cdexDedLineItemList.size()));
                //Database.upsert( cdexFinalWrap.cdexDedLineItemList, Deduction__c.detailId__c.getDescribe().getSObjectField() ,true ) ;
                Database.insert( cdexFinalWrap.cdexDedLineItemList);
            }
            
            //create Log record if any exceptions occur    
        }catch(Exception e){
            retMap.put('ERROR',String.valueOf(e.getMessage()));
            
            log__c logRec = new log__c();
            logRec.Process__c = 'Cdex Check Import';
            logRec.Status__c = 'ERROR';
            logRec.Error_Message__c = e.getMessage();
            logRec.Additional_Details__c = 'Check Number: '+checkNumber+' ---- Check Url: '+urlStr;
            logRec.Stack_Trace__c = e.getStackTraceString();
            insert logRec;
            
            energyLinkBucket__c eRec = [Select Id from energyLinkBucket__c where checkUrl__c =:urlStr Limit 1];
            eRec.invalid__c = true;
            if(e.getMessage().contains('Insert failed. First exception on row 0; first error: DUPLICATE_VALUE, duplicate value found: Check_Number__c')){
                eRec.isDuplicate__c = true;
            }
            update eRec;
            
            
        }
        return retMap;
    }
    
    /**
* @description : Parse JSON check to CdexParser wrapper instances
* @author : Jade Tran
* @param : body 
* @return : CdexWrapper 
**/
    public static CdexWrapper createCdexChecks(){
        cdexWrapper cdexFileWrap = new cdexWrapper();
        List<Royalty_Check__c> checkList = new List<Royalty_Check__c>();
        Royalty_Check__c check;
        Map<String,List<sObject>> detailTaxDeductionMap = new Map<String,List<sObject>>();
        List<Royalty_Line_Item__c> cdexLineItemList = new List<Royalty_Line_Item__c>();
        List<Deduction__c> cdexDedLineItemList = new List<Deduction__c>(); 
        //Iterate all checks in wrapper and create instances of Royalty_Check__c
        CdexParser.Check c = CDEXCalloutHelper.cdex.Check;
        //Create CDEX_Company__c instance for operator
        check = new Royalty_Check__c();
        check.source__c = 'CDEX';
        check.EnergyLInk_URL__c = CDEXCalloutHelper.cdex.url;
        CDEXCalloutHelper.cdex = null;
        check.Amount__c  = (c.TotalAmount!=null)? c.TotalAmount:0;
        check.Check_Issue_Date__c  = (c.CheckDate!=null)? date.valueOf(c.CheckDate):null;
        String checkNumberStr = string.valueOf(c.CheckNumber);
        while(checkNumberStr.indexOf('0')==0){
            checkNumberStr=checkNumberStr.replaceFirst('0','');
        }
        check.Check_Number__c  = (c.CheckNumber!=null)? checkNumberStr :null;
        check.Operator_Name__c  = (c.Operator.OrgName!=null)? c.Operator.OrgName:null;
        String ownerNumberStr = string.valueOf(c.OwnerNumber);
        while(ownerNumberStr.indexOf('0')==0){
            ownerNumberStr=ownerNumberStr.replaceFirst('0','');
        }
        check.Owner_Number__c  = (c.OwnerNumber!=null)? ownerNumberStr:null;
        check.Payee_from_Source_File__c = (c.Owner.OrgName!=null)? c.Owner.OrgName:null;
        check.Payor_from_Source_File__c = (c.Operator.OrgName!=null)? c.Operator.OrgName:null; 
        List<Account> accList = [Select Id from Account where Name =: c.Owner.OrgName];
        if(accList.size()>0){
            check.Payee_Lookup__c  = accList[0].Id;
        }
        accList = new List<Account>();
        accList = [Select Id from Account where Name =: c.Operator.OrgName];
        if(accList.size()>0){
            check.Payor_Lookup__c = accList[0].Id;
        }
        //check.InvoiceId__c  = (c.InvoiceId!=null)? String.valueOf(c.InvoiceId):null;
        
        checkList.add(check);
        
        //create check related child objects.
        detailTaxDeductionMap = createCdexLineItem(c.Properties,checkNumberStr);
        c = null;
        //Add all created instances into wrapper
        if(checkList.size()>0){
            cdexFileWrap.checkList.addAll(checkList);
            checkList= null;
        }
        cdexLineItemList.addAll((List<Royalty_Line_Item__c>)detailTaxDeductionMap.get('Detail'));
        if(cdexLineItemList.size()>0){
            cdexFileWrap.cdexLineItemList.addAll(cdexLineItemList);
            cdexLineItemList = null;
        }
        cdexDedLineItemList.addAll((List<Deduction__c>)detailTaxDeductionMap.get('Deduction'));
        if(cdexDedLineItemList.size()>0){
            cdexFileWrap.cdexDedLineItemList.addAll(cdexDedLineItemList);
            cdexDedLineItemList = null;
        }
        detailTaxDeductionMap = null;
        return cdexFileWrap;
    }
    
    /**
* @description : Method fired from createCdexChecks to create instance of Cdex properties and its related child records
* @author : Jade Tran
* @param prList 
* @param check 
* @return Map<String, List<sObject>> 
**/
    public static Map<String,List<sObject>> createCdexLineItem(List<CdexParser.Properties> prList,String checkNumber){
        
        Map<String,List<sObject>> detailTaxDeductionMap = new Map<String,List<sObject>>();
        
        
        Map<String,List<sObject>> rliDedMap;
        String PrtCostCenterCode;
        String OpCostCenterDesc;
        for(CdexParser.Properties p : prList){
            PrtCostCenterCode=  p.CostCenter.PrtCostCenterCode;
            OpCostCenterDesc = p.CostCenter.OpCostCenterDesc;
            for(CdexParser.Details detail: p.Details){
                if(detail.Taxes!=null || detail.Deductions!=null){
                    
                    rliDedMap = new Map<String,List<sObject>>();
                    rliDedMap = createCdexDeductionLineItem(checkNumber,detail,PrtCostCenterCode,OpCostCenterDesc);
                    
                    if(detailTaxDeductionMap.containsKey('Detail')){
                        
                        detailTaxDeductionMap.get('Detail').addAll((List<Royalty_Line_Item__c>)rliDedMap.get('Detail'));
                        if(detailTaxDeductionMap.containsKey('Deduction') && detailTaxDeductionMap.get('Deduction') != null){
                            detailTaxDeductionMap.get('Deduction').addAll((List<Deduction__c>)rliDedMap.get('Deduction'));
                        }else{
                            detailTaxDeductionMap.put('Deduction',(List<Deduction__c>)rliDedMap.get('Deduction'));
                        }
                    }else{
                        
                        detailTaxDeductionMap.put('Detail',(List<Royalty_Line_Item__c>)rliDedMap.get('Detail'));
                        if(rliDedMap.containsKey('Deduction') && rliDedMap.keySet().size()>0){
                            detailTaxDeductionMap.put('Deduction',(List<Deduction__c>)rliDedMap.get('Deduction'));
                        }
                    }
                }else if(detail.Taxes==null && detail.Deductions==null){
                    
                    Royalty_Line_Item__c cdexLineItemRec = new Royalty_Line_Item__c();
                    cdexLineItemRec.ownerNetValueActual__c = (detail.OwnerAmount!=null)? detail.OwnerAmount:null;
                    if(detailTaxDeductionMap.containsKey('Detail')){
                        detailTaxDeductionMap.get('Detail').add(getLineItem(checkNumber,detail,cdexLineItemRec,PrtCostCenterCode,OpCostCenterDesc));
                    }else{
                        detailTaxDeductionMap.put('Detail',new List<Royalty_Line_Item__c>{getLineItem(checkNumber,detail,cdexLineItemRec,PrtCostCenterCode,OpCostCenterDesc)});
                    }
                }
            }            
        }
        return detailTaxDeductionMap;
    }
    
    /**
* @description : Method fired from createCdexDeductionLineItem to create instance Royalty_Line_Item__c
* @author : Jade Tran
* @param detail 
* @param cdexLineItemRec 
* @return Royalty_Line_Item__c
**/
    public static Royalty_Line_Item__c getLineItem(String checkNumber,CdexParser.Details detail,Royalty_Line_Item__c cdexLineItemRec,String PrtCostCenterCode,String OpCostCenterDesc){
        Royalty_Check__c check = new Royalty_Check__c(Check_Number__c = checkNumber);
        cdexLineItemRec.detailId__c  = (detail.DetailId!=null)? String.valueOf(detail.DetailId):null;
        cdexLineItemRec.grossValueActual__c  = (detail.GrossAmount!=null)? detail.GrossAmount:null;
        cdexLineItemRec.grossVolumeActual__c  = (detail.GrossVolume!=null)? detail.GrossVolume:null;
        cdexLineItemRec.interestType__c  = (detail.OpTypeCode!=null)? detail.OpTypeCode:null;
        cdexLineItemRec.ownerValueActual__c  = (detail.OwnerAmount!=null)? detail.OwnerAmount:null;
        cdexLineItemRec.ownerVolumeActual__c  = (detail.OwnerVolume!=null)? detail.OwnerVolume:null;
        cdexLineItemRec.lineItemDecimal__c = (detail.OwnerPercent!=null)? detail.OwnerPercent/100:0; 
        cdexLineItemRec.Price__c  = (detail.Price!=null)? detail.Price:0;
        cdexLineItemRec.Product__c  = (detail.OpProductCode!=null)? detail.OpProductCode:null;
        //Commented Invalid Production month
        /*if(detail.ActivityDate!=null && Date.valueOf(detail.ActivityDate).year()>1700){
cdexLineItemRec.Production_Month__c  = (detail.ActivityDate!=null)? Date.valueOf(detail.ActivityDate):null;
}*/
        cdexLineItemRec.Production_Month__c  = (detail.ActivityDate!=null)? Date.valueOf(detail.ActivityDate):null;
        cdexLineItemRec.Property_Id__c = PrtCostCenterCode;
        cdexLineItemRec.Royalty_Check__r = check;
        cdexLineItemRec.propertyName__c = OpCostCenterDesc;
        return cdexLineItemRec;
    }
    
    
    
    /**
* @description : Method fired from createCdexLineItem to create instance of Cdex deduction
* @author : Jade Tran
* @param detail 
* @param type 
* @return List<Deduction__c> 
**/
    public static Map<String,List<sObject>> createCdexDeductionLineItem(String checkNumber,CdexParser.Details detail,String PrtCostCenterCode,String OpCostCenterDesc){
        Royalty_Line_Item__c cdexLineItemRec = new Royalty_Line_Item__c();
        cdexLineItemRec.detailId__c = (detail.DetailId!=null)? String.valueOf(detail.DetailId):null;
        Map<String,List<sObject>> rliDedMap = new Map<String,List<sObject>>();
        Royalty_Line_Item__c dummyRLI;
        List<Royalty_Line_Item__c> cdexLineItemList = new List<Royalty_Line_Item__c>();
        List<Deduction__c> cdexDedLineItemList = new List<Deduction__c>(); 
        Deduction__c cdexDedLineItemRec;
        Decimal grossAdjustmentsActual = 0.0;
        Decimal grossNetActual = 0.0;
        Decimal grossTaxesActual = 0.0;
        Decimal ownerAdjustmentsActual = 0.0;
        Decimal ownerNetValueActual = 0.0;
        Decimal ownerTaxesActual = 0.0;
        
        if(detail.Taxes!=null){
            for(CdexParser.Deductions tax: detail.Taxes){
                
                dummyRLI = new Royalty_Line_Item__c(detailId__c = cdexLineItemRec.detailId__c);
                cdexDedLineItemRec = new Deduction__c();
                cdexDedLineItemRec.detailId__c  = (tax.DetailId!=null)? String.valueOf(tax.DetailId):null;
                cdexDedLineItemRec.OpTypeCode__c  = (tax.OpTypeCode!=null)? tax.OpTypeCode:null;
                cdexDedLineItemRec.OpTypeDesc__c  = (tax.OpTypeDesc!=null)? tax.OpTypeDesc:null;
                cdexDedLineItemRec.EnergyLinkTypeDesc__c  = (tax.EnergyLinkTypeDesc!=null)? tax.EnergyLinkTypeDesc:null;
                cdexDedLineItemRec.PrtTypeCode__c  = (tax.PrtTypeCode!=null)? tax.PrtTypeCode:null;
                cdexDedLineItemRec.GrossAmount__c  = (tax.GrossAmount!=null)? tax.GrossAmount:0;
                cdexDedLineItemRec.OwnerAmount__c  = (tax.OwnerAmount!=null)? tax.OwnerAmount:0;
                cdexDedLineItemRec.type__c = 'Tax';
                cdexDedLineItemRec.RoyaltyLineItem__r = dummyRLI;
                cdexDedLineItemList.add(cdexDedLineItemRec);
                grossTaxesActual += cdexDedLineItemRec.GrossAmount__c;
                ownerTaxesActual += cdexDedLineItemRec.OwnerAmount__c;
                
            }
        }
        
        if(detail.Deductions != null){
            for(CdexParser.Deductions deduction: detail.Deductions){
                
                dummyRLI = new Royalty_Line_Item__c(detailId__c = cdexLineItemRec.detailId__c);
                cdexDedLineItemRec = new Deduction__c();
                cdexDedLineItemRec.detailId__c  = (deduction.DetailId!=null)? String.valueOf(deduction.DetailId):null;
                cdexDedLineItemRec.OpTypeCode__c  = (deduction.OpTypeCode!=null)? deduction.OpTypeCode:null;
                cdexDedLineItemRec.OpTypeDesc__c  = (deduction.OpTypeDesc!=null)? deduction.OpTypeDesc:null;
                cdexDedLineItemRec.EnergyLinkTypeDesc__c  = (deduction.EnergyLinkTypeDesc!=null)? deduction.EnergyLinkTypeDesc:null;
                cdexDedLineItemRec.PrtTypeCode__c  = (deduction.PrtTypeCode!=null)? deduction.PrtTypeCode:null;
                cdexDedLineItemRec.GrossAmount__c  = (deduction.GrossAmount!=null)? deduction.GrossAmount:0;
                cdexDedLineItemRec.OwnerAmount__c  = (deduction.OwnerAmount!=null)? deduction.OwnerAmount:0;
                cdexDedLineItemRec.type__c = 'Deductions'; 
                cdexDedLineItemRec.RoyaltyLineItem__r = dummyRLI;   
                cdexDedLineItemList.add(cdexDedLineItemRec);   
                grossAdjustmentsActual += cdexDedLineItemRec.GrossAmount__c;
                ownerAdjustmentsActual += cdexDedLineItemRec.OwnerAmount__c;
            }
        }
        grossNetActual = (detail.GrossAmount!=null)? detail.GrossAmount+ grossTaxesActual + grossAdjustmentsActual :0 + grossTaxesActual + grossAdjustmentsActual;
        ownerNetValueActual = (detail.OwnerAmount!=null)? detail.OwnerAmount+ ownerTaxesActual + ownerAdjustmentsActual:0 + ownerTaxesActual + ownerAdjustmentsActual;
        
        cdexLineItemRec.grossAdjustmentsActual__c = grossAdjustmentsActual ;
        cdexLineItemRec.grossNetActual__c = grossNetActual ;
        cdexLineItemRec.grossTaxesActual__c = grossTaxesActual ;
        cdexLineItemRec.ownerAdjustmentsActual__c = ownerAdjustmentsActual ;
        cdexLineItemRec.ownerNetValueActual__c = ownerNetValueActual ;
        cdexLineItemRec.ownerTaxesActual__c = ownerTaxesActual ;
        cdexLineItemList.add(getLineItem(checkNumber,detail,cdexLineItemRec,PrtCostCenterCode,OpCostCenterDesc));
        
        rliDedMap.put('Detail',cdexLineItemList);
        rliDedMap.put('Deduction',cdexDedLineItemList);
        return rliDedMap;
    }
    
    public class CdexWrapper{
        public  List<Royalty_Check__c> checkList = new List<Royalty_Check__c>();
        public  List<Royalty_Line_Item__c> cdexLineItemList = new List<Royalty_Line_Item__c>();
        public  List<Deduction__c> cdexDedLineItemList = new List<Deduction__c>();
    }
    
	public virtual class cdexException extends Exception{}
}