src/objects/diTexasPermitWithAcreage__c.object
<CustomObject>
    <description>Drilling Info Texas Permits with Acreage</description>
    <fields>
        <fullName>API10__c</fullName>
        <label>API10</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>countyName__c</fullName>
        <label>County Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>leaseName__c</fullName>
        <label>Lease Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>permitNumber__c</fullName>
        <label>Permit Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>permittedAcres__c</fullName>
        <label>Permitted Acres</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rrcDistrict__c</fullName>
        <label>RRC District</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rrcLeaseNumber__c</fullName>
        <label>RRC Lease Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>stateName__c</fullName>
        <label>State Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Texas Permit with Acreage</label>
    <nameField>
        <displayFormat>DITP-{0000000000}</displayFormat>
        <label>DI Texas Permit with Acreage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Texas Permits with Acreage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RRCLease__c.object
<CustomObject>
    <fields>
        <fullName>legalDescription__c</fullName>
        <label>Legal Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>permitAcresUserOverride__c</fullName>
        <label>Permit Acres User Override</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rrcLeaseNumber__c</fullName>
        <label>RRC Lease Number</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>texasPermitWithAcre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Texas Permit with Acre</label>
        <referenceTo>diTexasPermitWithAcreage__c</referenceTo>
        <relationshipLabel>RRC Leases</relationshipLabel>
        <relationshipName>RRCLeases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>uid__c</fullName>
        <label>UID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RRC Lease</label>
    <nameField>
        <displayFormat>RRCL-{0000000000}</displayFormat>
        <label>RRC Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RRC Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TaxRollInterest__c.object
<CustomObject>
    <description>Tax Roll Interest to be imported from Drilling Info files.</description>
    <fields>
        <fullName>account__c</fullName>
        <formula>taxRollOwner__r.account__r.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>countyName__c</fullName>
        <label>County Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalDescription__c</fullName>
        <label>Legal Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>permitAcresUserOverride__c</fullName>
        <formula>rrcLease__r.permitAcresUserOverride__c</formula>
        <label>Permit Acres User Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rrcLeaseNumber__c</fullName>
        <formula>rrcLease__r.rrcLeaseNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RRC Lease Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rrcLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RRC Lease</label>
        <referenceTo>RRCLease__c</referenceTo>
        <relationshipLabel>Tax Roll Interests</relationshipLabel>
        <relationshipName>TaxRollInterests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>taxRollOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tax Roll Owner</label>
        <referenceTo>TaxRollOwner__c</referenceTo>
        <relationshipLabel>Tax Roll Interests</relationshipLabel>
        <relationshipName>TaxRollInterests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tax Roll Interest</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Tax Roll Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Roll Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TaxRollOwner__c.object
<CustomObject>
    <fields>
        <fullName>account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax Roll Owners</relationshipLabel>
        <relationshipName>TaxRollOwners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ownerAddress__c</fullName>
        <label>Owner Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ownerCity__c</fullName>
        <label>Owner City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ownerName__c</fullName>
        <label>Owner Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ownerState__c</fullName>
        <label>Owner State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ownerZip__c</fullName>
        <label>Owner Zip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>uid__c</fullName>
        <description>Unique Id for this record based on a combination of the first 50 characters of the following fields:
Owner Name
Owner Address
Owner City
Owner State
Owner Zip</description>
        <label>UID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Tax Roll Owner</label>
    <nameField>
        <displayFormat>TRON-{0000000000}</displayFormat>
        <label>Tax Roll Owner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Roll Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/taxRollRelateItemAura.cls
public with sharing class taxRollRelateItemAura  {

	@AuraEnabled
	public static taxRollInterestSearchResponse getInitialResults(Id recordId, String searchObject){
		taxRollInterestSearchResponse response = new taxRollInterestSearchResponse();
		//sObject currentRecord = recordId.getSObjectType().newSObject(recordId);
		String sObjectTypeName = recordId.getSObjectType().getDescribe().getName();
		System.debug('sObjectType value is: ' + sObjectTypeName);
		if(sObjectTypeName == 'TaxRollInterest__c'){
			response.currentInterest = [SELECT Id, Name, rrcLeaseNumber__c, taxRollOwner__c, taxRollOwner__r.account__c, taxRollOwner__r.account__r.Name, taxRollOwner__r.Name, taxRollOwner__r.ownerName__c FROM taxRollInterest__c WHERE Id = :recordId];
			response.rrcLeaseNumber = response.currentInterest.rrcLeaseNumber__c;
		}
		if(sObjectTypeName == 'TaxRollOwner__c'){
			response.currentOwner = [SELECT Account__c,Id,Name,ownerAddress__c,ownerCity__c,ownerName__c,ownerState__c,ownerZip__c,uid__c FROM TaxRollOwner__c WHERE Id = :recordId];
			//response.rrcLeaseNumber = response.currentInterest.rrcLeaseNumber__c;
		}
		if(sObjectTypeName == 'RRCLease__c'){
			response.currentLease = [SELECT Id, Name, legalDescription__c, permitAcresUserOverride__c, rrcLeaseNumber__c, texasPermitWithAcre__c, uid__c FROM RRCLease__c WHERE Id = :recordId];
			response.rrcLeaseNumber = response.currentLease.rrcLeaseNumber__c;
		}
		Schema.DescribeSObjectResult[] descResult = Schema.describeSObjects(new String[]{searchObject});
		response.searchObjectLabel = descResult[0].getLabel();
		switch on searchObject{
			when 'diTexasPermitWithAcreage__c'{
				//response.diPermits.Id
				List<diTexasPermitWithAcreage__c> diPermits = new List<diTexasPermitWithAcreage__c>();
				diPermits = [SELECT Id, Name, API10__c, countyName__c, leaseName__c, permitNumber__c, permittedAcres__c, rrcDistrict__c, rrcLeaseNumber__c, stateName__c 
									  FROM diTexasPermitWithAcreage__c
									  WHERE rrcLeaseNumber__c = :response.rrcLeaseNumber];
				for(diTexasPermitWithAcreage__c diPermit: diPermits){
					diPermitSearchResult newResult = new diPermitSearchResult();
					newResult.Id = diPermit.Id;
					newResult.Name = diPermit.Name;
					newResult.api10 = diPermit.API10__c;
					newResult.permitNumber = diPermit.permitNumber__c;
					newResult.leaseName = diPermit.leaseName__c;
					newResult.permittedAcres = diPermit.permittedAcres__c;
					newResult.rrcLeaseNumber = diPermit.rrcLeaseNumber__c;
					if(diPermit.Id == response.currentLease.texasPermitWithAcre__c){
						newResult.permitSelected = true;
						response.selectedRecord = newResult.Id;
					}
					response.diPermits.add(newResult);
				}
			}
			when 'Account'{
				System.debug('Tax Roll Owner Name value is: ' + response.currentOwner.ownerName__c);
				response.accounts = getAccountSearchResults(response.currentOwner.ownerName__c, 0, response.currentOwner.account__c); 
				response.selectedRecord = response.currentOwner.account__c;
			}
			when else{

			}
		}
		system.debug(descResult[0].getLabel());
		return response;
	}

	@AuraEnabled
	public static String setRelatedRecord (Id recordId, String relatedRecordId, String updateField){
		System.debug('Record Id value is: ' + recordId + ' relatedRecordId value is: ' + relatedRecordId + ' updateField value is: ' + updateField);
		String response = 'Updated Related Record';
		try{
			sObject currentRecord = recordId.getSObjectType().newSObject(recordId);
			//taxRollInterest__c currentRecord = [SELECT ID FROM taxRollInterest__c WHERE ID = :recordId];
			currentRecord.put(updateField, relatedRecordId);
			System.debug('Current record value for field: ' + updateField + ' value: ' + currentRecord.get(updateField));
			update currentRecord;
		}
		Catch(Exception e){
			response = e.getMessage();
			system.debug('ERROR SETTING RELATED RECORD ON TAX ROLL INTEREST ' + e + '\n' + e.getMessage() + ' Line Number: ' + e.getLineNumber() + ' ' + e.getStackTraceString());
		}
		return response;

	}

	@AuraEnabled
	public static taxRollInterestSearchResponse getNewSearchResult(String searchString, Integer searchCounter, String currentAccountId){
		taxRollInterestSearchResponse response = new taxRollInterestSearchResponse();
		System.debug('Method called');
		try{
			response.accounts = getAccountSearchResults(searchString, searchCounter, currentAccountId);
			response.searchCounter = searchCounter;
			for(accountSearchResult asr: response.accounts){
					if(asr.Id == response.currentInterest.taxRollOwner__r.account__c){
						response.selectedRecord = asr.Id;
					}
				}
		}
		Catch(Exception e){
			response.hasError = true;
			response.errorString = e.getMessage();
			system.debug('ERROR GETTING SEARCH RESPONSE ' + e + '\n' + e.getMessage() + ' Line Number: ' + e.getLineNumber() + ' ' + e.getStackTraceString());
		}
		
		return response;
	}

	private static List<accountSearchResult> getAccountSearchResults(String searchString, Integer searchCounter, String currentAccountId){
		//System.debug('TON ID is: ' + tonRecordId);
		List<accountSearchResult> returnValue = new List<accountSearchResult>();
		//returnValue.searchCounter = searchCounter;
		
		//Escape special characters for SOSL search - order of replacement matters - if you replace all backslashes late, you will end up with double backslashes.
		//searchString = searchString.replaceAll('[|,|.|\\,||"||:|~|!|@|#|$|%|^|&|*|_|+|=|<|>|?|\\(|\\)|\\{|\\}|\\;|\\\'"]', '-');
		searchString = searchString.replace('\\', '\\');
		System.debug(searchString);
		searchString = String.escapeSingleQuotes(searchString);
		System.debug(searchString);
		searchString = searchString.replace('-', '\\-');
		System.debug(searchString);
		searchString = searchString.replace('+', '\\+');
		System.debug(searchString);
		searchString = searchString.replace('&', '\\&');
		System.debug(searchString);
		searchString = searchString.replace('|', '\\|');
		System.debug(searchString);
		searchString = searchString.replace('!', '\\!');
		System.debug(searchString);
		searchString = searchString.replace('{', '\\{');
		System.debug(searchString);
		searchString = searchString.replace('}', '\\}');
		System.debug(searchString);
		searchString = searchString.replace('[', '\\[');
		System.debug(searchString);
		searchString = searchString.replace(']', '\\]');
		System.debug(searchString);
		searchString = searchString.replace('(', '\\(');
		System.debug(searchString);
		searchString = searchString.replace(')', '\\)');
		System.debug(searchString);
		searchString = searchString.replace('^', '\\^');
		System.debug(searchString);
		searchString = searchString.replace('~', '\\~');
		System.debug(searchString);
		searchString = searchString.replace('*', '\\*');
		System.debug(searchString);
		searchString = searchString.replace(':', '\\:');
		System.debug(searchString);
		
		searchString = searchString.replace('\"', '\\"');
		System.debug(searchString);
		
		List<Account> currentInterestAccount = [SELECT Id,Name, BillingAddress, BillingStreet, BillingCity, BillingCountry, BillingPostalCode FROM Account WHERE Id = :currentAccountId];
		if(currentInterestAccount.size() > 0){
			accountSearchResult currentInterestasr = new accountSearchResult();
			currentInterestasr.Id = currentInterestAccount[0].Id;
			currentInterestasr.Name = currentInterestAccount[0].Name;
			currentInterestasr.accountSelected = true;
			currentInterestasr.BillingAddress = currentInterestAccount[0].BillingAddress;
			currentInterestasr.BillingStreet = currentInterestAccount[0].BillingStreet;
			currentInterestasr.BillingCity = currentInterestAccount[0].BillingCity;
			currentInterestasr.BillingCountry = currentInterestAccount[0].BillingCountry;
			currentInterestasr.BillingPostalCode = currentInterestAccount[0].BillingPostalCode;
			returnValue.add(currentInterestasr);
		}

		String searchQuery = 'FIND {' + searchString + '} IN ALL FIELDS RETURNING Account (Id,Name, BillingAddress, BillingStreet, BillingCity, BillingCountry, BillingPostalCode) LIMIT 10';
		
		List<List<SObject>>searchList = Search.query(searchQuery);
		for(SObject currentSObject:searchList[0]){
			Account currentAccount = (Account)currentSObject;
			if((returnValue.size()>0 && currentAccount.Id != returnValue[0].Id)||returnValue.size()==0){
				accountSearchResult asr = new accountSearchResult();
				asr.Id = currentAccount.Id;
				asr.Name = currentAccount.Name;
				asr.BillingAddress = currentAccount.BillingAddress;
				asr.BillingStreet = currentAccount.BillingStreet;
				asr.BillingCity = currentAccount.BillingCity;
				asr.BillingCountry = currentAccount.BillingCountry;
				asr.BillingPostalCode = currentAccount.BillingPostalCode;
				if(asr.Id == currentAccountId){
					asr.accountSelected = true;
				}
				returnValue.add(asr);
			}
			
		}
		return returnValue;
	}


	public class taxRollInterestSearchResponse{
		@AuraEnabled public DescribeSObjectResult searchObject {get; set;}
		@AuraEnabled public String errorString {get; set;}
		@AuraEnabled public Boolean hasError {get; set;}
		@AuraEnabled public String searchObjectLabel {get; set;}
		@AuraEnabled public TaxRollInterest__c currentInterest{get; set;}
		@AuraEnabled public TaxRollOwner__c currentOwner{get; set;}
		@AuraEnabled public RRCLease__c currentLease{get;set;}
		@AuraEnabled public List<accountSearchResult> accounts {get; set;}
		@AuraEnabled public List<diPermitSearchResult> diPermits {get; set;}
		@AuraEnabled public Integer searchCounter {get; set;}
		@AuraEnabled public String selectedRecord {get; set;}
		@AuraEnabled public String rrcLeaseNumber{get;set;}

			public taxRollInterestSearchResponse(){
			
			errorString = '';
			hasError = false;
			currentInterest = new taxRollInterest__c();
			currentLease = new RRCLease__c();
			currentOwner = new TaxRollOwner__c();
			//searchObject = new DescribeSObjectResult();
			accounts = new List<accountSearchResult>();
			diPermits = new List<diPermitSearchResult>();
			searchObjectLabel = '';
			searchCounter = 0;
			selectedRecord = '';
			rrcLeaseNumber = '';
		}
	}

	public class accountSearchResult{
		@AuraEnabled public string Id {get; set;}
		@AuraEnabled public string Name {get; set;}
		@AuraEnabled public Address BillingAddress {get; set;}
		@AuraEnabled public string BillingStreet {get; set;}
		@AuraEnabled public string BillingCity {get; set;}
		@AuraEnabled public string BillingCountry {get; set;}
		@AuraEnabled public string BillingPostalCode {get; set;}
		@AuraEnabled public Boolean accountSelected {get; set;}

		public accountSearchResult(){
			Id = '';
			Name = '';
			//BillingAddress = '';
			BillingStreet = '';
			BillingCity = '';
			BillingCountry = '';
			BillingPostalCode = '';
			accountSelected = false;

		}
		
	}

	public class diPermitSearchResult{
		@AuraEnabled public string Id {get; set;}
		@AuraEnabled public string Name {get; set;}
		@AuraEnabled public String rrcLeaseNumber {get; set;}
		@AuraEnabled public String api10 {get; set;}
		@AuraEnabled public String permitNumber {get; set;}
		@AuraEnabled public String leaseName {get; set;}
		@AuraEnabled public Decimal permittedAcres {get; set;}
		@AuraEnabled public Boolean permitSelected {get; set;}

		public diPermitSearchResult(){
			Id = '';
			Name = '';
			rrcLeaseNumber = '';
			api10 = '';
			permitNumber = '';
			leaseName = '';
			permittedAcres = 0;
			permitSelected = false;

		}
		
	}

}