src/objects/diTexasPermitWithAcreage__c.object
<CustomObject>
    <description>Drilling Info Texas Permits with Acreage</description>
    <label>Texas Permit with Acreage</label>
    <nameField>
        <displayFormat>DITP-{0000000000}</displayFormat>
        <label>DI Texas Permit with Acreage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Texas Permits with Acreage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RRCLease__c.object
<CustomObject>
    <label>RRC Lease</label>
    <nameField>
        <displayFormat>RRCL-{0000000000}</displayFormat>
        <label>RRC Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RRC Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TaxRollInterest__c.object
<CustomObject>
    <description>Tax Roll Interest to be imported from Drilling Info files.</description>
    <fields>
        <fullName>account__c</fullName>
        <formula>taxRollOwner__r.account__r.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rrcLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RRC Lease</label>
        <referenceTo>RRCLease__c</referenceTo>
        <relationshipLabel>Tax Roll Interests</relationshipLabel>
        <relationshipName>TaxRollInterests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>taxRollOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tax Roll Owner</label>
        <referenceTo>TaxRollOwner__c</referenceTo>
        <relationshipLabel>Tax Roll Interests</relationshipLabel>
        <relationshipName>TaxRollInterests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tax Roll Interest</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Tax Roll Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Roll Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TaxRollOwner__c.object
<CustomObject>
    <fields>
        <fullName>account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax Roll Owners</relationshipLabel>
        <relationshipName>TaxRollOwners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tax Roll Owner</label>
    <nameField>
        <displayFormat>TRON-{0000000000}</displayFormat>
        <label>Tax Roll Owner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Roll Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/taxRollRelateItemAuraTest.cls
@isTest 
private class taxRollRelateItemAuraTest {
	static Final String accountRelatedObject = 'Account';
	static Final String accountField = 'account__c';
	static Final String permitRelatedObject = 'diTexasPermitWithAcreage__c';
	static Final String permitField = 'diTexasPermitWithAcreage__c';

	@TestSetup
	static void setupTestData(){
		
		TestDataFactory.dataSetup();
	}
	@isTest
	private static void testTaxRollRelateItem() {
		List<taxRollOwner__c> taxRollOwners = [SELECT ID FROM taxRollOwner__c];
		List<Account> testAccounts = [SELECT ID, Name FROM Account];
		List<diTexasPermitWithAcreage__c> diPermits = [SELECT ID FROM diTexasPermitWithAcreage__c];
		List<RRCLease__c> testLeases = [SELECT ID FROM RRCLease__c];
		//List<RRC
		Integer testCount = 0;
		Id [] fixedSearchResults= new Id[2];
		fixedSearchResults[0] = testAccounts[0].Id;
		fixedSearchResults[1] = testAccounts[1].Id;
		Test.setFixedSearchResults(fixedSearchResults);
		taxRollRelateItemAura.taxRollInterestSearchResponse firstSearchResponse = taxRollRelateItemAura.getNewSearchResult('New Account', 0, testAccounts[0].Id);
		Integer count = 5;
		for(Integer i = 0; i<count; i++){
			taxRollRelateItemAura.taxRollInterestSearchResponse relatedAccountResponse = taxRollRelateItemAura.getInitialResults(taxRollOwners[i].Id, accountRelatedObject);
			taxRollRelateItemAura.taxRollInterestSearchResponse permitAccountResponse = taxRollRelateItemAura.getInitialResults(testLeases[i].Id, permitRelatedObject);
			List<TaxRollInterest__c> taxRollInterests = taxRollRelatedListAura.getTaxRollOwnerInterests(taxRollOwners[i].Id);
			List<TaxRollInterest__c> leaseTaxRollInterests = taxRollRelatedListAura.getRRCLeaseInterests(testLeases[i].Id);
			//String setAccountReturnMessage = taxRollInterestRelatedItemAura.setRelatedRecord(interest.Id, testAccounts[testCount].Id, accountField);
			//System.assertEquals(setAccountReturnMessage, 'Updated Related Record');
			//String setPermitReturnMessage = taxRollInterestRelatedItemAura.setRelatedRecord(interest.Id, diPermits[testCount].Id, permitField);
			//System.assertEquals(setPermitReturnMessage, 'Updated Related Record');
			if(testCount +1  < testAccounts.size() && testCount + 1 < diPermits.size()){
				testCount++;
			}
			else{
				testCount = 0;
			}
			
		}

	}
	
}