src/objects/divisionOrder__c.object
<CustomObject>
    <fields>
        <fullName>account__c</fullName>
        <formula>case__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Division Orders</relationshipLabel>
        <relationshipName>Division_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dateConfirmed__c</fullName>
        <label>Date Confirmed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dateReceivedFromOperator__c</fullName>
        <label>Date Received from Operator</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dateReturnedToOperator__c</fullName>
        <label>Date Returned to Operator</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Division Orders</relationshipLabel>
        <relationshipName>Division_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>priority__c</fullName>
        <label>Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                    <default>true</default>
                    <label>Medium</label>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sharedDrivePath__c</fullName>
        <label>Shared Drive Path</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Dispute</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Division Order</label>
    <nameField>
        <displayFormat>DO-{000000}</displayFormat>
        <label>Division Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Division Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DivisionOrderRelatedListAura.cls
public without sharing class DivisionOrderRelatedListAura {
    @AuraEnabled
    public static List<divisionOrder__c> getDivisionOrders(Id recordId) {
        List<divisionOrder__c> divisionOrderList = [
            SELECT
                Id,
                Name,
                status__c,
                account__c,
                CreatedById,
                CreatedDate,
                dateConfirmed__c,
                dateReceivedFromOperator__c,
                dateReturnedToOperator__c,
                operator__c,
                operator__r.Name,
                OwnerId,
                Owner.Name,
                priority__c,
                sharedDrivePath__c,
                CreatedBy.Name,
                LastModifiedById,
                case__r.Type,
                case__r.AccountId,
                case__r.Account.Name
            FROM divisionOrder__c
            WHERE case__c = :recordId
        ];

        return divisionOrderList;
    }

    @AuraEnabled
    public static String getCaseRecType(Id recordId) {
        Case caseRec = [SELECT Type FROM Case WHERE Id = :recordId LIMIT 1];
        return caseRec.Type;
    }
}