src/objects/energyLinkBucket__c.object
<CustomObject>
    <fields>
        <fullName>checkURL__c</fullName>
        <externalId>true</externalId>
        <label>Check URL</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>reprocess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true for the system to automatically reprocess the related check during the next scheduled job.</description>
        <label>Reprocess</label>
        <type>Checkbox</type>
    </fields>
    <label>Energy Link Bucket</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Energy Link Check</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energy Link Bucket</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CDEX_ImportChecksScheduler.cls
global class CDEX_ImportChecksScheduler implements Schedulable,Database.AllowsCallouts {
    global void execute(SchedulableContext SC) {
        
        
        List<energyLinkBucket__c> linkList = new List<energyLinkBucket__c>();
        Integer counter = 0;
        for(energyLinkBucket__c  eRec : [Select Id,checkURL__c from energyLinkBucket__c where createdDate>=:system.today() OR reprocess__c = TRUE]){
            if(counter<90){
                linkList.add(eRec);
                counter++;
            }else{
                MakeCalloutsBatch btch = new MakeCalloutsBatch(linkList);
                database.executeBatch(btch,1);
                linkList.clear();
                linkList.add(eRec);
                counter = 0;
            }
        }
        if(linkList.size()>0){
            MakeCalloutsBatch btch = new MakeCalloutsBatch(linkList);
            database.executeBatch(btch,1);
        }
    }
}