src/objects/energyLinkBucket__c.object
<CustomObject>
    <fields>
        <fullName>checkId__c</fullName>
        <description>For reprocessing, insert original check Id.  Without the ID, the reprocess will fail.</description>
        <label>Check Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>checkURL__c</fullName>
        <externalId>true</externalId>
        <label>Check URL</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>reprocess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true for the system to automatically reprocess the related check during the next scheduled job.</description>
        <label>Reprocess</label>
        <type>Checkbox</type>
    </fields>
    <label>Energy Link Bucket</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Energy Link Check</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energy Link Bucket</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Details__c</fullName>
        <label>Additional Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Find Royalty Check</fullName>
                </value>
                <value>
                    <fullName>Delete Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Read Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Insert Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Upsert</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                    <default>true</default>
                    <label>Error</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MakeCalloutsBatch.cls
global class MakeCalloutsBatch implements Database.batchable<sObject >,Database.AllowsCallouts{
	global List<energyLinkBucket__c> linkList = new List<energyLinkBucket__c>();
    
    global MakeCalloutsBatch(List<energyLinkBucket__c> linkList){
        this.linkList = linkList;
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        String soqlQuery = 'SELECT Id,checkUrl__c, checkId__c From energyLinkBucket__c where Id In:linkList';
        return Database.getQueryLocator(soqlQuery);
    }
    
    global void execute(Database.batchableContext info, List<energyLinkBucket__c > scope){ 
        for(energyLinkBucket__c eRec : scope){
            try{
            	CDEXCalloutHelper.getCheckBody(eRec.checkUrl__c,eRec.checkId__c);
				eRec.reprocess__c = false;
            }catch(Exception e){
                log__c logRec = new log__c();
                logRec.Process__c = 'Cdex Check Import';
                logRec.Status__c = 'ERROR';
                logRec.Error_Message__c = e.getMessage();
                logRec.Additional_Details__c = 'Check Url: '+eRec.checkUrl__c;
                logRec.Stack_Trace__c = e.getStackTraceString();
                insert logRec;
            }
        }
		update scope;
   } 
    
   global void finish(Database.batchableContext info){  
       
   }
    
}