src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>Eval-{000000}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GIS_Update_Request__c.object
<CustomObject>
    <description>use to track mapping update request from the GIS team</description>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>GIS Update Requests</relationshipLabel>
        <relationshipName>GIS_Update_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>GIS Update Request</label>
    <nameField>
        <displayFormat>GIS-{000000000}</displayFormat>
        <label>GIS Update Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GIS Update Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>GIS_Unit_Name__c</fullName>
        <label>GIS Unit Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Horizontal</fullName>
                </value>
                <value>
                    <fullName>Vertical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/unitAllocation__c.object
<CustomObject>
    <description>Contains the subtracts in a unit and the associated percent allocation for each subtract</description>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>allocationPercentage__c</fullName>
        <label>% of Subtract Gross Acres in Unit</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>subtractGrossAcres__c</fullName>
        <description>Calculated subtract gross acres based on subtract unit allocation percentage</description>
        <formula>/*subtract__r.Subtract_Gross_Acres__c * (allocationPercentage__c / 100) - original formula, modifying per discussion with Andrew Kock 03-31-2020 jdg*/
subtract__r.Subtract_Gross_Acres__c/* * allocationPercentage__c*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated subtract gross acres based on subtract unit allocation percentage</inlineHelpText>
        <label>Tract - Gross Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>subtract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subtract</label>
        <referenceTo>Subtract__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>uaSubtractGrossAcres__c</fullName>
        <formula>/*subtract__r.Subtract_Gross_Acres__c * (allocationPercentage__c / 100) - original formula, modifying per discussion with Andrew Kock 03-31-2020 jdg*/
subtract__r.Subtract_Gross_Acres__c * allocationPercentage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tract - Gross Acres in Unit</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>unitGrossAcres__c</fullName>
        <description>Unit gross acres estimate unless unit gross acres actual is populated.</description>
        <formula>unit__r.Gross_Acres__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Unit gross acres estimate unless unit gross acres actual is populated.</inlineHelpText>
        <label>Unit Gross Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>unitNRI__c</fullName>
        <description>Subtract NRI * Allocation factor computed</description>
        <formula>subtract__r.Subtract_NRI__c * allocationFactorComputed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Subtract NRI * Allocation factor computed</inlineHelpText>
        <label>Unit NRI</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Unit Allocation</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Unit Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/SubtractUnitAllocationController.cls
public class SubtractUnitAllocationController {

    /**
    * @description 
    * @author Jade Tran
    * @param recordId 
    * @return uaWrapper 
    **/
    @AuraEnabled
    public static uaWrapper getRecords(Id recordId, String acctName){
        List<unitAllocation__c> uaList = new List<unitAllocation__c>();

        if(recordId.getSObjectType().getDescribe().getName() =='Tract__c' ){
            List<Subtract__c> subtractList = [Select Id from subtract__c where Tract__c =:recordId];
            uaList = [Select id,Name,unit__c,unit__r.Name,Subtract__c,Subtract__r.name,
                       subtractGrossAcres__c, uaSubtractGrossAcres__c,unitGrossAcres__c,allocationPercentage__c,
                       unitNRI__c,unit__r.GIS_Unit_Name__c,unit__r.Unit_Type__c,
                       Subtract__r.Tract__r.Name,
                       Subtract__r.Tract__c,Subtract__r.Tract__r.Account__c,
                       Subtract__r.Tract__r.Account__r.Name
                       from unitAllocation__c where subtract__c In: subtractList and Inactive__c = false];
        }else if(recordId.getSObjectType().getDescribe().getName() =='Subtract__c' ){
            uaList = [Select id,Name,unit__c,unit__r.Name,Subtract__c,Subtract__r.name,
                       subtractGrossAcres__c, uaSubtractGrossAcres__c,unitGrossAcres__c,allocationPercentage__c,
                       unitNRI__c,unit__r.GIS_Unit_Name__c,
                       unit__r.Unit_Type__c,Subtract__r.Tract__r.Name,
                       Subtract__r.Tract__c,Subtract__r.Tract__r.Account__c,
                       Subtract__r.Tract__r.Account__r.Name
                       from unitAllocation__c where subtract__c =: recordId and Inactive__c = false];
        }else if(recordId.getSObjectType().getDescribe().getName() =='Unit__c'){
            if (acctName !=''){
			    acctName = '%'+acctName+'%';
                uaList = [Select id,Name,unit__c,unit__r.Name,Subtract__c,Subtract__r.name,
                        subtractGrossAcres__c, uaSubtractGrossAcres__c,unitGrossAcres__c,allocationPercentage__c, unit__r.GIS_Unit_Name__c,
                        unitNRI__c,Subtract__r.Tract__r.Name, Subtract__r.Tract__r.CreatedDate,
                        unit__r.Unit_Type__c,Subtract__r.Tract__c,Subtract__r.Tract__r.Account__c,
                        Subtract__r.Tract__r.Account__r.Name
                        from unitAllocation__c where unit__c =: recordId  and Subtract__r.Tract__r.Account__r.Name like :acctName and Inactive__c = false];
            }else{
                uaList = [Select id,Name,unit__c,unit__r.Name,Subtract__c,Subtract__r.name,
                        subtractGrossAcres__c, uaSubtractGrossAcres__c,unitGrossAcres__c,allocationPercentage__c, unit__r.GIS_Unit_Name__c,
                        unitNRI__c,Subtract__r.Tract__r.Name, Subtract__r.Tract__r.CreatedDate,
                        unit__r.Unit_Type__c,Subtract__r.Tract__c,Subtract__r.Tract__r.Account__c,
                        Subtract__r.Tract__r.Account__r.Name
                        from unitAllocation__c where unit__c =: recordId and Inactive__c = false];
            }
        }else if(recordId.getSObjectType().getDescribe().getName() =='Opportunity'){
            List<Subtract__c> subs = [SELECT Id FROM Subtract__c WHERE Tract__c IN
                                        (SELECT Tract__c FROM Opportunity_Tract__c WHERE Opportunity__c =: recordId)];
            
            uaList = [Select id,Name,unit__c,unit__r.Name,Subtract__c,Subtract__r.name,subtractGrossAcres__c, uaSubtractGrossAcres__c,unitGrossAcres__c,allocationPercentage__c,unitNRI__c,Subtract__r.Tract__r.Name,
                       Subtract__r.Tract__c,Subtract__r.Tract__r.Account__c,unit__r.GIS_Unit_Name__c,unit__r.Unit_Type__c,
                       Subtract__r.Tract__r.Account__r.Name from unitAllocation__c where subtract__c In: subs and Inactive__c = false];
        }
		else if(recordId.getSObjectType().getDescribe().getName() =='Evaluation__c'){
			Evaluation__c currentEval = [SELECT Id, Opportunity__c FROM Evaluation__c WHERE Id = :recordId LIMIT 1];
			return getRecords(currentEval.opportunity__c, '');
		}

		else if(recordId.getSObjectType().getDescribe().getName() =='Account'){
           
            
            uaList = [Select id,Name,unit__c,unit__r.Name,Subtract__c,Subtract__r.name,subtractGrossAcres__c, uaSubtractGrossAcres__c,unitGrossAcres__c,allocationPercentage__c,unitNRI__c,Subtract__r.Tract__r.Name,
                       Subtract__r.Tract__c,Subtract__r.Tract__r.Account__c,unit__r.GIS_Unit_Name__c,unit__r.Unit_Type__c,
                       Subtract__r.Tract__r.Account__r.Name from unitAllocation__c where subtract__r.Tract__r.Account__c =: recordId and Inactive__c = false];
        }else if(recordId.getSObjectType().getDescribe().getName() =='Well__c'){
            
            Well__c wellRec = [Select Id, unit__c from Well__c where Id =: recordId];

            uaList = [Select id,Name,unit__c,unit__r.Name,Subtract__c,Subtract__r.name,
                        subtractGrossAcres__c, uaSubtractGrossAcres__c,unitGrossAcres__c,allocationPercentage__c,
                        unitNRI__c,Subtract__r.Tract__r.Name,
                        Subtract__r.Tract__c,Subtract__r.Tract__r.Account__c,unit__r.GIS_Unit_Name__c,unit__r.Unit_Type__c,
                        Subtract__r.Tract__r.Account__r.Name from unitAllocation__c where unit__c =: wellRec.unit__c  and Inactive__c = false];
        }else if(recordId.getSObjectType().getDescribe().getName() =='GIS_Update_Request__c'){

            GIS_Update_Request__c record = [Select Id, Unit__c from GIS_Update_Request__c where Id=:recordId];
			if (acctName !=''){
			acctName = '%'+acctName+'%';
            uaList = [Select id,Name,unit__c,unit__r.Name,Subtract__c,Subtract__r.name,
                        subtractGrossAcres__c, uaSubtractGrossAcres__c,unitGrossAcres__c,allocationPercentage__c,
                        unitNRI__c,Subtract__r.Tract__r.Name,
                        Subtract__r.Tract__c,Subtract__r.Tract__r.Account__c,Inactive__c,CreatedDate,LastModifiedDate,
                        Subtract__r.Tract__r.Account__r.Name from unitAllocation__c where unit__c =: record.unit__c and Subtract__r.Tract__r.Account__r.Name like :acctName];
        }
		 else {
			 uaList = [Select id,Name,unit__c,unit__r.Name,Subtract__c,Subtract__r.name,
                        subtractGrossAcres__c, uaSubtractGrossAcres__c,unitGrossAcres__c,allocationPercentage__c,
                        unitNRI__c,Subtract__r.Tract__r.Name,
                        Subtract__r.Tract__c,Subtract__r.Tract__r.Account__c,Inactive__c,CreatedDate,LastModifiedDate,
                        Subtract__r.Tract__r.Account__r.Name from unitAllocation__c where unit__c =: record.unit__c];
		 }
		}
        uaWrapper sWrap = new uaWrapper();
        sWrap.sObjectName = recordId.getSObjectType().getDescribe().getName();
        sWrap.uaList  = uaList;
        return sWrap;
    }

    public class uaWrapper{
        @AuraEnabled
        public List<unitAllocation__c> uaList{get;set;}
        @AuraEnabled
        public string sObjectName{get;set;}
        
    }
}