src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>hasAttachment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Attachment</label>
        <type>Checkbox</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>Eval-{000000}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/ContentDocumentLinkTriggerHelper.cls
public class ContentDocumentLinkTriggerHelper {

    public static void updateEvaluationRecords(List<contentDocumentLink> newList){
        
        Set<Id> evaluationSet = new Set<Id>();
        for(contentDocumentLink rec : newList){
            if(rec.LinkedEntityId.getSObjectType().getDescribe().getName() == 'Evaluation__c'){
                evaluationSet.add(rec.LinkedEntityId);
            }
        }
        if(evaluationSet.size()>0){
            List<Evaluation__c> eList = new List<Evaluation__c>();
            for(Id eId : evaluationSet){
                Evaluation__c eRec = new Evaluation__c();
                eRec.hasAttachment__c =true;
                eRec.Id = eId;
                eList.add(eRec);
            }
            if(eList.size()>0){
                update eList;
            }
        }
    }
}