src/objects/Evaluation__c.object
<CustomObject>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>Eval-{000000}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LandGridTract__c.object
<CustomObject>
    <label>LandGridTract</label>
    <nameField>
        <label>LandGridTract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LandGridTracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_AOI__c.object
<CustomObject>
    <description>Project AOI</description>
    <label>Project AOI</label>
    <nameField>
        <label>Project AOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAOIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_AOI_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>ProjectAOITracts</relationshipLabel>
        <relationshipName>ProjectAOITracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project AOI Tract</label>
    <nameField>
        <label>Project AOI Tract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAOITracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TitleIntegrationJob__c.object
<CustomObject>
    <description>Batch job information for title loading</description>
    <fields>
        <fullName>landGridTract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>LandGridTract related to job</description>
        <inlineHelpText>LandGridTract related to job</inlineHelpText>
        <label>LandGridTract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Title Integration Jobs</relationshipLabel>
        <relationshipName>titleIntegrationJobs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Title Integration Job</label>
    <nameField>
        <displayFormat>TIJ-{0000000000}</displayFormat>
        <label>Title Integration Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Integration Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>LandGridTract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LandGridTract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Tracts (LandGridTract)</relationshipLabel>
        <relationshipName>Tracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactoryTest.cls
@isTest 
private class TestDataFactoryTest {

	@TestSetup
	static void tractReconciliationTestData(){
		TestDataFactory.dataSetup();
		TitleIntegrationJob__c tpj = [SELECT ID FROM TitleIntegrationJob__c LIMIT 1];
		String str = 'Party,Final,Address,Notes,Lease,Book,Page,Inst.,Lease LOR,Executive,Royalty,NPRI8,Bonus,Delay,Ingress,WI,NRI,LOR,OI,Area,Gr.Ac.,NMRA,NLRA,Depth,Mineral,State,County,Location,Status,Assigned User\r' +
							'Sherri Lee Hollis,final,"6405 Hamstead Dr. Amarillo, TX 79109",,1020/432,1020,432,,0.1875,0.11111111,0.02222222,,0.02222222,0.02222222,0.02222222,,,0.00416667,,SW,160.00,3.55555556,0.66666667,,,TX,Howard,031-02N-009,Initial Rev.,MSB\r'+
							'Sherri Lee Hollis,final,"6405 Hamstead Dr. Amarillo, TX 79109",,1253/16,1253,16,,0.25,,0.00444444,,0.00444444,0.00444444,0.00444444,,,0.00111111,,N2,320.00,1.42222222,0.35555556,,,TX,Howard,031-02N-009,Initial Rev.,MSB\r'+
							'Sherri Lee Hollis,final,"6405 Hamstead Dr. Amarillo, TX 79109",,1253/19,1253,19,,0.25,,0.00444444,,0.00444444,0.00444444,0.00444444,,,0.00111111,,N2,320.00,1.42222222,0.35555556,,,TX,Howard,031-02N-009,Initial Rev.,MSB\r'+
							'Sherri Lee Hollis,final,"6405 Hamstead Dr. Amarillo, TX 79109",,1253/13,1253,13,,0.25,,0.00444444,,0.00444444,0.00444444,0.00444444,,,0.00111111,,N2,320.00,1.42222222,0.35555556,,,TX,Howard,031-02N-009,Initial Rev.,MSB\r'+
							'Sherri Lee Hollis,final,"6405 Hamstead Dr. Amarillo, TX 79109",,1253/22,1253,22,,0.25,0.11111111,0.02222222,,0.02222222,0.02222222,0.02222222,,,0.00555556,,SE,160.00,3.55555556,0.88888889,,,TX,Howard,031-02N-009,Initial Rev.,MSB\r';
		String[] csvFileLines;
		Blob csvFileBody;
		//ContentDocument newDocument = new ContentDocument();
		ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        //cv.ContentDocumentId = contentDocumentId;
        cv.VersionData = Blob.valueOf(str);
        cv.Title = 'flatFileTest.csv';
		cv.FirstPublishLocationId = tpj.Id;
		//cv.FileExtension = 'csv';
		//cv.FileType = 'csv';
        cv.PathOnClient = 'flatFileTest.csv';
        
        insert cv;
		//newDocument.Title = 'flatFileTest';
		//Insert newDocument;
		System.debug('newDocumentId value is: ' + cv.Id);
		
	}



    static testmethod void mainMethod(){
		Test.startTest();

		Profile userProfile = [Select ID, Name from Profile Where Name = :'Standard User' LIMIT 1];
		Profile adminProfile = [Select ID, Name from Profile Where Name = :'System Administrator' LIMIT 1];


		List<LandGridTract__c> landGridTracts = [SELECT ID FROM LandGridTract__c];
		System.assertEquals(12, landGridTracts.size());

        List<Account> accounts = [SELECT ID FROM Account];
		System.assertEquals(5, accounts.size());

        List<Tract__c> tracts = [SELECT ID FROM Tract__c];
		System.assertEquals(12, tracts.size());

		List<Subtract__c> subtracts = [SELECT ID FROM Subtract__c];
		System.assertEquals(12, subtracts.size());

		List<Project_AOI__c> projectAOIs = [SELECT ID FROM Project_AOI__c];
		System.assertEquals(3, projectAOIs.size());

		List<Project_AOI_Tract__c> projectAOITracts = [SELECT ID FROM Project_AOI_Tract__c];
		System.assertEquals(36, projectAOITracts.size());

        List<Opportunity> opps = [SELECT ID FROM Opportunity];
		System.assertEquals(1, opps.size());

        List<Case> cases = [SELECT ID FROM Case];
		System.assertEquals(5, cases.size());

        List<Opportunity_Tract__c> ots = [SELECT ID FROM Opportunity_Tract__c];
		System.assertEquals(12, ots.size());

        //List<Case_Tract__c> cts = [SELECT ID FROM Case_Tract__c];
		//System.assertEquals(60, cts.size());

		List<TitleIntegrationJob__c> tpjs = [SELECT ID FROM TitleIntegrationJob__c];
		System.assertEquals(5, tpjs.size());
		
		List<Evaluation__c> evals = [SELECT ID FROM Evaluation__c];
		System.assertEquals(2, evals.size());

		Test.stopTest();
	}
	
}