src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>Eval-{000000}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Monthly_Production__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <formula>Well__r.API10__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>API10</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Operator_Name__c</fullName>
        <label>Current Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Operator (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Well__c</fullName>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000000}</displayFormat>
        <label>Monthly Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/revenueEstimate__c.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>monthlyProduction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Production</label>
        <referenceTo>Monthly_Production__c</referenceTo>
        <relationshipName>Owner_Interest_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ownerNetRevenueValueGas__c</fullName>
        <formula>/*monthlyProduction__r.Well_Net_Revenue_Value_Gas__c * unitAllocation__r.unitNRI__c*/
monthlyProduction__r.Well_Net_Revenue_Value_Gas__c * unitAllocation__r.uaNRI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Net Revenue Value Gas</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ownerNetRevenueValueOil__c</fullName>
        <formula>/*monthlyProduction__r.Well_Net_Revenue_Value_Oil__c* unitAllocation__r.unitNRI__c*/
monthlyProduction__r.Well_Net_Revenue_Value_Oil__c* unitAllocation__r.uaNRI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Net Revenue Value Oil</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>unitAllocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Allocation</label>
        <referenceTo>unitAllocation__c</referenceTo>
        <relationshipLabel>Revenue Estimates</relationshipLabel>
        <relationshipName>Owner_Interest_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Estimate</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>RevenueEstimate  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/unitAllocation__c.object
<CustomObject>
    <description>Contains the subtracts in a unit and the associated percent allocation for each subtract</description>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subtract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subtract</label>
        <referenceTo>Subtract__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Unit Allocation</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Unit Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <description>API/Unique Well Identifier (10 Digit)</description>
        <externalId>true</externalId>
        <inlineHelpText>API/Unique Well Identifier (10 Digit)</inlineHelpText>
        <label>API10</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Current_Operator_Name__c</fullName>
        <label>Current Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Operator (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hole_Direction__c</fullName>
        <label>Hole Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vertical</fullName>
                </value>
                <value>
                    <fullName>Directional</fullName>
                </value>
                <value>
                    <fullName>HORIZONTAL</fullName>
                    <label>Horizontal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Paying_calc__c</fullName>
        <description>Returns true if there is monthly production activity data in the last 12 months. Calculated in GIS database.</description>
        <formula>IF(YEAR(Last_Production_Month__c ) - YEAR( TODAY() )&lt;1,true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Returns true if there is monthly production activity data in the last 12 months. Calculated in GIS database.</inlineHelpText>
        <label>Is Paying</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Permit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Returns True if the record is a Well Permit only.  Calculated in GIS Database.</description>
        <inlineHelpText>Returns True if the record is a Well Permit only.  Calculated in GIS Database.</inlineHelpText>
        <label>Is Permit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastActivityDate__c</fullName>
        <formula>IF( CONTAINS(wellStatus__c, &apos;Permit&apos;), Permit_Date__c ,Spud_Date__c   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LastActivityType__c</fullName>
        <formula>IF(CONTAINS(wellStatus__c,&apos;Permit&apos;), &apos;Permit&apos;, &apos;Spud&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Activity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Production_Date__c</fullName>
        <description>Date of the last Monthly Production record.  Calculated by GIS database.</description>
        <inlineHelpText>Date of the last Monthly Production record.  Calculated by GIS database.</inlineHelpText>
        <label>Last Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Production_Month_Used__c</fullName>
        <description>Month used for 1 month production oil, gas, and totals and Last Production Month used in the calculation for 3 month production oil, gas, and totals.</description>
        <inlineHelpText>Month used for 1 month production oil, gas, and totals and Last Production Month used in the calculation for 3 month production oil, gas, and totals.</inlineHelpText>
        <label>Last Production Month Used</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Production_Month__c</fullName>
        <description>Last Month from Monthly Production record for Well</description>
        <inlineHelpText>Last Month from Monthly Production record for Well</inlineHelpText>
        <label>Last Production Month</label>
        <summarizedField>Monthly_Production__c.Production_Date__c</summarizedField>
        <summaryForeignKey>Monthly_Production__c.Well__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Permit_Date__c</fullName>
        <label>Permit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Production_Actual_Start_Date__c</fullName>
        <label>Production Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Spud_Date__c</fullName>
        <label>Spud Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>wellStatus__c</fullName>
        <formula>IF(  NOT(ISBLANK(First_Production_Month__c)) ,&apos;Producing&apos;, IF(  AND(NOT(ISBLANK(Spud_Date__c)),Today() - Spud_Date__c&gt;=730),&apos;Shut-In&apos;,IF(NOT(ISBLANK(Spud_Date__c)) ,&apos;DUC&apos;,IF(  TODAY() -  Permit_Date__c &gt;= 730 ,&apos;Expired Permits&apos; , IF(  NOT(ISBLANK(Permit_Date__c)) ,&apos;Permit&apos; ,&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Well Status</label>
        <type>Text</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WellUnitUtil.cls
public with sharing class WellUnitUtil {
    @AuraEnabled(Cacheable=true)
    public static WellUnitUtilInfo getWellInfo(Id objId) {
        // Build the set of Subtract Ids based on object type
        Set <Id> subIds = new Set<Id>();
        if (Schema.Subtract__c.SObjectType == objId.getSobjectType()) {
            // Add Subtract Id
            subIds.add(objId);
            WellUnitUtilInfo w = getWellInfoBySubtracts(subIds);
            w.objName = 'Subtract__c';
            return w;
        } else if (Schema.Tract__c.SObjectType == objId.getSobjectType()) {
            // Add Subtracts that are children of this tract
            List<Subtract__c> subs = [SELECT Id FROM Subtract__c WHERE Tract__c = : objId];
            subIds = Util.getIds(subs);
            WellUnitUtilInfo w = getWellInfoBySubtracts(subIds);
            w.objName = 'Tract__c';
            return w;
        } else if (Schema.Opportunity.SObjectType == objId.getSobjectType()) {
            //Add unique Subtracts that are related to this opportunity
            List<Subtract__c> subs = [SELECT Id FROM Subtract__c WHERE Tract__c IN
                                        (SELECT Tract__c FROM Opportunity_Tract__c WHERE Opportunity__c =: objId)];
            subIds = Util.getIds(subs);
            WellUnitUtilInfo w = getWellInfoBySubtracts(subIds);
            w.objName = 'Opportunity';
            return w;
		} else if (Schema.Evaluation__c.SObjectType == objId.getSobjectType()) {
			Evaluation__c currentEval = [SELECT Id, Opportunity__c FROM Evaluation__c WHERE Id = :objId LIMIT 1];
			return getWellInfo(currentEval.opportunity__c);
        } else if(Schema.Unit__c.SObjectType == objId.getSobjectType()){
            WellUnitUtilInfo w = getWellInfoByUnits(new Set<Id>{objId});
            w.objName = 'Unit__c';
            return w;
        } else if(Schema.Account.SObjectType == objId.getSobjectType()){
            //Add unique Subtracts that are related to this opportunity
            List<Subtract__c> subs = [SELECT Id FROM Subtract__c WHERE Tract__r.Account__c =: objId];
            subIds = Util.getIds(subs);
            WellUnitUtilInfo w = getWellInfoBySubtracts(subIds);
            w.objName = 'Account';
            return w;
        }
        return null;
    }

    public static WellUnitUtilInfo getWellInfoBySubtracts(Set<Id> subtractIds) {
        WellUnitUtilInfo wi = new WellUnitUtilInfo();
        Date lastMonth = null;
        Set<Id> permitIds = new Set<Id>();
        Set<Id> payingHzIds = new Set<Id>();
        Set<Id> hzIds = new Set<Id>();
        Set<Id> payingVtIds = new Set<Id>();
        Set<Id> vtIds = new Set<Id>();
        Map<Id,Decimal> oirGasWellMap = new Map<Id,Decimal>();
        Map<Id,Decimal> oirOilWellMap  = new Map<Id,Decimal>();
        // Load Well Interest Allocations
        wi.permits = new List<Well__c>();
        wi.hzWells = new List<WellUnitWrapper>();
        wi.vertWells = new List<WellUnitWrapper>();

        Set<String> strSet = new Set<String>();
        Set<Id> wellIds = new Set<Id>();
        Map<Id,String> uaMap = new Map<Id,String>();
        Map<Id,Decimal> uaNRIMap = new Map<Id,Decimal>();
        Map<Id,unitAllocation__c> uaRecMap = new Map<Id,unitAllocation__c>();
        Set<Id> unitIds = new Set<Id>();
        unitAllocation__c uaRec;
        String str;

        for(revenueEstimate__c oir : [SELECT Id, unitAllocation__c,monthlyProduction__r.Well__c,
                ownerNetRevenueValueGas__c,ownerNetRevenueValueOil__c
                FROM revenueEstimate__c 
                WHERE unitAllocation__r.Subtract__c IN: subtractIds AND Inactive__c = false]){

                if(oirGasWellMap.containsKey(oir.monthlyProduction__r.Well__c)){
                    Decimal sumGas = oirGasWellMap.get(oir.monthlyProduction__r.Well__c)+((oir.ownerNetRevenueValueGas__c==null)?0.0:oir.ownerNetRevenueValueGas__c);
                    Decimal sumOil = oirGasWellMap.get(oir.monthlyProduction__r.Well__c)+((oir.ownerNetRevenueValueOil__c==null)?0.0:oir.ownerNetRevenueValueOil__c);
                    oirGasWellMap.put(oir.monthlyProduction__r.Well__c,sumGas);
                    oirOilWellMap.put(oir.monthlyProduction__r.Well__c,sumOil);
                }else{
                    oirGasWellMap.put(oir.monthlyProduction__r.Well__c,(oir.ownerNetRevenueValueGas__c==null)?0.0:oir.ownerNetRevenueValueGas__c);
                    oirOilWellMap.put(oir.monthlyProduction__r.Well__c,(oir.ownerNetRevenueValueOil__c==null)?0.0:oir.ownerNetRevenueValueOil__c);
                }
        } 
        for(unitAllocation__c sub:[Select Id,Unit__c from unitAllocation__c where subtract__c In:subtractIds and Inactive__c = false]){
            unitIds.add(sub.Unit__c);
        }
        Map<Id,Well__c> wellMap = new Map<Id,Well__c>([Select Id,Name,Current_Operator__r.Name, API10__c, Hole_Direction__c,
                Spud_Date__c, Permit_Date__c, Production_Actual_Start_Date__c, Unit__c,Unit__r.Name,
                Current_Operator_Name__c, Is_Permit__c, Is_Paying_calc__c, LastActivityDate__c,
                LastActivityType__c, Last_Production_Date__c, Last_Production_Month_Used__c,
                Last_Production_Month__c From Well__c where unit__c In: unitIds AND wellStatus__c ='Producing']);
system.debug(wellMap);
        Well__c wellRec;
        
        for(Id wellId : wellMap.keySet()){
            wellRec = new Well__c();
            wellRec = wellMap.get(wellId);
            
            Datetime actDate = null;
            if (null != wellRec.LastActivityDate__c) {
                actDate = wellRec.LastActivityDate__c + 1;  // without +1, the day before is displayed
            }
            Datetime prodDate = null;
            if (wellRec.Last_Production_Date__c != null) {
                prodDate = wellRec.Last_Production_Date__c + 1; // without +1, the day before is displayed
            }
            String direction = wellRec.Hole_Direction__c.left(1).toLowerCase();
            
            if (!wellRec.Is_Permit__c) {
                
                WellUnitWrapper ww = new WellUnitWrapper();
                ww.well = wellRec;
                ww.sumGas = oirGasWellMap.get(wellRec.Id);
                ww.sumOil = oirOilWellMap.get(wellRec.Id);
                
                if (wellRec.Is_Paying_calc__c) {
                    if (prodDate != null) {
                     ww.lastActivityInfo = prodDate.format('MM/dd/yy') + ' Prod';
                    }
                    if (direction == 'h') {
                        payingHzIds.add(wellRec.Id);
                    } else {
                        payingVtIds.add(wellRec.Id);
                    }
                }
                else {
                    // This is not paying, so update the last activity appropriately
                    if (actDate != null) {
                        ww.lastActivityInfo = actDate.format('MM/dd/yy') + ' ' + wellRec.LastActivityType__c;
                    }
                    else
                    {
                        if (wellRec.LastActivityDate__c  == null) {
                            ww.lastActivityInfo = 'Unknown';
                        }
                    }
                }
                // Increment horizontal/vertical counter
                if (direction == 'h') {
                    hzIds.add(wellRec.Id);
                    wi.hzWells.add(ww);
                    //wi.hzPaying++;
                } else {
                    vtIds.add(wellRec.Id);
                    wi.vertWells.add(ww);
                    //wi.vertPaying++;
                }
            }
        }
        // Track the last month there is a production record
        wi.lastMonth = lastmonth;

        // Get permits as wells without using the WellInfo wrapper
        List<Well__c> permitWells = new List<Well__c>();
        List<Well__c> ducs = new List<Well__c>();
        System.debug(unitIds);
        for(Well__c wRec: [SELECT Id, API10__c, Is_Permit__c, Current_Operator_Name__c,
                    Hole_Direction__c, LastActivityDate__c, LastActivityType__c, Name,wellStatus__c,Spud_Date__c, Unit__r.Name, Unit__c
                    FROM Well__c WHERE unit__c IN: unitIds AND (wellStatus__c = 'Permit' OR wellStatus__c = 'DUC')
                    AND Hole_Direction__c != 'Vertical'
                    ORDER BY Current_Operator_Name__c, LastActivityDate__c]){

                        if(wRec.wellStatus__c=='Permit'){
                            permitWells.add(wRec);
                        }else{
                            ducs.add(wRec);
                        }
                    }
        


        wi.permits = permitWells;
        wi.ducWells = ducs;
        wi.hzPaying = payingHzIds.size();
        wi.vertPaying = payingVtIds.size();
        wi.hzWellCount = hzIds.size();
        wi.vertWellCount = vtIds.size();
        
        return wi;
    }

    public static WellUnitUtilInfo getWellInfoByUnits(Set<id> unitIds){
        WellUnitUtilInfo wi = new WellUnitUtilInfo();
        Date lastMonth = null;
        Set<Id> permitIds = new Set<Id>();
        Set<Id> payingHzIds = new Set<Id>();
        Set<Id> hzIds = new Set<Id>();
        Set<Id> payingVtIds = new Set<Id>();
        Set<Id> vtIds = new Set<Id>();
        Map<Id,Decimal> oirGasWellMap = new Map<Id,Decimal>();
        Map<Id,Decimal> oirOilWellMap  = new Map<Id,Decimal>();
        // Load Well Interest Allocations
        wi.permits = new List<Well__c>();
        wi.hzWells = new List<WellUnitWrapper>();
        wi.vertWells = new List<WellUnitWrapper>();

        Set<String> strSet = new Set<String>();
        Set<Id> wellIds = new Set<Id>();
        Map<Id,String> uaMap = new Map<Id,String>();
        Map<Id,Decimal> uaNRIMap = new Map<Id,Decimal>();
        Map<Id,unitAllocation__c> uaRecMap = new Map<Id,unitAllocation__c>();
        unitAllocation__c uaRec;
        String str;
        Map<Id,Well__c> wellMap = new Map<Id,Well__c>([Select Id,Name,Current_Operator__r.Name, API10__c, Hole_Direction__c,
                Spud_Date__c, Permit_Date__c, Production_Actual_Start_Date__c, Unit__c,Unit__r.Name,
                Current_Operator_Name__c, Is_Permit__c, Is_Paying_calc__c, LastActivityDate__c,
                LastActivityType__c, Last_Production_Date__c, Last_Production_Month_Used__c,
                Last_Production_Month__c From Well__c where unit__c In: unitIds AND wellStatus__c ='Producing']);
system.debug(wellMap);
        Well__c wellRec;
        
        for(Id wellId : wellMap.keySet()){
            wellRec = new Well__c();
            wellRec = wellMap.get(wellId);
            
            Datetime actDate = null;
            if (null != wellRec.LastActivityDate__c) {
                actDate = wellRec.LastActivityDate__c + 1;  // without +1, the day before is displayed
            }
            Datetime prodDate = null;
            if (wellRec.Last_Production_Date__c != null) {
                prodDate = wellRec.Last_Production_Date__c + 1; // without +1, the day before is displayed
            }
            String direction = wellRec.Hole_Direction__c.left(1).toLowerCase();
            
            if (!wellRec.Is_Permit__c) {
                
                WellUnitWrapper ww = new WellUnitWrapper();
                ww.well = wellRec;
                
                if (wellRec.Is_Paying_calc__c) {
                    if (prodDate != null) {
                     ww.lastActivityInfo = prodDate.format('MM/dd/yy') + ' Prod';
                    }
                    if (direction == 'h') {
                        payingHzIds.add(wellRec.Id);
                    } else {
                        payingVtIds.add(wellRec.Id);
                    }
                }
                else {
                    // This is not paying, so update the last activity appropriately
                    if (actDate != null) {
                        ww.lastActivityInfo = actDate.format('MM/dd/yy') + ' ' + wellRec.LastActivityType__c;
                    }
                    else
                    {
                        if (wellRec.LastActivityDate__c  == null) {
                            ww.lastActivityInfo = 'Unknown';
                        }
                    }
                }

                // Increment horizontal/vertical counter

                if (direction == 'h') {
                    hzIds.add(wellRec.Id);
                    wi.hzWells.add(ww);
                    //wi.hzPaying++;
                } else {
                    vtIds.add(wellRec.Id);
                    wi.vertWells.add(ww);
                    //wi.vertPaying++;
                }
            }
        }

        // Track the last month there is a production record
        wi.lastMonth = lastmonth;

        // Get permits as wells without using the WellInfo wrapper
        List<Well__c> permitWells = new List<Well__c>();
        List<Well__c> ducs = new List<Well__c>();
        System.debug(unitIds);
        for(Well__c wRec: [SELECT Id, API10__c, Is_Permit__c, Current_Operator_Name__c,
                    Hole_Direction__c, LastActivityDate__c, LastActivityType__c, Name,wellStatus__c,Spud_Date__c, Unit__r.Name, Unit__c
                    FROM Well__c WHERE unit__c IN: unitIds AND (wellStatus__c = 'Permit' OR wellStatus__c = 'DUC')
                    AND Hole_Direction__c != 'Vertical'
                    ORDER BY Current_Operator_Name__c, LastActivityDate__c]){

                        if(wRec.wellStatus__c=='Permit'){
                            permitWells.add(wRec);
                        }else{
                            ducs.add(wRec);
                        }
                    }
        


        wi.permits = permitWells;
        wi.ducWells = ducs;
        wi.hzPaying = payingHzIds.size();
        wi.vertPaying = payingVtIds.size();
        wi.hzWellCount = hzIds.size();
        wi.vertWellCount = vtIds.size();
        
        return wi;
    }


    public class WellUnitUtilInfo {
        @AuraEnabled
        public string objName{get;set;}
        @AuraEnabled
        public List<Well__c> permits {get; set;}
        @AuraEnabled
        public List<Well__c> ducWells {get; set;}
        @AuraEnabled
        public List<WellUnitWrapper> hzWells {get; set;}
        @AuraEnabled
        public List<WellUnitWrapper> vertWells {get; set;}
        @AuraEnabled
        public Integer hzPaying {get; set;}
        @AuraEnabled
        public Integer vertPaying {get; set;}
        @AuraEnabled
        public Integer hzWellCount {get; set;}
        @AuraEnabled
        public Integer vertWellCount {get; set;}
        @AuraEnabled
        public Date lastMonth {get; set;}
    }

    public class WellUnitWrapper {
        @AuraEnabled
        public String lastActivityInfo {get; set;}
        @AuraEnabled
        public Well__c well {get; set;}
        @AuraEnabled
        public String uaName {get; set;}
        @AuraEnabled
        public Decimal uaDecimal {get; set;}
        @AuraEnabled
        public unitAllocation__c uaRec {get; set;}
        @AuraEnabled
        public Decimal sumGas {get; set;}
        @AuraEnabled
        public Decimal sumOil {get; set;}
    }

}