src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>Eval-{000000}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FMV_Per_Acre__c</fullName>
        <description>Sum of all FMV divided by Total Acres for related tracts</description>
        <formula>if (Total_Acreage__c = 0,0, Total_FMV__c /  Total_Acreage__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Sum of all FMV divided by Total Acres for related tracts</inlineHelpText>
        <label>FMV Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gain_on_Asset__c</fullName>
        <description>Gain on sale (Total FMV - Total Cost)</description>
        <formula>Total_FMV__c - Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gain on sale (Total FMV - Total Cost)</inlineHelpText>
        <label>Gain on Asset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <formula>if(Total_Cost__c = 0, 0, Total_Cost__c /  Total_Acreage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Sum of all &quot;Total Cost&quot; fields</description>
        <label>Total Cost</label>
        <summarizedField>Opportunity_Tract__c.Total_Cost__c</summarizedField>
        <summaryForeignKey>Opportunity_Tract__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>askTotalPrice__c</fullName>
        <label>Ask Total Price</label>
        <summarizedField>Opportunity_Tract__c.askTotalPrice__c</summarizedField>
        <summaryForeignKey>Opportunity_Tract__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>totalPrice__c</fullName>
        <label>Total Price</label>
        <summarizedField>Opportunity_Tract__c.totalPrice__c</summarizedField>
        <summaryForeignKey>Opportunity_Tract__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Acquisition</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <label>Acquisition</label>
    </recordTypes>
    <recordTypes>
        <fullName>Divestiture</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <label>Divestiture</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>FMV_Per_Acre__c</fullName>
        <label>FMV Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fair_Market_Value__c</fullName>
        <formula>FMV_Per_Acre__c * Tract_Acres__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fair Market Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gain_on_Asset__c</fullName>
        <label>Gain on Asset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Instrument_Type__c</fullName>
        <formula>TEXT(Tract__r.Instrument_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Instrument Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes from tract record</description>
        <label>Notes</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <description>OTG = &quot;Off the Ground&quot; - how much was paid to the previous owner (does not include commissions, title costs etc.)</description>
        <inlineHelpText>OTG = &quot;Off the Ground&quot; - how much waspaid to the previous owner (does not include commissions, title costs etc.)</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTG_Cost__c</fullName>
        <description>Cost per acre copied from tract for roll up calculations</description>
        <label>OTG Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Copied from Tract used for roll up calculations</description>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tract_Acres__c</fullName>
        <label>Tract Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>askUnitPrice__c</fullName>
        <label>Ask Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>totalPrice__c</fullName>
        <formula>unitPrice__c *  Tract_Acres__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>unitPrice__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_AOI_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>ProjectAOITracts</relationshipLabel>
        <relationshipName>ProjectAOITracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>netAcreageUnits__c</fullName>
        <formula>TEXT(Tract__r.netAcreageUnits__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Acreage Units</label>
        <type>Text</type>
    </fields>
    <label>Project AOI Tract</label>
    <nameField>
        <label>Project AOI Tract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAOITracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Fair_Market_Value__c</fullName>
        <formula>Value_Per_Acre__c *  netAcres__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Value per acre times net acres</inlineHelpText>
        <label>Fair Market Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_Legal_Name__c</fullName>
        <formula>LandGridTract__r.Name  &amp; &apos; &apos; &amp; Quarter_Call__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gain_on_Asset__c</fullName>
        <formula>Fair_Market_Value__c -  Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>FMV - Total Cost</inlineHelpText>
        <label>Gain on Asset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Instrument_Type__c</fullName>
        <label>Instrument Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OGL</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ORRI</fullName>
                </value>
                <value>
                    <fullName>Surface</fullName>
                </value>
                <value>
                    <fullName>Commission</fullName>
                </value>
                <value>
                    <fullName>NPRI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <inlineHelpText>OTG Cost per Acre</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTG_Cost__c</fullName>
        <formula>netAcres__c * OTG_Cost_Per_Acre__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OTG Price per acre x Net Acres</inlineHelpText>
        <label>OTG Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <formula>if (netAcres__c == 0,0,Total_Cost__c /  netAcres__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Costs divided by Net Acres</inlineHelpText>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>OTG Costs plus Commissions and title</description>
        <formula>(netAcres__c *  OTG_Cost_Per_Acre__c) +  Commission_Amount__c +  Title_Cost__c +  Other_Capitalized_Costs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OTG Costs plus Commissions and title</inlineHelpText>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>depth__c</fullName>
        <label>Depth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>maxPPA__c</fullName>
        <formula>if(aoiNetAcres__c &lt;&gt; 0, maxPrice__c / aoiNetAcres__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Max Price Per Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>maxPrice__c</fullName>
        <description>Max Price for Tract</description>
        <inlineHelpText>Max Price for Tract</inlineHelpText>
        <label>Max Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>netAcreageUnits__c</fullName>
        <label>Net Acreage Units</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NRA</fullName>
                </value>
                <value>
                    <fullName>NMA</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>percentCovered__c</fullName>
        <description>Sum of percentage in AOI for project AOI tract</description>
        <inlineHelpText>Sum of percentage in AOI for project AOI tract</inlineHelpText>
        <label>percentCovered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>targetPPA__c</fullName>
        <formula>if(aoiNetAcres__c &lt;&gt; 0, targetPrice__c /  aoiNetAcres__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Price Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>targetPrice__c</fullName>
        <description>Sum of target price for Project AOI Tract</description>
        <inlineHelpText>Sum of target price for Project AOI Tract</inlineHelpText>
        <label>Target Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>titleSourceType__c</fullName>
        <formula>TEXT(titleSource__r.type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title Source Type</label>
        <type>Text</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OppExtension.cls
public with sharing class OppExtension {
    public List<Opportunity_Tract__c> oppTractList {get; set;}
	public List<Project_AOI_Tract__c> projectAOITractList {get; set;}
    public Boolean isAcquisition {get; set;}
    public Boolean isDivestiture {get; set;}


    @AuraEnabled(Cacheable=true)
    public static String getOppType(Id oppId) {
        Opportunity opp = [SELECT Id, RecordType.Name FROM Opportunity WHERE Id =: oppId];
        return opp.RecordType.Name;
    }

    @AuraEnabled(Cacheable=true)
    public static List<Opportunity_Tract__c> getTracts(Id recordId, String sObjectName) {
		String oppId = '';
		if(sObjectName == 'Opportunity'){
			oppId = recordId;
		}
		else if(sObjectName == 'Evaluation__c'){
			Evaluation__c currentEval = [SELECT Id, Opportunity__c FROM Evaluation__c WHERE Id = :recordId LIMIT 1];
			oppId = currentEval.opportunity__c;
		} 
        List<Opportunity_Tract__c> ots = [SELECT Tract__r.Id,Tract__c,Tract__r.Name,Tract__r.Full_Legal_Name__c,Tract__r.Instrument_Type__c,            
				OTG_Cost__c, OTG_Cost_Per_Acre__c, Total_Cost__c,Total_Cost_Per_Acre__c,Tract__r.Notes__c, Tract__r.titleSourceType__c,
                FMV_Per_Acre__c, Fair_Market_Value__c, Instrument_Type__c, Tract_Acres__c,tract__r.depth__c,
                Gain_on_Asset__c, Tract__r.percentCovered__c, Tract__r.targetPrice__c, Tract__r.maxPrice__c, Tract__r.targetPPA__c, Tract__r.maxPPA__c,
				Tract__r.netAcreageUnits__c, Name, Id, unitPrice__c, totalPrice__c, askUnitPrice__c, askTotalPrice__c
        FROM Opportunity_Tract__c WHERE Opportunity__c =: oppId
        ORDER BY Opportunity__r.Type,Opportunity__r.PSA_Date__c DESC
        ];
        return ots;
    }

	@AuraEnabled
	public static string updatePricing(Object data){
		List<Opportunity_Tract__c> updateOTs = (List<Opportunity_Tract__c>) JSON.deserialize(JSON.serialize(data), List<Opportunity_Tract__c>.class);
		try{
			update updateOTs;
			return 'Success: Pricing updated successfully';
		}
		catch (Exception e){
			return 'The following exception has occurred: ' + e.getMessage();
		}
	}

	//@AuraEnabled(Cacheable=true)
    //public static List<Opportunity_Tract__c> getTracts(Id oppId) {
	//	return getTracts(oppId, 'Opportunity');
    //}

	
    public OppExtension(ApexPages.StandardController oppController)
    {
        Id oppId = oppController.getRecord().Id;
        String oppType = getOppType(oppId);
		String sObjectName = oppController.getRecord().getSObjectType().getDescribe().getName();
        oppTractList = getTracts(oppId, sObjectName);
        isAcquisition = (oppType == 'Acquisition');
        isDivestiture = (oppType == 'Divestiture');
    }

}