src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Data Prep</fullName>
                </value>
                <value>
                    <fullName>Ready for Eval</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>completionDate__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>srpInvestmentTeamReviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SRP Investment Team Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EvaluationsReviewer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>startDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>Eval-{000000}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EvaluationListController.cls
public class EvaluationListController {
	
    @AuraEnabled
    public static EvaluationWrapper getEvaluationRecords(Id recordId){
        
        List<Evaluation__c> evalList = new List<Evaluation__c>();
        String sObjName = recordId.getSObjectType().getDescribe().getName(); 
		if(sObjName=='Opportunity'){
            evalList = [Select Id,Name,Status__c,opportunity__c, Owner.Name , Owner.Id , srpInvestmentTeamReviewer__r.Name, srpInvestmentTeamReviewer__c, startDate__c, completionDate__c  from Evaluation__c where opportunity__c=:recordId];
        }
        EvaluationWrapper wrap = new EvaluationWrapper();
        wrap.evalList = evalList;
        wrap.sObjectType = sObjName;
        return wrap;
    }
    
    public class EvaluationWrapper{
        @AuraEnabled
        public List<Evaluation__c> evalList{get;set;}
        @AuraEnabled
        public string sObjectType{get;set;}
    }
}