src/objects/GIS_Update_Request__c.object
<CustomObject>
    <description>use to track mapping update request from the GIS team</description>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>GIS Update Requests</relationshipLabel>
        <relationshipName>GIS_Update_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>GIS Update Request</label>
    <nameField>
        <displayFormat>GIS-{000000000}</displayFormat>
        <label>GIS Update Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GIS Update Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/mapControllerV2Test.cls
@isTest
public class mapControllerV2Test {

	@TestSetup
	static void setupTestData(){
		TestDataFactory.dataSetup();
	}

    static testMethod void testmapControllerV2() {
        //TestDataFactory.dataSetup();

		List<Tract__c> tracts = [SELECT ID FROM Tract__c LIMIT 3];
		//List<Opportunity> opps = [SELECT ID FROM Opportunity LIMIT 1];
		//List<Subtract__c> subtracts = [SELECT ID FROM Subtract__c LIMIT 1];
		//List<Well__c> wells = [SELECT ID FROM Well__c LIMIT 1];
		//List<Account> accounts = [SELECT ID FROM Account LIMIT 1];
		//List<GIS_Update_Request__c> gisUpdateRequests = [SELECT ID FROM GIS_Update_Request__c LIMIT 1];
		//List<Unit__c> units = [SELECT ID FROM Unit__c LIMIT 1];

        Test.startTest();
        Test.setMock(HttpCalloutMock.class,new ArcgisMock());
        mapControllerV2.getMaps(tracts[0].Id,'Tract__c');
        // Call again immediately to test caching of token
        mapControllerV2.getMaps(tracts[1].Id,'Tract__c');
        mapControllerV2.getMaps(tracts[2].Id,'Tract__c');
        //mapControllerV2.getMaps(opps[0].Id,'Opportunity');
		//mapControllerV2.getMaps(subtracts[0].Id, 'Subtract__c');
		//mapControllerV2.getMaps(wells[0].Id, 'Well__c');
		//mapControllerV2.getMaps(accounts[0].Id, 'Account');
		//mapControllerV2.getMaps(gisUpdateRequests[0].Id, 'GIS_Update_Request__c');
		//mapControllerV2.getMaps(units[0].Id, 'Unit__c');
        //mapControllerV2.getMaps(cases[2].Id,'Case');

        //Test.setMock(HttpCalloutMock.class,new ArcgisWellMock());
        //mapControllerV2.getWellPermitInfo(tracts[0].Id,'Tract__c','Tract');

        Test.stopTest();

    }

	static testMethod void testmapControllerV22() {
        //TestDataFactory.dataSetup();

		//List<Tract__c> tracts = [SELECT ID FROM Tract__c LIMIT 3];
		//List<Opportunity> opps = [SELECT ID FROM Opportunity LIMIT 1];
		//List<Subtract__c> subtracts = [SELECT ID FROM Subtract__c LIMIT 1];
		List<Well__c> wells = [SELECT ID FROM Well__c LIMIT 1];
		List<Account> accounts = [SELECT ID FROM Account LIMIT 1];
		//List<GIS_Update_Request__c> gisUpdateRequests = [SELECT ID FROM GIS_Update_Request__c LIMIT 1];
		//List<Unit__c> units = [SELECT ID FROM Unit__c LIMIT 1];

        Test.startTest();
        Test.setMock(HttpCalloutMock.class,new ArcgisMock());
        //mapControllerV2.getMaps(tracts[0].Id,'Tract__c');
        // Call again immediately to test caching of token
        //mapControllerV2.getMaps(tracts[1].Id,'Tract__c');
        //mapControllerV2.getMaps(tracts[2].Id,'Tract__c');
        //mapControllerV2.getMaps(opps[0].Id,'Opportunity');
		//mapControllerV2.getMaps(subtracts[0].Id, 'Subtract__c');
		mapControllerV2.getMaps(wells[0].Id, 'Well__c');
		mapControllerV2.getMaps(accounts[0].Id, 'Account');
		//mapControllerV2.getMaps(gisUpdateRequests[0].Id, 'GIS_Update_Request__c');
		//mapControllerV2.getMaps(units[0].Id, 'Unit__c');
        //mapControllerV2.getMaps(cases[2].Id,'Case');

        //Test.setMock(HttpCalloutMock.class,new ArcgisWellMock());
        //mapControllerV2.getWellPermitInfo(tracts[0].Id,'Tract__c','Tract');

        Test.stopTest();

    }

		static testMethod void testmapControllerV23() {
        //TestDataFactory.dataSetup();

		//List<Tract__c> tracts = [SELECT ID FROM Tract__c LIMIT 3];
		//List<Opportunity> opps = [SELECT ID FROM Opportunity LIMIT 1];
		//List<Subtract__c> subtracts = [SELECT ID FROM Subtract__c LIMIT 1];
		//List<Well__c> wells = [SELECT ID FROM Well__c LIMIT 1];
		//List<Account> accounts = [SELECT ID FROM Account LIMIT 1];
		List<GIS_Update_Request__c> gisUpdateRequests = [SELECT ID FROM GIS_Update_Request__c LIMIT 1];
		List<Unit__c> units = [SELECT ID FROM Unit__c LIMIT 1];

        Test.startTest();
        Test.setMock(HttpCalloutMock.class,new ArcgisMock());
        //mapControllerV2.getMaps(tracts[0].Id,'Tract__c');
        // Call again immediately to test caching of token
        //mapControllerV2.getMaps(tracts[1].Id,'Tract__c');
        //mapControllerV2.getMaps(tracts[2].Id,'Tract__c');
        //mapControllerV2.getMaps(opps[0].Id,'Opportunity');
		//mapControllerV2.getMaps(subtracts[0].Id, 'Subtract__c');
		//mapControllerV2.getMaps(wells[0].Id, 'Well__c');
		//mapControllerV2.getMaps(accounts[0].Id, 'Account');
		mapControllerV2.getMaps(gisUpdateRequests[0].Id, 'GIS_Update_Request__c');
		mapControllerV2.getMaps(units[0].Id, 'Unit__c');
        //mapControllerV2.getMaps(cases[2].Id,'Case');

       // Test.setMock(HttpCalloutMock.class,new ArcgisWellMock());
        //mapControllerV2.getWellPermitInfo(tracts[0].Id,'Tract__c','Tract');

        Test.stopTest();

    }

		static testMethod void testmapControllerV24() {
        //TestDataFactory.dataSetup();

		//List<Tract__c> tracts = [SELECT ID FROM Tract__c LIMIT 3];
		List<Opportunity> opps = [SELECT ID FROM Opportunity LIMIT 1];
		List<Subtract__c> subtracts = [SELECT ID FROM Subtract__c LIMIT 1];
		//List<Well__c> wells = [SELECT ID FROM Well__c LIMIT 1];
		//List<Account> accounts = [SELECT ID FROM Account LIMIT 1];
		//List<GIS_Update_Request__c> gisUpdateRequests = [SELECT ID FROM GIS_Update_Request__c LIMIT 1];
		//List<Unit__c> units = [SELECT ID FROM Unit__c LIMIT 1];

        Test.startTest();
        Test.setMock(HttpCalloutMock.class,new ArcgisMock());
        //mapControllerV2.getMaps(tracts[0].Id,'Tract__c');
        // Call again immediately to test caching of token
        //mapControllerV2.getMaps(tracts[1].Id,'Tract__c');
        //mapControllerV2.getMaps(tracts[2].Id,'Tract__c');
        mapControllerV2.getMaps(opps[0].Id,'Opportunity');
		mapControllerV2.getMaps(subtracts[0].Id, 'Subtract__c');
		//mapControllerV2.getMaps(wells[0].Id, 'Well__c');
		//mapControllerV2.getMaps(accounts[0].Id, 'Account');
		//mapControllerV2.getMaps(gisUpdateRequests[0].Id, 'GIS_Update_Request__c');
		//mapControllerV2.getMaps(units[0].Id, 'Unit__c');
        //mapControllerV2.getMaps(cases[2].Id,'Case');

        //Test.setMock(HttpCalloutMock.class,new ArcgisWellMock());
        //mapControllerV2.getWellPermitInfo(tracts[0].Id,'Tract__c','Tract');

        Test.stopTest();

    }


}