src/objects/GIS_Update_Request__c.object
<CustomObject>
    <description>use to track mapping update request from the GIS team</description>
    <fields>
        <fullName>Completed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Completed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GIS_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <label>Completion Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shape_UpdatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shape Updated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GIS_Update_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shape_Updated_Date__c</fullName>
        <label>Shape Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>GIS Update Requests</relationshipLabel>
        <relationshipName>GIS_Update_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>GIS Update Request</label>
    <nameField>
        <displayFormat>GIS-{000000000}</displayFormat>
        <label>GIS Update Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GIS Update Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GISUpdateRequestController.cls
public without sharing class GISUpdateRequestController {
    
    @AuraEnabled
    public static void markAsComplete(Id recordId){

        GIS_Update_Request__c gisRec = [Select name from GIS_Update_Request__c where Id =: recordId];
        gisRec.Completion_Date__c = system.now();
        gisRec.Completed_By__c  = UserInfo.getUserId();
        update gisRec;

        FeedItem post = new FeedItem();
        post.ParentId = recordId;
        post.Body = 'User has completed GIS Update Request: '+gisRec.name;
        insert post;
    }
    
    @AuraEnabled
    public static void shapeUpdated(Id recordId){

        GIS_Update_Request__c gisRec = [Select name from GIS_Update_Request__c where Id =: recordId];  //new GIS_Update_Request__c(Id=recordId);
        gisRec.Shape_Updated_Date__c = system.now();
        gisRec.Shape_UpdatedBy__c = UserInfo.getUserId();
        update gisRec;

		FeedItem post = new FeedItem();
        post.ParentId = recordId;
        post.Body = 'User has updated shape for GIS Update Request: '+gisRec.name;
        insert post;

    }
    
    @AuraEnabled
    public static List<GIS_Update_Request__c> getRelatedGISUpdateRequest(Id unitId){

        List<GIS_Update_Request__c>  gisList = [Select Id, Name, Completed_By__c,Completed_By__r.Name,Completion_Date__c, Createdby.Name,CreatedDate from GIS_Update_Request__c where Unit__c=:unitId];
        return gisList;
    }
}