src/objects/Instrument__c.object
<CustomObject>
    <label>Instrument</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Instrument Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instruments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Instrument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instrument</label>
        <referenceTo>Instrument__c</referenceTo>
        <relationshipLabel>Subtracts</relationshipLabel>
        <relationshipName>Instrument_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InstrumentTriggerHelper.cls
public with sharing class InstrumentTriggerHelper {

    public static boolean preventDelete(Map<Id,Instrument__c> oldMap) {
        boolean result = false;
		List<Subtract__c> sts  = [SELECT Id,Instrument__c FROM Subtract__c WHERE Instrument__c IN: oldMap.keySet()];
        Map<Id,Boolean> hasSubtract = new Map<Id,Boolean>();
        for (Subtract__c st : sts) {
            if (!hasSubtract.containsKey(st.Instrument__c))
            {
                hasSubtract.put(st.Instrument__c,true);
                oldMap.get(st.Instrument__c).addError('Cannot delete an instrument with Subtracts');
				result = true;
            }
        }
		return result;
    }

}