src/objects/Instrument__c.object
<CustomObject>
    <fields>
        <fullName>Lessee__c</fullName>
        <externalId>true</externalId>
        <label>Lessee</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lessor__c</fullName>
        <externalId>true</externalId>
        <label>Lessor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instrument</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Instrument Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instruments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LandGridTract__c.object
<CustomObject>
    <fields>
        <fullName>Abstract__c</fullName>
        <label>Abstract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Block__c</fullName>
        <label>Block</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <externalId>true</externalId>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <externalId>true</externalId>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Notes__c</fullName>
        <inlineHelpText>Brief comments and title notes. Full comments should be entered into Tracts.Co</inlineHelpText>
        <label>Title Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Title_Status__c</fullName>
        <label>Title Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Imaging In Progress</fullName>
                </value>
                <value>
                    <fullName>Imaging Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready For Review</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Complete - Acquisition</fullName>
                </value>
                <value>
                    <fullName>Complete - Limited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Township__c</fullName>
        <label>Township</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LandGridTract</label>
    <nameField>
        <label>LandGridTract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LandGridTracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Grid_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this option if the legal description cannot correctly be mapped based on quarter calls and/or lots</inlineHelpText>
        <label>Grid Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Instrument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instrument</label>
        <referenceTo>Instrument__c</referenceTo>
        <relationshipLabel>Subtracts</relationshipLabel>
        <relationshipName>Instrument_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lessee__c</fullName>
        <formula>Instrument__r.Lessee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lessee</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lessor__c</fullName>
        <formula>Instrument__r.Lessor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lessor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lot__c</fullName>
        <label>Lot</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subtract_Acres__c</fullName>
        <label>Subtract Acres</label>
        <precision>18</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subtract_Full_Legal_Description__c</fullName>
        <label>Subtract Full Legal Description</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subtract_Gross_Acres__c</fullName>
        <label>Subtract Gross Acres</label>
        <precision>18</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subtract_Quarter_Call__c</fullName>
        <label>Subtract Quarter Call</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Abstract__c</fullName>
        <label>Abstract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ford_Tract_Status__c</fullName>
        <description>legacy statuses from project ford, should be removed and migrated to a standard status</description>
        <inlineHelpText>ONLY use for project Ford assets, this field needs to be removed</inlineHelpText>
        <label>Ford Tract Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>101 - Contact Info Not Yet Found</fullName>
                </value>
                <value>
                    <fullName>103 - Outreach</fullName>
                </value>
                <value>
                    <fullName>107 - Pending Investigation</fullName>
                </value>
                <value>
                    <fullName>109 - Premium Investigation</fullName>
                </value>
                <value>
                    <fullName>201 - Continued Discussions</fullName>
                </value>
                <value>
                    <fullName>301 - Rejected - Price</fullName>
                </value>
                <value>
                    <fullName>302 - Rejected - Not Interested</fullName>
                </value>
                <value>
                    <fullName>401 - Offer Outstanding</fullName>
                </value>
                <value>
                    <fullName>404 - Offer Outstanding - Offer Letter Sent</fullName>
                </value>
                <value>
                    <fullName>405 - Offer Outstanding - PSA Sent</fullName>
                </value>
                <value>
                    <fullName>410 - Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>411 - Offer Accepted - Verbal</fullName>
                </value>
                <value>
                    <fullName>420 - Offer Expired</fullName>
                </value>
                <value>
                    <fullName>450 - Offer Accepted - Pending Title</fullName>
                </value>
                <value>
                    <fullName>501 - Offer Declined</fullName>
                </value>
                <value>
                    <fullName>601 - Invoiced - Pending</fullName>
                </value>
                <value>
                    <fullName>602 - Invoiced - Consummated</fullName>
                </value>
                <value>
                    <fullName>701 - Wrong Owner</fullName>
                </value>
                <value>
                    <fullName>801 - EMC Rejected</fullName>
                </value>
                <value>
                    <fullName>901 - Title Fail - Rejected</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>1001 - Dropped Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Legal_Name__c</fullName>
        <formula>LandGridTract__r.Name  &amp; &apos; &apos; &amp; Quarter_Call__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grid_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has a quarter call that can not be automapped</description>
        <inlineHelpText>Has a quarter call that can not be automapped</inlineHelpText>
        <label>Grid Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gross_Acres__c</fullName>
        <label>Gross Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Instrument_Type__c</fullName>
        <label>Instrument Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OGL</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ORRI</fullName>
                </value>
                <value>
                    <fullName>Surface</fullName>
                </value>
                <value>
                    <fullName>Commission</fullName>
                </value>
                <value>
                    <fullName>NPRI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LandGridTract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LandGridTract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Tracts (LandGridTract)</relationshipLabel>
        <relationshipName>Tracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link_to_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link to Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tracts (Opportunity)</relationshipLabel>
        <relationshipName>Tracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lots__c</fullName>
        <description>Lot detail</description>
        <inlineHelpText>Lot detail</inlineHelpText>
        <label>Lots</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quarter_Call__c</fullName>
        <inlineHelpText>Quarter Call</inlineHelpText>
        <label>Quarter Call</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>netAcres__c</fullName>
        <label>Net Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewTractWizardExtension.cls
public with sharing class NewTractWizardExtension {

    public LandGridTract__c selLandGridTract {get; set;}
    public String selLandGridTractId {get; set;}
    public Tract__c newTract {get; set;}
    public Boolean showNext {get; set;}

    public Boolean showInstrument {get; set;}
    public Boolean showExisting {get; set;}
    public Boolean showNewInstrument {get; set;}

    public Instrument__c newInstrument {get; set;}
    public Subtract__c newSubtract {get; set;}

    public NewTractWizardExtension(ApexPages.StandardController tractController)
    {
        newSubtract = new Subtract__c();
        showNext = false;
        newTract = new Tract__c(Ford_Tract_Status__c = '107 - Pending Investigation');
        newInstrument = new Instrument__c();
        selLandGridTract = new LandGridTract__c();
        showInstrument = false;
        showExisting = false;
        showNewInstrument = false;
    }

    public PageReference saveNew() {
        return saveTract(Page.NewTractWizard);
    }

    public PageReference save() {
        return saveTract(null);
    }

	//Instrument functionality removed per Quin Cogdell (jdg 02-13-2020)
/*    public PageReference useExisting() {
        showExisting = true;
        showNewInstrument = false;
        return null;
    }

    public PageReference useNewInstrument() {
        showExisting = false;
        showNewInstrument = true;
        return null;
    }
*/

    private PageReference saveTract(PageReference nextPage) {

        Boolean isValid = true;

        if (newTract.LandGridTract__c == null)
        {
            ApexPages.Message newMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'LandGridTract is required.');
            ApexPages.addMessage(newMsg);
            isValid = false;
        }
        if (newTract.Instrument_Type__c == null)
        {
            newTract.Instrument_Type__c.addError('Instrument Type is Required.');
            isValid = false;
        }
        /*if (showInstrument && showNewInstrument) {
            // if the user is creating a new instrument Lessor and Lessee must be filled in at a minimum
            if (newInstrument.Lessee__c == null) {
                newInstrument.Lessee__c.addError('Lessee is required for a new instrument.');
                isValid = false;
            }
            if (newInstrument.Lessor__c == null) {
                newInstrument.Lessor__c.addError('Lessor is required for a new instrument.');
                isValid = false;
            }
        }*/
		System.debug(newTract.Ford_Tract_Status__c);
        if (newTract.Ford_Tract_Status__c == null) {
            newTract.Ford_Tract_Status__c.addError('Ford Tract Status is required.');
            isValid = false;
        }

        if (isValid) {
			try{
				insert newTract;
			}
			catch(DmlException ex){
				System.debug('ex value is: ' + ex.getCause());
				//System.debug(ex.
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage().replace('&quot;', '"')));
				return null;
			}
            

            /*newSubtract.Subtract_Quarter_Call__c = newTract.Quarter_Call__c;
            newSubtract.Subtract_Gross_Acres__c = newTract.Gross_Acres__c;
            newSubtract.Subtract_Acres__c = newTract.netAcres__c;
            newSubtract.Subtract_Full_Legal_Description__c = newTract.Full_Legal_Name__c;
            newSubtract.Lot__c = newTract.Lots__c;
            newSubtract.Grid_Exception__c = newTract.Grid_Exception__c;
            newSubtract.Tract__c = newTract.Id;

            // If a new instrument is created, insert it and link it to the subtract
            if (showInstrument && showNewInstrument) {
                insert newInstrument;
                newSubtract.Instrument__c = newInstrument.Id;
            }
			List<Subtract__c> subTracts = [SELECT Id FROM Subtract__c WHERE Tract__c =:newTract.Id];
            if(subTracts.size()<1){
            	insert newSubtract;
            }*/

            PageReference tractPage = nextPage;
            if (tractPage == null) {
                tractPage = new PageReference('/'+newTract.Id);
            }

            tractPage.setRedirect(true);
            return tractPage;
            //return null;
        }
        else {
            return null;
        }
    }

    public void setId() {
		
        selLandGridTractId = ApexPages.currentPage().getParameters().get('selectedValue');
		if(String.isNotEmpty(selLandGridTractId)){
			newTract.LandGridTract__c = selLandGridTractId;
			selLandGridTract = [SELECT Id,Name,State__c,County__c,
					Abstract__c,Block__c,Section__c,Title_Notes__c,
					Township__c,Title_Status__c,RecordType.Name
				FROM LandGridTract__c WHERE Id =: selLandGridTractId];
			showNext=true;
		}
		else{
			newTract.LandGridTract__c = null;
			showNext=true;
		}
		
    }
    public void setOppId() {
        newTract.Link_to_Opportunity__c= ApexPages.currentPage().getParameters().get('selectedOppValue');
    }

/*    public void updateInstrument() {
        showInstrument = (newTract.Instrument_Type__c != 'Surface');
        System.debug('Instrument Type: ' + newTract.Instrument_Type__c);
        if (showInstrument) {
            showExisting = true;
            showNewInstrument = false;
        } else {
            showExisting = false;
            showNewInstrument = false;
        }

    }
*/
}