src/objects/Instrument__c.object
<CustomObject>
    <label>Instrument</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Instrument Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instruments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Monthly_Production__c.object
<CustomObject>
    <fields>
        <fullName>Current_Operator_Name__c</fullName>
        <label>Current Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Operator (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gas__c</fullName>
        <description>Value comes from GIS (source is IHS or DI)</description>
        <inlineHelpText>Value comes from GIS (source is IHS or DI)</inlineHelpText>
        <label>Monthly Production (Gas)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Liquid__c</fullName>
        <description>Value comes from GIS (source is IHS or DI)</description>
        <inlineHelpText>Value comes from GIS (source is IHS or DI)</inlineHelpText>
        <label>Monthly Production (Oil)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Well__c</fullName>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000000}</displayFormat>
        <label>Monthly Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Instrument_Lease_Royalty__c</fullName>
        <description>Royalty from Instrument Object</description>
        <formula>Instrument__r.Lease_Royalty__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Royalty from Instrument Object</inlineHelpText>
        <label>Instrument Lease Royalty</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Instrument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instrument</label>
        <referenceTo>Instrument__c</referenceTo>
        <relationshipLabel>Subtracts</relationshipLabel>
        <relationshipName>Instrument_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtract_Acres__c</fullName>
        <label>Subtract Acres</label>
        <precision>18</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subtract_Gross_Acres__c</fullName>
        <label>Subtract Gross Acres</label>
        <precision>18</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subtract_NRI__c</fullName>
        <description>If Subtract NRI Actual is blank, use Estimate Calculation: Mineral Interest *  Instrument Lease Royalty</description>
        <formula>Mineral_Interest__c *  Instrument_Lease_Royalty__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If Subtract NRI Actual is blank, use Estimate Calculation: Mineral Interest *  Instrument Lease Royalty</inlineHelpText>
        <label>Subtract NRI</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subtract_Quarter_Call__c</fullName>
        <label>Subtract Quarter Call</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator_Name__c</fullName>
        <label>Operator Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>Current_Operator_Name__c</fullName>
        <label>Current Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Operator (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Depth__c</fullName>
        <label>Total Depth</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WellInterestAllocationListController.cls
public class WellInterestAllocationListController {
    
    @AuraEnabled
    public static list<Well__c> getAllWellUnits(string acId){
        list<Well__c> AllUnitWells =  new list<Well__c>(); 
        AllUnitWells = [select id, name,Unit__c, Type__c, Total_Depth__c,Current_Operator_Name__c, Current_Operator__c,Current_Operator__r.Name from Well__c where Unit__c =: acId and Unit__c!=null limit 50000];
        return AllUnitWells;
    }
   
    @AuraEnabled
    public static list<Tract__c> getAllAccountsTracts(string accID){
        list<Tract__c> AllWellTracts =  new list<Tract__c>(); 
        system.debug('--------accID--------'+accID); 
        AllWellTracts = [select id, name,Operator_Name__c from Tract__c where Account__c =: accID and Account__c!=null and Account__r.Type='Portfolio Investment' limit 50000];
        return AllWellTracts;
    }
    @AuraEnabled
    public Static list<Monthly_Production__c>getAllMonthlyProduction(string oId){
        list<Monthly_Production__c> monthlProductionlist= new list<Monthly_Production__c>();
        monthlProductionlist=[Select Name,Production_Date__c,Gas__c,Liquid__c from Monthly_Production__c where Well__c=:oId];
        return monthlProductionlist;
    }
    
    
    @AuraEnabled
    public Static list<Subtract__c> getSubtracts(Id tractId){
        list<Subtract__c> subtractList= new list<Subtract__c>();
        String sObjName = tractId.getSObjectType().getDescribe().getName();
        if(sObjName=='Tract__c'){
            subtractList=[Select Id,Name, Subtract_Quarter_Call__c,Subtract_Acres__c,Subtract_Gross_Acres__c,Subtract_NRI__c, Instrument__c, Instrument__r.Name, Instrument_Lease_Royalty__c From Subtract__c Where Tract__c=:tractId Limit 5000];
        }
        if(subtractList.size()>0)
            return subtractList;
        return subtractList;
    }
    
}