src/objects/Instrument__c.object
<CustomObject>
    <fields>
        <fullName>extensionTermMeasure__c</fullName>
        <label>Extension Term Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Year</fullName>
                    <default>true</default>
                    <label>Year</label>
                </value>
                <value>
                    <fullName>Month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>termMeasure__c</fullName>
        <description>Term length measure (Year or Month)</description>
        <label>Term Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Year</fullName>
                    <default>true</default>
                    <label>Year</label>
                </value>
                <value>
                    <fullName>Month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Instrument</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Instrument Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instruments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LandGridTract__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <externalId>true</externalId>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LandGridTract</label>
    <nameField>
        <label>LandGridTract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LandGridTracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Instrument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instrument</label>
        <referenceTo>Instrument__c</referenceTo>
        <relationshipLabel>Subtracts</relationshipLabel>
        <relationshipName>Instrument_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LandGridTract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LandGridTract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Tracts (LandGridTract)</relationshipLabel>
        <relationshipName>Tracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/InstrumentTriggerHelperTest.cls
@isTest
public with sharing class InstrumentTriggerHelperTest {


    static testMethod void testTrigger() {
        // test the trigger and helper method

        Account a1 = new Account();
        a1.Name = 'Seller';
        insert a1;

        Account a2 = new Account();
        a2.Name = 'Buyer';
        insert a2;

        List<LandGridTract__c> lts = new List<LandGridTract__c>();
        LandGridTract__c lt1 = new LandGridTract__c();
        lt1.Name='Bexar 1-579e38 TX';
        lt1.County__c ='Bexar';
        lts.add(lt1);

        LandGridTract__c lt2 = new LandGridTract__c();
        lt2.Name='Bexar 1-179347 TX';
        lt2.County__c ='Bexar';
        lts.add(lt2);
        insert lts;

        Tract__c t1 = new Tract__c();
        t1.LandGridTract__c = lt1.Id;
		t1.Account__c = a1.Id;
        insert t1;

        Tract__c t2 = new Tract__c();
        t2.LandGridTract__c = lt2.Id;
		t2.Account__c = a2.Id;
        insert t2;

        Instrument__c inst1 = new Instrument__c(termMeasure__c=null, extensionTermMeasure__c = null);
        Instrument__c inst2 = new Instrument__c(termMeasure__c=null, extensionTermMeasure__c = null);
        insert inst1;
        insert inst2;

        Subtract__c st1 = new Subtract__c();
        Subtract__c st2 = new Subtract__c();
        st1.Tract__c = t1.Id;
        st1.Instrument__c = inst1.Id;
        insert st1;

        Test.startTest();
        delete inst2;
        try {
            delete inst1;
        }
        catch (Exception e)
        {
            System.assert(e != null);
        }

        Test.stopTest();


    }
}