src/objects/InventoryAsset__c.object
<CustomObject>
    <fields>
        <fullName>assetAcquisitionOverride__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>select any OT to calculate inventory related statistics</description>
        <label>Asset Acquisition Override</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Acquisition Overrides</relationshipLabel>
        <relationshipName>AssetAcquisitionOverrides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assetAcquisition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Acquisition</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Asset Acquisitions</relationshipLabel>
        <relationshipName>AssetAcquisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assetSaleOverride__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Sale Override</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Asset Sale Overrides</relationshipLabel>
        <relationshipName>AssetSaleOverrides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assetSale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Sale</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Asset Sales</relationshipLabel>
        <relationshipName>AssetSales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Asset</label>
    <nameField>
        <displayFormat>IA-{0000000000}</displayFormat>
        <label>Inventory Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>totalPrice__c</fullName>
        <formula>unitPrice__c *  Tract_Acres__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IAInformationAura.cls
public with sharing class IAInformationAura  {
	
	@AuraEnabled
    public static InventoryAsset__c getInventoryAsset(Id recordId) {
		InventoryAsset__c response = [SELECT Id, Name, assetAcquisition__c, assetAcquisitionOverride__c, assetSale__c, assetSaleOverride__c, 
										assetAcquisition__r.Opportunity__r.Acquiring_Entity__c,
										assetAcquisition__r.Opportunity__r.Acquiring_Entity__r.Name,
										assetAcquisition__r.Opportunity__r.Effective_Date__c,
										assetAcquisition__r.Opportunity__r.CloseDate,
										assetAcquisition__r.totalPrice__c,
										assetAcquisition__r.Opportunity__c,
										assetAcquisition__r.Opportunity__r.Name,
										assetAcquisition__r.Opportunity__r.AccountId,
										assetAcquisition__r.Opportunity__r.Account.Name,
										assetAcquisitionOverride__r.Opportunity__r.Effective_Date__c,
										assetAcquisitionOverride__r.Opportunity__r.CloseDate,
										assetAcquisitionOverride__r.totalPrice__c,
										assetAcquisitionOverride__r.Opportunity__c,
										assetAcquisitionOverride__r.Opportunity__r.Name,
										assetAcquisitionOverride__r.Opportunity__r.AccountId,
										assetAcquisitionOverride__r.Opportunity__r.Account.Name,
										assetSale__r.Opportunity__r.Effective_Date__c,
										assetSale__r.Opportunity__r.CloseDate,
										assetSale__r.totalPrice__c,
										assetSale__r.Opportunity__c,
										assetSale__r.Opportunity__r.Name,
										assetSale__r.Opportunity__r.Acquiring_Entity__c,
										assetSale__r.Opportunity__r.Acquiring_Entity__r.Name,
										assetSaleOverride__r.Opportunity__r.Effective_Date__c,
										assetSaleOverride__r.Opportunity__r.CloseDate,
										assetSaleOverride__r.totalPrice__c,
										assetSaleOverride__r.Opportunity__c,
										assetSaleOverride__r.Opportunity__r.Name,
										assetSaleOverride__r.Opportunity__r.Acquiring_Entity__c,
										assetSaleOverride__r.Opportunity__r.Acquiring_Entity__r.Name
									   FROM InventoryAsset__c 
									   WHERE Id = :recordId
									   LIMIT 1];
        return response;
    }


}