src/objects/InventoryAsset__c.object
<CustomObject>
    <fields>
        <fullName>assetAcquisitionOverride__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>select any OT to calculate inventory related statistics</description>
        <label>Asset Acquisition Override</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Acquisition Overrides</relationshipLabel>
        <relationshipName>AssetAcquisitionOverrides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assetAcquisition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Acquisition</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Asset Acquisitions</relationshipLabel>
        <relationshipName>AssetAcquisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assetSaleOverride__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Sale Override</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Asset Sale Overrides</relationshipLabel>
        <relationshipName>AssetSaleOverrides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assetSale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Sale</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Asset Sales</relationshipLabel>
        <relationshipName>AssetSales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Asset</label>
    <nameField>
        <displayFormat>IA-{0000000000}</displayFormat>
        <label>Inventory Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Acquiring_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Acquiring Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Acquiring Entity)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FMV_Per_Acre__c</fullName>
        <description>Sum of all FMV divided by Total Acres for related tracts</description>
        <formula>if (Total_Acreage__c = 0,0, Total_FMV__c /  Total_Acreage__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Sum of all FMV divided by Total Acres for related tracts</inlineHelpText>
        <label>FMV Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gain_on_Asset__c</fullName>
        <description>Gain on sale (Total FMV - Total Cost)</description>
        <formula>Total_FMV__c - Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gain on sale (Total FMV - Total Cost)</inlineHelpText>
        <label>Gain on Asset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <formula>if(Total_Cost__c = 0, 0, Total_Cost__c /  Total_Acreage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Sum of all &quot;Total Cost&quot; fields</description>
        <label>Total Cost</label>
        <summarizedField>Opportunity_Tract__c.Total_Cost__c</summarizedField>
        <summaryForeignKey>Opportunity_Tract__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Acquisition</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <label>Acquisition</label>
    </recordTypes>
    <recordTypes>
        <fullName>Divestiture</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <label>Divestiture</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>FMV_Per_Acre__c</fullName>
        <label>FMV Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gain_on_Asset__c</fullName>
        <label>Gain on Asset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes from tract record</description>
        <label>Notes</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <description>OTG = &quot;Off the Ground&quot; - how much was paid to the previous owner (does not include commissions, title costs etc.)</description>
        <inlineHelpText>OTG = &quot;Off the Ground&quot; - how much waspaid to the previous owner (does not include commissions, title costs etc.)</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTG_Cost__c</fullName>
        <description>Cost per acre copied from tract for roll up calculations</description>
        <label>OTG Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Copied from Tract used for roll up calculations</description>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tract_Acres__c</fullName>
        <label>Tract Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>unitPrice__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Acquisition_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Acquisition Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <errorMessage>Opportunity must be closed won acquisition</errorMessage>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>equals</operation>
                <value>Closed Won</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Acquisition</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Commission Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Divestiture_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Divestiture Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <errorMessage>Opportunity must be closed won divestiture</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Divestiture</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>equals</operation>
                <value>Closed Won</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tracts (Divestiture Opportunity)</relationshipLabel>
        <relationshipName>Tracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gain_on_Asset__c</fullName>
        <formula>Fair_Market_Value__c -  Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>FMV - Total Cost</inlineHelpText>
        <label>Gain on Asset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <inlineHelpText>OTG Cost per Acre</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTG_Cost__c</fullName>
        <formula>netAcres__c * OTG_Cost_Per_Acre__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OTG Price per acre x Net Acres</inlineHelpText>
        <label>OTG Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Capitalized_Costs__c</fullName>
        <label>Other Capitalized Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Title_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Title Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <formula>if (netAcres__c == 0,0,Total_Cost__c /  netAcres__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Costs divided by Net Acres</inlineHelpText>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>OTG Costs plus Commissions and title</description>
        <formula>(netAcres__c *  OTG_Cost_Per_Acre__c) +  Commission_Amount__c +  Title_Cost__c +  Other_Capitalized_Costs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OTG Costs plus Commissions and title</inlineHelpText>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_Per_Acre__c</fullName>
        <inlineHelpText>FMV for the tract</inlineHelpText>
        <label>FMV Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>netAcres__c</fullName>
        <label>Net Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityTractTriggerHelper.cls
public class OpportunityTractTriggerHelper{

    public static void updateRelatedTractRecords(List<Opportunity_Tract__c> newRecords){

        Map<Id,Tract__c> tractMap = new Map<Id,Tract__c>();
        Tract__c tractRec;
        for(Opportunity_Tract__c oppTractRec: [Select Id, Opportunity__c,Tract__c,Opportunity__r.StageName,
                                              Opportunity__r.Type,Opportunity__r.Effective_Date__c,Opportunity__r.Account.Type,
                                              Opportunity__r.Acquiring_Entity__r.Type, Tract__r.Acquisition_Opportunity__c, Tract__r.Divestiture_Opportunity__c
                                               From Opportunity_Tract__c Where Id In: newRecords]){

            tractRec = new Tract__c();
            if(oppTractRec.Opportunity__r.Type == 'Acquisition' &&
                    oppTractRec.Opportunity__r.Effective_Date__c != null && 
                    (oppTractRec.Opportunity__r.StageName== 'Closed Won')){
						if(oppTractRec.Tract__r.Acquisition_Opportunity__c != oppTractRec.Opportunity__c){
							oppTractRec.Tract__r.Acquisition_Opportunity__c = oppTractRec.Opportunity__c;
							tractMap.put(oppTractRec.Tract__c,oppTractRec.Tract__r);
						}
			}
            else if(oppTractRec.Opportunity__r.Type == 'Divestiture' &&
                    oppTractRec.Opportunity__r.Effective_Date__c != null && 
                    (oppTractRec.Opportunity__r.StageName== 'Closed Won')){
						if(oppTractRec.Tract__r.Divestiture_Opportunity__c != oppTractRec.Opportunity__c){
							oppTractRec.Tract__r.Divestiture_Opportunity__c = oppTractRec.Opportunity__c;
							tractMap.put(oppTractRec.Tract__c,oppTractRec.Tract__r);
						}
                }
        }
        if(!tractMap.values().isEmpty()){
            update tractMap.values();
        }
    }

	public static void recalcInventoryAssets(List<Opportunity_Tract__ChangeEvent> newList, Map<Id, Opportunity_Tract__ChangeEvent> newMap){
		List<String> priceChange = new List<String>();
		for (Opportunity_Tract__ChangeEvent oTCE: newList) {
			EventBus.ChangeEventHeader header = oTCE.ChangeEventHeader;
			if(header.changedFields.contains('unitPrice__c')){
				System.debug('Contains price change');
				priceChange.addAll(header.recordids);
			}
			
			
			//System.debug('Received change event for ' + header.entityName +
            //        ' for the ' + header.changeType + ' operation.'); 
			//System.debug('header change type is: ' + header.getChangeType());
			//System.debug('recordIds value is: ' + header.getRecordIds());
			//System.debug('Difffields value is: ' + header.getDiffFields());
			//System.debug('nulledFields value is: ' + header.nulledfields);
			//System.debug('changedFields value is: ' + header.changedfields);
			//priceChange.add(oT.Id);
        }
		//Get list of related Inventory Assets and trigger an update so that the Rollup Helper fields on Accounting Investment (totalCostBasisInventoryAssets__c
		//and totalSalesProceedsInventoryAssets__c) will update.
		List<InventoryAsset__c> inventoryAssetUpdates = [SELECT Id FROM InventoryAsset__c 
														 WHERE assetAcquisition__c IN :priceChange
														 OR assetAcquisitionOverride__c IN :priceChange
														 OR assetSale__c IN :priceChange
														 OR assetSaleOverride__c IN :priceChange];
		if (inventoryAssetUpdates.size() > 0){
			update inventoryAssetUpdates;
		}
	}

	public static void recalcByOppTract(List<Opportunity_Tract__c> newOppTracts)
    {
        System.debug('recalc opp called');
        if (newOppTracts != null && newOppTracts.size() > 0)
        {
            Set<Id> tractIds = new Set<Id>();
            for (Opportunity_Tract__c ct : newOppTracts)
            {
				System.debug('Tract ID is: ' + ct.Tract__c + ' Opportunity Tract Id is: ' + ct.Id );
                tractIds.add(ct.Tract__c);
            }

            Map<Id,Tract__c> tractMap = TractTriggerHelper.getTractsbyIds(tractIds);


            for (Opportunity_Tract__c ot : newOppTracts)
            {
                setOppTractFields(ot,tractMap.get(ot.Tract__c));
            }
        }
    }

	    private static void setOppTractFields(Opportunity_Tract__c ot, Tract__c tract)
    {
        //ot.Commission_Amount__c = tract.Commission_Amount__c;
        ot.FMV_Per_Acre__c = tract.Value_Per_Acre__c;
        ot.OTG_Cost_Per_Acre__c = tract.OTG_Cost_Per_Acre__c;
        //ot.Other_Capitalized_Costs__c = tract.Other_Capitalized_Costs__c;
        //ot.Title_Cost__c = tract.Title_Cost__c;
        ot.Total_Cost__c = tract.Total_Cost__c;
        ot.Total_Cost_Per_Acre__c = tract.Total_Cost_Per_Acre__c;
        ot.Tract_Acres__c = tract.netAcres__c;
        ot.OTG_Cost__c = tract.OTG_Cost__c;
        ot.Notes__c = tract.Notes__c;
        ot.Gain_on_Asset__c = tract.Gain_on_Asset__c;
    }


}