src/objects/InventoryAsset__c.object
<CustomObject>
    <fields>
        <fullName>assetAcquisitionOverride__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>select any OT to calculate inventory related statistics</description>
        <label>Asset Acquisition Override</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Acquisition Overrides</relationshipLabel>
        <relationshipName>AssetAcquisitionOverrides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assetAcquisition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Acquisition</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Asset Acquisitions</relationshipLabel>
        <relationshipName>AssetAcquisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assetSaleOverride__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Sale Override</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Asset Sale Overrides</relationshipLabel>
        <relationshipName>AssetSaleOverrides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assetSale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Sale</label>
        <referenceTo>Opportunity_Tract__c</referenceTo>
        <relationshipLabel>Asset Sales</relationshipLabel>
        <relationshipName>AssetSales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Asset</label>
    <nameField>
        <displayFormat>IA-{0000000000}</displayFormat>
        <label>Inventory Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IARelatedOpportunityAuraTest.cls
@isTest 
private class IARelatedOpportunityAuraTest {

	@TestSetup
	static void setupTestData(){
		TestDataFactory.dataSetup();
	}

    static testMethod void mainTestMethod() {

		List<InventoryAsset__c> inventoryAssets = [SELECT ID FROM InventoryAsset__c];
		IARelatedOpportunityAura.IARelatedOpportunity assetAcquisition = IARelatedOpportunityAura.getRelatedOpp(inventoryAssets[0].Id, 'assetAcquisition__c');
		IARelatedOpportunityAura.IARelatedOpportunity assetAcquisitionOverride = IARelatedOpportunityAura.getRelatedOpp(inventoryAssets[0].Id, 'assetAcquisitionOverride__c');
		IARelatedOpportunityAura.IARelatedOpportunity assetSale = IARelatedOpportunityAura.getRelatedOpp(inventoryAssets[0].Id, 'assetSale__c');
		IARelatedOpportunityAura.IARelatedOpportunity assetSaleOverride = IARelatedOpportunityAura.getRelatedOpp(inventoryAssets[0].Id, 'assetSaleOverride__c');

	}
}