src/objects/LandGridTract__c.object
<CustomObject>
    <label>LandGridTract</label>
    <nameField>
        <label>LandGridTract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LandGridTracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TitleWorkJob__c.object
<CustomObject>
    <description>Contains details pertaining to running title for a particular area.  Includes Landmen, Integration Review, and Attorney Review records.</description>
    <fields>
        <fullName>completionDate__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>landGridTract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Land Grid Tract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Title Work Jobs</relationshipLabel>
        <relationshipName>titleWorkJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>srpOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SRP Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>titleWorkJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>startDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Attorney Review - Complete</fullName>
                    <isActive>false</isActive>
                    <label>Attorney Review - Complete</label>
                </value>
                <value>
                    <fullName>In Progress - Attorney Review</fullName>
                    <isActive>false</isActive>
                    <label>In Progress - Attorney Review</label>
                </value>
                <value>
                    <fullName>In Progress - Integration Review</fullName>
                    <isActive>false</isActive>
                    <label>In Progress - Integration Review</label>
                </value>
                <value>
                    <fullName>Integration Review - Complete</fullName>
                    <isActive>false</isActive>
                    <label>Integration Review - Complete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>titleWorkTracker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Title Work Tracker</label>
        <referenceTo>TitleWorkTracker__c</referenceTo>
        <relationshipLabel>Title Work Jobs</relationshipLabel>
        <relationshipName>titleWorkJobs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Landman</fullName>
                    <default>true</default>
                    <label>Landman</label>
                </value>
                <value>
                    <fullName>Integration Review</fullName>
                </value>
                <value>
                    <fullName>Attorney Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Title Work Job</label>
    <nameField>
        <displayFormat>TWJ-{0000000000}</displayFormat>
        <label>Title Work Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Work Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TitleWorkTracker__c.object
<CustomObject>
    <fields>
        <fullName>completionDate__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>landGridTract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Land Grid Tract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Title Work Trackers</relationshipLabel>
        <relationshipName>titleTrackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>projectAOI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project AOI</label>
        <referenceTo>Project_AOI__c</referenceTo>
        <relationshipLabel>Title Work Trackers</relationshipLabel>
        <relationshipName>TitleWorkTrackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>srpOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SRP Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>titleWorkTrackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>startDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Title Work Tracker</label>
    <nameField>
        <displayFormat>TWT-{0000000000}</displayFormat>
        <label>Title Work Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Work Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Full_Legal_Name__c</fullName>
        <formula>LandGridTract__r.Name  &amp; &apos; &apos; &amp; Quarter_Call__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instrument_Type__c</fullName>
        <label>Instrument Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OGL</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ORRI</fullName>
                </value>
                <value>
                    <fullName>Surface</fullName>
                </value>
                <value>
                    <fullName>Commission</fullName>
                </value>
                <value>
                    <fullName>NPRI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LandGridTract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LandGridTract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Tracts (LandGridTract)</relationshipLabel>
        <relationshipName>Tracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <inlineHelpText>OTG Cost per Acre</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTG_Cost__c</fullName>
        <formula>netAcres__c * OTG_Cost_Per_Acre__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OTG Price per acre x Net Acres</inlineHelpText>
        <label>OTG Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <formula>if (netAcres__c == 0,0,Total_Cost__c /  netAcres__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Costs divided by Net Acres</inlineHelpText>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>OTG Costs plus Commissions and title</description>
        <formula>(netAcres__c *  OTG_Cost_Per_Acre__c) +  Commission_Amount__c +  Title_Cost__c +  Other_Capitalized_Costs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OTG Costs plus Commissions and title</inlineHelpText>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>depth__c</fullName>
        <label>Depth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>maxPPA__c</fullName>
        <formula>if(aoiNetAcres__c &lt;&gt; 0, maxPrice__c / aoiNetAcres__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Max Price Per Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>maxPrice__c</fullName>
        <description>Max Price for Tract</description>
        <inlineHelpText>Max Price for Tract</inlineHelpText>
        <label>Max Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>netAcreageUnits__c</fullName>
        <label>Net Acreage Units</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NRA</fullName>
                </value>
                <value>
                    <fullName>NMA</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>netAcres__c</fullName>
        <label>Net Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>percentCovered__c</fullName>
        <description>Sum of percentage in AOI for project AOI tract</description>
        <inlineHelpText>Sum of percentage in AOI for project AOI tract</inlineHelpText>
        <label>percentCovered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>targetPPA__c</fullName>
        <formula>if(aoiNetAcres__c &lt;&gt; 0, targetPrice__c /  aoiNetAcres__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Price Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>targetPrice__c</fullName>
        <description>Sum of target price for Project AOI Tract</description>
        <inlineHelpText>Sum of target price for Project AOI Tract</inlineHelpText>
        <label>Target Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/landGridTractRelatedListAura.cls
//Test coverage included in titleWorkAuraTest.cls

public class landGridTractRelatedListAura  {

	@AuraEnabled
    public static List<TitleWorkJob__c> getTitleWorkJobs(Id recordId) {
		List<TitleWorkJob__c> titleWorkJobs = new List<TitleWorkJob__c>();
        titleWorkJobs = [SELECT 
						 completionDate__c,CreatedDate,Id,Name ,srpOwner__c,
						 startDate__c,status__c, type__c, srpOwner__r.Name, titleWorkTracker__c
						 FROM TitleWorkJob__c
						 WHERE titleWorkTracker__r.landGridTract__c =: recordId
						 ORDER by Name
        ];
        return titleWorkJobs;
    }

	@AuraEnabled
    public static List<TitleWorkTracker__c> getTitleWorkTrackers(Id recordId) {
		List<TitleWorkTracker__c> titleWorkTrackers = new List<TitleWorkTracker__c>();
        titleWorkTrackers = [SELECT	completionDate__c, CreatedById, CreatedDate, Id, IsDeleted, landGridTract__c,  LastActivityDate,
								LastModifiedById, LastModifiedDate, Name, projectAOI__c, srpOwner__c, startDate__c, status__c, SystemModstamp 
						 FROM TitleWorkTracker__c
						 WHERE landGridTract__c =: recordId
						 ORDER by Name DESC
        ];
        return titleWorkTrackers;
    }


	@AuraEnabled
	public static List<Tract__c> getTracts(Id recordId){
		List<Tract__c> relatedTracts = new List<Tract__c>();
		relatedTracts = [SELECT 
						 netAcreageUnits__c,netAcres__c,depth__c,Full_Legal_Name__c,maxPPA__c,maxPrice__c,Name,Notes__c,
						 OTG_Cost_Per_Acre__c,OTG_Cost__c,percentCovered__c,targetPPA__c,targetPrice__c,Total_Cost_Per_Acre__c,Total_Cost__c,
						 LandGridTract__c, Instrument_Type__c 
						 FROM Tract__c
						 WHERE LandGridTract__c = :recordId
						 ORDER by Name
		];
		return relatedTracts;
	}
	
}