src/objects/LandGridTract__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <externalId>true</externalId>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LandGridTract</label>
    <nameField>
        <label>LandGridTract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LandGridTracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Acquiring_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Acquiring Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Acquiring Entity)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes from tract record</description>
        <label>Notes</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <description>OTG = &quot;Off the Ground&quot; - how much was paid to the previous owner (does not include commissions, title costs etc.)</description>
        <inlineHelpText>OTG = &quot;Off the Ground&quot; - how much waspaid to the previous owner (does not include commissions, title costs etc.)</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Commission Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LandGridTract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LandGridTract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Tracts (LandGridTract)</relationshipLabel>
        <relationshipName>Tracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <inlineHelpText>OTG Cost per Acre</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Capitalized_Costs__c</fullName>
        <label>Other Capitalized Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Title_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Title Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_Per_Acre__c</fullName>
        <inlineHelpText>FMV for the tract</inlineHelpText>
        <label>FMV Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>netAcres__c</fullName>
        <label>Net Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManageTractControllerTest.cls
@isTest
public class ManageTractControllerTest{
    
    @testSetup static void methodName() {
        Account a1 = new Account();
        a1.Name = 'Seller';
        a1.Type = 'Portfolio Investment';
        insert a1;
        
        Account a2 = new Account();
        a2.Name = 'Buyer';
        a2.Type = 'Portfolio Investment';
        insert a2;
        
        Opportunity o = new Opportunity();
        o.Name = 'New Opp 1';
        o.AccountId = a1.Id;
        o.Acquiring_Entity__c = a2.Id;
        o.CloseDate = Date.today() + 30;
        o.StageName='Closed Won';
        o.Effective_Date__c=system.today();
        insert o;
        
        List<LandGridTract__c> lts = new List<LandGridTract__c>();
        LandGridTract__c lt1 = new LandGridTract__c();
        lt1.Name='Bexar 1-579e38 TX';
        lt1.County__c ='Bexar';
        lts.add(lt1);
        
        LandGridTract__c lt2 = new LandGridTract__c();
        lt2.Name='Bexar 1-179347 TX';
        lt2.County__c ='Bexar';
        lts.add(lt2);
        insert lts;
        
        Tract__c t1 = new Tract__c();
        t1.LandGridTract__c = lt1.Id;
        t1.Commission_Amount__c=1.00;
        t1.Value_Per_Acre__c=1.00;
        t1.OTG_Cost_Per_Acre__c=1.00;
        t1.Other_Capitalized_Costs__c=1.00;
        t1.Title_Cost__c=1.00;
        t1.netAcres__c=1.00;
        t1.Notes__c='test';
		t1.Account__c = a1.Id;
        insert t1;
        
        Tract__c t2 = new Tract__c();
        t2.LandGridTract__c = lt2.Id;
        t2.Commission_Amount__c=1.00;
        t2.Value_Per_Acre__c=1.00;
        t2.OTG_Cost_Per_Acre__c=1.00;
        t2.Other_Capitalized_Costs__c=1.00;
        t2.Title_Cost__c=1.00;
        t2.netAcres__c=1.00;
        t2.Notes__c='test';
		t2.Account__c = a2.Id;
        insert t2;
        
        Opportunity_Tract__c ot = new Opportunity_Tract__c();
        ot.Opportunity__c = o.Id;
        ot.Tract__c = t2.Id;
        insert ot;
        
    }
    
    
    @isTest
    private static void getTractTestMethod(){
        Opportunity oppRec = [Select id,AccountId from Opportunity Limit 1];
        ManageTractController.getTract(oppRec.Id);
    }
    
    @isTest 
    public static void getFilteredTractsTestMethod(){
		Test.startTest();
        Opportunity opp = [Select id,AccountId from Opportunity Limit 1];
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'tex', 2);
        List<Tract__c> t = [Select Id from tract__c];
        delete t;
        List<LandGridTract__c> l = [Select Id from LandGridTract__c];
        delete l;
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'tex', 2);
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'arka', 2);
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'colo', 2);
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'monta', 2);
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'kans', 2);
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'new', 2);
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'louis', 2);
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'wyo', 2);
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'test', 2);
        ManageTractController.getFilteredTracts(opp.Id, 1, 5,'', 2);
        Test.stopTest();
    }
    @isTest
    public static void addTractTestmethod(){
        
        List<Tract__c> tracts = new List<Tract__c>();
        List<LandGridTract__c> lts = new List<LandGridTract__c>();
        LandGridTract__c lt1 = new LandGridTract__c();
        lt1.Name='Bexar 1-579e38 TX';
        lt1.County__c ='Bexar';
        lts.add(lt1);
        
        LandGridTract__c lt2 = new LandGridTract__c();
        lt2.Name='Bexar 1-179347 TX';
        lt2.County__c ='Bexar';
        lts.add(lt2);
        insert lts;
        
        Tract__c t1 = new Tract__c();
        t1.LandGridTract__c = lt1.Id;
        t1.Commission_Amount__c=1.00;
        t1.Value_Per_Acre__c=1.00;
        t1.OTG_Cost_Per_Acre__c=1.00;
        t1.Other_Capitalized_Costs__c=1.00;
        t1.Title_Cost__c=1.00;
        t1.netAcres__c=1.00;
        t1.Notes__c='test';
        tracts.add(t1);
        
        Tract__c t2 = new Tract__c();
        t2.LandGridTract__c = lt2.Id;
        t2.Commission_Amount__c=1.00;
        t2.Value_Per_Acre__c=1.00;
        t2.OTG_Cost_Per_Acre__c=1.00;
        t2.Other_Capitalized_Costs__c=1.00;
        t2.Title_Cost__c=1.00;
        t2.netAcres__c=1.00;
        t2.Notes__c='test';
        tracts.add(t2);
        Opportunity oppRec = [Select id,AccountId from Opportunity Limit 1];
        try{
            ManageTractController.addTract(oppRec.Id,tracts);
        }catch(Exception e){
            
        }
    }
    
    @isTest
    public static void removeTractTestMethod(){
        Opportunity opp = [Select id,AccountId from Opportunity Limit 1];
        List<Tract__c> tracts = [Select Id from Tract__c];
        
        ManageTractController.removeTract(opp.Id,tracts);
    }
}