src/objects/LandGridTract__c.object
<CustomObject>
    <label>LandGridTract</label>
    <nameField>
        <label>LandGridTract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LandGridTracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Instrument_Type__c</fullName>
        <formula>TEXT(Tract__r.Instrument_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Instrument Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes from tract record</description>
        <label>Notes</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Full_Legal_Name__c</fullName>
        <formula>LandGridTract__r.Name  &amp; &apos; &apos; &amp; Quarter_Call__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gross_Acres__c</fullName>
        <label>Gross Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Instrument_Type__c</fullName>
        <label>Instrument Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OGL</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ORRI</fullName>
                </value>
                <value>
                    <fullName>Surface</fullName>
                </value>
                <value>
                    <fullName>Commission</fullName>
                </value>
                <value>
                    <fullName>NPRI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LandGridTract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LandGridTract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Tracts (LandGridTract)</relationshipLabel>
        <relationshipName>Tracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Quarter_Call__c</fullName>
        <inlineHelpText>Quarter Call</inlineHelpText>
        <label>Quarter Call</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>depth__c</fullName>
        <label>Depth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>netAcreageUnits__c</fullName>
        <label>Net Acreage Units</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NRA</fullName>
                </value>
                <value>
                    <fullName>NMA</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>netAcres__c</fullName>
        <label>Net Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManageTractController.cls
public class ManageTractController {
    
    @AuraEnabled
    public static tableWrapper getTract(Id oppId){
        tableWrapper tableWrap = new tableWrapper();
        Set<Id> tractIds = new Set<id>(); 
        Opportunity oppRec = [Select id,AccountId from Opportunity Where Id =:oppId Limit 1];
        
        for(Opportunity_Tract__c oppTract : [Select Tract__c From Opportunity_Tract__c 
                        where Opportunity__c =: oppId]){
                            
                            tractIds.add(oppTract.Tract__c);
                        }  

        tableWrap.unassociatedTracts = [Select id,name,Full_Legal_Name__c,Quarter_Call__c,Instrument_Type__c,
                                        netAcreageUnits__c,netAcres__c, Gross_Acres__c, Notes__c, LandGridTract__c from tract__c 
                                        Where Account__c =:oppRec.AccountId AND Id not In: tractIds];

        tableWrap.associatedTracts = [Select id,name,Full_Legal_Name__c,Quarter_Call__c,Instrument_Type__c,
                                      netAcreageUnits__c,netAcres__c, Gross_Acres__c, Notes__c, LandGridTract__c from tract__c 
                                      Where Id In: tractIds];

        return tableWrap;
    }
	
	@AuraEnabled 
	public static tableWrapper getFilteredTracts(Id oppId, Integer pageNumber, Integer pageSize, String searchTerm, Integer searchCount){
        tableWrapper tableWrap = new tableWrapper();
		string searchStringCheck = '';
		if(searchTerm != null){
		 searchStringCheck = searchTerm.trim();
		}
		Boolean isFiltered = false;
		List<String> landGridTractIds = new List<String>();
		if(searchStringCheck.length() >1){
			Opportunity oppRec = [Select id,AccountId from Opportunity Where Id =:oppId Limit 1];
			landGridTractIds = getFilteredLandGridTracts(searchTerm, oppRec.AccountId);
			isFiltered = true;
		}
		tableWrap.associatedTracts = getAssociatedTract(oppId, pageNumber, pageSize, landGridTractIds, isFiltered, null);
		tableWrap.unassociatedTracts = getUnassociatedTract(oppId, pageNumber, pageSize, landGridTractIds, isFiltered, null);
		tableWrap.searchCounter = searchCount;
		return tableWrap;
		
			
	}
	
	@AuraEnabled
    public static List<Tract__c> getUnassociatedTract(Id oppId,Integer pageNumber,Integer pageSize, List<String> landGridTractIds, boolean filtered, String searchString){
		System.debug('input values are - oppId: ' + oppId + ' pageNumber: ' + pageNumber + ' pageSize: ' + pageSize + ' landGridTractIds: ' + landGridTractIds);
        
		Set<Id> tractIds = new Set<id>(); 
        Opportunity oppRec = [Select id,AccountId from Opportunity Where Id =:oppId Limit 1];
        if (landGridTractIds == null){
			landGridTractIds = new List<String>();
		}
		if(searchString == null){
			searchString = '';
		}
		if(searchString.length()>1 && landGridTractIds.size() == 0){
			System.debug('searching for landgridtracts with searchString: ' + searchString + ' account id: ' + oppRec.AccountId);
			landGridTractIds = getFilteredLandGridTracts(searchString, oppRec.AccountId);
		}

        //Separate Tracts and Land Grid Tracts
        Set<Id> searchedTractIds = new Set<Id>(); 
        Set<Id> searchedLandGridTractIds = new Set<Id>(); 
        for(Id objId: (List<Id>)landGridTractIds){
            if(objId.getSObjectType(). getDescribe().getName() =='Tract__c'){
                searchedTractIds.add(objId);
            }else{
                searchedLandGridTractIds.add(objId);
            }
        }

		System.debug('Modified input values are - searchString: ' + searchString + ' landGridTractIds: ' + landGridTractIds);
		System.debug('landGridTracts size is: ' + landGridTractIds.size());
		for(Opportunity_Tract__c oppTract : [Select Tract__c From Opportunity_Tract__c 
                        where Opportunity__c =: oppId]){                       
                            tractIds.add(oppTract.Tract__c);
		}
		List<Tract__c> unassociatedTracts = new List<Tract__c>();
		if(filtered){  
			unassociatedTracts = [Select id,name,Full_Legal_Name__c,Quarter_Call__c,Instrument_Type__c,
									netAcreageUnits__c,netAcres__c, Gross_Acres__c, Notes__c, LandGridTract__c,depth__c from tract__c 
									Where Account__c =:oppRec.AccountId AND Id not In: tractIds
									AND (LandGridTract__c IN :searchedLandGridTractIds OR Id In: searchedTractIds)
									LIMIT :pageSize OFFSET :pageSize*(pageNumber-1)];
		}
		else{
			unassociatedTracts = [Select id,name,Full_Legal_Name__c,Quarter_Call__c,Instrument_Type__c,
									netAcreageUnits__c,netAcres__c, Gross_Acres__c, Notes__c, LandGridTract__c,depth__c from tract__c 
									Where Account__c =:oppRec.AccountId AND Id not In: tractIds
									LIMIT :pageSize OFFSET :pageSize*(pageNumber-1)];
		}
		return unassociatedTracts;   
                       
    }   
	
    @AuraEnabled
    public static List<Tract__c> getAssociatedTract(Id oppId,Integer pageNumber,Integer pageSize, List<String> landGridTractIds, Boolean filtered, String searchString){
		System.debug('input values are - oppId: ' + oppId + ' pageNumber: ' + pageNumber + ' pageSize: ' + pageSize + ' landGridTractIds: ' + landGridTractIds);
        Set<Id> tractIds = new Set<id>(); 
        Opportunity oppRec = [Select id,AccountId from Opportunity Where Id =:oppId Limit 1];
		if (landGridTractIds == null){
			landGridTractIds = new List<String>();
		}
		if(searchString == null){
			searchString = '';
		}
		if(searchString.length()>1 && landGridTractIds.size() == 0){
			System.debug('searching for landgridtracts with searchString: ' + searchString + ' account id: ' + oppRec.AccountId);
			landGridTractIds = getFilteredLandGridTracts(searchString, oppRec.AccountId);
		}

        //Separate Tracts and Land Grid Tracts
        Set<Id> searchedTractIds = new Set<Id>(); 
        Set<Id> searchedLandGridTractIds = new Set<Id>(); 
        for(Id objId: (List<Id>)landGridTractIds){
            if(objId.getSObjectType(). getDescribe().getName() =='Tract__c'){
                searchedTractIds.add(objId);
            }else{
                searchedLandGridTractIds.add(objId);
            }
        }

		System.debug('Modified input values are - searchString: ' + searchString + ' landGridTractIds: ' + landGridTractIds);
		System.debug('landGridTracts size is: ' + landGridTractIds.size());
        for(Opportunity_Tract__c oppTract : [Select Tract__c From Opportunity_Tract__c 
                        where Opportunity__c =: oppId]){
                            
                            tractIds.add(oppTract.Tract__c);
        }  
		List<Tract__c> associatedTracts = new List<Tract__c>();
		if(filtered){  
			associatedTracts = [Select id,name,Full_Legal_Name__c,Quarter_Call__c,Instrument_Type__c,
                                netAcreageUnits__c,netAcres__c, Gross_Acres__c, Notes__c, LandGridTract__c,depth__c from tract__c 
                                Where Id In: tractIds
								AND (LandGridTract__c IN :searchedLandGridTractIds OR Id In: searchedTractIds)
                                LIMIT :pageSize OFFSET :pageSize*(pageNumber-1)];
		}
		else{
			associatedTracts = [Select id,name,Full_Legal_Name__c,Quarter_Call__c,Instrument_Type__c,
                                netAcreageUnits__c,netAcres__c, Gross_Acres__c, Notes__c, LandGridTract__c,depth__c from tract__c 
                                Where Id In: tractIds 
                                LIMIT :pageSize OFFSET :pageSize*(pageNumber-1)];
		}

        return associatedTracts;                           
    }
    
    @AuraEnabled
    public static void addTract(Id oppId,List<Tract__c> tracts){
        
        List<Opportunity_Tract__c> otList = new List<Opportunity_Tract__c>();
        Opportunity_Tract__c otRec;
        Opportunity oppRec = [Select id,AccountId from Opportunity Where Id =:oppId Limit 1];
        
        for(Tract__c tractRec : tracts){

            otRec = new  Opportunity_Tract__c();
            otRec.Tract__c = tractRec.Id;
            otRec.Opportunity__c = oppId;
            otList.add(otRec);
        }
        if(otList.size()>0){
            insert otList;
        }
    }

    @AuraEnabled
    public static void removeTract(Id oppId,List<Tract__c> tracts){
        
        List<Opportunity_Tract__c> otList = [Select Id from Opportunity_Tract__c 
                    Where Opportunity__c =:oppId AND Tract__c In: tracts];
        
        if(otList.size()>0){
            delete otList;
        }
    }

	public static List<String> getFilteredLandGridTracts (String searchTerm, String accountId){
        // Prepare query parameters
        List<string> results = new List<String>();
		if(!String.isBlank(searchTerm)){
			List<String> terms = searchTerm.split('\\s');
			List<String> newTerms = new List<String>();
			Map<String,String> aliasList = new Map<String,String>();

			for(String term : terms)		
			{
				// Aliases

				if (hasTerm(term,'tex'))
				{
					newTerms.add('(*TX* OR *' + term + '*)');
				}
				else if (hasTerm(term,'arka'))
				{
					newTerms.add('(*AR* OR *' + term + '*)');
				}
				else if (hasTerm(term,'colo'))
				{
					newTerms.add('(*CO* OR *' + term + '*)');
				}
				else if (hasTerm(term,'monta'))
				{
					newTerms.add('(*MT* OR *' + term + '*)');
				}
				else if (hasTerm(term,'kans'))
				{
					newTerms.add('(*KS* OR *' + term + '*)');
				}
				else if (hasTerm(term,'new') || hasTerm(term,'mexi'))
				{
					newTerms.add('(*NM* OR *' + term + '*)');
				}
				else if (hasTerm(term,'louis'))
				{
					newTerms.add('(*LA* OR *' + term + '*)');
				}
				else if (hasTerm(term,'wyo'))
				{
					newTerms.add('(*WY* OR *' + term + '*)');
				}
				else
				{
					newTerms.add('*' + term + '*');
				}
			}

			String newTerm = String.join(newTerms,' AND ');
			System.debug('newTerm: ' + newTerm + ' accountId: ' + accountId);
			Datetime qryStart = Datetime.now();
        
			List<List<SObject>> searchResults = [FIND :newTerm IN Name fields Returning Landgridtract__c(Id WHERE Id in (SELECT landgridtract__c FROM Tract__c WHERE account__c = :accountId)),Tract__c(Id WHERE account__c = :accountId)];
			System.debug('Result size: ' + searchResults.size());
        
			Datetime qryEnd = Datetime.now();
        
			System.debug(LoggingLevel.WARN, 'Result time: ' + (qryEnd.getTime() - qryStart.getTime()) + 'ms');
		

			// Extract Land Grid Tracts & convert them into LookupSearchResult
			
            

			LandGridTract__c [] lgTracts = ((List<LandGridTract__c>) searchResults[0]);
			for (LandGridTract__c lt : lgTracts) {
				results.add(String.valueOf(lt.Id));
			}

            Tract__c [] tracts = ((List<Tract__c>) searchResults[1]);
			for (Tract__c t : tracts) {
				results.add(String.valueOf(t.Id));
			}
            system.debug('********results*****'+results);
		}
		return results;
	}

	  //If the term starts with the selected value, return true
    private static Boolean hasTerm(String term, String value)
    {
        return (term.left(value.length()).toLowerCase() == value.toLowerCase());
    }


    public class tableWrapper{
        @AuraEnabled
        public List<Tract__c> unassociatedTracts{get;set;}
        @AuraEnabled
        public List<Tract__c> associatedTracts{get;set;}
		@AuraEnabled 
		public Integer searchCounter{get;set;}

		public tableWrapper(){
			unassociatedTracts = new List<Tract__c>();
			associatedTracts = new List<Tract__c>();
			searchCounter = 0;
		}
    }
}