src/objects/LandGridTract__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <externalId>true</externalId>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LandGridTract</label>
    <nameField>
        <label>LandGridTract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LandGridTracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Acquiring_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Acquiring Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Acquiring Entity)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Divestiture</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <label>Divestiture</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>unitPrice__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LandGridTract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LandGridTract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Tracts (LandGridTract)</relationshipLabel>
        <relationshipName>Tracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityTractTriggerHelperTest.cls
@isTest
public with sharing class OpportunityTractTriggerHelperTest {


    static testMethod void testTrigger() {
        // test the trigger and helper method
		Test.enableChangeDataCapture();
        Account a1 = new Account();
        a1.Name = 'Seller';
        a1.Type = 'Portfolio Investment';
        insert a1;

        Account a2 = new Account();
        a2.Name = 'Buyer';
        a2.Type = 'Portfolio Investment';
        insert a2;

        List<LandGridTract__c> lts = new List<LandGridTract__c>();
        LandGridTract__c lt1 = new LandGridTract__c();
        lt1.Name='Bexar 1-579e38 TX';
        lt1.County__c ='Bexar';
        lts.add(lt1);

        LandGridTract__c lt2 = new LandGridTract__c();
        lt2.Name='Bexar 1-179347 TX';
        lt2.County__c ='Bexar';
        lts.add(lt2);
        insert lts;

        Opportunity o = new Opportunity();
        o.Name = 'New Opp 1';
        o.AccountId = a1.Id;
        o.Acquiring_Entity__c = a2.Id;
        o.CloseDate = Date.today() + 30;
        o.StageName='Closed Won';
        o.Effective_Date__c=system.today();
        insert o;

        Opportunity o2 = new Opportunity();
        o2.Name = 'New Opp 1';
        o2.AccountId = a1.Id;
        o2.Acquiring_Entity__c = a2.Id;
        o2.CloseDate = Date.today() + 30;
        o2.StageName='Closed Won';
        o2.Effective_Date__c=system.today();
        o2.Type='Divestiture';
        o2.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Divestiture').getRecordTypeId();
        
        insert o2;

        Tract__c t1 = new Tract__c();
        t1.LandGridTract__c = lt1.Id;
		t1.Account__c = a1.Id;
        insert t1;

        Tract__c t2 = new Tract__c();
        t2.LandGridTract__c = lt2.Id;
		t2.Account__c = a2.Id;
        insert t2;

        Opportunity_Tract__c ot = new Opportunity_Tract__c();
        ot.Opportunity__c = o.Id;
        ot.Tract__c = t2.Id;
        insert ot;
        
        Opportunity_Tract__c ot1 = new Opportunity_Tract__c();
        ot1.Opportunity__c = o2.Id;
        ot1.Tract__c = t1.Id;
        insert ot1;
        
        ot.unitPrice__c = 10;
        update ot;
        
        Test.getEventBus().deliver();
     
    }
}