src/objects/LandGridTract__c.object
<CustomObject>
    <label>LandGridTract</label>
    <nameField>
        <label>LandGridTract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LandGridTracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_AOI__c.object
<CustomObject>
    <description>Project AOI</description>
    <label>Project AOI</label>
    <nameField>
        <label>Project AOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAOIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TitleWorkJob__c.object
<CustomObject>
    <description>Contains details pertaining to running title for a particular area.  Includes Landmen, Integration Review, and Attorney Review records.</description>
    <fields>
        <fullName>landGridTract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Land Grid Tract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Title Work Jobs</relationshipLabel>
        <relationshipName>titleWorkJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>titleWorkTracker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Title Work Tracker</label>
        <referenceTo>TitleWorkTracker__c</referenceTo>
        <relationshipLabel>Title Work Jobs</relationshipLabel>
        <relationshipName>titleWorkJobs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Title Work Job</label>
    <nameField>
        <displayFormat>TWJ-{0000000000}</displayFormat>
        <label>Title Work Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Work Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TitleWorkTracker__c.object
<CustomObject>
    <fields>
        <fullName>landGridTract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Land Grid Tract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Title Work Trackers</relationshipLabel>
        <relationshipName>titleTrackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Title Work Tracker</label>
    <nameField>
        <displayFormat>TWT-{0000000000}</displayFormat>
        <label>Title Work Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Work Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>LandGridTract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LandGridTract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Tracts (LandGridTract)</relationshipLabel>
        <relationshipName>Tracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/titleWorkAuraTest.cls
//Test class provides coverage for the following classes

//homeTitleWorkTrackerAura
//lgtTitleWorkTrackerAura
//newTitleWorkTrackerModalAura
//titleWorkTrackerAura
//titleWorkTrackingCardAura
//landGridTractRelatedListAura 
//lookupUtility


@isTest 
private class titleWorkAuraTest {

	@TestSetup
	static void setupTestData(){
		TestDataFactory.dataSetup();
	}

	@isTest
	private static void titleTrackerTest() {
		List<AuraSelectOption> workJobTypes = newTitleWorkTrackerModalAura.getWorkJobTypes(null);
		List<LookupSearchResult> currentUser = newTitleWorkTrackerModalAura.fetchUser();
		List<LandGridTract__c> lgts = [SELECT ID FROM LandGridTract__c];
		List<Id> fixedSearchResults = new List<Id>();
		for(LandGridTract__c lgt: lgts){
			fixedSearchResults.add(lgt.Id);
		} 
		Test.setFixedSearchResults(fixedSearchResults);
		List<LookupSearchResult> landGridTracts = newTitleWorkTrackerModalAura.searchLandGridTracts('Howard', new List<String>());
		fixedSearchResults.clear();
		List<Project_AOI__c> projectAOIs = [SELECT ID FROM Project_AOI__c];
		for(Project_AOI__c projectAOI: projectAOIs){
			fixedSearchResults.add(projectAOI.Id);
		}
		Test.setFixedSearchResults(fixedSearchResults);
		List<LookupSearchResult> lookupProjectAOIs = newTitleWorkTrackerModalAura.searchProjectAOIs('Test', new List<String>());
		fixedSearchResults.clear();
		List<User> users = [SELECT ID FROM User LIMIT 20];
		for(User u: users){
			fixedSearchResults.add(u.Id);
		}
		Test.setFixedSearchResults(fixedSearchResults);
		List<LookupSearchResult> lookupUsers = newTitleWorkTrackerModalAura.searchUsers('Testing', new List<String>());
		newTitleWorkTrackerModalAura.createTitleTrackerResponse trackerResponse = newTitleWorkTrackerModalAura.createTitleWorkTracker(null, String.valueOf(lgts[0].Id), null, workJobTypes[0].value, String.valueOf(currentUser[0].getId()), System.today(), true, 'Not Started', null);
		newTitleWorkTrackerModalAura.createTitleTrackerResponse trackerResponse2 = newTitleWorkTrackerModalAura.createTitleWorkTracker(null, String.valueOf(lgts[0].Id), null, workJobTypes[0].value, String.valueOf(currentUser[0].getId()), System.today(), true, 'Not Started', null);
		newTitleWorkTrackerModalAura.createTitleTrackerResponse trackerResponse3 = newTitleWorkTrackerModalAura.createTitleWorkTracker(String.valueOf(trackerResponse.titleWorkTracker.Id), String.valueOf(lgts[0].Id), '', workJobTypes[0].value, String.valueOf(currentUser[0].getId()), System.today(), false, 'Not Started', null);
		titleWorkTrackerAura.titleTrackerResponse titleTrackerResponse = titleWorkTrackerAura.getTitleTracker(trackerResponse.titleWorkTracker.Id);
		List<TitleWorkJob__c> titleWorkJobs = titleWorkTrackerAura.getTitleWorkJobs(lgts[0].Id);
		lgtTitleWorkTrackerAura.titleTrackerResponse lgtTitleTrackerResponse = lgtTitleWorkTrackerAura.getTitleTrackers(lgts[0].Id);
		List<TitleWorkJob__c> lgtTitleWorkJobs = lgtTitleWorkTrackerAura.getTitleWorkJobs(lgts[0].Id);
		List<TitleWorkJob__c> homeTitleWorkJobs = homeTitleWorkTrackerAura.getTitleWorkJobs(lgts[0].Id);
		homeTitleWorkTrackerAura.titleTrackerResponse homeTrackerResponse = homeTitleWorkTrackerAura.getTitleTrackers('In Progress');
		String updateTrackerResponseComplete = titleWorkTrackingCardAura.updateTitleWorkComplete(trackerResponse.titleWorkTracker, 'TitleWorkTracker__c');
		String updateLGTResponseComplete = titleWorkTrackingCardAura.updateTitleWorkComplete(lgts[0], 'LandGridTract__c');
		homeTitleWorkTrackerAura.titleTrackerResponse homeTrackerResponse2 = homeTitleWorkTrackerAura.getTitleTrackers('Complete');
		List<TitleWorkTracker__c> twts = landGridTractRelatedListAura.getTitleWorkTrackers(lgts[0].Id);
		List<TitleWorkJob__c> twjs = [SELECT ID, landGridTract__c FROM TitleWorkJob__c];
		for(TitleWorkJob__c twj:twjs){
			List<TitleWorkJob__c> relatedTWJs = landGridTractRelatedListAura.getTitleWorkJobs(twj.landGridTract__c);
			//System.assertEquals(relatedTWJs.size(), 1);	
			List<Tract__c> relatedTracts = landGridTractRelatedListAura.getTracts(twj.landGridTract__c);
		}
        
        Test.setFixedSearchResults(fixedSearchResults);
		List<LookupSearchResult> acctSearchRes = lookupUtility.searchAccounts('New Account', new List<String>());
		fixedSearchResults.clear();     
	}
	
}