src/objects/LandGridTract__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <externalId>true</externalId>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LandGridTract</label>
    <nameField>
        <label>LandGridTract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LandGridTracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Lessee__c</fullName>
        <formula>Instrument__r.Lessee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lessee</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lessor__c</fullName>
        <formula>Instrument__r.Lessor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lessor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ford_Tract_Status__c</fullName>
        <description>legacy statuses from project ford, should be removed and migrated to a standard status</description>
        <inlineHelpText>ONLY use for project Ford assets, this field needs to be removed</inlineHelpText>
        <label>Ford Tract Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>101 - Contact Info Not Yet Found</fullName>
                </value>
                <value>
                    <fullName>103 - Outreach</fullName>
                </value>
                <value>
                    <fullName>107 - Pending Investigation</fullName>
                </value>
                <value>
                    <fullName>109 - Premium Investigation</fullName>
                </value>
                <value>
                    <fullName>201 - Continued Discussions</fullName>
                </value>
                <value>
                    <fullName>301 - Rejected - Price</fullName>
                </value>
                <value>
                    <fullName>302 - Rejected - Not Interested</fullName>
                </value>
                <value>
                    <fullName>401 - Offer Outstanding</fullName>
                </value>
                <value>
                    <fullName>404 - Offer Outstanding - Offer Letter Sent</fullName>
                </value>
                <value>
                    <fullName>405 - Offer Outstanding - PSA Sent</fullName>
                </value>
                <value>
                    <fullName>410 - Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>411 - Offer Accepted - Verbal</fullName>
                </value>
                <value>
                    <fullName>420 - Offer Expired</fullName>
                </value>
                <value>
                    <fullName>450 - Offer Accepted - Pending Title</fullName>
                </value>
                <value>
                    <fullName>501 - Offer Declined</fullName>
                </value>
                <value>
                    <fullName>601 - Invoiced - Pending</fullName>
                </value>
                <value>
                    <fullName>602 - Invoiced - Consummated</fullName>
                </value>
                <value>
                    <fullName>701 - Wrong Owner</fullName>
                </value>
                <value>
                    <fullName>801 - EMC Rejected</fullName>
                </value>
                <value>
                    <fullName>901 - Title Fail - Rejected</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>1001 - Dropped Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Instrument_Type__c</fullName>
        <label>Instrument Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OGL</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ORRI</fullName>
                </value>
                <value>
                    <fullName>Surface</fullName>
                </value>
                <value>
                    <fullName>Commission</fullName>
                </value>
                <value>
                    <fullName>NPRI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LandGridTract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>LandGridTract</label>
        <referenceTo>LandGridTract__c</referenceTo>
        <relationshipLabel>Tracts (LandGridTract)</relationshipLabel>
        <relationshipName>Tracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewTractWizardExtensionTest.cls
@isTest
public class NewTractWizardExtensionTest {


static testMethod void testPage() {

        Account a = new Account();
        a.Name = 'Responsible Entity';
        insert a;

        LandGridTract__c lt = new LandGridTract__c();
    	lt.Name='Bexar 1-579348 TX';
        lt.County__c ='Bexar';
        insert lt;

		List<Opportunity> opps = TestDataFactory.createOpportunities(1,a);
        insert opps;


        Test.startTest();

        PageReference p = Page.NewTractWizard;
        Test.setCurrentPage(p);
        Tract__c newTract = new Tract__c();
        //newTract.SRP_Responsible_Entity__c = a.Id;

        ApexPages.StandardController c = new ApexPages.StandardController(newTract);
        NewTractWizardExtension ne = new NewTractWizardExtension(c);

        ne.saveNew();
		
		//Check for errors
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		for(ApexPages.Message message: pageMessages){
			System.debug(message);
		}
		
		System.assertEquals(2, pageMessages.size());

		//Clear error messages

		System.Test.clearApexPageMessages();
		System.debug('message size after clear is: ' + ApexPages.getMessages().size());
		newTract.Instrument_Type__c = 'Surface';
        newTract.Ford_Tract_Status__c = '103 - Outreach';

        ne.newTract = newTract;
		//Removing instrument per Quin (jdg 2-13-2020)
        //ne.updateInstrument();
        newTract.Instrument_Type__c = 'ORRI';
        newTract.LandGridTract__c = lt.Id;
		newTract.Account__c = a.Id;

        ne.newTract = newTract;
        ne.selLandGridTract = lt;
        ne.selLandGridTractId = lt.Id;
		ne.newTract.LandgridTract__c = lt.Id;

        /*ne.showInstrument = true;
        ne.updateInstrument();

        ne.showNewInstrument = false;
        ne.updateInstrument();

        ne.useExisting();
        ne.useNewInstrument();
		*/
        ne.save();
		
		pageMessages = ApexPages.getMessages();
		

		for(ApexPages.Message message: pageMessages){
			System.debug(message);
		}

		System.assertEquals(0, pageMessages.size());

		/*
        ne.newInstrument.Lessor__c = 'Billy';
        ne.newInstrument.Lessee__c = 'Willy';
        ne.saveNew();
		*/
        ne.newTract = new Tract__c();
        //ne.newTract.SRP_Responsible_Entity__c = a.Id;
        ne.selLandGridTract = lt;
        ne.selLandGridTractId = lt.Id;
        ne.newTract.LandgridTract__c = lt.Id;
        ne.save();

		pageMessages = ApexPages.getMessages();
		

		for(ApexPages.Message message: pageMessages){
			System.debug(message);
		}

		System.assertEquals(2, pageMessages.size());

        ApexPages.currentPage().getParameters().put('selectedValue', lt.Id);
        ne.setId();

		ApexPages.currentPage().getParameters().put('selectedOppValue', opps[0].Id);
		ne.setOppId();

		List<Account> accounts = [SELECT ID FROM Account];
		System.assertEquals(1, accounts.size());

		List<LandGridTract__c> landGridTracts = [SELECT ID FROM LandGridTract__c];
		System.assertEquals(1, landGridTracts.size());

		List<Tract__c> tracts = [SELECT ID FROM Tract__c];
		System.assertEquals(1, tracts.size());

		List<Subtract__c> subtracts = [SELECT ID FROM Subtract__c];
		System.assertEquals(1, subtracts.size());

        Test.stopTest();

    }

        
    }