src/objects/Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Total Check Amount</description>
        <inlineHelpText>Total Check Amount</inlineHelpText>
        <label>Check Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Issue_Date__c</fullName>
        <description>Date Check was Issued</description>
        <inlineHelpText>Date Check was Issued</inlineHelpText>
        <label>Check Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <externalId>true</externalId>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Unique Check Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>grossVolumeActual__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Gross volume from royalty check from operator (5 decimal places)</description>
        <inlineHelpText>Gross volume from royalty check from operator (5 decimal places)</inlineHelpText>
        <label>Gross Volume Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lineItemDecimal__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Royalty check line item well interest / distribution decimal from operator.</description>
        <inlineHelpText>Royalty check line item well interest / distribution decimal from operator.</inlineHelpText>
        <label>Line Item Decimal</label>
        <precision>11</precision>
        <required>true</required>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ownerNetValueActual__c</fullName>
        <label>Owner Net Value Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>Price from operator royalty check line item (4 decimal places)</description>
        <inlineHelpText>Price from operator royalty check line item (4 decimal places)</inlineHelpText>
        <label>Price</label>
        <precision>11</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>production_Month__c</fullName>
        <label>Production Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <externalId>true</externalId>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>royalty_Check__c</fullName>
        <description>Royalty Check</description>
        <label>Royalty Check</label>
        <referenceTo>Royalty_Check__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DeleteAndUploadRoyaltyLineItemBatch_Test.cls
@isTest
public class DeleteAndUploadRoyaltyLineItemBatch_Test{

    @isTest
    public static void deleteRLI_TestMethod(){

        String csvString = 'Check Number,Check Amount,Check Date,DedCode,Gross Adjustments,Gross Net,Gross Taxes,Gross Value,Gross Volume,Line Item Decimal,Line Item Net Value,Net Value,Price,Product,Production Month,Type,Property Id,Property Name,Owner Net Value \n';
        csvString += '123,123,01/01/2020,1.01,1.01,42942.8,1.01,45259.53,645.8,0.00068433,30.97,1.01,70.08,OIL,01-09-2018,R1,TestName,64356345,23,"test" \n';

        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.csv';
        cv.VersionData = Blob.valueOf(csvString);
        cv.IsMajorVersion = true;
        Insert  cv;

        Royalty_Check__c rcRecc= new Royalty_Check__c();
        rcRecc.Check_Number__c ='123';
        rcRecc.Check_Issue_Date__c = date.newinstance(2020,01,01);
        rcRecc.Amount__c = 123;
        rcRecc.Description__c = 'Test #987654321 '+rcRecc.Check_Issue_Date__c.format()+' $100.00' ;
        system.debug(rcRecc.Check_Issue_Date__c);
        insert rcRecc;
        
        Royalty_Line_Item__c rliRec = new Royalty_Line_Item__c();
        rliRec.Royalty_Check__c = rcRecc.id;
        //rliRec.Type__c = 'Revenue';
        rliRec.Production_Month__c = system.today();
        rliRec.ownerNetValueActual__c = 123;
        rliRec.lineItemDecimal__c = 0.00012122;
        rliRec.grossVolumeActual__c = 230.50;
        rliRec.propertyName__c = 'Test';
        rliRec.Price__c  = 200;
        insert rliRec;

        Log__c log = new Log__c();
        insert log;
        
        List<ContentDocument> cd = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        DeleteAndUploadRoyaltyLineItemBatch deleteAndUpload = new DeleteAndUploadRoyaltyLineItemBatch(cd[0].Id, rcRecc.Id,log.Id);
        Database.executebatch(deleteAndUpload);

    }

}