src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OldRoyaltyLineItem__c</fullName>
        <label>Old Royalty Line Item</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Find Royalty Check</fullName>
                </value>
                <value>
                    <fullName>Delete Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Read Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Insert Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Upsert</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                    <default>true</default>
                    <label>Error</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>royaltyCheck__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Royalty Check</label>
        <referenceTo>Royalty_Check__c</referenceTo>
        <relationshipLabel>Logs</relationshipLabel>
        <relationshipName>Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>royalty_Check__c</fullName>
        <description>Royalty Check</description>
        <label>Royalty Check</label>
        <referenceTo>Royalty_Check__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DeleteAndUploadRoyaltyLineItemBatch.cls
/**
    * @description : This class is used to delete RLI records related to the given RC Id
    *               Once all related RLI are deleted, the finish method of the class calls the
    *               ImportLineItemsController.importRecords method to read the uploaded file and insert nnew RC.
    * @author Jade Tran
    **/
public class DeleteAndUploadRoyaltyLineItemBatch implements Database.batchable<sObject>,Database.Stateful{
	Id rcId;
    Id contentDocumentId;
    Id logId;
    Integer OldRoyaltyLineItem = 0;
    public DeleteAndUploadRoyaltyLineItemBatch(Id contentDocumentId,Id rcId,Id logId){
        this.rcId = rcId;
        this.contentDocumentId = contentDocumentId;
        this.logId = logId;
    }
    
    public Database.QueryLocator start(Database.BatchableContext context){ 
        String query='Select Id from Royalty_Line_Item__c where Royalty_Check__c =: rcId';
        return Database.getQueryLocator(query);

    }     
    public void execute(Database.BatchableContext context, List<sObject> scope){ 
        try{
            OldRoyaltyLineItem += scope.size();
        	delete scope;
            if(Test.isRunningTest()){
                throw new applicationException('error message');
            }
        }catch(Exception e){
            log__c log = new log__c();
            log.Id = logId;
            log.Status__c = 'Error';
            log.Process__c = 'Delete Royalty Line Items';
            log.Error_Message__c = e.getMessage() ;
            log.Stack_Trace__c = e.getStackTraceString();
            log.royaltyCheck__c = rcId;
            update log;
            
        }
    }     
    public void finish(Database.batchableContext context){
        ImportLineItemsController.importRecords(contentDocumentId,'Flat', rcId,logId);
        log__c log = new log__c();
        log.Id = logId;
        log.Status__c = 'Complete';
        log.Process__c = 'Delete Royalty Line Items';
        log.OldRoyaltyLineItem__c = OldRoyaltyLineItem;
        update log;
    }
    
    public class applicationException extends Exception {}
}