src/objects/Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/mappingMetadata__c.object
<CustomObject>
    <fields>
        <fullName>key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Metadata</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Mapping Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping Metadata</pluralLabel>
    <recordTypes>
        <fullName>AssociatedWell</fullName>
        <active>true</active>
        <label>AssociatedWell</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Total Check Amount</description>
        <inlineHelpText>Total Check Amount</inlineHelpText>
        <label>Check Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Issue_Date__c</fullName>
        <description>Date Check was Issued</description>
        <inlineHelpText>Date Check was Issued</inlineHelpText>
        <label>Check Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <externalId>true</externalId>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Unique Check Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <description>API/Unique Well Identifier (10 Digit)</description>
        <externalId>true</externalId>
        <inlineHelpText>API/Unique Well Identifier (10 Digit)</inlineHelpText>
        <label>API10</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ImportLineItemsController_Test.cls
@isTest
public class ImportLineItemsController_Test{

    @isTest
    public static void testMethod1(){

        String csvString = 'Check Number,Check Amount,Check Date,Owner Net Value,Price,Property Name,Gross Value,Property Id,Owner Taxes,Line Item Decimal,Gross Volume,Gross Net,Gross Taxes,Type,Owner Volume,Line Item Net Value,Production Month,Product,Deduct Type 1,Gross Deduct 1,Net Deduct 1,Deduct Type 2,Gross Deduct 2,Net Deduct 2 \n';
		csvString += '123,123,01/01/2020,123,123,test,123,123,123,123,123,123,123,R1,123,123,01-09-2018,OIL,R1,123,123,R1,123,123 \n';

        String csvString1 = 'Check Number,Check Amount,Check Date,Owner Net Value,Price,Property Name,Gross Value,Property Id,Owner Taxes,Line Item Decimal,Gross Volume,Gross Net,Gross Taxes,Type,Owner Volume,Line Item Net Value,Production Month,Product,Deduct Type 1,Gross Deduct 1,Net Deduct 1 \n';
		csvString1 += '123,123,01/01/2020,123,123,TestWell,123,123,123,123,123,123,123,R1,123,123,01-09-2018,OIL,R1,123,123,"Test" \n';

        String csvString2 = 'Check Number,Check Amount,Check Date,Owner Net Value,Price,Property Name,Gross Value,Property Id,Owner Taxes,Line Item Decimal,Gross Volume,Gross Net,Gross Taxes,Type,Owner Volume,Line Item Net Value,Production Month,Product,Deduct Type 1,Gross Deduct 1,Net Deduct 1 \n';
		csvString2 += '123,123,01/01/2020,123,123,TestWells,123,123,123,123,123,123,123,R1,123,123,01-09-2018,OIL,R1,123,123,"Test" \n';

        String csvString3 = 'Check Number,Check Amount,Check Date,Price,Property Name,Gross Value,Property Id,Owner Taxes,Line Item Decimal,Gross Volume,Gross Net,Gross Taxes,Type,Owner Volume,Line Item Net Value,Production Month,Product \n';
		csvString3 += '123,123,01/01/2020,123,TestWell,123,123,123,123,123,123,123,R1,123,123,01-09-2018,OIL,"Test" \n';
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.csv';
        cv.VersionData = Blob.valueOf(csvString);
        cv.IsMajorVersion = true;
        Insert  cv;
        
        Log__c log = new Log__c();
        insert log;
              
        
        Well__c wellRec = new Well__c();
        wellRec.Name = 'TestWell';
        wellRec.API10__c ='9501724908';
        insert wellRec;

        wellRec = new Well__c();
        wellRec.Name = 'TestWell';
        wellRec.API10__c ='9501';
        insert wellRec;

        Royalty_Check__c rcRecc= new Royalty_Check__c();
        //rcRecc.Payor__c = 'Test';
        rcRecc.Check_Number__c ='987654321';
        rcRecc.Check_Issue_Date__c = system.today();
        rcRecc.Amount__c = 100;
        rcRecc.Description__c = 'Test #987654321 '+system.today().format()+' $100.00' ;
        insert rcRecc;
		
        mappingMetadata__c mmRec = new mappingMetadata__c();
        mmRec.key__c='TestWell';
        mmRec.value__c='95017324908';
        mmRec.RecordTypeId = Schema.getGlobalDescribe().get('mappingMetadata__c').getDescribe().getRecordTypeInfosByName().get('AssociatedWell').getRecordTypeId();
        insert mmRec;

        mmRec = new mappingMetadata__c();
        mmRec.key__c='TestWells';
        mmRec.value__c='95017324908,9501';
        mmRec.RecordTypeId = Schema.getGlobalDescribe().get('mappingMetadata__c').getDescribe().getRecordTypeInfosByName().get('AssociatedWell').getRecordTypeId();
        insert mmRec;
        
        List<ContentDocument> cd = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        ImportLineItemsController.importRecords(cd[0].Id,'Flat',rcRecc.Id,log.Id);
        ImportLineItemsController.importRecords(cd[0].Id,'Raw',rcRecc.Id,log.Id);
        
        ImportLineItemsController.readCSVFile(csvString1,rcRecc.Id,log.Id);
        ImportLineItemsController.readCSVFile(csvString2,rcRecc.Id,null);
        ImportLineItemsController.readCSVFile(csvString3,rcRecc.Id,null);
    }
}