src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewRoyaltyLineItems__c</fullName>
        <label>New Royalty Line Items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Find Royalty Check</fullName>
                </value>
                <value>
                    <fullName>Delete Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Read Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Insert Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Upsert</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                    <default>true</default>
                    <label>Error</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InserRoyaltyLineItemBatch.cls
/**
    * @description : This class is used to insert RLI records in Batches 
    * @author Jade Tran
    **/
public class InserRoyaltyLineItemBatch implements Database.batchable<sObject>,Database.Stateful{
	public List<Royalty_Line_Item__c> rliList = new List<Royalty_Line_Item__c>();
	public Id logId;  
    public Integer NewRoyaltyLineItems = 0;
    public InserRoyaltyLineItemBatch(List<Royalty_Line_Item__c> rliList,Id logId){
        this.rliList = rliList;
        this.logId = logId;
    }
    
    public Iterable<sObject> start(Database.BatchableContext context){ 
        NewRoyaltyLineItems += rliList.Size();
        return rliList;
    }     
    public void execute(Database.BatchableContext context, List<Royalty_Line_Item__c> scope){ 
        try{
        	insert scope;
        }catch(exception e){
            Log__c log = new Log__c();
            log.id = logId;
            log.Process__c = 'Insert Royalty Line Items';
            log.Status__c = 'Error';
            log.Error_Message__c = e.getMessage();
            log.Stack_Trace__c = e.getStackTraceString();
            update log;
        }
    }     
    public void finish(Database.batchableContext context){
        if(logId!=null){
            Log__c log = new Log__c();
            log.id = logId;
            log.Process__c = 'Insert Royalty Line Items';
            log.Status__c = 'Complete';
            log.NewRoyaltyLineItems__c = NewRoyaltyLineItems;
            update log;
        }
    }
}