src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Find Royalty Check</fullName>
                </value>
                <value>
                    <fullName>Delete Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Read Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Insert Royalty Line Items</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Upsert</fullName>
                </value>
                <value>
                    <fullName>Cdex Check Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                    <default>true</default>
                    <label>Error</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchCreateRoyaltyLineItem.cls
/**
    * @description : This class is used to split each row into a string and then create a RLI instance from that row  
    * @author Jade Tran
    **/
global class BatchCreateRoyaltyLineItem implements Database.batchable<String>,Database.Stateful{
    global String csvString;
    global  string str; 
    global  Boolean isFirstRow = true;
    global String errorStr;
    global Map<Integer,String> NumberFieldMap = new Map<Integer,String>();
    global Map<String,String> fieldConfigMap = new Map<String,String>();
    global ID rcId;
    global Integer propertyNameColumn;
    global LIst<Royalty_Line_Item__c> rliFinalList = new List<Royalty_Line_Item__c>();
    global Id logId; 
    
    global BatchCreateRoyaltyLineItem (String csvString,
                        Map<Integer,String> NumberFieldMap,
                        Map<String,String> fieldConfigMap,
                        ID rcId,Integer propertyNameColumn,Id logId){
                            this.csvString = csvString;
                            this.NumberFieldMap = NumberFieldMap;
                            this.fieldConfigMap = fieldConfigMap;
                            this.rcId = rcId;
                            this.propertyNameColumn = propertyNameColumn;
                            this.logId = logId;
                                
                        }
    
    global Iterable<String> start(Database.batchableContext info){ 
        return new Utility_RowIterator(csvString); 
    }     
    global void execute(Database.batchableContext info, List<String> scope){ 
        List<Royalty_Line_Item__c>  rliList = ImportLineItemsController.getRecords(scope,NumberFieldMap,fieldConfigMap,rcId,propertyNameColumn,logId);
        rliFinalList.addAll(rliList);
    }     
    global void finish(Database.batchableContext info){
        InserRoyaltyLineItemBatch insertRoyaltyLineItem = new InserRoyaltyLineItemBatch(rliFinalList,logId);
        Database.executeBatch(insertRoyaltyLineItem);
        if(logId!=null){
            log__c log = new log__c();
            log.Id = logId;
            log.Status__c = 'Complete';
            log.Process__c = 'Read Royalty Line Items';
            update log;
        }
    } 
}