src/objects/mappingMetadata__c.object
<CustomObject>
    <fields>
        <fullName>key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Metadata</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Mapping Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping Metadata</pluralLabel>
    <recordTypes>
        <fullName>AssociatedAccount</fullName>
        <active>true</active>
        <label>AssociatedAccount</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Total Check Amount</description>
        <inlineHelpText>Total Check Amount</inlineHelpText>
        <label>Check Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Issue_Date__c</fullName>
        <description>Date Check was Issued</description>
        <inlineHelpText>Date Check was Issued</inlineHelpText>
        <label>Check Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <externalId>true</externalId>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Unique Check Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator_Name__c</fullName>
        <description>Name of Operator related to check</description>
        <inlineHelpText>Name of Operator related to check</inlineHelpText>
        <label>Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payee_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Royalty Checks</relationshipLabel>
        <relationshipName>Royalty_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payee_from_Source_File__c</fullName>
        <description>Payee from imported source file</description>
        <inlineHelpText>Payee from imported source file</inlineHelpText>
        <label>Payee from Source File</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payor_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Royalty Checks (Payor)</relationshipLabel>
        <relationshipName>Royalty_Checks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payor_from_Source_File__c</fullName>
        <description>Payor from source import file.</description>
        <inlineHelpText>Payor from source import file.</inlineHelpText>
        <label>Payor from Source File</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSV</fullName>
                </value>
                <value>
                    <fullName>CDEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>operatorCheckNumberKey__c</fullName>
        <description>This field stores a unique value of Operator name and Check Number combination</description>
        <label>Operator Check Number Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/RoyaltyCheckTriggerHandler.cls
public class RoyaltyCheckTriggerHandler{

    public static void updateCheckInfo(List<Royalty_Check__c> newList){
        
        Map<Id,String> accMap = new Map<Id,String>();
        Set<Id> accId= new Set<id>();
        for(Royalty_Check__c  rcRec : newList){
            accId.add(rcRec.Payor_Lookup__c);
        }
        for(Account accRec:[Select Id, name From Account Where id In: accId]){
            accMap.put(accRec.Id, accRec.Name);
        }
        for(Royalty_Check__c  rcRec : newList){
            String payorStr = accMap.get(rcRec.Payor_Lookup__c)==null?'':accMap.get(rcRec.Payor_Lookup__c);
            rcRec.Description__c = payorStr+' #'+rcRec.Check_Number__c+' '+rcRec.Check_Issue_Date__c.format()+' $' + String.valueOf(rcRec.Amount__c);
            
            rcRec.operatorCheckNumberKey__c = accMap.get(rcRec.Payor_Lookup__c)+' #'+rcRec.Check_Number__c;
            if(rcRec.Operator_Name__c==null){
                rcRec.Operator_Name__c = accMap.get(rcRec.Payor_Lookup__c);
            }
        }
    }

    public static void UpdatePayorNPayee(List<Royalty_Check__c> newList){
        Id recTypeId = Schema.getGlobalDescribe().get('mappingMetadata__c').getDescribe().getRecordTypeInfosByName().get('AssociatedAccount').getRecordTypeId();
        Map<String,String> accountMapping = new Map<String,String>();
        for(mappingMetadata__c mapRec : [Select Id,key__c,value__c from mappingMetadata__c where RecordTypeId =: recTypeId]){
            accountMapping.put(mapRec.key__c,mapRec.value__c);
        }

        for(Royalty_Check__c  rcRec : newList){
            if(rcRec.Source__c == 'CDEX'){
                if(accountMapping.containsKey(rcRec.Payee_from_Source_File__c)){
                    rcRec.Payee_Lookup__c = accountMapping.get(rcRec.Payee_from_Source_File__c);
                }
                if(accountMapping.containsKey(rcRec.Payor_from_Source_File__c)){
                    rcRec.Payor_Lookup__c = accountMapping.get(rcRec.Payor_from_Source_File__c);
                }
            }
        }
    }

    public static void updateAccountMapping(List<Royalty_Check__c> newList,Map<Id,Royalty_Check__c> oldMap){
        
        Map<String,String> accountMapping = new Map<String,String>();

        for(Royalty_Check__c  rcRec : newList){
            if(rcRec.Source__c == 'CDEX'){
                if(rcRec.Payee_Lookup__c != oldMap.get(rcRec.Id).Payee_Lookup__c && 
                    String.isNotBlank(rcRec.Payee_from_Source_File__c) && rcRec.Payee_Lookup__c!=null){
                    
                    accountMapping.put( rcRec.Payee_from_Source_File__c,rcRec.Payee_Lookup__c);
                }if(rcRec.Payor_Lookup__c != oldMap.get(rcRec.Id).Payor_Lookup__c && 
                    String.isNotBlank(rcRec.Payor_from_Source_File__c) && rcRec.Payor_Lookup__c!=null){
                    
                    accountMapping.put( rcRec.Payor_from_Source_File__c,rcRec.Payor_Lookup__c);
                }
            }
        }

        List<mappingMetadata__c> mppList = new List<mappingMetadata__c>();
        Id recTypeId = Schema.getGlobalDescribe().get('mappingMetadata__c').getDescribe().getRecordTypeInfosByName().get('AssociatedAccount').getRecordTypeId();
        for(mappingMetadata__c mapRec : [Select Id,key__c,value__c from mappingMetadata__c where RecordTypeId =: recTypeId AND key__c IN: accountMapping.keySet()]){
            mapRec.value__c = accountMapping.get(mapRec.key__c);
            mppList.add(mapRec);
            accountMapping.remove(mapRec.key__c);
        }

        for(String key: accountMapping.keySet()){
            mppList.add(new mappingMetadata__c(key__c=key,value__c=accountMapping.get(key),RecordTypeId=recTypeId));
        }
        upsert mppList;
    }
}