src/objects/mappingMetadata__c.object
<CustomObject>
    <fields>
        <fullName>key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Metadata</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Mapping Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping Metadata</pluralLabel>
    <recordTypes>
        <fullName>AssociatedAccount</fullName>
        <active>true</active>
        <label>AssociatedAccount</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/revenueProperty__c.object
<CustomObject>
    <fields>
        <fullName>api10__c</fullName>
        <description>This field stores a set of API10 values which are associated to the property name.</description>
        <label>API10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Revenue Property</label>
    <nameField>
        <displayFormat>Revenue Property-{00000}</displayFormat>
        <label>Revenue Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Total Check Amount</description>
        <inlineHelpText>Total Check Amount</inlineHelpText>
        <label>Check Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Issue_Date__c</fullName>
        <description>Date Check was Issued</description>
        <inlineHelpText>Date Check was Issued</inlineHelpText>
        <label>Check Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payee_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Royalty Checks</relationshipLabel>
        <relationshipName>Royalty_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payee_from_Source_File__c</fullName>
        <description>Payee from imported source file</description>
        <inlineHelpText>Payee from imported source file</inlineHelpText>
        <label>Payee from Source File</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payor_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Royalty Checks (Payor)</relationshipLabel>
        <relationshipName>Royalty_Checks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payor_from_Source_File__c</fullName>
        <description>Payor from source import file.</description>
        <inlineHelpText>Payor from source import file.</inlineHelpText>
        <label>Payor from Source File</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSV</fullName>
                </value>
                <value>
                    <fullName>CDEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>ownerNetValueActual__c</fullName>
        <label>Owner Net Value Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <externalId>true</externalId>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>revenueProperty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Property</label>
        <referenceTo>revenueProperty__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>royalty_Check__c</fullName>
        <description>Royalty Check</description>
        <label>Royalty Check</label>
        <referenceTo>Royalty_Check__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>source__c</fullName>
        <formula>TEXT(royalty_Check__r.Source__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>well__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Well (Discarded)</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Royalty Line Items (Well)</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <description>API/Unique Well Identifier (10 Digit)</description>
        <externalId>true</externalId>
        <inlineHelpText>API/Unique Well Identifier (10 Digit)</inlineHelpText>
        <label>API10</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <inlineHelpText>Source of the well information (IHS, DrillingInfo, etc.)</inlineHelpText>
        <label>Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/RoyaltyLineItemController_Test.cls
@istest
public class RoyaltyLineItemController_Test {
    
    @isTest
    public static void testmethod1(){
        List<Account> acc = TestDataFactory.createAccounts(1);
        insert acc;
        
        
        Royalty_Check__c rcRec = new Royalty_Check__c();
        rcRec.Amount__c = 100;
        rcRec.Check_Issue_Date__c = system.today();
        rcRec.Payor_Lookup__c = acc[0].Id;
        insert rcRec;
        
        RoyaltyLineItemController.getRecords(rcRec.Id,10,1,'Name','asc');
    }
    @isTest
    public static void testmethod2(){
        List<Account> acc = TestDataFactory.createAccounts(1);
        insert acc;
        
        
        Royalty_Check__c rcRec = new Royalty_Check__c();
        rcRec.Amount__c = 100;
        rcRec.Check_Issue_Date__c = system.today();
        rcRec.Payor_Lookup__c = acc[0].Id;
        insert rcRec;
        
        Royalty_Line_Item__c rli = new Royalty_line_item__c();
        rli.Royalty_Check__c= rcRec.id;   
        rli.propertyName__c='test';
        insert rli;
        RoyaltyLineItemController.getRecordsForAssociation(rcRec.Id);
    }
    @isTest
    public static void testmethod3(){
        List<Account> acc = TestDataFactory.createAccounts(1);
        insert acc;
        
        
        Royalty_Check__c rcRec = new Royalty_Check__c();
        rcRec.Amount__c = 100;
        rcRec.Check_Issue_Date__c = system.today();
        rcRec.Payor_Lookup__c = acc[0].Id;
        insert rcRec;
        
        Royalty_Line_Item__c rli = new Royalty_line_item__c();
        rli.Royalty_Check__c= rcRec.id;   
        rli.propertyName__c='test';
        insert rli;
        RoyaltyLineItemController.getSearchResults('test');
    }
    
    
    
    @isTest
    public static void testmethod4(){
        List<Account> acc = TestDataFactory.createAccounts(1);
        insert acc;
        
        
        Royalty_Check__c rcRec = new Royalty_Check__c();
        rcRec.Amount__c = 100;
        rcRec.Check_Issue_Date__c = system.today();
        rcRec.Payor_Lookup__c = acc[0].Id;
        insert rcRec;
        
        Royalty_Line_Item__c rli = new Royalty_line_item__c();
        rli.Royalty_Check__c= rcRec.id;   
        rli.propertyName__c='test';
        rli.ownerNetValueActual__c=0.45;
        insert rli;
        List<String> rliIds = new List<String>();
        rliIds.add(rli.id);
        
        Well__c wellRec = new Well__c();
        wellRec.Name = 'TestWell';
        wellRec.API10__c ='9501724908';
        insert wellRec;
        List<String> wellIds = new List<String>();
        wellIds.add(wellRec.id);
        // RoyaltyLineItemController.associateWells(wellIds,'Test', rliIds,false);
        Well__c wellRec1 = new Well__c();
        wellRec1.Name = 'TestWell1';
        wellRec1.API10__c ='950249081';
        insert wellRec1;
        wellIds.add(wellRec1.id);
        // RoyaltyLineItemController.associateWells(wellIds,'Test', rliIds,false);
    }
    @isTest
    public static void testmethod5(){
        List<Account> acc = TestDataFactory.createAccounts(1);
        insert acc;
        
        
        Royalty_Check__c rcRec = new Royalty_Check__c();
        rcRec.Amount__c = 100;
        rcRec.Check_Issue_Date__c = system.today();
        rcRec.Payor_Lookup__c = acc[0].Id;
        insert rcRec;
        
        Royalty_Line_Item__c rli = new Royalty_line_item__c();
        rli.Royalty_Check__c= rcRec.id;   
        rli.propertyName__c='test';
        insert rli;
        List<String> rliIds = new List<String>();
        rliIds.add(rli.Id);
        RoyaltyLineItemController.getRLIData(rliIds);
        
    }
    
    @isTest
    public static void testmethod6(){
        Id recTypeId = Schema.getGlobalDescribe().get('mappingMetadata__c').getDescribe().getRecordTypeInfosByName().get('AssociatedAccount').getRecordTypeId();
        mappingMetadata__c mM = new mappingMetadata__c(RecordTypeId = recTypeId, key__c = 'testkey');
        insert mM;
        List<Royalty_Check__c> rcRecLst = new List<Royalty_Check__c>();
        List<Account> acc = TestDataFactory.createAccounts(1);
        insert acc;

        Royalty_Check__c rcRec = new Royalty_Check__c();
        rcRec.Amount__c = 100;
        rcRec.Check_Issue_Date__c = system.today();
        rcRec.Payor_Lookup__c = acc[0].Id;
        rcRec.Source__c = 'CDEX';
        rcRec.Payee_from_Source_File__c = 'testkey';
        rcRec.Payor_from_Source_File__c = 'testkey';
        insert rcRec;
        rcRecLst.add(rcRec);
        
        RoyaltyCheckTriggerHandler.UpdatePayorNPayee(rcRecLst);
    }
    
    @isTest
    public static void testmethod7(){
        List<Royalty_Check__c> newRCRecLst = new List<Royalty_Check__c>();
        Map<Id,Royalty_Check__c> oldRCRecMap = new Map<Id,Royalty_Check__c>();
        List<Account> acc = TestDataFactory.createAccounts(2);
        insert acc;

        Royalty_Check__c rcRecNew = new Royalty_Check__c();
        rcRecNew.Amount__c = 100;
        rcRecNew.Check_Issue_Date__c = system.today();
        rcRecNew.Payor_Lookup__c = acc[0].Id;
        rcRecNew.Payee_Lookup__c = acc[1].Id;
        rcRecNew.Source__c = 'CDEX';
        rcRecNew.Payee_from_Source_File__c = 'testkey';
        rcRecNew.Payor_from_Source_File__c = 'testkey';
        insert rcRecNew;
        rcRecNew.Payor_Lookup__c = acc[1].Id;
        rcRecNew.Payee_Lookup__c = acc[0].Id;
        update rcRecNew;
    }
    
    @isTest
    public static void testmethod8(){
        List<Account> acc = TestDataFactory.createAccounts(1);
        insert acc;
        
        Royalty_Check__c rcRec = new Royalty_Check__c();
        rcRec.Amount__c = 100;
        rcRec.Check_Issue_Date__c = system.today();
        rcRec.Payor_Lookup__c = acc[0].Id;
        rcRec.Source__c = 'CDEX';
        insert rcRec;

        Royalty_line_item__c rli = new Royalty_line_item__c(royalty_Check__c = rcRec.Id);
        insert rli;
        
        RoyaltyLineItemController.deleteLineItem(rli.Id);
    }
    
        @isTest
    public static void testmethod9(){
        List<Account> acc = TestDataFactory.createAccounts(1);
        insert acc;
        
        Royalty_Check__c rcRec = new Royalty_Check__c();
        rcRec.Amount__c = 100;
        rcRec.Check_Issue_Date__c = system.today();
        rcRec.Payor_Lookup__c = acc[0].Id;
        insert rcRec;
        
        Royalty_Line_Item__c rli = new Royalty_line_item__c();
        rli.Royalty_Check__c= rcRec.id;   
        rli.propertyName__c='test';
        rli.ownerNetValueActual__c=0.45;
        insert rli;
        List<String> rliIds = new List<String>();
        rliIds.add(rli.id);
        
        Well__c wellRec = new Well__c();
        wellRec.Name = 'TestWell';
        wellRec.API10__c ='9501724908';
        insert wellRec;
        List<String> wellIds = new List<String>();
        wellIds.add(wellRec.id);
        // RoyaltyLineItemController.associateWells(wellIds,'Test', rliIds,false);
        Well__c wellRec1 = new Well__c();
        wellRec1.Name = 'TestWell1';
        wellRec1.API10__c ='950249081';
        insert wellRec1;
        wellIds.add(wellRec1.id);
        // RoyaltyLineItemController.associateWells(wellIds,'Test', rliIds,false);
        
        revenueProperty__c revProp = new revenueProperty__c();
        insert revProp;
        
        RoyaltyLineItemController.associateWells(wellIds, String.valueOf(revProp.Id), rliIds, false); 
        RoyaltyLineItemController.associateWells(wellIds, String.valueOf(revProp.Id), rliIds, true);
    }
	@isTest
    public static void testmethod10(){
        List<Account> acc = TestDataFactory.createAccounts(1);
        insert acc;
        
        
        Royalty_Check__c rcRec = new Royalty_Check__c();
        rcRec.Amount__c = 100;
        rcRec.Check_Issue_Date__c = system.today();
        rcRec.Payor_Lookup__c = acc[0].Id;
        insert rcRec;
        
        RoyaltyLineItemController.getFilteredRecords(rcRec.Id,10,1,'Name','asc', 'LI', 1);
    }
	
}