src/objects/Monthly_Production__c.object
<CustomObject>
    <fields>
        <fullName>Well__c</fullName>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000000}</displayFormat>
        <label>Monthly Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MonthlyProductionTriggerHelper.cls
public class MonthlyProductionTriggerHelper{


    
    public static void createOwnerInterestRevenue(List<Monthly_Production__c> newRecords){
        
        Map<Id,Id> mpUnitMap = new Map<Id,Id>();
        for(Monthly_Production__c mpRec : [Select id, Well__r.Unit__c from Monthly_Production__c where Id In: newRecords]){
            mpUnitMap.put(mpRec.Id,mpRec.Well__r.Unit__c);
        }
        
        if(mpUnitMap.size()>0){
            createOwnerInterestRevenueBatch oirBatch = new createOwnerInterestRevenueBatch('Monthly_Production__c',mpUnitMap);
            Database.executeBatch(oirBatch,50);
        }
    }
}