src/objects/Monthly_Production__c.object
<CustomObject>
    <fields>
        <fullName>Production_Date__c</fullName>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Well__c</fullName>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000000}</displayFormat>
        <label>Monthly Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/revenueEstimate__c.object
<CustomObject>
    <fields>
        <fullName>monthlyProduction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Production</label>
        <referenceTo>Monthly_Production__c</referenceTo>
        <relationshipName>Owner_Interest_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>unitAllocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Allocation</label>
        <referenceTo>unitAllocation__c</referenceTo>
        <relationshipLabel>Revenue Estimates</relationshipLabel>
        <relationshipName>Owner_Interest_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Estimate</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>RevenueEstimate  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/unitAllocation__c.object
<CustomObject>
    <description>Contains the subtracts in a unit and the associated percent allocation for each subtract</description>
    <fields>
        <fullName>subtract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subtract</label>
        <referenceTo>Subtract__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Unit Allocation</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Unit Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/createOwnerInterestRevenueBatch.cls
global class createOwnerInterestRevenueBatch implements Database.Batchable<sObject>{
    
    global final String Query;
    global static boolean updateWellInterestRevenue = true;
    global string objectName;
    global Map<Id,Id> objectUnitMap ;
    global Set<id> unitIds = new Set<Id>();
    global date dt = system.Today().addMonths(-6);
    global createOwnerInterestRevenueBatch(String objectName,Map<Id,Id> objectUnitMap){
        this.objectName = objectName;
        this.objectUnitMap = new Map<Id,Id>();
        this.objectUnitMap = objectUnitMap;
        
        for(Id uId : objectUnitMap.values()){
            this.unitIds.add(uId);
        }
        if(objectName == 'unitAllocation__c'){
            
            Query='Select Id,well__r.Unit__c From monthly_Production__c Where well__r.Unit__c In: unitIds  and   Production_Date__c >=: dt';
        }else if(objectName == 'Monthly_Production__c'){
            Query='Select Id,unit__c from unitAllocation__c where unit__c In: unitIds AND subtract__r.Tract__r.Instrument_Type__c != \'OGL\' AND subtract__r.Tract__r.Instrument_Type__c != \'Surface\'';
        }else{ 
            Query='Select Id,unit__c from unitAllocation__c where oirCount__c = 0';
        }
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, 
                        List<sObject> scope){
                            revenueEstimate__c oirRec;
                            List<revenueEstimate__c> oirList = new List<revenueEstimate__c>();
                            
                            if(objectName =='Monthly_Production__c' ){
                                for(unitAllocation__c suaRec: (List<unitAllocation__c>)scope){   
                                    for(Id mpRecId : objectUnitMap.keySet()){
                                        if(objectUnitMap.get(mpRecId)==suaRec.unit__c){
                                            oirRec = new revenueEstimate__c();
                                            oirRec.unitAllocation__c = suaRec.Id;
                                            oirRec.MonthlyProduction__c = mpRecId;
                                            oirList.add(oirRec);
                                        }
                                    }
                                }
                            }else if(objectName =='unitAllocation__c' ){
                                for(Monthly_Production__c mpRec: (List<Monthly_Production__c>)scope){   
                                    for(Id suaRecId : objectUnitMap.keySet()){
                                        if(objectUnitMap.get(suaRecId)==mpRec.Well__r.Unit__c){
                                            oirRec = new revenueEstimate__c();
                                            oirRec.unitAllocation__c = suaRecId;
                                            oirRec.MonthlyProduction__c = mpRec.Id;
                                            oirList.add(oirRec);
                                        }
                                    }
                                }
                            }
                            
                            if(!oirList.isEmpty()){
                                insert oirList;
                            } 

                        }
    
    global void finish(Database.BatchableContext BC){
        //do nothing
    }
    
}