src/objects/Monthly_Production__c.object
<CustomObject>
    <fields>
        <fullName>Well__c</fullName>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000000}</displayFormat>
        <label>Monthly Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/revenueEstimate__c.object
<CustomObject>
    <fields>
        <fullName>InactiveNotes__c</fullName>
        <description>Reason for RE being Inactive</description>
        <label>Inactive Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <label>Revenue Estimate</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>RevenueEstimate  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/createDeleteRevenueEstimatesBatch.cls
global class createDeleteRevenueEstimatesBatch implements Database.Batchable<sObject>,Database.Stateful{
    
    global String query;
    global String operation;
    global Set<Id> objectIds;
    global Map<Id,Id> wellUnitMap;
    global String processType;
    
    global createDeleteRevenueEstimatesBatch(String operation,String processType,Set<Id> objectIds,String query,Map<Id,Id> wellUnitMap){
        
        this.query = query;
        this.operation = operation;
        this.objectIds = objectIds;
        this.wellUnitMap = wellUnitMap;
        this.processType = processType;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC,List<sObject> scope){
        
        if(operation=='delete'){
            for(revenueEstimate__c rev : (List<revenueEstimate__c>)scope){
                rev.inactive__c = true;
                rev.inactiveNotes__c = 'Revenue Estimate Reprocessed: '+processType;
            }
            update scope;
        }else if(operation=='insert'){
            insert reprocessRevenueEstimatesController.createRevenueEstimates((List<Monthly_Production__c>)scope);
        }
    }
    
    global void finish(Database.BatchableContext BC){
        if(operation=='delete'){
            String queryStr = 'Select Id,well__c,well__r.unit__c from Monthly_Production__c where well__c In:objectIds';
            createDeleteRevenueEstimatesBatch insertJob = new createDeleteRevenueEstimatesBatch('insert',processType,wellUnitMap.keySet(),queryStr,wellUnitMap);
            database.executeBatch(insertJob,5);
        }
    }
    
}