src/objects/Monthly_Production__c.object
<CustomObject>
    <fields>
        <fullName>Well__c</fullName>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000000}</displayFormat>
        <label>Monthly Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/revenueEstimate__c.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isUnitSame__c</fullName>
        <formula>If( monthlyProduction__r.Well__r.Unit__c =  unitAllocation__r.unit__c ,true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isUnitSame</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>monthlyProduction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Production</label>
        <referenceTo>Monthly_Production__c</referenceTo>
        <relationshipName>Owner_Interest_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Estimate</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>RevenueEstimate  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/reprocessRevenueEstimatesBatch.cls
global class reprocessRevenueEstimatesBatch implements Database.Batchable<sObject>,Database.Stateful{
    
    global String query;
    global String operation;
    global Set<Id> objectIds;
    global Map<Id,Id> wellUnitMap = new Map<Id,Id>();
    global date dt = system.today().addMonths(-6);
    
    
    global reprocessRevenueEstimatesBatch(String operation){
        this.operation = operation;
        if(operation =='reprocessMismatchRE'){
            this.query = 'Select Id,Monthlyproduction__r.well__c,Monthlyproduction__r.well__r.unit__c from revenueEstimate__c where isUnitSame__c = false AND inactive__c = false';
        }else if(operation =='createMissingRE'){
             this.query = 'Select Id,Well__c,Well__r.Unit__c from Monthly_Production__c where Id Not In (Select monthlyProduction__c from revenueEstimate__c Where inactive__c = false)';
        }
    } 
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC,List<sObject> scope){
        if(operation =='reprocessMismatchRE'){
            for(revenueEstimate__c reRec:(List<revenueEstimate__c>)scope){
                wellUnitMap.put(reRec.Monthlyproduction__r.well__c,reRec.Monthlyproduction__r.well__r.unit__c);
            }
        }else if(operation =='createMissingRE'){
            insert reprocessRevenueEstimatesController.createRevenueEstimates((List<Monthly_Production__c>)scope);
        }
    }
    
    global void finish(Database.BatchableContext BC){
        if(operation =='reprocessMismatchRE'){
            String query = 'Select Id from revenueEstimate__c where monthlyProduction__r.well__c In:objectIds AND Inactive__c = false';
            Set<Id> objectIds = wellUnitMap.keySet();
            createDeleteRevenueEstimatesBatch deleteJob = new createDeleteRevenueEstimatesBatch('delete',operation,objectIds,query,wellUnitMap);
            database.executeBatch(deleteJob);
        }
    }
    
}