src/objects/Monthly_Production__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <formula>Well__r.API10__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>API10</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <description>Unique key built with API10 and Production Date</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique key built with API10 and Production Date</inlineHelpText>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Well__c</fullName>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000000}</displayFormat>
        <label>Monthly Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <description>API/Unique Well Identifier (10 Digit)</description>
        <externalId>true</externalId>
        <inlineHelpText>API/Unique Well Identifier (10 Digit)</inlineHelpText>
        <label>API10</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/MonthlyProductionTriggerHandlerTest.cls
@isTest
public with sharing class MonthlyProductionTriggerHandlerTest {


    static testMethod void testTrigger() {
        
        Well__c wellRec = new Well__c();
        wellRec.Name = 'TestWell';
        wellRec.API10__c ='9501724908';
        insert wellRec;

        Test.startTest();
        Monthly_Production__c mpRec = new Monthly_Production__c();
        mpRec.Unique_Key__c = wellRec.API10__c+'.'+system.today().format();
        mpRec.Production_Date__c = system.today();
        mpRec.Well__c = wellRec.Id;
        Insert mpRec;
        Test.stopTest();     
    }
}