src/objects/Monthly_Production__c.object
<CustomObject>
    <fields>
        <fullName>Well__c</fullName>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000000}</displayFormat>
        <label>Monthly Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/revenueEstimate__c.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owner_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Revenue Estimates</relationshipLabel>
        <relationshipName>Revenue_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SRP_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SRP Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>excludeFromSRPRevenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude from SRP Revenue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>monthlyProduction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Production</label>
        <referenceTo>Monthly_Production__c</referenceTo>
        <relationshipName>Owner_Interest_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ownerNetRevenueValueGas__c</fullName>
        <formula>/*monthlyProduction__r.Well_Net_Revenue_Value_Gas__c * unitAllocation__r.unitNRI__c*/
monthlyProduction__r.Well_Net_Revenue_Value_Gas__c * unitAllocation__r.uaNRI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Net Revenue Value Gas</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ownerNetRevenueValueOil__c</fullName>
        <formula>/*monthlyProduction__r.Well_Net_Revenue_Value_Oil__c* unitAllocation__r.unitNRI__c*/
monthlyProduction__r.Well_Net_Revenue_Value_Oil__c* unitAllocation__r.uaNRI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Net Revenue Value Oil</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ownerNetRevenueValue__c</fullName>
        <formula>/*monthlyProduction__r.Well_Net_Revenue_Value__c * unitAllocation__r.unitNRI__c*/
monthlyProduction__r.Well_Net_Revenue_Value__c * unitAllocation__r.uaNRI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Net Revenue Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>productionMonth__c</fullName>
        <formula>monthlyProduction__r.Production_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Production Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>unitAllocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Allocation</label>
        <referenceTo>unitAllocation__c</referenceTo>
        <relationshipLabel>Revenue Estimates</relationshipLabel>
        <relationshipName>Owner_Interest_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>wellInterestAllocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Well Interest Allocation</label>
        <referenceTo>wellInterestAllocation__c</referenceTo>
        <relationshipLabel>Revenue Estimates</relationshipLabel>
        <relationshipName>Revenue_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Estimate</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>RevenueEstimate  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/unitAllocation__c.object
<CustomObject>
    <description>Contains the subtracts in a unit and the associated percent allocation for each subtract</description>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Unit Allocation</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Unit Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/wellInterestAllocation__c.object
<CustomObject>
    <fields>
        <fullName>UniqueId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>UniqueId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>unitAllocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Allocation</label>
        <referenceTo>unitAllocation__c</referenceTo>
        <relationshipLabel>Well Interest Allocation</relationshipLabel>
        <relationshipName>Well_Interest_Allocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>well__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Well Interest Allocation</relationshipLabel>
        <relationshipName>Well_Interest_Allocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well Interest Allocation</label>
    <nameField>
        <displayFormat>WIA-{000000}</displayFormat>
        <label>Well interest Allocation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Well Interest Allocation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OwnerInterestRevenueController.cls
public class OwnerInterestRevenueController {
	/**
    * @description : Method referred by OIRRelatedList Aura Component
    * @author : Jade Tran
    * @param recordId , uaId
    * @return OIRWrapper 
    **/
    
	@AuraEnabled
    public static OIRWrapper getRecords(Id recordId, Id uaId){
        List<revenueEstimate__c> oirList = new List<revenueEstimate__c>();
        OIRWrapper sWrap = new OIRWrapper();
		
        sWrap.excludedSrpRevenue = false;
        sWrap.sObjectName = recordId.getSObjectType().getDescribe().getName();
        sWrap.oirList  = oirList;
        
        //return list of OIR realted to specific Well and ua record
        oirList = [Select Name,productionMonth__c,SRP_Owned__c,ownerNetRevenueValueGas__c,ownerNetRevenueValueOil__c,
        ownerNetRevenueValue__c,Owner_Entity__c,Owner_Entity__r.Name from revenueEstimate__c 
        where monthlyProduction__r.Well__c =: recordId AND unitAllocation__c =: uaId
        AND inactive__c = false];
        
        List<wellInterestAllocation__c> wia = new List< wellInterestAllocation__c>();
        for(wellInterestAllocation__c wiaRec : [Select Id from wellInterestAllocation__c where unitAllocation__c=:uaId
                                             AND well__c =:recordId Limit 1]){
                                                 wia.add(wiaRec);
                                             }
        
        if(wia.size()>0){
            sWrap.excludedSrpRevenue = true;
            swrap.wellInterestAllocation = wia[0].Id;
        }else{
            //Get Sum of Owner Net Revenue of OIRs realted to specific Well and ua record and SRP owned = true
            AggregateResult[] groupedResults = [SELECT SUM(ownerNetRevenueValue__c) from revenueEstimate__c 
                    where monthlyProduction__r.Well__c =: recordId AND unitAllocation__c =: uaId
                    AND SRP_Owned__c = true AND inactive__c = false];
            for (AggregateResult ar : groupedResults)  {
                sWrap.ownerNetRevenueValue = Double.valueOf(ar.get('expr0'));
            }
            sWrap.excludedSrpRevenue = false;
            sWrap.oirList  = oirList;
        }
        return sWrap;
    }

    /**
    * @description : Method referred by OIRRelatedList Aura Component
    * @author : Jade Tran
    * @param Id recordId, uaId, excludedRevenue
    * @return List<well__c> 
    **/
    @AuraEnabled
    public static void saveExcludedRevenue(Id recordId, Id uaId, String excludedRevenue){
        List<revenueEstimate__c> oirList = new List<revenueEstimate__c>();
        OIRWrapper sWrap = new OIRWrapper();

        //return list of OIR that needs to be excluded from SRP Revenue
        if (excludedRevenue == 'true'){
            
            wellInterestAllocation__c wia= new wellInterestAllocation__c();
            wia.unitAllocation__c = uaId;
            wia.well__c = recordId;
            wia.UniqueId__c =  String.valueOf(wia.unitAllocation__c) + String.valueof(wia.well__c);
            insert wia;
            
            oirList = [Select Name,productionMonth__c,SRP_Owned__c,ownerNetRevenueValueGas__c,ownerNetRevenueValueOil__c,
            ownerNetRevenueValue__c,Owner_Entity__c,Owner_Entity__r.Name from revenueEstimate__c 
            where monthlyProduction__r.Well__c =: recordId AND unitAllocation__c =: uaId
            AND Inactive__c = false];
             
            for(revenueEstimate__c revRec:oirList){
                revRec.Inactive__c = true;
                revRec.excludeFromSRPRevenue__c = true;
                revRec.wellInterestAllocation__c = wia.Id;
            } 

            update oirList;

        } else{
            wellInterestAllocation__c wia = [Select Id from wellInterestAllocation__c where unitAllocation__c=:uaId
                                        AND well__c =:recordId];
            if(wia!=null){
                delete wia;
            }
            oirList = [Select Name,productionMonth__c,SRP_Owned__c,ownerNetRevenueValueGas__c,ownerNetRevenueValueOil__c,
            ownerNetRevenueValue__c,Owner_Entity__c,Owner_Entity__r.Name from revenueEstimate__c 
            where monthlyProduction__r.Well__c =: recordId AND unitAllocation__c =: uaId
            AND excludeFromSRPRevenue__c = true];
			
            for(revenueEstimate__c revRec:oirList){
                revRec.Inactive__c = false;
                revRec.excludeFromSRPRevenue__c = false;
                revRec.wellInterestAllocation__c = null;
            } 

            update oirList;
        } 
     }
    
    /**
    * @description : Method referred by oirWithWellAccordion Aura Component
    * @author : Jade Tran
    * @param Id recordId
    * @return List<well__c> 
    **/
	@AuraEnabled
    public static List<WellWrapper> getWells(Id recordId){
        
        List<WellWrapper> wellWrapList = new List<WellWrapper>();
        WellWrapper wellWrap;
        //query to get the unit related to ua
        unitAllocation__c ua = [Select Id, unit__c, Inactive__c from unitAllocation__c where Id =: recordId limit 1];
        
        Map<String,Integer> wellOirCountMap = new Map<String,Integer>();
        Integer count = 0;
        for(Well__c well : [Select Id, Name from well__c where unit__c =: ua.unit__c]){
            count = 0;
            for(AggregateResult ar:[SELECT count(Id) from revenueEstimate__c
                            Where monthlyProduction__r.well__c =: well.Id and unitAllocation__c =: recordId
                            AND inactive__c = false]){
                            
                count=Integer.valueOf(ar.get('expr0'));
            }
            wellWrap = new WellWrapper();
            wellWrap.wellName = well.Name;
            wellWrap.wellId = well.Id;
            wellWrap.inactive = ua.Inactive__c;
            wellWrap.oirCount = count;
            wellWrapList.add(wellWrap);
        }
        
        
        //Get all Well records realted to ua's Unit
        //List<Well__c> wellList = [Select Id, Name from well__c where unit__c =: ua.unit__c];
        return wellWrapList;
    }

    @AuraEnabled
    public static void excludeRevenueEstimate(List<revenueEstimate__c> oirList, Boolean excludedRevenue){
        for(revenueEstimate__c revRec : oirList){
            revRec.excludeFromSRPRevenue__c = excludedRevenue;
        }
        update oirList;
    }

	public class OIRWrapper{
        @AuraEnabled
        public List<revenueEstimate__c> oirList{get;set;}
        @AuraEnabled
        public string sObjectName{get;set;}
        @AuraEnabled
        public double ownerNetRevenueValue{get;set;}
        @AuraEnabled
        public Id wellInterestAllocation{get;set;}
		@AuraEnabled
        public Boolean excludedSrpRevenue{get;set;}
       
    }
    public class WellWrapper{
        @AuraEnabled
        public String wellName{get;set;}
        @AuraEnabled
        public String wellId{get;set;}
        @AuraEnabled
        public Integer oirCount{get;set;}
        @AuraEnabled
        public Boolean inactive{get;set;}
    }
    
    
}