src/objects/Monthly_Production__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <formula>Well__r.API10__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>API10</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Operator_Name__c</fullName>
        <label>Current Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <description>Unique key built with API10 and Production Date</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique key built with API10 and Production Date</inlineHelpText>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Well__c</fullName>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000000}</displayFormat>
        <label>Monthly Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/unitAllocation__c.object
<CustomObject>
    <description>Contains the subtracts in a unit and the associated percent allocation for each subtract</description>
    <fields>
        <fullName>subtract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subtract</label>
        <referenceTo>Subtract__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Unit Allocation</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Unit Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <description>API/Unique Well Identifier (10 Digit)</description>
        <externalId>true</externalId>
        <inlineHelpText>API/Unique Well Identifier (10 Digit)</inlineHelpText>
        <label>API10</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Current_Operator_Name__c</fullName>
        <label>Current Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hole_Direction__c</fullName>
        <label>Hole Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vertical</fullName>
                </value>
                <value>
                    <fullName>Directional</fullName>
                </value>
                <value>
                    <fullName>HORIZONTAL</fullName>
                    <label>Horizontal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Permit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Returns True if the record is a Well Permit only.  Calculated in GIS Database.</description>
        <inlineHelpText>Returns True if the record is a Well Permit only.  Calculated in GIS Database.</inlineHelpText>
        <label>Is Permit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Activity_Date__c</fullName>
        <description>Most recent Permit or Spud date - type of activity will be specified in the Last Activity Type field.  Calculated by GIS database.</description>
        <inlineHelpText>Most recent Permit or Spud date - type of activity will be specified in the Last Activity Type field.  Calculated by GIS database.</inlineHelpText>
        <label>Last Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Activity_Type__c</fullName>
        <description>Type of activity for Last Activity Date field.  Calculated by GIS database.</description>
        <inlineHelpText>Type of activity for Last Activity Date field.  Calculated by GIS database.</inlineHelpText>
        <label>Last Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Permit</fullName>
                </value>
                <value>
                    <fullName>Spud</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Production_Date__c</fullName>
        <description>Date of the last Monthly Production record.  Calculated by GIS database.</description>
        <inlineHelpText>Date of the last Monthly Production record.  Calculated by GIS database.</inlineHelpText>
        <label>Last Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/WellUnitUtil_Test.cls
@isTest
public class WellUnitUtil_Test{

    @TestSetup
    private static void makeData(){
        TestDataFactory.dataSetup();
        Account accRec = [Select Id from Account Limit 1];
        Unit__c unit = new Unit__c();
        unit.Operator__c = accRec.Id;
        insert unit;
	
        List<Well__c> wells = new List<Well__c>();
        wells.add(new Well__c(
                unit__c = unit.id,
                Current_Operator_Name__c = 'Surge',
                API10__c = '422273655',
                Name = 'My Well #1A',
                Hole_Direction__c = 'Horizontal',
                Last_Activity_Date__c = Date.parse('1/1/18'),
                Last_Production_Date__c = Date.parse('2/1/18'),
                Last_Activity_Type__c = 'Spud',
                //Is_Paying__c = false,
                Is_Permit__c = true
        ));

        wells.add(new Well__c(
                unit__c = unit.id,
                Current_Operator_Name__c = 'Surge',
                API10__c = '422273656',
                Name = 'My Well #2A',
                Hole_Direction__c = 'Horizontal',
                Last_Activity_Date__c = Date.parse('1/1/18'),
                Last_Production_Date__c = Date.parse('2/1/18'),
                Last_Activity_Type__c = 'Spud',
                //Is_Paying__c = true,
                Is_Permit__c = false
        ));

        wells.add(new Well__c(
                unit__c = unit.id,
                Current_Operator_Name__c = 'Surge',
                API10__c = '422273657',
                Name = 'My Well #3A',
                Hole_Direction__c = 'Vertical',
                Last_Activity_Date__c = Date.parse('1/1/18'),
                Last_Production_Date__c = Date.parse('2/1/18'),
                Last_Activity_Type__c = 'Spud',
                //Is_Paying__c = true,
                Is_Permit__c = false
        ));


        wells.add(new Well__c(
                unit__c = unit.id,
                Current_Operator_Name__c = 'Surge',
                API10__c = '422273658',
                Name = 'My Well #4A',
                Hole_Direction__c = 'Horizontal',
                Last_Activity_Date__c = Date.parse('2/1/18'),
                Last_Activity_Type__c = 'Spud',
                Last_Production_Date__c = Date.parse('2/1/18'),
                //Is_Paying__c = false,
                Is_Permit__c = false
        ));

        wells.add(new Well__c(
                unit__c = unit.id,
                Current_Operator_Name__c = 'Surge',
                API10__c = '422273659',
                Name = 'My Well #5A',
                Hole_Direction__c = 'Horizontal',
                Last_Activity_Date__c = Date.parse('3/1/18'),
                Last_Production_Date__c = Date.parse('2/1/18'),
                Last_Activity_Type__c = 'Permit',
               // Is_Paying__c = false,
                Is_Permit__c = false
        ));

        wells.add(new Well__c(
                unit__c = unit.id,
                Current_Operator_Name__c = 'Surge',
                API10__c = '422273610',
                Name = 'My Well #6A',
                Hole_Direction__c = 'Horizontal',
                Last_Activity_Date__c = Date.parse('4/1/18'),
                Last_Production_Date__c = Date.parse('2/1/18'),
                Last_Activity_Type__c = 'Spud',
                //Is_Paying__c = true,
                Is_Permit__c = true
        ));

        insert wells;

        List<Monthly_Production__c> mpList = new List<Monthly_Production__c>();
        for(Well__c well :wells){
        Monthly_Production__c mpRec = new Monthly_Production__c();
        mpRec.Unique_Key__c = well.API10__c+'.'+system.today().format();
        mpRec.Production_Date__c = system.today();
        mpRec.Well__c = well.Id;
            mpList.add(mpRec);
        }
        Insert mpList;

        List<unitAllocation__c> uaList = new List<unitAllocation__c>();
        for(Subtract__c subtract : [Select Id from Subtract__c Limit 50]){
            unitAllocation__c suaRec = new unitAllocation__c();
            suaRec.subtract__c = subtract.Id;
            suaRec.unit__c = unit.Id;
            uaList.add(suaRec);
        }
        insert uaList;

        
    }

    @isTest
    private static void testmethod1(){
        
        Opportunity opp = [Select Id from Opportunity Limit 1];
        Tract__c Tract = [Select Id from Tract__c Limit 1];
        Subtract__c subtract = [Select Id from Subtract__c Limit 1];
		Unit__c unit = [Select Id from Unit__c Limit 1];
		Account acct = [Select Id from Account Limit 1];
        
        Test.StartTest();
        WellUnitUtil.getWellInfo(opp.Id);
        WellUnitUtil.getWellInfo(Tract.Id);
        WellUnitUtil.getWellInfo(subtract.id);
		WellUnitUtil.getWellInfo(unit.id);
		WellUnitUtil.getWellInfo(acct.id);
        Test.StopTest();
    }
}