src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Acquiring_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Acquiring Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Acquiring Entity)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/revenueEstimate__c.object
<CustomObject>
    <fields>
        <fullName>Owner_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Revenue Estimates</relationshipLabel>
        <relationshipName>Revenue_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SRP_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SRP Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>productionMonth__c</fullName>
        <formula>monthlyProduction__r.Production_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Production Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>unitAllocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Allocation</label>
        <referenceTo>unitAllocation__c</referenceTo>
        <relationshipLabel>Revenue Estimates</relationshipLabel>
        <relationshipName>Owner_Interest_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Estimate</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>RevenueEstimate  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/unitAllocation__c.object
<CustomObject>
    <description>Contains the subtracts in a unit and the associated percent allocation for each subtract</description>
    <fields>
        <fullName>subtract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subtract</label>
        <referenceTo>Subtract__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Unit Allocation</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Unit Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/UpdateOwnerEntity.cls
global class UpdateOwnerEntity implements Database.Batchable<sObject>{

    global Set<Id> updatedOppIds = new Set<Id>();

    global UpdateOwnerEntity(Set<Id> updatedOppIds){
        this.updatedOppIds = updatedOppIds;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        String query ='';
        if(updatedOppIds.size()>0){
            Set<Id> tractIds = new Set<Id>();
            for(Opportunity_Tract__c otRec : [Select Id, Tract__c from Opportunity_Tract__c where Opportunity__c In: updatedOppIds]){
                tractIds.add(otRec.Tract__c);
            }
            query = 'Select Id from Tract__c where Id In: tractIds';
        }else{
            query = 'Select Id from Tract__c';
        }
        return Database.getQueryLocator(query);
    }

   global void execute(Database.BatchableContext BC, List<sobject> scope){
         
        Set<Id> tractIds = new Set<Id>();
        for(Tract__c tRec : (List<Tract__c>)scope){
            tractIds.add(tRec.Id);
        }

        Map<Id,List<oppWrapper>> tractOppMap = new Map<Id,List<oppWrapper>>();
        oppWrapper opp;
        List<oppWrapper> oppList;
        for(Opportunity_Tract__c otRec : [Select Id, Tract__c,Opportunity__c,Opportunity__r.StageName,Opportunity__r.CreatedDate,
                    Opportunity__r.Effective_Date__c,Opportunity__r.Acquiring_Entity__r.Type,Opportunity__r.Acquiring_Entity__c
                    from Opportunity_Tract__c where Tract__c In: tractIds order by Opportunity__r.CloseDate asc]){
            
            opp = new oppWrapper();
            opp.StageName = otRec.Opportunity__r.StageName;
            opp.EffectiveDate= otRec.Opportunity__r.Effective_Date__c;
            opp.AcquiringEntity = otRec.Opportunity__r.Acquiring_Entity__c;
            opp.AcquiringEntityType = otRec.Opportunity__r.Acquiring_Entity__r.Type;
            opp.CreatedDate= otRec.Opportunity__r.CreatedDate;

            if(tractOppMap.containsKey(otRec.Tract__c)){
                tractOppMap.get(otRec.Tract__c).add(opp);
            }else{
                oppList = new List<oppWrapper>();
                oppList.add(opp);
                tractOppMap.put(otRec.Tract__c,oppList);
            }
        }
        Map<Id,revenueEstimate__c> revMap = new Map<Id,revenueEstimate__c>();
        Boolean check;
        Date prevMonth;
        Integer oppCounter;
        Integer oppListSize;
        for(revenueEstimate__c revRec :[Select Id,unitAllocation__r.subtract__r.Tract__c,productionMonth__c from revenueEstimate__c 
                where unitAllocation__r.subtract__r.Tract__c In:tractOppMap.keySet() order by unitAllocation__r.subtract__r.Tract__c asc]){
            check = false;
            prevMonth = null;
            oppCounter = 1;
            oppListSize = tractOppMap.get(revRec.unitAllocation__r.subtract__r.Tract__c).size();
            for(oppWrapper oppRec: tractOppMap.get(revRec.unitAllocation__r.subtract__r.Tract__c)){

                
                if((oppRec.StageName=='Closed Won') &&  oppRec.AcquiringEntityType =='Portfolio Investment' && revRec.productionMonth__c >= oppRec.EffectiveDate){
                    revRec.srp_owned__c = true;
                    revRec.owner_entity__c = oppRec.AcquiringEntity;
                    check = true;
                }
                if(((oppRec.StageName!='Closed Won') ||  oppRec.AcquiringEntityType !='Portfolio Investment') && revRec.productionMonth__c >= oppRec.EffectiveDate){
                    revRec.srp_owned__c = false;
                    revRec.owner_entity__c = null;
                    check = true;
                }
                //Commenting BackDated Opportunity logic
                /*if(oppCounter == oppListSize){
                    if((oppRec.StageName=='Closed Review'||oppRec.StageName=='Closed Complete') &&  oppRec.AcquiringEntityType =='Portfolio Investment' && revRec.productionMonth__c >= oppRec.EffectiveDate){
                        revRec.srp_owned__c = true;
                        revRec.owner_entity__c = oppRec.AcquiringEntity;
                        check = true;
                    }
                }*/
                oppCounter++;
            }
            if(check == false){
                    revRec.srp_owned__c = false;
                    revRec.owner_entity__c = null;
            }
            revMap.put(revRec.Id,revRec);
        }
        if(revMap.values().size()>0){
            update revMap.values();
        }
   }

   global void finish(Database.BatchableContext BC){

   }
    
    public class oppWrapper{
        
        public String StageName;
        public Date EffectiveDate;
        public Id AcquiringEntity;
        public String AcquiringEntityType ;
        public DateTime CreatedDate;
    }

}