src/objects/Opportunity_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Opportunity Tracts</relationshipLabel>
        <relationshipName>Opportunity_Tracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Tract</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_AOI_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>ProjectAOITracts</relationshipLabel>
        <relationshipName>ProjectAOITracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>aoiMaxOtgPrice__c</fullName>
        <formula>if( projectAoi__r.isParent__c , 0, aoiMaxOtgPricePerAcre__c * netAcresWithinAoi__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AOI Max OTG Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>aoiTargetOtgPrice__c</fullName>
        <formula>if( projectAoi__r.isParent__c , 0, aoiTargetOtgPricePerAcre__c *  netAcresWithinAoi__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AOI Target OTG Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pricingNetAcres__c</fullName>
        <formula>if( projectAoi__r.isParent__c , 0,  netAcresWithinAoi__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>pricingNetAcres</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pricingPercentAcres__c</fullName>
        <formula>if( projectAoi__r.isParent__c , 0,   percentageOfAcreageInAoi__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>pricingPercentAcres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project AOI Tract</label>
    <nameField>
        <label>Project AOI Tract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAOITracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>netAcres__c</fullName>
        <label>Net Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/oppProjectAOIPricingAura.cls
//Created by John Gorrell December 2019
//Code coverage provided by projectPricingTest.cls

public class oppProjectAOIPricingAura  {

	@AuraEnabled
	public static oppProjectPricing getOppPricing2 (String recordId){
		oppProjectPricing result = new oppProjectPricing();
		List<Project_AOI_Tract__c> oppProjectTracts = new List<Project_AOI_Tract__c>();
		List<Tract__c> relatedTracts = new List<Tract__c>();
		relatedTracts = [SELECT Id, netAcres__c 
										FROM Tract__c 
										WHERE Id in (SELECT Tract__c FROM Opportunity_Tract__c WHERE Opportunity__c = :recordId)];
		oppProjectTracts = [SELECT Id, aoiMaxOtgPrice__c, aoiTargetOtgPrice__c, pricingPercentAcres__c, pricingNetAcres__c, Tract__r.netAcres__c
						    FROM Project_AOI_Tract__c 
							WHERE Tract__c in (SELECT Tract__c FROM Opportunity_Tract__c WHERE Opportunity__c = :recordId)];
		for(Project_AOI_Tract__c oppProjectTract: oppProjectTracts){
			//result.suggestedPrice = result.suggestedPrice + oppProjectTract.aoiSuggestedOtgPrice__c;
			result.targetPrice = result.targetPrice + oppProjectTract.aoiTargetOtgPrice__c;
			result.maxPrice = result.maxPrice + oppProjectTract.aoiMaxOtgPrice__c;
			result.netAcres = result.netAcres + oppProjectTract.pricingNetAcres__c;
		}
		for(Tract__c relatedTract : relatedTracts){
			if(relatedTract.netAcres__c <> null){
				result.totalAcres = result.totalAcres + relatedTract.netAcres__c;
			}
		}
		if(result.netAcres > 0){
			//result.suggestedPPA = result.suggestedPrice/result.netAcres;
			result.targetPPA = result.targetPrice/result.netAcres;
			result.maxPPA = result.maxPrice/result.netAcres;
		}

		if(result.totalAcres > 0){
			result.percentCovered = result.netAcres/result.totalAcres;
		}


		return result;
	}

	public class oppProjectPricing{
		@AuraEnabled public Double percentCovered {get; set;}
		@AuraEnabled public Double netAcres {get; set;}
		@AuraEnabled public Double totalAcres {get; set;}
		@AuraEnabled public Double suggestedPPA {get; set;}
		@AuraEnabled public Double suggestedPrice {get; set;}
		@AuraEnabled public Double targetPPA {get; set;}
		@AuraEnabled public Double targetPrice {get; set;}
		@AuraEnabled public Double maxPPA {get; set;}
		@AuraEnabled public Double maxPrice {get; set;}

		public oppProjectPricing(){
			percentCovered = 0;
			netAcres = 0;
			totalAcres = 0;
			suggestedPPA = 0;
			suggestedPrice = 0;
			targetPPA = 0;
			targetPrice = 0;
			maxPPA = 0;
			maxPrice = 0;
		}
	}

}