src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Acquiring_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Acquiring Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Acquiring Entity)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Date__c</fullName>
        <label>PSA Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>askTotalPricePerAcre__c</fullName>
        <formula>if(askTotalPrice__c = 0, 0, askTotalPrice__c / Total_Acreage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ask Total Price Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>askTotalPrice__c</fullName>
        <label>Ask Total Price</label>
        <summarizedField>Opportunity_Tract__c.askTotalPrice__c</summarizedField>
        <summaryForeignKey>Opportunity_Tract__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field used in the Manage Cases modal on the Cases related list. It is initially left off the page layout in order to serve only the purpose of searching for cases in the modal.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>totalPricePerAcre__c</fullName>
        <formula>if(totalPrice__c = 0, 0, totalPrice__c /  Total_Acreage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>totalPrice__c</fullName>
        <label>Total Price</label>
        <summarizedField>Opportunity_Tract__c.totalPrice__c</summarizedField>
        <summaryForeignKey>Opportunity_Tract__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Case__c.object
<CustomObject>
    <description>Junction obj for a many-to-many relationship between Opportunity and Case</description>
    <fields>
        <fullName>case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>Opportunity_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>Opportunity_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Case</label>
    <nameField>
        <displayFormat>OC-{0000000000}</displayFormat>
        <label>Opportunity Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManageOpportunitiesAura.cls
public class ManageOpportunitiesAura {
    @AuraEnabled
    public static List<Opportunity_Case__c> getOpportunities(Id recordId) {
        List<Opportunity_Case__c> oppCaseList = new List<Opportunity_Case__c>();

        oppCaseList = [
            SELECT
                Id,
                Name,
                opportunity__c,
                opportunity__r.Name,
                opportunity__r.StageName,
                opportunity__r.Acquiring_Entity__r.Name,
                opportunity__r.Acquiring_Entity__c,
                opportunity__r.Type,
                opportunity__r.Account.Name,
                opportunity__r.Account.Id,
                opportunity__r.AccountId,
                opportunity__r.PSA_Date__c,
                opportunity__r.CloseDate,
                opportunity__r.Effective_Date__c,
                opportunity__r.Owner.Name,
                opportunity__r.OwnerId,
                opportunity__r.totalPricePerAcre__c,
                opportunity__r.totalPrice__c,
                opportunity__r.askTotalPricePerAcre__c,
                opportunity__r.askTotalPrice__c
            FROM Opportunity_Case__c
            WHERE case__c = :recordId
        ];

        return oppCaseList;
    }

    @AuraEnabled
    public static List<Opportunity_Case__c> getOpportunitySearchResults(List<String> oppIds,Id recordId) {
        List<Opportunity_Case__c> oppCaseList = new List<Opportunity_Case__c>();
        Map<Id, Opportunity_Case__c> oppCaseMap = new Map<Id, Opportunity_Case__c>();
        List<Id> oppCaseIds = new List<Id>();

        oppCaseList = getOpportunities(recordId);

        for (Opportunity_Case__c oc : oppCaseList) {
            oppCaseMap.put(oc.opportunity__c, oc);
        }

        if (oppCaseMap.containsKey(oppIds[0])) {
            return oppCaseList;
        }

        Opportunity[] oppLst = [
            SELECT
            Id,
            Name,
            StageName,
            Acquiring_Entity__r.Name,
            Acquiring_Entity__c,
            Type,
            Account.Name,
            Account.Id,
            AccountId,
            PSA_Date__c,
            CloseDate,
            Effective_Date__c,
            Owner.Name,
            OwnerId,
            totalPricePerAcre__c,
            totalPrice__c,
            askTotalPricePerAcre__c,
            askTotalPrice__c
            FROM Opportunity
            WHERE Id = :oppIds
        ];

        try {
            if (oppLst.size() > 0) {
                insert new Opportunity_Case__c(
                    opportunity__c = oppLst[0].Id,
                    case__c = recordId
                );
            }
            return getOpportunities(recordId);
        } catch (exception e) {
            System.debug('EXCEPTION: ' + e);
            return null;
        }
    }

    @AuraEnabled
    public static List<Opportunity_Case__c> updateRecordAssociation(
        Id recordId,
        Id oppCaseId
    ) {
        System.debug(
            'delete OppCase called with parameters recordId: ' +
            recordId +
            ' oppCaseId: ' +
            oppCaseId
        );
        Opportunity_Case__c oppCaseToDelete = new Opportunity_Case__c();
        oppCaseToDelete.Id = oppCaseId;
        try {
            System.debug('oppCaseToDelete is -----------> ' + oppCaseToDelete);
            delete oppCaseToDelete;
            return getOpportunities(recordId);
        } catch (exception e) {
            System.debug('EXCEPTION: ' + e);
            return null;
        }
    }
}