src/objects/Project_AOI__c.object
<CustomObject>
    <description>Project AOI</description>
    <fields>
        <fullName>aoiMaxOtgPrice__c</fullName>
        <description>AOI Max OTG Price</description>
        <inlineHelpText>AOI Max OTG Price</inlineHelpText>
        <label>AOI Max OTG Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>aoiTargetOtgPrice__c</fullName>
        <description>AOI Target OTG Price</description>
        <inlineHelpText>AOI Target OTG Price</inlineHelpText>
        <label>AOI Target OTG Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project AOI</label>
    <nameField>
        <label>Project AOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAOIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_AOI_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>ProjectAOITracts</relationshipLabel>
        <relationshipName>ProjectAOITracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>aoiMaxOtgPricePerAcre__c</fullName>
        <formula>projectAoi__r.aoiMaxOtgPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AOI Max OTG Price Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>aoiMaxOtgPrice__c</fullName>
        <formula>if( projectAoi__r.isParent__c , 0, aoiMaxOtgPricePerAcre__c * netAcresWithinAoi__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AOI Max OTG Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>aoiTargetOtgPricePerAcre__c</fullName>
        <formula>projectAoi__r.aoiTargetOtgPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AOI Target OTG Price Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>aoiTargetOtgPrice__c</fullName>
        <formula>if( projectAoi__r.isParent__c , 0, aoiTargetOtgPricePerAcre__c *  netAcresWithinAoi__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AOI Target OTG Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>grossAcresWithinAoi__c</fullName>
        <formula>Tract__r.Gross_Acres__c *  percentageOfAcreageInAoi__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Acres Within AOI</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>netAcreageUnits__c</fullName>
        <formula>TEXT(Tract__r.netAcreageUnits__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Acreage Units</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>netAcresWithinAoi__c</fullName>
        <formula>Tract__r.netAcres__c *  percentageOfAcreageInAoi__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Acres within AOI</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>percentageOfAcreageInAoi__c</fullName>
        <label>Percentage of Acreage in AOI</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>pricingNetAcres__c</fullName>
        <formula>if( projectAoi__r.isParent__c , 0,  netAcresWithinAoi__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>pricingNetAcres</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pricingPercentAcres__c</fullName>
        <formula>if( projectAoi__r.isParent__c , 0,   percentageOfAcreageInAoi__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>pricingPercentAcres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>projectAoi__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project AOI</label>
        <referenceTo>Project_AOI__c</referenceTo>
        <relationshipLabel>ProjectAOITracts</relationshipLabel>
        <relationshipName>ProjectAOITracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tractGrossAcres__c</fullName>
        <formula>Tract__r.Gross_Acres__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tract Gross Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tractNetAcres__c</fullName>
        <formula>Tract__r.netAcres__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tract Net Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project AOI Tract</label>
    <nameField>
        <label>Project AOI Tract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAOITracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>netAcreageUnits__c</fullName>
        <label>Net Acreage Units</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NRA</fullName>
                </value>
                <value>
                    <fullName>NMA</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/tractProjectAOIListAura.cls
//Created by John Gorrell December 2019
//Code coverage provided by projectPricingTest.cls

public class tractProjectAOIListAura  {

	@AuraEnabled
	public static projectTractsResult getTractProjectAOIs(String recordId){
		projectTractsResult result = new projectTractsResult();
		result.projectTracts = [SELECT aoiMaxOtgPrice__c, aoiMaxOtgPricePerAcre__c, aoiTargetOtgPrice__c, aoiTargetOtgPricePerAcre__c,
									grossAcresWithinAoi__c, netAcreageUnits__c, netAcresWithinAoi__c, percentageOfAcreageInAoi__c, pricingNetAcres__c, projectAoi__c, Name, Tract__c, tractGrossAcres__c,
									tractNetAcres__c, pricingPercentAcres__c, Id, projectAoi__r.Name
								FROM Project_AOI_Tract__c
								WHERE Tract__c = :recordId];
		for (Project_AOI_Tract__c projectTract: result.projectTracts){
			result.sumMaxPrice = result.sumMaxPrice + projectTract.aoiMaxOtgPrice__c;
			result.sumNetAcres = result.sumNetAcres + projectTract.pricingNetAcres__c;
			result.sumPercentAcres = result.sumPercentAcres + projectTract.pricingPercentAcres__c*100;
			result.sumTargetPrice = result.sumTargetPrice + projectTract.aoiTargetOtgPrice__c;
		}
		if(result.sumNetAcres > 0){
			result.maxPPA = result.sumMaxPrice/result.sumNetAcres;
			result.targetPPA = result.sumTargetPrice/result.sumNetAcres;
		}
		return result;
		
		/*finalResult result = new finalResult();
		List<Tract__c> tractList = [SELECT ID FROM Tract__c WHERE ID = :recordId];
		Map<String, Map<String, tractUtility.tractProjectPricing>> resultSet = tractUtility.getTractsPricing(tractList);
		System.debug(resultSet);
		System.debug(recordId);
		Map<String, tractUtility.tractProjectPricing> tractResults = resultSet.get(recordId);
		for(String projectTract:tractResults.keySet()){
			System.debug ('Adding pricing result for ' + projectTract);
			tractUtility.tractProjectPricing pricing = tractResults.get(projectTract);
			tractPricingResult newResult = new tractPricingResult();
			newResult.projectTractId = projectTract;
			newResult.projectTractName = pricing.projectTract.Name;
			newResult.projectTractLink = Url.getSalesforceBaseUrl().toExternalForm() + '/' + pricing.projectTract.Id;
			newResult.projectAOIId = pricing.projectAOI.Id;
			newResult.projectAOIName = pricing.projectAOI.Name;
			System.debug('pricing.projectAOI.Name value is: ' + newResult.projectAOIName);
			newResult.projectAOILink = Url.getSalesforceBaseUrl().toExternalForm() + '/' + pricing.projectAOI.Id;
			newResult.percentAcres = pricing.projectTract.percentageOfAcreageInAOI__c/100;
			newResult.netAcres = pricing.projectTract.netAcresWithinAOI__c;
			newResult.aoiSuggPPA = pricing.projectAOI.aoiSuggestedOtgPrice__c;
			newResult.aoiTargetPPA = pricing.projectAOI.aoiTargetOtgPrice__c;
			newResult.aoiMaxPPA = pricing.projectAOI.aoiMaxOtgPrice__c; 
			newResult.aoiTractTargetPrice = pricing.aoiTractTargetOTGPrice;
			newResult.aoiTractMaxPrice = pricing.aoiTractMaxOTGPrice;
			result.pricingResults.add(newResult);
			System.debug(newResult);
		}

		Map<String, tractUtility.tractPricing> defaultPricing = tractUtility.getTractsDefaultPricing(tractList);
		tractUtility.tractPricing currentTractDefaultPricing = defaultPricing.get(recordId);
		result.percentAcres = currentTractDefaultPricing.percentCovered;

		result.targetPrice = currentTractDefaultPricing.targetTotalOTGCost;
		result.maxPrice = currentTractDefaultPricing.maxTotalOTGCost;
		result.netAcres = currentTractDefaultPricing.totalIncludedAcres;
		result.targetPPA = currentTractDefaultPricing.targetOTGCostPerAcre;
		result.maxPPA = currentTractDefaultPricing.maxOTGCostPerAcre;

		System.debug(result);
		return result;
		*/
	}

	public class projectTractsResult{
		@AuraEnabled public List<Project_AOI_Tract__c> projectTracts {get; set;}
		@AuraEnabled public Double sumNetAcres {get; set;}
		@AuraEnabled public Double sumPercentAcres {get; set;}
		@AuraEnabled public Double sumTargetPrice {get; set;}
		@AuraEnabled public Double targetPPA {get; set;}
		@AuraEnabled public Double sumMaxPrice {get; set;}
		@AuraEnabled public Double maxPPA {get; set;}


		public projectTractsResult(){
		projectTracts = new List<Project_AOI_Tract__c>();
		sumNetAcres = 0;
		sumPercentAcres = 0;
		sumTargetPrice = 0;
		targetPPA = 0;
		sumMaxPrice = 0;
		maxPPA = 0;
		}

	}
/*
	public class finalResult{
		@AuraEnabled public List<tractPricingResult> pricingResults {get; set;}
		@AuraEnabled public Double percentAcres {get; set;}
		@AuraEnabled public Double netAcres {get; set;}
		@AuraEnabled public Double targetPrice {get; set;}
		@AuraEnabled public Double maxPrice {get; set;}
		@AuraEnabled public Double targetPPA {get; set;}
		@AuraEnabled public Double maxPPA {get; set;}

		public finalResult(){
			pricingResults = new List<tractPricingResult>();
			netAcres = 0;
			percentAcres = 0;
			targetPrice = 0.00;
			maxPrice = 0.00;
			targetPPA = 0.00;
			maxPPA = 0.00;
		}
	}

	public class tractPricingResult{
		@AuraEnabled public String projectTractId {get; set;}
		@AuraEnabled public String projectTractName {get; set;}
		@AuraEnabled public String projectTractLink {get; set;}
		@AuraEnabled public String projectAOIId {get; set;}
		@AuraEnabled public String projectAOIName {get; set;}
		@AuraEnabled public String projectAOILink {get; set;}
		@AuraEnabled public Double percentAcres {get; set;}
		@AuraEnabled public Double netAcres {get; set;}
		@AuraEnabled public Decimal aoiSuggPPA {get; set;}
		@AuraEnabled public Decimal aoiTargetPPA {get; set;}
		@AuraEnabled public Decimal aoiMaxPPA {get; set;}
		@AuraEnabled public Decimal aoiTractTargetPrice {get; set;}
		@AuraEnabled public Decimal aoiTractMaxPrice {get; set;}

		public tractPricingResult(){
			projectTractId = '';
			projectTractName = '';
			projectTractLink = '';
			projectAOIId = '';
			projectAOIName = '';
			projectAOILink = '';
			netAcres = 0;
			percentAcres = 0;
			aoiSuggPPA = 0;
			aoiTargetPPA = 0;
			aoiMaxPPA = 0; 
			aoiTractTargetPrice = 0;
			aoiTractMaxPrice = 0;
		}
	}
*/
}