src/objects/Project_AOI__c.object
<CustomObject>
    <description>Project AOI</description>
    <fields>
        <fullName>aoiMaxOtgPrice__c</fullName>
        <description>AOI Max OTG Price</description>
        <inlineHelpText>AOI Max OTG Price</inlineHelpText>
        <label>AOI Max OTG Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>parentAOI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent AOI</label>
        <referenceTo>Project_AOI__c</referenceTo>
        <relationshipLabel>ProjectAOIs</relationshipLabel>
        <relationshipName>ProjectAOIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project AOI</label>
    <nameField>
        <label>Project AOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAOIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_AOI_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>ProjectAOITracts</relationshipLabel>
        <relationshipName>ProjectAOITracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>aoiMaxOtgPrice__c</fullName>
        <formula>if( projectAoi__r.isParent__c , 0, aoiMaxOtgPricePerAcre__c * netAcresWithinAoi__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AOI Max OTG Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>projectAoi__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project AOI</label>
        <referenceTo>Project_AOI__c</referenceTo>
        <relationshipLabel>ProjectAOITracts</relationshipLabel>
        <relationshipName>ProjectAOITracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project AOI Tract</label>
    <nameField>
        <label>Project AOI Tract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAOITracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/projectPricingTest.cls
//Test class created by John Gorrell 01/07/2020

//Provides code coverage for the following classes:
//oppProjectAOIPricingAura
//srpFieldHistoryUtility
//ProjectAOITrigger
//tractProjectAOIListAura

@isTest 
private class projectPricingTest {
	



	@TestSetup
	static void setupTestData(){
		TestDataFactory.dataSetup();
	}

	static testmethod void mainMethod(){
	Opportunity opp = [SELECT ID FROM Opportunity LIMIT 1];
	oppProjectAOIPricingAura.oppProjectPricing pricing = oppProjectAOIPricingAura.getOppPricing2(opp.Id);
	List<Project_AOI__c> projectAOIs = [SELECT ID FROM Project_AOI__c];
	List<Project_AOI_Tract__c> relatedProjectAOITracts = [SELECT ID FROM Project_AOI_Tract__c WHERE projectAoi__c = :projectAOIs[1].Id];
	if (projectAOIs.size() > 1){
		projectAOIs[0].parentAOI__c = projectAOIs[1].Id;
		update projectAOIs[0];
		projectAOIs[1].aoiMaxOtgPrice__c = 100;
		update projectAOIs[1];
		delete relatedProjectAOITracts;
		delete projectAOIs[1];
	}
	Tract__c tract = [SELECT ID FROM Tract__c LIMIT 1];
	tractProjectAOIListAura.projectTractsResult tractProjectAOIResult = tractProjectAOIListAura.getTractProjectAOIs(tract.Id);

	}
}