src/objects/quarterCallMapping__c.object
<CustomObject>
    <description>Used to specify list of values for TOR area field to quarter call when reconciling a TOT and Tract record</description>
    <fields>
        <fullName>area__c</fullName>
        <label>Area</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>quarterCall__c</fullName>
        <label>Quarter Call</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>titleIntegrationJob__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to title projecting job</description>
        <label>Title Integration Job</label>
        <referenceTo>TitleIntegrationJob__c</referenceTo>
        <relationshipLabel>Quarter Call Mappings</relationshipLabel>
        <relationshipName>QuarterCallMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quarter Call Mapping</label>
    <nameField>
        <label>Quarter Call Mapping</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quarter Call Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TargetOwnershipName__c.object
<CustomObject>
    <description>TON, or unique name with ownership.</description>
    <fields>
        <fullName>jobId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Title Processing Job Id</description>
        <inlineHelpText>Title Processing Job Id</inlineHelpText>
        <label>Job Id</label>
        <referenceTo>TitleIntegrationJob__c</referenceTo>
        <relationshipLabel>Target Ownership Names</relationshipLabel>
        <relationshipName>Target_Ownership_Names</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Target Ownership Name</label>
    <nameField>
        <displayFormat>TON-{0000000000}</displayFormat>
        <label>Target Ownership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Ownership Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TitleIntegrationJob__c.object
<CustomObject>
    <description>Batch job information for title loading</description>
    <fields>
        <fullName>quarterCallLock__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System field for determining if Quarter Call Mapping can be updated.</description>
        <label>Quarter Call Lock</label>
        <type>Checkbox</type>
    </fields>
    <label>Title Integration Job</label>
    <nameField>
        <displayFormat>TIJ-{0000000000}</displayFormat>
        <label>Title Integration Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Integration Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TitleOwnershipDetail__c.object
<CustomObject>
    <description>Contains TORs and TOTs created during the reconciliation process between Tracts.co and Salesforce</description>
    <fields>
        <fullName>area__c</fullName>
        <label>Area</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>quarterCall__c</fullName>
        <description>Store the value cross referenced in Quarter Call Mapping.</description>
        <label>Quarter Call</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>targetOwnershipName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Ownership Name</label>
        <referenceTo>TargetOwnershipName__c</referenceTo>
        <relationshipLabel>Title Ownership Details</relationshipLabel>
        <relationshipName>titleOwnershipDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Title Ownership Detail</label>
    <nameField>
        <displayFormat>TOD-{0000000000}</displayFormat>
        <label>TOD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Ownership Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/tpjQuarterCallMappingAura.cls
//Create by John Gorrell 02/24/2019 as part of Tract Reconciliation Prject

//Test coverage provided by tractReconciliationAuraTest

public with sharing class tpjQuarterCallMappingAura  {

	@AuraEnabled(Cacheable=true)
    public static List<QuarterCallMapping__c> getMappings(Id recordId) {

        List<QuarterCallMapping__c> quarterCallMappings = [SELECT area__c,CreatedById,CreatedDate,Id,IsDeleted,LastModifiedById,LastModifiedDate,Name,OwnerId,quarterCall__c,SystemModstamp,
														   titleIntegrationJob__c, titleIntegrationJob__r.Name, titleIntegrationJob__r.quarterCallLock__c 
														   FROM QuarterCallMapping__c 
														   WHERE titleIntegrationJob__c =: recordId
        ];
        return quarterCallMappings;
    }

	@AuraEnabled
	public static String updateMappings(List<QuarterCallMapping__c> mappings, Id recordId){
		String response = 'Success';
		List<String> areas = new List<String>();
		Map<String, String> quarterCallMap = new Map<String, String>();
		List<TitleOwnershipDetail__c> updateList = new List<TitleOwnershipDetail__c>();
		try{
			update mappings;
			for(QuarterCallMapping__c qCMap: mappings){
				areas.add(qCMap.area__c);
				quarterCallMap.put(qCMap.area__c, qCMap.quarterCall__c);
			}

			List<TitleOwnershipDetail__c> relatedTODs = new List<TitleOwnershipDetail__c>();
			relatedTODs = [SELECT Id, area__c FROM TitleOwnershipDetail__c WHERE targetOwnershipName__r.jobId__c = :recordId];
			for(TitleOwnershipDetail__c currentTOD : relatedTODs){
				if(quarterCallMap.containsKey(currentTOD.area__c)){
					currentTOD.quarterCall__c = quarterCallMap.get(currentTOD.area__c);
					updateList.add(currentTOD);
				}
			}
			if(updateList.size() > 0){
				update updateList;
			}
		}
		catch (Exception e) {
			 response = 'ERROR UPDATING QUARTER CALL MAPPINGS ' + e + '\n' + e.getMessage() + ' Line Number: ' + e.getLineNumber() + ' ' + e.getStackTraceString();
			 system.debug('ERROR UPDATING QUARTER CALL MAPPINGS ' + e + '\n' + e.getMessage() + ' Line Number: ' + e.getLineNumber() + ' ' + e.getStackTraceString());
		}
		return response;

	}

	@AuraEnabled
	public static String lockQuarterCallMap(Id recordId){
		String response = 'Success';
		try{
			TitleIntegrationJob__c currentJob = new TitleIntegrationJob__c();
			currentJob.Id = recordId;
			currentJob.quarterCallLock__c = true;
			update currentJob;
		}
		catch (Exception e) {
			 response = 'ERROR LOCKING QUARTER CALL MAP ' + e + '\n' + e.getMessage() + ' Line Number: ' + e.getLineNumber() + ' ' + e.getStackTraceString();
			 system.debug('ERROR LOCKING QUARTER CALL MAP ' + e + '\n' + e.getMessage() + ' Line Number: ' + e.getLineNumber() + ' ' + e.getStackTraceString());
		}
		return response;
	}

}