src/objects/revenueProperty__c.object
<CustomObject>
    <fields>
        <fullName>notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>operatorName__c</fullName>
        <label>Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Revenue Property</label>
    <nameField>
        <displayFormat>Revenue Property-{00000}</displayFormat>
        <label>Revenue Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RevenuePropertyWellAllocation__c.object
<CustomObject>
    <fields>
        <fullName>revenueProperty__c</fullName>
        <label>Revenue Property</label>
        <referenceTo>revenueProperty__c</referenceTo>
        <relationshipLabel>Revenue Property Well Allocations</relationshipLabel>
        <relationshipName>Revenue_Property_Well_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>splitPercent__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Percentage of revenue applied to well</description>
        <inlineHelpText>Percentage of revenue applied to well</inlineHelpText>
        <label>Split Percent</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>well__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Revenue Property Well Allocations</relationshipLabel>
        <relationshipName>Revenue_Property_Well_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Property Well Allocation</label>
    <nameField>
        <displayFormat>RPW-{000000000}</displayFormat>
        <label>Revenue Property Well Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Property Well Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>adjustmentCode__c</fullName>
        <label>Adjustment Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>detailId__c</fullName>
        <externalId>true</externalId>
        <label>DetailId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>grossAdjustmentsActual__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Gross Adjustments Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>grossNetActual__c</fullName>
        <label>Gross Net Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>grossTaxesActual__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Gross Taxes Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>grossValueActual__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Gross Value Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>grossValueAfterAdjustments__c</fullName>
        <description>Gross Value - Gross Adjustments - Gross Taxes</description>
        <formula>grossValue__c -  ABS(grossTaxesActual__c)  -  ABS(grossAdjustmentsActual__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gross Value - Gross Adjustments - Gross Taxes</inlineHelpText>
        <label>Gross Value after Adjustments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>grossValue__c</fullName>
        <description>Gross Value x Price</description>
        <formula>grossVolumeActual__c *  price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gross Value x Price</inlineHelpText>
        <label>Gross Value Calc</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>grossVolumeActual__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Gross volume from royalty check from operator (5 decimal places)</description>
        <inlineHelpText>Gross volume from royalty check from operator (5 decimal places)</inlineHelpText>
        <label>Gross Volume Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>interestType__c</fullName>
        <label>Interest Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isLastProductionMonth__c</fullName>
        <formula>IF(production_Month__c =  well__r.Last_Production_Month__c , true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Last Production Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isNonWellLineItem__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Non Well Line Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>lineItemDecimal__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Royalty check line item well interest / distribution decimal from operator.</description>
        <inlineHelpText>Royalty check line item well interest / distribution decimal from operator.</inlineHelpText>
        <label>Line Item Decimal</label>
        <precision>11</precision>
        <required>true</required>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>line_Item_Net_Val__c</fullName>
        <description>Gross Value After Adjustments x Line Item Decimal</description>
        <formula>ABS(grossValueAfterAdjustments__c) *  lineItemDecimal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gross Value After Adjustments x Line Item Decimal</inlineHelpText>
        <label>Line Item Net Value Calc</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>net_Adjustments__c</fullName>
        <description>Gross Adjustments x Decimal</description>
        <formula>grossAdjustmentsActual__c  *  lineItemDecimal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gross Adjustments x Decimal</inlineHelpText>
        <label>Net Adjustments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>net_Taxes__c</fullName>
        <description>Gross Taxes x Line Item Decimal</description>
        <formula>grossTaxesActual__c  *  lineItemDecimal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gross Taxes x Line Item Decimal</inlineHelpText>
        <label>Net Taxes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>net_Value__c</fullName>
        <description>Gross_Value__c * Line_Item_Decimal__c</description>
        <formula>grossValue__c  *  lineItemDecimal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gross_Value__c * Line_Item_Decimal__c</inlineHelpText>
        <label>Net Value Calc</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>notes__c</fullName>
        <description>Optional field for additional information related to royalty check line item</description>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>operatorName__c</fullName>
        <formula>royalty_Check__r.Operator_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Operator Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ownerAdjustmentsActual__c</fullName>
        <label>Owner Adjustments Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ownerNetValueActual__c</fullName>
        <label>Owner Net Value Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ownerTaxesActual__c</fullName>
        <label>Owner Taxes Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>revenueProperty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Property</label>
        <referenceTo>revenueProperty__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>well__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Well (Discarded)</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Royalty Line Items (Well)</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/unitAllocation__c.object
<CustomObject>
    <description>Contains the subtracts in a unit and the associated percent allocation for each subtract</description>
    <fields>
        <fullName>subtract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subtract</label>
        <referenceTo>Subtract__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Unit Allocation</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Unit Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/csvDownloadController.cls
public class csvDownloadController {
	@AuraEnabled
	public static list <contact> fetchContact(){
      
		List <contact> returnConList = new List < contact > ();
        
		for(contact con: [SELECT firstName, LastName, Department, MobilePhone From contact LIMIT 1000]) {
				returnConList.add(con);
			}
			return returnConList;
	}
	
	@AuraEnabled
	public static List<Royalty_Line_Item__c> getAccountWellRevenue(String recordId){
		//List<Subtract__c> accountSubtracts = [SELECT ID FROM Subtract__c WHERE Tract__c IN (SELECT Id FROM Tract__c WHERE Account__c = :recordId)];
		Set<Id> subtractIds = new Set<Id>();
		for(Subtract__c subtract: [SELECT ID FROM Subtract__c WHERE Tract__c IN (SELECT Id FROM Tract__c WHERE Account__c = :recordId)]){
			subtractIds.add(subtract.Id);
		}
		Set<Id> wellIds = new Set<Id>();
		for(Well__c well: [SELECT ID FROM Well__c WHERE Unit__c IN (SELECT Unit__c FROM unitAllocation__c WHERE Subtract__c IN :subtractIds)]){
			wellIds.add(well.Id);
		}
		Set<Id> revenuePropertyIds = new Set<Id>();
		List<RevenuePropertyWellAllocation__c> revenuePropertyWellAllocations = [SELECT Id, revenueProperty__c, splitPercent__c, well__c FROM RevenuePropertyWellAllocation__c WHERE well__c IN :wellIds];
		Map<Id, List<revenuePropertyWellAllocation__c>> revenuePropertyMap = new Map<Id, List<revenuePropertyWellAllocation__c>>();
		for(RevenuePropertyWellAllocation__c revenuePropertyWellAllocation: revenuePropertyWellAllocations){
			revenuePropertyIds.add(revenuePropertyWellAllocation.revenueProperty__c);
			if(revenuePropertyMap.get(revenuePropertyWellAllocation.revenueProperty__c) != null){
				revenuePropertyMap.get(revenuePropertyWellAllocation.revenueProperty__c).add(revenuePropertyWellAllocation);
			}
			else{
				List<revenuePropertyWellAllocation__c> tempList = new List<revenuePropertyWellAllocation__c>();
				tempList.add(revenuePropertyWellAllocation);
				revenuePropertyMap.put(revenuePropertyWellAllocation.revenueProperty__c, tempList);
			}
		}
		System.debug(revenuePropertyIds);
		List<Royalty_Line_Item__c> royaltyCheckLineItems = [SELECT adjustmentCode__c,CreatedById,CreatedDate,detailId__c,grossAdjustmentsActual__c,grossNetActual__c,grossTaxesActual__c,grossValueActual__c,
															grossValueAfterAdjustments__c,grossValue__c,grossVolumeActual__c,Id,interestType__c,IsDeleted,isLastProductionMonth__c,isNonWellLineItem__c,
															LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,lineItemDecimal__c,line_Item_Net_Val__c,Name,net_Adjustments__c,
															net_Taxes__c,net_Value__c,notes__c,operatorName__c,ownerAdjustmentsActual__c,ownerNetValueActual__c,ownerTaxesActual__c,ownerValueActual__c,
															ownerVolumeActual__c,price__c,productCode__c,productionMonthCalc__c,production_Month__c,product_Category__c,product__c,propertyName__c,
															property_Id__c,revenueAllocated__c,revenueProperty__c,royalty_Check__c,source__c,SystemModstamp,totalAllocatedAmount__c,type__c,
															wellNames__c,well__c 
															FROM Royalty_Line_Item__c
															WHERE revenueProperty__c IN: revenuePropertyIds
															ORDER BY CreatedDate DESC 
															LIMIT 40000];

		return royaltyCheckLineItems;
		
	}

	public static Set<Id> getAccountRevenuePropertyIds(String recordId){
	//public static List<Royalty_Line_Item__c> getAccountWellRevenue(String recordId){
		//List<Subtract__c> accountSubtracts = [SELECT ID FROM Subtract__c WHERE Tract__c IN (SELECT Id FROM Tract__c WHERE Account__c = :recordId)];
		Set<Id> subtractIds = new Set<Id>();
		for(Subtract__c subtract: [SELECT ID FROM Subtract__c WHERE Tract__c IN (SELECT Id FROM Tract__c WHERE Account__c = :recordId)]){
			subtractIds.add(subtract.Id);
		}
		Set<Id> wellIds = new Set<Id>();
		for(Well__c well: [SELECT ID FROM Well__c WHERE Unit__c IN (SELECT Unit__c FROM unitAllocation__c WHERE Subtract__c IN :subtractIds)]){
			wellIds.add(well.Id);
		}
		Set<Id> revenuePropertyIds = new Set<Id>();
		List<RevenuePropertyWellAllocation__c> revenuePropertyWellAllocations = [SELECT Id, revenueProperty__c, splitPercent__c, well__c FROM RevenuePropertyWellAllocation__c WHERE well__c IN :wellIds];
		Map<Id, List<revenuePropertyWellAllocation__c>> revenuePropertyMap = new Map<Id, List<revenuePropertyWellAllocation__c>>();
		for(RevenuePropertyWellAllocation__c revenuePropertyWellAllocation: revenuePropertyWellAllocations){
			revenuePropertyIds.add(revenuePropertyWellAllocation.revenueProperty__c);
			/*if(revenuePropertyMap.get(revenuePropertyWellAllocation.revenueProperty__c) != null){
				revenuePropertyMap.get(revenuePropertyWellAllocation.revenueProperty__c).add(revenuePropertyWellAllocation);
			}
			else{
				List<revenuePropertyWellAllocation__c> tempList = new List<revenuePropertyWellAllocation__c>();
				tempList.add(revenuePropertyWellAllocation);
				revenuePropertyMap.put(revenuePropertyWellAllocation.revenueProperty__c, tempList);
			}*/
		}
		System.debug(revenuePropertyIds);
		/*List<Royalty_Line_Item__c> royaltyCheckLineItems = [SELECT adjustmentCode__c,CreatedById,CreatedDate,detailId__c,grossAdjustmentsActual__c,grossNetActual__c,grossTaxesActual__c,grossValueActual__c,
															grossValueAfterAdjustments__c,grossValue__c,grossVolumeActual__c,Id,interestType__c,IsDeleted,isLastProductionMonth__c,isNonWellLineItem__c,
															LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,lineItemDecimal__c,line_Item_Net_Val__c,Name,net_Adjustments__c,
															net_Taxes__c,net_Value__c,notes__c,operatorName__c,ownerAdjustmentsActual__c,ownerNetValueActual__c,ownerTaxesActual__c,ownerValueActual__c,
															ownerVolumeActual__c,price__c,productCode__c,productionMonthCalc__c,production_Month__c,product_Category__c,product__c,propertyName__c,
															property_Id__c,revenueAllocated__c,revenueProperty__c,royalty_Check__c,source__c,SystemModstamp,totalAllocatedAmount__c,type__c,
															wellNames__c,well__c 
															FROM Royalty_Line_Item__c
															WHERE revenueProperty__c IN: revenuePropertyIds
															ORDER BY CreatedDate DESC 
															LIMIT 40000];
															*/
		//return royaltyCheckLineItems;
		return revenuePropertyIds;
	}

}