src/objects/revenueProperty__c.object
<CustomObject>
    <fields>
        <fullName>api10__c</fullName>
        <description>This field stores a set of API10 values which are associated to the property name.</description>
        <label>API10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>royaltyChecks__c</fullName>
        <description>This field stores a set of royalty check Ids which are associated to the property name.</description>
        <label>Royalty Checks</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>wells__c</fullName>
        <label>Wells</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Revenue Property</label>
    <nameField>
        <displayFormat>Revenue Property-{00000}</displayFormat>
        <label>Revenue Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RevenuePropertyWellAllocation__c.object
<CustomObject>
    <fields>
        <fullName>revenueProperty__c</fullName>
        <label>Revenue Property</label>
        <referenceTo>revenueProperty__c</referenceTo>
        <relationshipLabel>Revenue Property Well Allocations</relationshipLabel>
        <relationshipName>Revenue_Property_Well_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>well__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Revenue Property Well Allocations</relationshipLabel>
        <relationshipName>Revenue_Property_Well_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Property Well Allocation</label>
    <nameField>
        <displayFormat>RPW-{000000000}</displayFormat>
        <label>Revenue Property Well Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Property Well Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <description>API/Unique Well Identifier (10 Digit)</description>
        <externalId>true</externalId>
        <inlineHelpText>API/Unique Well Identifier (10 Digit)</inlineHelpText>
        <label>API10</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/updateRevenuePropertiesWell_Batch.cls
global class updateRevenuePropertiesWell_Batch implements Database.batchable<sObject >{
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        String soqlQuery = 'SELECT Id,propertyName__c,royaltyChecks__c,API10__c  From revenueProperty__c';
        return Database.getQueryLocator(soqlQuery);
    }
    
    global void execute(Database.batchableContext info, List<revenueProperty__c > scope){ 
        String[] wells = scope[0].API10__c.split(',');
        List<revenuePropertyWellAllocation__c> rpwList = new List<revenuePropertyWellAllocation__c>();
        revenuePropertyWellAllocation__c rpw;
        List<String> wellNames = new List<String>();
        for(well__c well:[Select Id,Name from Well__C where API10__c In: wells]){
            rpw = new revenuePropertyWellAllocation__c();
            rpw.revenueProperty__c = scope[0].Id;
            rpw.well__c = well.Id;
            rpwList.add(rpw);
            wellNames.add(well.Name);
        }
        insert rpwList;
        scope[0].wells__c = String.join(wellNames,',');
        update scope;
    } 
    
    global void finish(Database.batchableContext info){  
        
    }
    
}