src/objects/revenueProperty__c.object
<CustomObject>
    <fields>
        <fullName>api10__c</fullName>
        <description>This field stores a set of API10 values which are associated to the property name.</description>
        <label>API10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>operatorName__c</fullName>
        <label>Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>royaltyChecks__c</fullName>
        <description>This field stores a set of royalty check Ids which are associated to the property name.</description>
        <label>Royalty Checks</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>uniqueKey__c</fullName>
        <description>This field stores the concatenation of Property Name + Operator Name</description>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Revenue Property</label>
    <nameField>
        <displayFormat>Revenue Property-{00000}</displayFormat>
        <label>Revenue Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Operator_Name__c</fullName>
        <description>Name of Operator related to check</description>
        <inlineHelpText>Name of Operator related to check</inlineHelpText>
        <label>Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/updateRevenuePropertiesOPName_Batch.cls
global class updateRevenuePropertiesOPName_Batch implements Database.batchable<sObject >{
    
    
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        String soqlQuery = 'SELECT Id,propertyName__c,royaltyChecks__c,API10__c  From revenueProperty__c where OperatorName__c=null';
        return Database.getQueryLocator(soqlQuery);
    }
    
    global void execute(Database.batchableContext info, List<revenueProperty__c > scope){ 
        if(scope[0].royaltyChecks__c!='' && scope[0].royaltyChecks__c!=null){
            String[] rcIds = scope[0].royaltyChecks__c.split(',');
            List<Royalty_Check__c> rlist = [Select Id,Operator_Name__c from Royalty_Check__c where Id In: rcIds];
            Set<String> OpSet = new Set<String>();
            for(Royalty_Check__c rc : rlist){
                OpSet.add(rc.Operator_Name__c.toUpperCase());
            }
            if(!OpSet.isEmpty()){
                Integer counter = 0;
                List<revenueProperty__c> revenuePropertyList = new List<revenueProperty__c>();
                revenueProperty__c revenueProperty;
                for(String op: OpSet){
                    if(counter == 0){
                        revenueProperty = new revenueProperty__c();
                        revenueProperty.Id = scope[0].Id;
                        revenueProperty.propertyName__c = scope[0].propertyName__c;
                        revenueProperty.OperatorName__c = op;
                        revenueProperty.UniqueKey__c = scope[0].propertyName__c+'_-_'+op;
                        revenuePropertyList.add(revenueProperty);
                        counter++;
                    }else{
                        revenueProperty = new revenueProperty__c();
                        revenueProperty.propertyName__c = scope[0].propertyName__c;
                        revenueProperty.OperatorName__c = op;
                        revenueProperty.UniqueKey__c = scope[0].propertyName__c+'_-_'+op;
                        revenuePropertyList.add(revenueProperty);
                    }
                }
                if(!revenuePropertyList.isEmpty()){
                    database.upsert(revenuePropertyList,false);
                }
            }
        }
    } 
    
    global void finish(Database.batchableContext info){  
        
    }
    
}