src/objects/revenueEstimate__c.object
<CustomObject>
    <fields>
        <fullName>InactiveNotes__c</fullName>
        <description>Reason for RE being Inactive</description>
        <label>Inactive Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SRP_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SRP Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>productionMonth__c</fullName>
        <formula>monthlyProduction__r.Production_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Production Month</label>
        <type>Date</type>
    </fields>
    <label>Revenue Estimate</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>RevenueEstimate  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/DeleteUnusedRevenueEstimates_Batch.cls
global with sharing class DeleteUnusedRevenueEstimates_Batch  implements Database.Batchable<sObject>{
    global final String query;
    global date dt = system.Today().addMonths(-12);
    public DeleteUnusedRevenueEstimates_Batch() {
        this.query='Select Id from revenueEstimate__c where inactive__c = false AND productionMonth__c <=: dt AND SRP_Owned__c = false';

    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC,  List<sObject> scope){
        
        for(revenueEstimate__c rev : (List<revenueEstimate__c>)scope){
            rev.inactive__c = true;
            rev.inactiveNotes__c = 'Not SRP owned and older than 12 months';
        }
        update scope;
    }

    global void finish(Database.BatchableContext BC){
        //do nothing
    }
}