src/objects/revenueProperty__c.object
<CustomObject>
    <fields>
        <fullName>api10__c</fullName>
        <description>This field stores a set of API10 values which are associated to the property name.</description>
        <label>API10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Revenue Property</label>
    <nameField>
        <displayFormat>Revenue Property-{00000}</displayFormat>
        <label>Revenue Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RevenuePropertyWellAllocation__c.object
<CustomObject>
    <fields>
        <fullName>revenueProperty__c</fullName>
        <label>Revenue Property</label>
        <referenceTo>revenueProperty__c</referenceTo>
        <relationshipLabel>Revenue Property Well Allocations</relationshipLabel>
        <relationshipName>Revenue_Property_Well_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>splitPercent__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Percentage of revenue applied to well</description>
        <inlineHelpText>Percentage of revenue applied to well</inlineHelpText>
        <label>Split Percent</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>well__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Well</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Revenue Property Well Allocations</relationshipLabel>
        <relationshipName>Revenue_Property_Well_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Property Well Allocation</label>
    <nameField>
        <displayFormat>RPW-{000000000}</displayFormat>
        <label>Revenue Property Well Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Property Well Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Check_Issue_Date__c</fullName>
        <description>Date Check was Issued</description>
        <inlineHelpText>Date Check was Issued</inlineHelpText>
        <label>Check Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <externalId>true</externalId>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payee_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Royalty Checks</relationshipLabel>
        <relationshipName>Royalty_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payor_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Royalty Checks (Payor)</relationshipLabel>
        <relationshipName>Royalty_Checks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>of_Allocated_Line_Items__c</fullName>
        <label># of Allocated Line Items</label>
        <summaryFilterItems>
            <field>Royalty_Line_Item__c.revenueAllocated__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Royalty_Line_Item__c.royalty_Check__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>of_Unallocated_Line_Items__c</fullName>
        <label># of Unallocated Line Items</label>
        <summaryFilterItems>
            <field>Royalty_Line_Item__c.revenueAllocated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Royalty_Line_Item__c.royalty_Check__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>ownerNetValueActual__c</fullName>
        <label>Owner Net Value Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>revenueProperty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Property</label>
        <referenceTo>revenueProperty__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>royalty_Check__c</fullName>
        <description>Royalty Check</description>
        <label>Royalty Check</label>
        <referenceTo>Royalty_Check__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>well__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Well (Discarded)</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Royalty Line Items (Well)</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <description>API/Unique Well Identifier (10 Digit)</description>
        <externalId>true</externalId>
        <inlineHelpText>API/Unique Well Identifier (10 Digit)</inlineHelpText>
        <label>API10</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Operator_Name__c</fullName>
        <label>Current Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Operator (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>wellStatus__c</fullName>
        <formula>IF(  NOT(ISBLANK(First_Production_Month__c)) ,&apos;Producing&apos;, IF(  AND(NOT(ISBLANK(Spud_Date__c)),Today() - Spud_Date__c&gt;=730),&apos;Shut-In&apos;,IF(NOT(ISBLANK(Spud_Date__c)) ,&apos;DUC&apos;,IF(  TODAY() -  Permit_Date__c &gt;= 730 ,&apos;Expired Permits&apos; , IF(  NOT(ISBLANK(Permit_Date__c)) ,&apos;Permit&apos; ,&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Well Status</label>
        <type>Text</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/RevenuePropertyController.cls
public class RevenuePropertyController {

    @AuraEnabled
    public static List<checkWrapper> getRoyaltyCheckList(String recordId){
        try{
            Set<String> rcIds = new Set<String>();
            for(Royalty_line_item__c rli :[Select royalty_Check__c from Royalty_line_item__c where RevenueProperty__c =: recordId]){
                rcIds.add(rli.royalty_Check__c);
            }
            List<Royalty_Check__C> rcList = [Select Id, Name,of_Allocated_Line_Items__c,of_Unallocated_Line_Items__c,
                                            Payor_Lookup__c,Payor_Lookup__r.Name,Payee_Lookup__c,Payee_Lookup__r.Name,
                                            Check_Number__c,Check_Issue_Date__c,
                                            (Select Id,ownerNetValueActual__c from Line_Items__r Where RevenueProperty__c =: recordId)
                                            from Royalty_Check__c where Id In: rcIds];
            List<checkWrapper> checkList = new List<checkWrapper>();
            checkWrapper check;
            Decimal ownerNetValue;
            for(Royalty_Check__C rc: rcList){
                check = new checkWrapper();
                ownerNetValue = 0;
                check.rcId = '/'+rc.Id;
                check.name = rc.Name;
                check.countRLI = rc.Line_Items__r.size();
                check.payor = rc.Payor_Lookup__r.Name;
                check.payorId = rc.Payor_Lookup__c!=null?'/'+rc.Payor_Lookup__c:'';
                check.payee = rc.Payee_Lookup__r.Name;
                check.payeeId = rc.Payee_Lookup__c!=null?'/'+rc.Payee_Lookup__c:'';
                check.checkNumber = rc.Check_Number__c;
                check.checkDate = rc.Check_Issue_Date__c;
                for(Royalty_line_item__c rli: rc.Line_Items__r){
                    ownerNetValue += rli.ownerNetValueActual__c!=null?rli.ownerNetValueActual__c:0;
                }
                check.ownerNetValue = ownerNetValue.setScale(2);
                checkList.add(check);
            }
            return checkList;
        }catch(Exception e){
            system.debug(e.getMessage());
            system.debug(e.getStackTraceString());
            throw new AuraHandledException('Error encountered in getRoyaltyCheckList');
        }
    }
    
    @AuraEnabled
    public static List<wellWrapper> getWellList(String recordId){
        try{
            Map<String,Decimal> wellMap = new Map<String,Decimal>();
            for(RevenuePropertyWellAllocation__c rpw : [Select splitPercent__c, well__c from RevenuePropertyWellAllocation__c where RevenueProperty__c =: recordId]){
                wellMap.put(rpw.well__c,rpw.splitPercent__c);
            }
            List<wellWrapper> wellWrapperList = new List<wellWrapper>();
            wellWrapper wellWrap;
            for(Well__c well : [Select Id,Name,API10__c,Current_Operator__c,
                                      Current_Operator__r.Name, wellStatus__c,
                                      Current_Operator_Name__c,County__c, State__c
                                     from Well__c where Id in: wellMap.keySet()]){

                                         wellWrap = new wellWrapper();
                                         wellWrap.well = well;
                                         wellWrap.splitPercent = wellMap.get(well.Id);
                                         wellWrapperList.add(wellWrap);
                                     }
            return wellWrapperList;
        }catch(Exception e){
            throw new AuraHandledException('Error encountered in getWellList');
        }
    }
    
    public class checkWrapper{
        @AuraEnabled
        public   String rcId{get;set;}
        @AuraEnabled
        public   String name{get;set;}
        @AuraEnabled
        public   Integer countRLI{get;set;}
        @AuraEnabled
        public   String payor{get;set;}
        @AuraEnabled
        public   String payorId{get;set;}
        @AuraEnabled
        public   String payee{get;set;}
        @AuraEnabled
        public   String payeeId{get;set;}
        @AuraEnabled
        public   String checkNumber{get;set;}
        @AuraEnabled
        public   date checkDate{get;set;}
        @AuraEnabled
        public   Decimal ownerNetValue{get;set;}
    }

    public class wellWrapper{

        @AuraEnabled
        public   Well__c well{get;set;}
        @AuraEnabled
        public decimal splitPercent{get;set;}
    }

}