src/objects/revenueProperty__c.object
<CustomObject>
    <fields>
        <fullName>isNonWellRevenueProperty__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Non Well Revenue Property</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>numberOfAllocations__c</fullName>
        <label>Number of Allocations</label>
        <summaryForeignKey>RevenuePropertyWellAllocation__c.revenueProperty__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>operatorName__c</fullName>
        <label>Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>uniqueKey__c</fullName>
        <description>This field stores the concatenation of Property Name + Operator Name</description>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Revenue Property</label>
    <nameField>
        <displayFormat>Revenue Property-{00000}</displayFormat>
        <label>Revenue Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>isNonWellLineItem__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Non Well Line Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>operatorName__c</fullName>
        <formula>royalty_Check__r.Operator_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Operator Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <externalId>true</externalId>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>revenueAllocated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Revenue Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>revenueProperty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Property</label>
        <referenceTo>revenueProperty__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RoyaltyLineItemTriggerHelper.cls
Public class RoyaltyLineItemTriggerHelper {

    
    /********************
    * @description This method associates the royalty Line Items with wells based on the property Id.
    * @param List<Royalty_line_item__c>
    * @retrun void 
    ********************/
    public void associateRoyaltyLineItem(List<Royalty_Line_Item__c> newList){
        Set<String> propertyOperatorSet = new Set<String>();
        Map<String,revenueProperty__c> revenuePropertyMap = new Map<String,revenueProperty__c>();
        for(Royalty_Line_Item__c rli: newList){
            String key = rli.propertyName__c+'_-_'+rli.OperatorName__c;
            propertyOperatorSet.add(key.toUpperCase());
        }
        for(revenueProperty__c revenueProperty: [Select Id,UniqueKey__c,NumberOfAllocations__c,IsNonWellRevenueProperty__c from revenueProperty__c where uniqueKey__c in: propertyOperatorSet]){
            revenuePropertyMap.put(revenueProperty.UniqueKey__c.toUpperCase(),revenueProperty);
        }
        propertyOperatorSet.removeAll(revenuePropertyMap.keySet());
        List<revenueProperty__c> revenuePropertyList = new List<revenueProperty__c>();
        for(String propertyOperator: propertyOperatorSet){
            String[] propertyOperatorArray = propertyOperator.split('_-_');
            revenuePropertyList.add(new revenueProperty__c(
                propertyName__c	= propertyOperatorArray[0],
                OperatorName__c = propertyOperatorArray[1],
                UniqueKey__c = propertyOperator
            ));
        }
        if(!revenuePropertyList.isEmpty()){
            database.insert(revenuePropertyList,false);
            for(revenueProperty__c revenueProperty: revenuePropertyList){
                revenuePropertyMap.put(revenueProperty.UniqueKey__c,revenueProperty);
            }
        }
        revenueProperty__c revenueProperty;
        for(Royalty_Line_Item__c rli: newList){
            String key = rli.propertyName__c+'_-_'+rli.OperatorName__c;
            if(revenuePropertyMap.containsKey(key.toUpperCase())){
                revenueProperty = revenuePropertyMap.get(key.toUpperCase());
                rli.revenueProperty__c = revenueProperty.Id;
                if(revenueProperty.NumberOfAllocations__c>0){
                    rli.revenueAllocated__c = true;
                }
                if(revenueProperty.IsNonWellRevenueProperty__c == true){
                    rli.isNonWellLineItem__c = true;
					rli.revenueAllocated__c = true;
                }

            }
        }
    }

}