src/objects/revenueProperty__c.object
<CustomObject>
    <fields>
        <fullName>operatorName__c</fullName>
        <label>Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>uniqueKey__c</fullName>
        <description>This field stores the concatenation of Property Name + Operator Name</description>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Revenue Property</label>
    <nameField>
        <displayFormat>Revenue Property-{00000}</displayFormat>
        <label>Revenue Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>operatorName__c</fullName>
        <formula>royalty_Check__r.Operator_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Operator Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <externalId>true</externalId>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>revenueProperty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Property</label>
        <referenceTo>revenueProperty__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/updateRevenuePropertiesRLI_Batch.cls
global class updateRevenuePropertiesRLI_Batch implements Database.batchable<sObject >{
    
    
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        String soqlQuery = 'SELECT Id,propertyName__c,operatorName__c  From royalty_line_item__c where revenueProperty__c=null Order by propertyName__c';
        return Database.getQueryLocator(soqlQuery);
    }
    
    global void execute(Database.batchableContext info, List<royalty_line_item__c > scope){ 
        Set<String> uniqueKeySet = new Set<String>();
        String key='';
        for(royalty_line_item__c rli: scope){
            key =rli.propertyName__c+'_-_'+rli.operatorName__c;
            uniqueKeySet.add(key.toUpperCase());
        }
        Map<String,String> revenuePropertyMap = new Map<String,String>();
        for(revenueProperty__c revenueProperty: [Select Id, uniqueKey__c from revenueProperty__c where uniqueKey__c in:uniqueKeySet]){
            revenuePropertyMap.put(revenueProperty.uniqueKey__c.toupperCase(),revenueProperty.Id);
        }
        for(royalty_line_item__c rli:scope){
            key =rli.propertyName__c+'_-_'+rli.operatorName__c;
            rli.revenueProperty__c = revenuePropertyMap.get(key.toUpperCase());
        }
        update scope;

    } 
    
    global void finish(Database.batchableContext info){  
        
    }
    
}