src/objects/revenueProperty__c.object
<CustomObject>
    <fields>
        <fullName>propertyName__c</fullName>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>royaltyChecks__c</fullName>
        <description>This field stores a set of royalty check Ids which are associated to the property name.</description>
        <label>Royalty Checks</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Revenue Property</label>
    <nameField>
        <displayFormat>Revenue Property-{00000}</displayFormat>
        <label>Revenue Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>propertyName__c</fullName>
        <externalId>true</externalId>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>revenueProperty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Property</label>
        <referenceTo>revenueProperty__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>royalty_Check__c</fullName>
        <description>Royalty Check</description>
        <label>Royalty Check</label>
        <referenceTo>Royalty_Check__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/updateRevenueProperties_Batch.cls
global class updateRevenueProperties_Batch implements Database.batchable<sObject >{
    
    
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        String soqlQuery = 'SELECT Id,royalty_check__c,propertyName__c From Royalty_line_item__c order by propertyName__c';
        return Database.getQueryLocator(soqlQuery);
    }
    
    global void execute(Database.batchableContext info, List<Royalty_line_item__c > scope){ 
        
        Map<String,Set<String>> propertyRCMap = new Map<String,Set<String>>();
        for(Royalty_line_item__c rli: scope){
            if(propertyRCMap.containsKey(rli.propertyName__c)){
                propertyRCMap.get(rli.propertyName__c.toUpperCase()).add(rli.royalty_check__c);
            }else{
                propertyRCMap.put(rli.propertyName__c.toUpperCase(),new Set<String>{rli.royalty_check__c});
            }
        }
        Set<String> rcIds;
        List<revenueProperty__c> revenuePropertyList = new List<revenueProperty__c>();
        for(revenueProperty__c revenueProperty : [Select id,propertyName__c,royaltyChecks__c 
                                                  from revenueProperty__c where propertyName__c In: propertyRCMap.keyset()]){
                                                      
                                                      rcIds = revenueProperty.royaltyChecks__c!=null?new Set<String>(revenueProperty.royaltyChecks__c.split(',')):new Set<String>();
                                                      if(propertyRCMap.get(revenueProperty.propertyName__c.toUpperCase())!=null){
                                                          rcIds.addAll(propertyRCMap.get(revenueProperty.propertyName__c.toUpperCase()));
                                                      }
                                                      
                                                      revenueProperty.royaltyChecks__c = String.join(new List<String>(rcIds),',');
                                                      revenuePropertyList.add(revenueProperty);
                                                  }
        
        update revenuePropertyList;
    } 
    
    global void finish(Database.batchableContext info){  
        
    }
    
}