src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSV</fullName>
                </value>
                <value>
                    <fullName>CDEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PropertyAssociation_Batch.cls
public class PropertyAssociation_Batch implements Database.batchable<sObject >, Database.AllowsCallouts{
	public String[] rcIds;
    public PropertyAssociation_Batch(String[] rcIds){
        this.rcIds = rcIds;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        String soqlQuery = 'Select Id from Royalty_Check__c where Id In: rcIds AND Source__c=\'CDEX\'';
        return Database.getQueryLocator(soqlQuery);
    }
    
    public void execute(Database.batchableContext info, List<sObject> scope){ 
        
        CDEXCalloutHelper.reprocessCdexCheck(scope[0].Id);
   } 
    
   public void finish(Database.batchableContext info){  
       
   }
    
}