src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSV</fullName>
                </value>
                <value>
                    <fullName>CDEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>isNonWellLineItem__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Non Well Line Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ownerNetValueActual__c</fullName>
        <label>Owner Net Value Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <externalId>true</externalId>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>revenueAllocated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Revenue Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>royalty_Check__c</fullName>
        <description>Royalty Check</description>
        <label>Royalty Check</label>
        <referenceTo>Royalty_Check__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>source__c</fullName>
        <formula>TEXT(royalty_Check__r.Source__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>well__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Well (Discarded)</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Royalty Line Items (Well)</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <description>API/Unique Well Identifier (10 Digit)</description>
        <externalId>true</externalId>
        <inlineHelpText>API/Unique Well Identifier (10 Digit)</inlineHelpText>
        <label>API10</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <inlineHelpText>Source of the well information (IHS, DrillingInfo, etc.)</inlineHelpText>
        <label>Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mnisardev/mnisarDev/force-app/main/default/classes/PropertyAssociation_Controller.cls
public class PropertyAssociation_Controller{
    /*
    //@future
    public static void reAssociateCSVChecks(String revenueProperty){
        system.debug( revenueProperty);
        revenuePropertyWrapper config = (revenuePropertyWrapper)System.JSON.deserialize(revenueProperty,revenuePropertyWrapper.class);
        List<Royalty_Line_Item__c> rliListUpdate = new List<Royalty_Line_Item__c>();
        Royalty_Line_Item__c rliInstance;
        
        if(config.oldValue.size() == config.newValue.size()){
            Map<String,String> wellMap = new Map<String,String>();
            for(Integer i = 0; i<config.newValue.size() ; i++){
                wellMap.put(config.oldValue[i],config.newValue[i]);
            }
            List<Royalty_Line_Item__c> rliList = [Select Id,well__r.API10__c,well__c
                            from Royalty_Line_Item__c 
                            where propertyName__c =: config.propertyName
                            AND (Royalty_Check__r.Source__c = 'CSV' OR Royalty_Check__r.Source__c = '')
                            order by well__c];
            for(Royalty_Line_Item__c rli : rliList){
                rliInstance = new Royalty_Line_Item__c(Id = rli.Id);
                if(wellMap.get(rli.well__r.API10__c) =='NONWELLITEM'){
                    rliInstance.Well__c = null;
                    rliInstance.isNonWellLineItem__c = true;
                    rliInstance.revenueAllocated__c = true;
                    System.debug('non');
                }else{
                    if(rli.well__c!=null && wellMap.containsKey(rli.well__r.API10__c)){
                        rliInstance.Well__r = new well__c(API10__c = wellMap.get(rli.well__r.API10__c));
                    }else{
                        rliInstance.Well__r =  new well__c(API10__c = wellMap.get( 'NONWELLITEM'));
                    }
                   
                }
                rliListUpdate.add(rliInstance);
            }
            update rliListUpdate;
        }else if(config.oldValue.size() > config.newValue.size()){
            Map<String,String> wellMap = new Map<String,String>();
            for(Integer i = 0; i<config.newValue.size() ; i++){
                wellMap.put(config.oldValue[i],config.newValue[i]);
            }
            
            List<Royalty_Line_Item__c> rliListDelete = new List<Royalty_Line_Item__c>();
            for(Royalty_Line_Item__c rli : [Select Id,well__r.API10__c,ownerNetValueActual__c 
                                from Royalty_Line_Item__c 
                                where propertyName__c =: config.propertyName 
                                AND Royalty_Check__r.Source__c != 'CDEX'
                                order by well__c]){
                if(wellMap.containsKey(rli.well__r.API10__c)){
                    rliInstance = new Royalty_Line_Item__c(Id = rli.Id);
                    if(wellMap.get(rli.well__r.API10__c) =='NONWELLITEM'){
                        rliInstance.Well__c = null;
                        rliInstance.isNonWellLineItem__c = true;
                        rliInstance.revenueAllocated__c = true;
                        if(rli.ownerNetValueActual__c!=null){
                            rliInstance.ownerNetValueActual__c = (rli.ownerNetValueActual__c*config.oldValue.size())/config.newValue.size();
                        }
                    }else{
                        rliInstance.Well__r = new well__c(API10__c = wellMap.get(rli.well__r.API10__c));
                        if(rli.ownerNetValueActual__c!=null){
                            rliInstance.ownerNetValueActual__c = (rli.ownerNetValueActual__c*config.oldValue.size())/config.newValue.size();
                        }
                    }
                    rliListUpdate.add(rliInstance);
                }else{
                    rliListDelete.add(rli);
                }

            }
            update rliListUpdate;
            delete rliListDelete;
        }else if(config.oldValue.size() < config.newValue.size()){
            Map<String,String> wellMap = new Map<String,String>();
            Set<String> newValueSet = new Set<String>();
            for(Integer i = 0; i<config.oldValue.size() ; i++){
                wellMap.put(config.oldValue[i],config.newValue[i]);
            }
            system.debug('----'+wellMap);
            for(String str : config.newValue){
                    newValueSet.add(str);
            }
            newValueSet.removeAll(wellMap.values());
            List<Royalty_Line_Item__c> rliListInsert = new List<Royalty_Line_Item__c>();

            Royalty_Line_Item__c newRli;
            List<String> fieldNames = new List<String>();
            for(String name: Royalty_Line_Item__c.sObjectType.getDescribe().fields.getMap().keySet()){
                fieldNames.add(name);
            }

            for(Royalty_Line_Item__c rli : Database.query('select ' + string.join(fieldNames, ',') +',well__r.API10__c'+ ' from Royalty_Line_Item__c'
                                +' where propertyName__c =\''+ config.propertyName+'\''
                                +' AND Royalty_Check__r.Source__c != \'CDEX\'')){
                                    
                    rliInstance = new Royalty_Line_Item__c(Id=rli.Id);
                    if(wellMap.get(rli.well__r.API10__c) =='NONWELLITEM'){
                        rliInstance.Well__c = null;
                        rliInstance.isNonWellLineItem__c = true;
                        rliInstance.revenueAllocated__c = true;
                        if(rli.ownerNetValueActual__c!=null){
                            rliInstance.ownerNetValueActual__c = (rli.ownerNetValueActual__c*config.oldValue.size())/config.newValue.size();
                        }
                    }else{
                         system.debug('-ELSE---');
                        if(rli.well__c!=null && wellMap.containsKey(rli.well__r.API10__c)){
                             system.debug('--ELSE--'+wellMap.get(rli.well__r.API10__c));
                        	rliInstance.Well__r = new well__c(API10__c = wellMap.get(rli.well__r.API10__c));
                        }else{
                            system.debug('--oldValue--'+wellMap.get( 'NONWELLITEM'));
                            rliInstance.Well__r =  new well__c(API10__c = wellMap.get( 'NONWELLITEM'));
                        }
                        if(rli.ownerNetValueActual__c!=null){
                            rliInstance.ownerNetValueActual__c = (rli.ownerNetValueActual__c*config.oldValue.size())/config.newValue.size();
                        }
                        
                    }
                    rliListUpdate.add(rliInstance);
                
                if(config.oldValue[0]==rli.well__r.API10__c || config.oldValue[0]== 'NONWELLITEM'){      
                    for(String api10 : newValueSet){
                                system.debug('2'+api10);
                        newRli = rli.clone(false,false,false,false);
                        Map<String,Object> objMap = (Map<String,Object>)JSON.deserializeUntyped( JSON.serialize( newRli ) );
                        objMap.remove('Well__c');
                        newRli = (Royalty_Line_Item__c)(JSON.deserialize(System.JSON.serialize(objMap), Royalty_Line_Item__c.class));
                        newrli.Well__r = new well__c(API10__c = api10);
                        if(rli.ownerNetValueActual__c!=null){
                            newrli.ownerNetValueActual__c = (rli.ownerNetValueActual__c*config.oldValue.size())/config.newValue.size();
                        }
                        newRLI.revenueAllocated__c = true;
                        rliListInsert.add(newRLI);
                    }
                }
            }
            system.debug(rliListUpdate.size());
            system.debug(rliListInsert.size());
            update rliListUpdate;
            insert rliListInsert;
        }else{
            //Do Nothing
        }
    }

    public class revenuePropertyWrapper{
        public string propertyName;
        public String[] oldValue;
        public string[] newValue;
    }*/
}