src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Total Check Amount</description>
        <inlineHelpText>Total Check Amount</inlineHelpText>
        <label>Check Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Issue_Date__c</fullName>
        <description>Date Check was Issued</description>
        <inlineHelpText>Date Check was Issued</inlineHelpText>
        <label>Check Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <externalId>true</externalId>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Owner_Number__c</fullName>
        <label>Owner Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoyaltyCheckExtensionTest.cls
@isTest
public class RoyaltyCheckExtensionTest {

    static testMethod void testRoyaltyCheckExtension() {

        Test.startTest();

        Royalty_Check__c chk = new Royalty_Check__c();
        ApexPages.StandardController sc = new ApexPages.StandardController(chk);
        PageReference pageRef = Page.RoyaltyCheckEdit;
        pageRef.getParameters().put('on', 'SM');
        Test.setCurrentPage(pageRef);
        RoyaltyCheckExtension rc = new RoyaltyCheckExtension(sc);

        Royalty_Check__c rc1 = rc.selCheck;
        rc.save();
       /* rc1.Payee__c = 'n';
        rc1.Payee__c = 'na';
        rc1.Payor__c = 'fufu'; */
        rc1.Amount__c = 4.44;
        rc1.Check_Issue_Date__c = Date.valueOf('2019-07-24');
        rc1.Owner_Number__c = '1293';
        rc1.Check_Number__c = 'E394867';
        rc1.Notes__c = 'H';
        rc.save();
        rc.saveNew();

        Test.stopTest();


    }
}