src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Total Check Amount</description>
        <inlineHelpText>Total Check Amount</inlineHelpText>
        <label>Check Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Issue_Date__c</fullName>
        <description>Date Check was Issued</description>
        <inlineHelpText>Date Check was Issued</inlineHelpText>
        <label>Check Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <externalId>true</externalId>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Unique Check Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Operator_Name__c</fullName>
        <description>Name of Operator related to check</description>
        <inlineHelpText>Name of Operator related to check</inlineHelpText>
        <label>Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Number__c</fullName>
        <label>Owner Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoyaltyCheckExtension.cls
/**
 * Created by Nathan.Shulman on 7/17/2019.
 */

public with sharing class RoyaltyCheckExtension {
    public Royalty_Check__c selCheck {get; set;}
    public String operatorName {get; set;}

    public String getUniqueName() {
        // Build the name to display
        String UniqueString =  '';//(selCheck.Payor__c == null ? '[payor]' : selCheck.Payor__c);
        UniqueString += ' #' + (selCheck.Check_Number__c == null ? '[check no.]' : selCheck.Check_Number__c);
        UniqueString += ' ' + (selCheck.Check_Issue_Date__c == null ? '[date]' : selCheck.Check_Issue_Date__c.format());
        UniqueString += ' $' + (selCheck.Amount__c == null ? '[amt]' : String.valueOf(selCheck.Amount__c));
        return UniqueString;
    }

    public RoyaltyCheckExtension (ApexPages.StandardController rcController) {
        // Create a new check, or load existing check
        Id selId = rcController.getId();
        if (selCheck == null && selId == null) {
            selCheck = new Royalty_Check__c();
            operatorName = ApexPages.currentPage().getParameters().get('on');
            if (operatorName != null) {
                System.debug('op ' + operatorName);
                selCheck.Operator_Name__c = operatorName;
                //selCheck.Payor__c = operatorName;
            }
        } else {
            selCheck = [SELECT Id, Name, Operator_Name__c, Amount__c, Check_Issue_Date__c, Owner_number__c,
                    Check_Number__c, Description__c,  Notes__c
            FROM Royalty_Check__c WHERE Id =: selId];
        }
    }

    public PageReference saveNew() {
        return saveCheck(Page.RoyaltyCheckEdit);
    }

    public PageReference save() {
        return saveCheck(null);
    }

    private PageReference saveCheck(PageReference nextPage) {
        Boolean isValid = true;

        /*if (String.IsBlank(selCheck.Payor__c)) {
            isValid = false;
            selCheck.Payor__c.addError('Payor is required.');
        }*/

        if (String.IsBlank(selCheck.Operator_Name__c)) {
            isValid = false;
            selCheck.Operator_Name__c.addError('Operator is required.');
        }

        if (String.IsBlank(selCheck.Check_Number__c)) {
            isValid = false;
            selCheck.Check_Number__c.addError('Check Number is required.');
        }

        if (selCheck.Check_Issue_Date__c == null) {
            isValid = false;
            selCheck.Check_Issue_Date__c.addError('Issue Date is required.');
        }

        if (selCheck.Amount__c == null) {
            isValid = false;
            selCheck.Amount__c.addError('Amount is required.');
        }

        if (isValid) {
            selCheck.Description__c = getUniqueName();
            upsert selCheck;
            PageReference tractPage = nextPage;
            if (tractPage == null) {
                tractPage = new PageReference('/'+selCheck.Id);
            }

            tractPage.setRedirect(true);
            return tractPage;
        }
        else {
            return null;
        }

    }
}