src/objects/Royalty_Check__c.object
<CustomObject>
    <description>Check received from an  operator</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Total Check Amount</description>
        <inlineHelpText>Total Check Amount</inlineHelpText>
        <label>Check Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Issue_Date__c</fullName>
        <description>Date Check was Issued</description>
        <inlineHelpText>Date Check was Issued</inlineHelpText>
        <label>Check Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <externalId>true</externalId>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Royalty Check</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Royalty Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Royalty_Line_Item__c.object
<CustomObject>
    <description>Royalty check line items</description>
    <fields>
        <fullName>grossVolumeActual__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Gross volume from royalty check from operator (5 decimal places)</description>
        <inlineHelpText>Gross volume from royalty check from operator (5 decimal places)</inlineHelpText>
        <label>Gross Volume Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lineItemDecimal__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Royalty check line item well interest / distribution decimal from operator.</description>
        <inlineHelpText>Royalty check line item well interest / distribution decimal from operator.</inlineHelpText>
        <label>Line Item Decimal</label>
        <precision>11</precision>
        <required>true</required>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ownerNetValueActual__c</fullName>
        <label>Owner Net Value Actual</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>Price from operator royalty check line item (4 decimal places)</description>
        <inlineHelpText>Price from operator royalty check line item (4 decimal places)</inlineHelpText>
        <label>Price</label>
        <precision>11</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>production_Month__c</fullName>
        <label>Production Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>propertyName__c</fullName>
        <externalId>true</externalId>
        <label>Property Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>royalty_Check__c</fullName>
        <description>Royalty Check</description>
        <label>Royalty Check</label>
        <referenceTo>Royalty_Check__c</referenceTo>
        <relationshipLabel>Royalty Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>well__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Well (Discarded)</label>
        <referenceTo>Well__c</referenceTo>
        <relationshipLabel>Royalty Line Items (Well)</relationshipLabel>
        <relationshipName>Royalty_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Royalty Line Item</label>
    <nameField>
        <displayFormat>LI-{000000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>API10__c</fullName>
        <description>API/Unique Well Identifier (10 Digit)</description>
        <externalId>true</externalId>
        <inlineHelpText>API/Unique Well Identifier (10 Digit)</inlineHelpText>
        <label>API10</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoyaltyLineItemTriggerHandler_Test.cls
@isTest
public class RoyaltyLineItemTriggerHandler_Test{

    @isTest
    public static void testMedhod1(){
        
        Well__c wellRec = new Well__c();
        wellRec.Name = 'TestWell';
        wellRec.API10__c ='9501724908';
        insert wellRec;
        
        Royalty_Check__c rcRec = new Royalty_Check__c();
        rcRec.Amount__c = 100.50;
        rcRec.Check_Issue_Date__c = system.today();
        rcRec.Check_Number__c = '123123123';
        insert rcRec;

        Royalty_Line_Item__c rliRec = new Royalty_Line_Item__c();
        rliRec.Royalty_Check__c = rcRec.id;
        //rliRec.Type__c = 'Revenue';
        rliRec.Production_Month__c = system.today();
        rliRec.ownerNetValueActual__c = 123;
        rliRec.lineItemDecimal__c = 0.00012122;
        rliRec.grossVolumeActual__c = 230.50;
        rliRec.Price__c  = 200;
        rliRec.propertyName__c = 'Test';
        insert rliRec;

        Test.startTest();
        rliRec.ownerNetValueActual__c = 123;
        update rliRec;
        Test.stopTest();


    }
}