src/objects/RRCLease__c.object
<CustomObject>
    <fields>
        <fullName>legalDescription__c</fullName>
        <label>Legal Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>permitAcresUserOverride__c</fullName>
        <label>Permit Acres User Override</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rrcLeaseNumber__c</fullName>
        <label>RRC Lease Number</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RRC Lease</label>
    <nameField>
        <displayFormat>RRCL-{0000000000}</displayFormat>
        <label>RRC Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RRC Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TaxRollInterest__c.object
<CustomObject>
    <description>Tax Roll Interest to be imported from Drilling Info files.</description>
    <fields>
        <fullName>account__c</fullName>
        <formula>taxRollOwner__r.account__r.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>calculatedInterest__c</fullName>
        <formula>if( interestType__c != &apos;NRI&apos;,  interest__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calculated Interest</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>countyName__c</fullName>
        <label>County Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>estimatedAcreage__c</fullName>
        <formula>calculatedInterest__c  *  permitsWithAcreage__c * 8</formula>
        <label>Estimated Acreage</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>interestType__c</fullName>
        <label>Interest Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>interest__c</fullName>
        <label>Interest</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>legalDescription__c</fullName>
        <label>Legal Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>permitAcresUserOverride__c</fullName>
        <formula>rrcLease__r.permitAcresUserOverride__c</formula>
        <label>Permit Acres User Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>permitsWithAcreage__c</fullName>
        <formula>if(ISBLANK(rrcLease__r.permitAcresUserOverride__c), if(ISBLANK(rrcLease__r.texasPermitWithAcre__c),0,rrcLease__r.texasPermitWithAcre__r.permittedAcres__c), rrcLease__r.permitAcresUserOverride__c)</formula>
        <label>Permits with Acreage</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rrcLeaseNumber__c</fullName>
        <formula>rrcLease__r.rrcLeaseNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RRC Lease Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rrcLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RRC Lease</label>
        <referenceTo>RRCLease__c</referenceTo>
        <relationshipLabel>Tax Roll Interests</relationshipLabel>
        <relationshipName>TaxRollInterests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>taxRollOwnerName__c</fullName>
        <formula>taxRollOwner__r.ownerName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Roll Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>taxRollOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tax Roll Owner</label>
        <referenceTo>TaxRollOwner__c</referenceTo>
        <relationshipLabel>Tax Roll Interests</relationshipLabel>
        <relationshipName>TaxRollInterests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>taxValue__c</fullName>
        <label>Tax Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>year__c</fullName>
        <label>Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tax Roll Interest</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Tax Roll Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Roll Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TaxRollOwner__c.object
<CustomObject>
    <fields>
        <fullName>account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax Roll Owners</relationshipLabel>
        <relationshipName>TaxRollOwners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ownerName__c</fullName>
        <label>Owner Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Tax Roll Owner</label>
    <nameField>
        <displayFormat>TRON-{0000000000}</displayFormat>
        <label>Tax Roll Owner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Roll Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/taxRollRelatedListAura.cls
public with sharing class taxRollRelatedListAura  {
	@AuraEnabled
    public static List<TaxRollInterest__c> getTaxRollOwnerInterests(Id recordId) {
		List<TaxRollInterest__c> taxRollInterests = new List<TaxRollInterest__c>();
        taxRollInterests = [SELECT	account__c, calculatedInterest__c, countyName__c, CreatedById, CreatedDate, estimatedAcreage__c, Id, interest__c, interestType__c, IsDeleted, LastActivityDate,
						 LastModifiedById, LastModifiedDate, LastReferencedDate, LastViewedDate, legalDescription__c, Name, OwnerId, permitAcresUserOverride__c, permitsWithAcreage__c, rrcLease__c,
						 rrcLeaseNumber__c, SystemModstamp, taxRollOwner__c, taxRollOwnerName__c, taxValue__c, year__c, taxRollOwner__r.ownerName__c, rrcLease__r.Name, taxRollOwner__r.account__r.Name
						 FROM TaxRollInterest__c
						 WHERE taxRollOwner__c =: recordId
						 ORDER by Name
        ];
        return taxRollInterests;
    }

	@AuraEnabled
    public static List<TaxRollInterest__c> getRRCLeaseInterests(Id recordId) {
		List<TaxRollInterest__c> taxRollInterests = new List<TaxRollInterest__c>();
        taxRollInterests = [SELECT	account__c, calculatedInterest__c, countyName__c, CreatedById, CreatedDate, estimatedAcreage__c, Id, interest__c, interestType__c, IsDeleted, LastActivityDate,
						 LastModifiedById, LastModifiedDate, LastReferencedDate, LastViewedDate, legalDescription__c, Name, OwnerId, permitAcresUserOverride__c, permitsWithAcreage__c, rrcLease__c,
						 rrcLeaseNumber__c, SystemModstamp, taxRollOwner__c, taxRollOwnerName__c, taxValue__c, year__c, taxRollOwner__r.ownerName__c, rrcLease__r.Name, taxRollOwner__r.account__r.Name
						 FROM TaxRollInterest__c
						 WHERE rrcLease__c =: recordId
						 ORDER by Name
        ];
        return taxRollInterests;
    }

}