src/objects/srpFieldHistory__c.object
<CustomObject>
    <description>Used for storing history of changes by object and field.</description>
    <fields>
        <fullName>fieldName__c</fullName>
        <description>Name of the field on the related Record that was changed.</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>recordId__c</fullName>
        <externalId>true</externalId>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <label>SObject Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>SRP Field History</label>
    <nameField>
        <label>SRP Field History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SRP Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TargetOwnershipName__c.object
<CustomObject>
    <description>TON, or unique name with ownership.</description>
    <label>Target Ownership Name</label>
    <nameField>
        <displayFormat>TON-{0000000000}</displayFormat>
        <label>Target Ownership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Ownership Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TitleOwnershipDetail__c.object
<CustomObject>
    <description>Contains TORs and TOTs created during the reconciliation process between Tracts.co and Salesforce</description>
    <fields>
        <fullName>targetOwnershipName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Ownership Name</label>
        <referenceTo>TargetOwnershipName__c</referenceTo>
        <relationshipLabel>Title Ownership Details</relationshipLabel>
        <relationshipName>titleOwnershipDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>targetOwnershipTract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should only be populated on Title Ownership Rows when there is a related Target Ownership Tract</description>
        <label>Target Ownership Tract</label>
        <referenceTo>TitleOwnershipDetail__c</referenceTo>
        <relationshipLabel>Title Ownership Details</relationshipLabel>
        <relationshipName>TitleOwnershipDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Title Ownership Detail</label>
    <nameField>
        <displayFormat>TOD-{0000000000}</displayFormat>
        <label>TOD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Ownership Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TitleSourceSettings__mdt.object
<CustomObject>
    <description>For Storing values that can be updated on a Tract that reset the Title Source Field.</description>
    <label>Title Source Setting</label>
    <pluralLabel>Title Source Settings</pluralLabel>
</CustomObject>

src/objects/TitleWorkJob__c.object
<CustomObject>
    <description>Contains details pertaining to running title for a particular area.  Includes Landmen, Integration Review, and Attorney Review records.</description>
    <fields>
        <fullName>completionDate__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Landman</fullName>
                    <default>true</default>
                    <label>Landman</label>
                </value>
                <value>
                    <fullName>Integration Review</fullName>
                </value>
                <value>
                    <fullName>Attorney Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Title Work Job</label>
    <nameField>
        <displayFormat>TWJ-{0000000000}</displayFormat>
        <label>Title Work Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Work Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>titleSourceResetDate__c</fullName>
        <description>System field used for determining last edit to field that indicates Title Source functionality should be reset.</description>
        <label>Title Source Reset Date</label>
        <type>DateTime</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/tractReconciliation__c.object
<CustomObject>
    <description>Record relating a Title Ownership Detail TOT record to a Tract Record.  Created during Tract Reconciliation process.</description>
    <fields>
        <fullName>Tract__c</fullName>
        <description>Relationship to the Tract Record</description>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipLabel>Tract Reconciliations</relationshipLabel>
        <relationshipName>Tract_Reconciliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>targetOwnershipTract__c</fullName>
        <description>Relationship to the Title Ownership Detail TOT record.</description>
        <label>Target Ownership Tract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TitleOwnershipDetail__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Target_Ownership_Tract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TitleOwnershipDetail__c</referenceTo>
        <relationshipLabel>Tract Reconciliations</relationshipLabel>
        <relationshipName>Tract_Reconciliation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tract Reconciliation</label>
    <nameField>
        <displayFormat>TR-{0000000000}</displayFormat>
        <label>Tract Reconciliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tract Reconciliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tractUtility.cls
public class tractUtility  {
	
	static final List<TitleSourceSettings__mdt> titleSourceSettings = [SELECT Label, DeveloperName FROM TitleSourceSettings__mdt];

	public static void updateTitleSourceResetDate(List<Tract__c> triggerNew, List<Tract__c> triggerOld, Map<Id, Tract__c> newMap, Map<Id, Tract__c> oldMap){
		System.debug('reset title source date called');
		Set<String> titleSourceFieldSet = new Set<String>();
		describerUtil describerUtility = new describerUtil();
		describerUtility.selectedObject = 'Tract__c';
		Map<String, Schema.SObjectField> fieldMap = describerUtility.getFields();
		for(TitleSourceSettings__mdt tss : titleSourceSettings){
			titleSourceFieldSet.add(tss.Label.toLowerCase());
			System.debug('fieldList includes: ' + tss.Label);
		}
		for(Id updateId: newMap.keySet()){
			for(String fieldName: fieldMap.keySet()){
				//System.debug('Field Type is: ' + fieldMap.get(fieldName).getDescribe().getType());
				System.debug('Field Name is: ' + fieldName  );
				
				//System.debug('Reference Target Field value: ' + fieldMap.get(fieldName).getDescribe().getReferenceTargetField());
				
				System.debug('if check newMap.get(updateId).get(fieldName) != oldMap.get(updateId).get(fieldName) value is: ' + (newMap.get(updateId).get(fieldName) != oldMap.get(updateId).get(fieldName)));
				System.debug('if check titleSourceFieldSet.contains(fieldName) value is: ' + titleSourceFieldSet.contains(fieldName));
				if((newMap.get(updateId).get(fieldName) != oldMap.get(updateId).get(fieldName))  && titleSourceFieldSet.contains(fieldName) ){
					System.debug('Setting reset date to ' + newMap.get(updateId).LastModifiedDate);
					newMap.get(updateId).titleSourceResetDate__c = Datetime.now();
				}
			}
		}
		
	}

	public static Map<String, tractTitleSourceValue> getTractTitleSource(List<Tract__c> inputTracts, Map<Id, Tract__c> newMap){
		System.debug('getTractTitleSource called');
		List<String> queryIds = new List<Id>();
		Map<String, tractTitleSourceValue> returnMap = new Map<String, tractTitleSourceValue>();
		Map<String, Datetime> lastTractClearDate = new Map<String, Datetime>();
		for(Tract__c inputTract: inputTracts){
			queryIds.add(inputTract.Id);
			tractTitleSourceValue newValue = new tractTitleSourceValue();
			newValue.tractId = inputTract.Id;
			returnMap.put(inputTract.Id, newValue);
			if(newMap.get(inputTract.Id).titleSourceResetDate__c != null){
				lastTractClearDate.put(inputTract.Id, newMap.get(inputTract.Id).titleSourceResetDate__c);
			}
		}
		/*for(String tractId: queryIds){
			System.debug('Tract Ids include: ' + tractId);
		}
		List<srpFieldHistory__c> fieldHistories = new List<srpFieldHistory__c>();
		List<String> fieldList = new List<String>();
		for(TitleSourceSettings__mdt tss : titleSourceSettings){
			fieldList.add(tss.Label);
			System.debug('fieldList includes: ' + tss.Label);
		}
		//System.debug(fieldList);
		fieldHistories = [SELECT CreatedDate, recordId__c, sObjectName__c, fieldName__c 
						  FROM srpFieldHistory__c 
						  WHERE sObjectName__c = 'Tract__c'
						  AND fieldName__c IN :fieldList
						  AND recordId__c IN :queryIds];*/
		List<tractReconciliation__c> tractReconciliations = new List<tractReconciliation__c>();
		tractReconciliations = [SELECT CreatedDate,targetOwnershipTract__c,Tract__c, targetOwnershipTract__r.targetOwnershipName__r.jobId__r.titleWorkJob__r.type__c, 
									targetOwnershipTract__r.targetOwnershipName__r.jobId__r.titleWorkJob__c, LastModifiedDate,
									targetOwnershipTract__r.targetOwnershipName__r.jobId__r.titleWorkJob__r.completionDate__c
								FROM tractReconciliation__c
								WHERE Tract__c IN :queryIds];
		//Build map to determine last time the Tract had a field update that should reset the Title Source field.
		/*for(srpFieldHistory__c fieldHistory : fieldHistories){
			if(lastTractClearDate.containsKey(fieldHistory.recordId__c)){
				if(fieldHistory.CreatedDate > lastTractClearDate.get(fieldHistory.recordId__c)){
					lastTractClearDate.put(fieldHistory.recordId__c, fieldHistory.CreatedDate);
				}			
			}
			else{
				lastTractClearDate.put(fieldHistory.recordId__c, fieldHistory.CreatedDate);
			}
		}*/

		//Loop through related reconciliations and create map with the latest Title Source values for the Tract.
		for(tractReconciliation__c tractReconciliation : tractReconciliations){
			tractTitleSourceValue newValue = new tractTitleSourceValue();
			newValue.createdDate = tractReconciliation.CreatedDate;
			newValue.twj.Id = tractReconciliation.targetOwnershipTract__r.targetOwnershipName__r.jobId__r.titleWorkJob__c;
			newValue.twj.completionDate__c = tractReconciliation.targetOwnershipTract__r.targetOwnershipName__r.jobId__r.titleWorkJob__r.completionDate__c;
			newValue.twj.type__c = tractReconciliation.targetOwnershipTract__r.targetOwnershipName__r.jobId__r.titleWorkJob__r.type__c;
			newValue.titleSource = tractReconciliation.targetOwnershipTract__r.targetOwnershipName__r.jobId__r.titleWorkJob__r.type__c;
			newValue.tractId = tractReconciliation.tract__c;
			//Tract has a clear date - only inlcude reconciliation Title Source if date is greater than last clear date
			if(lastTractClearDate.containsKey(tractReconciliation.Tract__c)){
				//System.debug('Tract has a clear date of : ' + lastTractClearDate.get(tractReconciliation.Tract__c));
				System.debug('Last Tract Clear Date value is: ' + lastTractClearDate.get(tractReconciliation.Tract__c) + ' tractReconciliation Last Modified Date is: ' + tractReconciliation.LastModifiedDate +
							 ' if statement evaluates to: ' + String.valueOf(lastTractClearDate.get(tractReconciliation.Tract__c) < tractReconciliation.LastModifiedDate));
					
				if(lastTractClearDate.get(tractReconciliation.Tract__c) <= tractReconciliation.LastModifiedDate){
					if(returnMap.containsKey(tractReconciliation.Tract__c)){
						returnMap.put(tractReconciliation.Tract__c, getHighestTitleSourceValue(returnMap.get(tractReconciliation.Tract__c),newValue)); 
					}
					else{
						returnMap.put(tractReconciliation.Tract__c, newValue); 
					}
				}
			}
			//Tract does not have a clear date - include any reconciliation Title Source data
			else{
				System.debug('No clear date');
				if(returnMap.containsKey(tractReconciliation.Tract__c)){
					System.debug('Adjusting existing item in return map');
					returnMap.put(tractReconciliation.Tract__c, getHighestTitleSourceValue(returnMap.get(tractReconciliation.Tract__c),newValue)); 
				}
				else{
					System.debug('Adding new item to return map with newValue type : ' + newValue.twj.type__c);
					returnMap.put(tractReconciliation.Tract__c, newValue); 
				} 
			}
		}

		return returnMap;
	}

		

	private static tractTitleSourceValue getHighestTitleSourceValue(tractTitleSourceValue oldValue, tractTitleSourceValue newValue){
		if(oldValue.twj.type__c == 'Attorney Review' && newValue.twj.type__c == 'Attorney Review'){
			if(newValue.twj.completionDate__c > oldValue.twj.completionDate__c){
				return newValue;
			}
			else{
				return oldValue;
			}
		}
		else if(oldValue.twj.type__c == 'Attorney Review'){
			return oldValue;
		}
		else if(newValue.twj.type__c == 'Attorney Review'){
			return newValue;
		}
		else if(oldValue.twj.type__c == 'Integration Review' && newValue.twj.type__c == 'Integration Review'){
			if(newValue.twj.completionDate__c > oldValue.twj.completionDate__c){
				return newValue;
			}
			else{
				return oldValue;
			}
		}
		else if(oldValue.twj.type__c == 'Integration Review'){
			return oldValue;
		}
		else if(newValue.twj.type__c == 'Integration Review'){
			return newValue;
		}
		else if(oldValue.twj.type__c == 'Landman' && newValue.twj.type__c == 'Landman'){
			if(newValue.twj.completionDate__c > oldValue.twj.completionDate__c){
				return newValue;
			}
			else{
				return oldValue;
			}
		}
		else if(oldValue.twj.type__c == 'Landman'){
			return oldValue;
		}
		else if(newValue.twj.type__c == 'Landman'){
			return newValue;
		}
		else{
			return newValue;
		}
	}


	public class tractTitleSourceValue{
		public String tractId {get; set;}
		public TitleWorkJob__c twj {get; set;}
		public String titleSource {get; set;}
		public Datetime createdDate {get; set;}

		public tractTitleSourceValue(){
			twj = new TitleWorkJob__c();
			tractId = '';
			titleSource = '';
		}
	}
}