src/objects/srpFieldHistory__c.object
<CustomObject>
    <description>Used for storing history of changes by object and field.</description>
    <fields>
        <fullName>action__c</fullName>
        <description>Should be either Updated or Deleted.</description>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>changedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the User that made the change</description>
        <label>Changed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SRP_Field_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>conversionErrorCount__c</fullName>
        <description>Stores the number of times this record has been attempted to convert to Big Object.</description>
        <label>Conversion Error Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fieldLabel__c</fullName>
        <description>Stores the field Label at time of history item creation.</description>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fieldName__c</fullName>
        <description>Name of the field on the related Record that was changed.</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isReference__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine if the field history is actually a reference value to another field.  If this is true, oldId and newId fields should be populated.</description>
        <label>Is Reference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>lastConversionErrorFields__c</fullName>
        <description>Stores the fields returned by the last conversion error.</description>
        <label>Last Conversion Error Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>lastConversionErrorMessage__c</fullName>
        <description>Stores the message of the last conversion error.</description>
        <label>Last Conversion Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>lastConversionErrorStatus__c</fullName>
        <description>Stores the status code of the last conversion error.</description>
        <label>Last Conversion Error Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>newId__c</fullName>
        <description>Used to store the new Id value of the referenced object.</description>
        <label>New Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>newValue__c</fullName>
        <description>The value of the field after change</description>
        <label>New Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>oldId__c</fullName>
        <description>Used to store the previous Id of the related object.</description>
        <label>Old Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>oldValue__c</fullName>
        <description>The value of the field before the change</description>
        <label>Old Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>recordId__c</fullName>
        <externalId>true</externalId>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>recordName__c</fullName>
        <label>Record Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>referenceSObjectType__c</fullName>
        <description>If history is for a reference field, store the type of the object that has changed.</description>
        <label>Reference SObject Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <label>SObject Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>SRP Field History</label>
    <nameField>
        <label>SRP Field History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SRP Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SRPFieldHistoryConversionSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store values to control SRP Field History Conversion to Big Object SRP Field History records</description>
    <fields>
        <fullName>conversionSize__c</fullName>
        <description>Number of records to process in a single run.</description>
        <label>Conversion Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cronTriggerId__c</fullName>
        <description>Holds the value for the current CronTrigger</description>
        <label>cronTriggerId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>defaultStartTime__c</fullName>
        <description>Default hour in military value (i.e. 10 PM would be 22) that the next process should be started if no records remain to be converted.</description>
        <label>Default Start Time</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>emailDistribution__c</fullName>
        <description>List of addresses that error email will be sent to if a record cannot be converted within 5 tries.  Should be formatted as &apos;email@email.com&apos;, &apos;email2@email2.com&apos;</description>
        <label>Email Distribution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>minutesBetweenRuns__c</fullName>
        <description>Number of minutes to delay before running the next scheduled group if items remain.</description>
        <label>Minutes Between Runs</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SRP Field History Conversion Settings</label>
</CustomObject>

src/classes/srpFieldHistoryConversion.cls
public class srpFieldHistoryConversion  {

	private List<srpFieldHistory__c> conversionList {get; set;}
	private List<CronTrigger>currentSchedule {get; set;}
	private CronTrigger nextSchedule {get; set;}
	private Integer totalFieldHistoryCount {get; set;}
	private SRPFieldHistoryConversionSettings__c conversionSettings{get; set;}
	private String nextRunTime {get; set;}

	public srpFieldHistoryConversion(){
		this.conversionList = new List<srpFieldHistory__c>();
		//Kill existing schedule and calculate next run time
		conversionSettings = SRPFieldHistoryConversionSettings__c.getOrgDefaults();
		Integer addMinutes = Integer.valueOf(conversionSettings.minutesBetweenRuns__c);
		Integer conversionSize = Integer.valueOf(conversionSettings.conversionSize__c);
		string queryString = 'SELECT Count() FROM srpFieldHistory__c';
		totalFieldHistoryCount = Database.countQuery(queryString);
		System.debug('Total History Item Count is: ' + totalFieldHistoryCount);
		if(conversionSettings.cronTriggerId__c != null){
			currentSchedule = [SELECT ID FROM CronTrigger WHERE ID = :conversionSettings.cronTriggerId__c];
			if(currentSchedule.size()>0){
				System.abortJob(conversionSettings.cronTriggerId__c);
			}
		}
		if(totalFieldHistoryCount > conversionSettings.conversionSize__c){
			nextRunTime = '0 ' + String.valueOf(System.now().addMinutes(addMinutes).minute()) + ' ' + String.valueOf(System.now().addMinutes(addMinutes).hour() + ' ' + String.valueOf(System.now().addMinutes(addMinutes).day()) + ' ' + String.valueOf(System.now().addMinutes(addMinutes).month()) + ' ? ' + String.valueOf(System.now().addMinutes(addMinutes).year())  );
		}
		else{
			Integer daysToAdd = System.now().hour() < conversionSettings.defaultStartTime__c?0:1;
			nextRunTime = '0 00 ' + String.valueOf(Integer.valueOf(conversionSettings.defaultStartTime__c)) +' '+ String.valueOf(System.now().addDays(daysToAdd).day()) + ' ' + String.valueOf(System.now().addDays(daysToAdd).month()) + ' ? ' + String.valueOf(System.now().addDays(daysToAdd).year());
		}
		System.debug('nextRunTime value is: ' + nextRunTime);
			
			
		srpFieldHistoryConversionSchedule conversionHandler = new srpFieldHistoryConversionSchedule(); //Schedule apex class name
		conversionSettings.cronTriggerId__c = system.schedule('SRP Field History Conversion', nextRunTime, conversionHandler);
		update conversionSettings;
		//Do the work
		List<srpFieldHistory__c> initialList = [SELECT action__c,changedBy__c,conversionErrorCount__c,CreatedById,CreatedDate,fieldLabel__c,fieldName__c,Id,IsDeleted,isReference__c,
												       lastConversionErrorFields__c,lastConversionErrorMessage__c,lastConversionErrorStatus__c,LastModifiedById,LastModifiedDate,LastReferencedDate,
												       LastViewedDate,Name,newId__c,newValue__c,oldId__c,oldValue__c,OwnerId,recordId__c,recordName__c,referenceSObjectType__c,sObjectName__c 
												  FROM srpFieldHistory__c
												  ORDER BY CreatedDate DESC NULLS FIRST LIMIT :conversionSize];
		Boolean errorExists = false;
		for(srpFieldHistory__c fieldHistory: initialList){
			if(fieldHistory.conversionErrorCount__c < 5 || fieldHistory.conversionErrorCount__c == null){
				this.conversionList.add(fieldHistory);
			}
			else{
				errorExists = true;
			}
		}
		if(errorExists){
			Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
			message.toAddresses = conversionSettings.emailDistribution__c.split(';');
			message.optOutPolicy = 'FILTER';
			message.subject = 'Unable to Convert SRP Field History Record';
			message.plainTextBody = 'There is a record in srpFieldHistory__c that has failed conversion 5 times. \n Please use the following query to locate the error records:'+
									' \n\nSELECT action__c,changedBy__c,conversionErrorCount__c,CreatedById,CreatedDate,fieldLabel__c,fieldName__c,Id,IsDeleted,isReference__c,' +
									'lastConversionErrorFields__c,lastConversionErrorMessage__c,lastConversionErrorStatus__c,LastModifiedById,LastModifiedDate,LastReferencedDate,'+
									'LastViewedDate,Name,newId__c,newValue__c,oldId__c,oldValue__c,OwnerId,recordId__c,recordName__c,referenceSObjectType__c,sObjectName__c '+
									'FROM srpFieldHistory__c'+
									' WHERE conversionErrorCount__c != null'+
									' AND conversionErrorCount__c >= 5'+
									' ORDER BY CreatedDate DESC NULLS FIRST LIMIT 200';
			Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
			Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);

			if (results[0].success) {
				System.debug('The email was sent successfully.');
			} else {
				System.debug('The email failed to send: ' + results[0].errors[0].message);
			}
		}
		boSRPFieldHistoryUtility.boSRPHistoryCreate(this.conversionList);

	}
}