src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/unitAllocation__c.object
<CustomObject>
    <description>Contains the subtracts in a unit and the associated percent allocation for each subtract</description>
    <fields>
        <fullName>subtract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subtract</label>
        <referenceTo>Subtract__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Unit Allocation</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Unit Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubtractUnitAllocationController_Test.cls
@isTest
public class SubtractUnitAllocationController_Test{

    @TestSetup
    private static void makeData(){
        
        TestDataFactory.dataSetup();
		Account accRec = [Select Id from Account Limit 1];
        Unit__c unit = new Unit__c();
        unit.Operator__c = accRec.Id;
        insert unit;
	
        List<unitAllocation__c> uaList = new List<unitAllocation__c>();
        for(Subtract__c subtract : [Select Id from Subtract__c Limit 50]){
            unitAllocation__c suaRec = new unitAllocation__c();
            suaRec.subtract__c = subtract.Id;
            suaRec.unit__c = unit.Id;
            uaList.add(suaRec);
        }
        insert uaList;
    }

    @isTest
    private static void testmethod1(){
        Subtract__c subtract = [Select Id from Subtract__c Limit 1];
        Unit__c unit = [Select Id from Unit__c Limit 1];
        Tract__c tract = [Select id from Tract__c limit 1];
        Opportunity opp = [Select Id from Opportunity limit 1];
        
        Test.StartTest();
        SubtractUnitAllocationController.getRecords(opp.Id,'');
        SubtractUnitAllocationController.getRecords(tract.Id,'');
        SubtractUnitAllocationController.getRecords(subtract.Id,'');
        SubtractUnitAllocationController.getRecords(unit.Id,'');
        Test.StopTest();
    }
}