src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>netAcreageUnits__c</fullName>
        <description>Net Acreage Units (from Tract)</description>
        <formula>TEXT(Tract__r.netAcreageUnits__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Net Acreage Units (from Tract)</inlineHelpText>
        <label>Net Acreage Units</label>
        <type>Text</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current owner of the tract</description>
        <inlineHelpText>Current owner of the tract</inlineHelpText>
        <label>Owner (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracts</relationshipLabel>
        <relationshipName>Tracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Full_Legal_Name__c</fullName>
        <formula>LandGridTract__r.Name  &amp; &apos; &apos; &amp; Quarter_Call__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instrument_Type__c</fullName>
        <label>Instrument Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OGL</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ORRI</fullName>
                </value>
                <value>
                    <fullName>Surface</fullName>
                </value>
                <value>
                    <fullName>Commission</fullName>
                </value>
                <value>
                    <fullName>NPRI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTG_Cost_Per_Acre__c</fullName>
        <inlineHelpText>OTG Cost per Acre</inlineHelpText>
        <label>OTG Cost Per Acre</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTG_Cost__c</fullName>
        <formula>netAcres__c * OTG_Cost_Per_Acre__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OTG Price per acre x Net Acres</inlineHelpText>
        <label>OTG Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Per_Acre__c</fullName>
        <formula>if (netAcres__c == 0,0,Total_Cost__c /  netAcres__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Costs divided by Net Acres</inlineHelpText>
        <label>Total Cost Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>OTG Costs plus Commissions and title</description>
        <formula>(netAcres__c *  OTG_Cost_Per_Acre__c) +  Commission_Amount__c +  Title_Cost__c +  Other_Capitalized_Costs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OTG Costs plus Commissions and title</inlineHelpText>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>depth__c</fullName>
        <label>Depth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>maxPPA__c</fullName>
        <formula>if(aoiNetAcres__c &lt;&gt; 0, maxPrice__c / aoiNetAcres__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Max Price Per Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>maxPrice__c</fullName>
        <description>Max Price for Tract</description>
        <inlineHelpText>Max Price for Tract</inlineHelpText>
        <label>Max Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>netAcreageUnits__c</fullName>
        <label>Net Acreage Units</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NRA</fullName>
                </value>
                <value>
                    <fullName>NMA</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>netAcres__c</fullName>
        <label>Net Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>percentCovered__c</fullName>
        <description>Sum of percentage in AOI for project AOI tract</description>
        <inlineHelpText>Sum of percentage in AOI for project AOI tract</inlineHelpText>
        <label>percentCovered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rptPercentCovered__c</fullName>
        <description>percent covered adapted to percentage format for reporting</description>
        <formula>percentCovered__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percent Covered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>targetPPA__c</fullName>
        <formula>if(aoiNetAcres__c &lt;&gt; 0, targetPrice__c /  aoiNetAcres__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Price Per Acre</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>targetPrice__c</fullName>
        <description>Sum of target price for Project AOI Tract</description>
        <inlineHelpText>Sum of target price for Project AOI Tract</inlineHelpText>
        <label>Target Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>titleSourceType__c</fullName>
        <formula>TEXT(titleSource__r.type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title Source Type</label>
        <type>Text</type>
    </fields>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>GIS_Unit_Name__c</fullName>
        <label>GIS Unit Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Horizontal</fullName>
                </value>
                <value>
                    <fullName>Vertical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/unitAllocation__c.object
<CustomObject>
    <description>Contains the subtracts in a unit and the associated percent allocation for each subtract</description>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>allocationPercentage__c</fullName>
        <label>% of Subtract Gross Acres in Unit</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>subtract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subtract</label>
        <referenceTo>Subtract__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>uaSubtractGrossAcres__c</fullName>
        <formula>/*subtract__r.Subtract_Gross_Acres__c * (allocationPercentage__c / 100) - original formula, modifying per discussion with Andrew Kock 03-31-2020 jdg*/
subtract__r.Subtract_Gross_Acres__c * allocationPercentage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tract - Gross Acres in Unit</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>unitGrossAcres__c</fullName>
        <description>Unit gross acres estimate unless unit gross acres actual is populated.</description>
        <formula>unit__r.Gross_Acres__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Unit gross acres estimate unless unit gross acres actual is populated.</inlineHelpText>
        <label>Unit Gross Acres</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>unitNRI__c</fullName>
        <description>Subtract NRI * Allocation factor computed</description>
        <formula>subtract__r.Subtract_NRI__c * allocationFactorComputed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Subtract NRI * Allocation factor computed</inlineHelpText>
        <label>Unit NRI</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Unit Allocation</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Unit Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountRelatedListAura.cls
public class AccountRelatedListAura {
	@AuraEnabled
    public static List<SObject> getData(String recordId, Integer recordOffset, String relatedObject){
	 //Package testing
        //system.debug(inputStr);
        //inputWrapper input = (inputWrapper)JSON.deserialize(inputStr,inputWrapper.class);
		switch on relatedObject{
			when 'Tract__c'{
				return [Select Id,Name,Full_Legal_Name__c,Instrument_Type__c,Notes__c,titleSourceType__c,
				depth__c,percentCovered__c,targetPrice__c,maxPrice__c,targetPPA__c,maxPPA__c,netAcreageUnits__c,
				OTG_Cost_Per_Acre__c, OTG_Cost__c, Total_Cost_Per_Acre__c, Total_Cost__c, rptPercentCovered__c, 
				netAcres__c
				from Tract__c where Account__c =:recordId
				Limit 50 Offset :recordOffset];
			}
			when 'unitAllocation__c'{
				return[Select id,Name,unit__c,unit__r.Name,Subtract__c,Subtract__r.name,uaSubtractGrossAcres__c,unitGrossAcres__c,allocationPercentage__c,unitNRI__c,Subtract__r.Tract__r.Name,
                       Subtract__r.Tract__c,Subtract__r.Tract__r.Account__c,unit__r.GIS_Unit_Name__c,unit__r.Unit_Type__c,
                       Subtract__r.Tract__r.Account__r.Name 
					   from unitAllocation__c 
					   where subtract__r.Tract__r.Account__c =: recordId 
					   and Inactive__c = false
					   Limit 50 Offset :recordOffset];
			}
			when else{
				throw new AuraHandledException('Related Object Query not defined');
			}
		}
		
		
    }
    @AuraEnabled
    public static integer getTotalTractCount(Id recordId, String relatedObject){
        integer  count;
		switch on relatedObject{
			when 'Tract__c'{
				count= database.countQuery('SELECT count() from Tract__c WHERE Account__c = \'' + recordId + '\'');
			}
			when 'unitAllocation__c'{
				count= database.countQuery('SELECT count() from unitAllocation__c WHERE Inactive__c = false and subtract__r.Tract__r.Account__c =\'' + recordId + '\'');
			}
		}
		return count;
        //List<Tract__c> tractList =  [Select Id,Name,Full_Legal_Name__c,Instrument_Type__c,Notes__c,titleSourceType__c,
        //        depth__c,percentCovered__c,targetPrice__c,maxPrice__c,targetPPA__c,maxPPA__c,netAcreageUnits__c
        //        from Tract__c where Account__c =:recordId];
        //return tractList.size();
    }
    /*public class inputWrapper{
        
        @AuraEnabled
        public String recordId{get;set;}
        @AuraEnabled
        public Integer recordOffset{get;set;}
    }*/

}