src/objects/Subtract__c.object
<CustomObject>
    <fields>
        <fullName>Tract__c</fullName>
        <label>Tract</label>
        <referenceTo>Tract__c</referenceTo>
        <relationshipName>Instrument_Tracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtract</label>
    <nameField>
        <displayFormat>ST-{0000000000}</displayFormat>
        <label>Subtract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tract__c.object
<CustomObject>
    <label>Tract</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/unitAllocation__c.object
<CustomObject>
    <description>Contains the subtracts in a unit and the associated percent allocation for each subtract</description>
    <fields>
        <fullName>subtract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subtract</label>
        <referenceTo>Subtract__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipName>subtractUnitAllocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Unit Allocation</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Unit Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Well__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Wells</relationshipLabel>
        <relationshipName>Wells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Well</label>
    <nameField>
        <label>Well Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UnitAllocationWithTractController.cls
public class UnitAllocationWithTractController{

    @AuraEnabled
    public static list<retWrapper> getUAwithTractOwner(Id recordId){

        Well__c wellRec = [Select unit__c from well__c where Id=:recordId];

        List<unitAllocation__c> uaList = [Select Id,Subtract__r.Tract__r.Account__c,Subtract__r.Tract__r.Account__r.Name from unitAllocation__c where unit__c =: wellRec.unit__c];
        Map<Id,retWrapper> retMap = new Map<Id,retWrapper>();
        Report r = [SELECT  Id,  DeveloperName FROM Report WHERE Name = 'Wells with Unit Allocations' LIMIT 1];
        for(unitAllocation__c ua : uaList){
            if(retMap.containsKey(ua.Subtract__r.Tract__r.Account__c)){
                retWrapper values = retMap.get(ua.Subtract__r.Tract__r.Account__c);
                values.count += 1;
                retMap.put(ua.Subtract__r.Tract__r.Account__c,values);
            }else{
                retWrapper values = new retWrapper();
                values.reportURL = URL.getSalesforceBaseUrl().toExternalForm()+'/lightning/r/Report/'+string.valueOF(r.Id)+'/view';
                values.ownerId = ua.Subtract__r.Tract__r.Account__c;
                values.ownerName = ua.Subtract__r.Tract__r.Account__r.Name;
                values.count = 1;
                retMap.put(ua.Subtract__r.Tract__r.Account__c,values);
            }
        }
        return retMap.values();
    }

    public class retWrapper{
        @AuraEnabled
        public String ownerId{get;set;}
        @AuraEnabled
        public String ownerName{get;set;}
        @AuraEnabled
        public Integer count{get;set;}
        @AuraEnabled
        public String reportURL{get;set;}
    }
}