src/objects/TitleWorkJob__c.object
<CustomObject>
    <description>Contains details pertaining to running title for a particular area.  Includes Landmen, Integration Review, and Attorney Review records.</description>
    <fields>
        <fullName>startDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Attorney Review - Complete</fullName>
                    <isActive>false</isActive>
                    <label>Attorney Review - Complete</label>
                </value>
                <value>
                    <fullName>In Progress - Attorney Review</fullName>
                    <isActive>false</isActive>
                    <label>In Progress - Attorney Review</label>
                </value>
                <value>
                    <fullName>In Progress - Integration Review</fullName>
                    <isActive>false</isActive>
                    <label>In Progress - Integration Review</label>
                </value>
                <value>
                    <fullName>Integration Review - Complete</fullName>
                    <isActive>false</isActive>
                    <label>Integration Review - Complete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>titleWorkTracker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Title Work Tracker</label>
        <referenceTo>TitleWorkTracker__c</referenceTo>
        <relationshipLabel>Title Work Jobs</relationshipLabel>
        <relationshipName>titleWorkJobs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Title Work Job</label>
    <nameField>
        <displayFormat>TWJ-{0000000000}</displayFormat>
        <label>Title Work Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Work Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TitleWorkTracker__c.object
<CustomObject>
    <fields>
        <fullName>startDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Title Work Tracker</label>
    <nameField>
        <displayFormat>TWT-{0000000000}</displayFormat>
        <label>Title Work Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title Work Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TitleWorkJobTriggerHelper.cls
public class TitleWorkJobTriggerHelper  {

	public static void updateTitleWorkTrackers(Map<Id,TitleWorkJob__c> newMap, Map<Id,TitleWorkJob__c> oldMap)
    {
		system.debug('------TitleWorkJobTriggerHelper');
		Map<Id, Date> trackerIds = new Map<Id, Date>();
		
		for(Id twjId : newMap.keySet()){
			if((oldMap == null || newMap.get(twjId).status__c != oldMap.get(twjId).status__c) && newMap.get(twjId).status__c != 'Not Started'){
				trackerIds.put(newMap.get(twjId).titleWorkTracker__c, newMap.get(twjId).startDate__c);
			}
		}
		List<TitleWorkTracker__c> parentTrackers = [SELECT Id, status__c, startDate__c FROM TitleWorkTracker__c WHERE Id IN :trackerIds.keySet()];
		List<TitleWorkTracker__c> updateTrackers = new List<TitleWorkTracker__c>();
		for(TitleWorkTracker__c parentTracker : parentTrackers){
			if(parentTracker.status__c == 'Not Started'){
				parentTracker.status__c = 'In Progress';
				parentTracker.startDate__c = trackerIds.get(parentTracker.Id);
				updateTrackers.add(parentTracker);
			}
		}
		
		update updateTrackers;
	}


}